-- SPIKE Clue Bank — Broadway Actor
-- 15 subjects x 25 clues each = 375 total rows

INSERT INTO clue_bank (show_name, category, level, clue_text, clue_type, specificity, notes) VALUES

-- ============================================================
-- LIN-MANUEL MIRANDA
-- ============================================================
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Grew up in the same neighborhood where his most famous musical is set', 'personal', 'fact', 'Washington Heights, NYC'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Wrote his first full musical while still an undergraduate at Wesleyan University', 'career', 'fact', 'In the Heights began as a sophomore project'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Read the biography that inspired his biggest hit while on vacation in Mexico', 'history', 'fact', 'Ron Chernow biography, 2008'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Performed a song from an unfinished project at the White House in 2009', 'history', 'fact', 'Obama White House Evening of Poetry'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Won his first Tony for Best Original Score at age 28', 'award', 'fact', 'In the Heights, 2008'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Is one Emmy away from achieving EGOT status', 'award', 'fact', 'Has Tony, Grammy, Oscar, Pulitzer'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Wrote songs for a Disney animated film set in Colombia', 'crossover', 'fact', 'Encanto, 2021'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Co-founded a theater company dedicated to producing Latin-influenced work', 'collaboration', 'fact', 'Freestyle Love Supreme'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'His father was a political consultant who advised the mayor of New York City', 'personal', 'fact', 'Luis A. Miranda Jr.'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Left his most famous show after less than a year in the role he originated', 'career', 'fact', 'Departed July 9, 2016'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Composed music for a Star Wars film during a break from Broadway', 'crossover', 'fact', 'Cantina music for The Force Awakens'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Spent 7 years writing the show that would win him 11 Tony Awards', 'career', 'fact', '2008-2015 development period'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Starred in a Disney sequel as a street lamp lighter', 'crossover', 'fact', 'Mary Poppins Returns, 2018'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'His debut musical earned 13 Tony nominations and won 4', 'award', 'fact', 'In the Heights, 2008'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Directed his first feature film, a musical adaptation, in 2021', 'crossover', 'fact', 'tick, tick... BOOM!'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Attended the same high school as Supreme Court Justice Sonia Sotomayor', 'personal', 'fact', 'Hunter College High School'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Won a Pulitzer Prize for Drama, only the second musical to receive the honor', 'award', 'fact', 'After A Chorus Line in 1976'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Wrote the Spanish-language translations for a revival of a Sondheim musical', 'collaboration', 'fact', 'West Side Story 2009 revival'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'His rap about a Founding Father has been streamed over 1 billion times', 'career', 'fact', 'Cast album on Spotify'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Performed freestyle rap battles in a weekly improv show for over a decade', 'backstage', 'fact', 'Freestyle Love Supreme'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Co-wrote a book about the making of his hit musical with a journalist', 'history', 'fact', 'Hamilton: The Revolution with Jeremy McCarter'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Received a MacArthur Fellowship genius grant in 2015', 'award', 'fact', '$625,000 no-strings-attached award'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Organized a benefit concert that raised over $15 million for hurricane relief', 'personal', 'fact', 'Puerto Rico hurricane Maria relief'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'His cast album debuted at number 12 on the Billboard 200 chart', 'career', 'fact', 'Highest debut for a cast album in decades'),
('Lin-Manuel Miranda', 'Broadway Actor', 0, 'Originally auditioned for a role in Rent but was not cast', 'history', 'fact', 'Before writing his own musicals'),

-- ============================================================
-- HUGH JACKMAN
-- ============================================================
('Hugh Jackman', 'Broadway Actor', 0, 'Trained at the Western Australian Academy of Performing Arts before moving to film', 'personal', 'fact', 'Graduated in 1994'),
('Hugh Jackman', 'Broadway Actor', 0, 'Won the Tony for Best Actor in a Musical on his first Broadway appearance', 'award', 'fact', 'The Boy from Oz, 2004'),
('Hugh Jackman', 'Broadway Actor', 0, 'Hosted the Tony Awards ceremony four times', 'career', 'fact', '2003, 2004, 2005, 2014'),
('Hugh Jackman', 'Broadway Actor', 0, 'His one-man Broadway concert show sold out an entire run in under 24 hours', 'career', 'fact', 'Hugh Jackman: Back on Broadway, 2011'),
('Hugh Jackman', 'Broadway Actor', 0, 'Broke the Broadhurst Theatre single-performance gross record', 'career', 'fact', 'The Music Man revival'),
('Hugh Jackman', 'Broadway Actor', 0, 'Performed his own vocals live in a film musical rather than lip-syncing to a studio track', 'backstage', 'fact', 'Les Miserables film, 2012'),
('Hugh Jackman', 'Broadway Actor', 0, 'Was offered the lead in a revival of a classic musical after producers saw him host the Tonys', 'history', 'fact', 'His hosting performances showcased his range'),
('Hugh Jackman', 'Broadway Actor', 0, 'Turned down a reported $2 million per week to extend a Broadway revival', 'career', 'fact', 'The Music Man revival, 2022'),
('Hugh Jackman', 'Broadway Actor', 0, 'Holds dual citizenship in Australia and the United Kingdom', 'personal', 'fact', 'Born in Sydney'),
('Hugh Jackman', 'Broadway Actor', 0, 'His Broadway debut required him to perform while roller-skating on stage', 'backstage', 'fact', 'The Boy from Oz choreography'),
('Hugh Jackman', 'Broadway Actor', 0, 'Performed 8 shows per week while simultaneously promoting a blockbuster film franchise', 'backstage', 'fact', 'Wolverine press tours overlapped with Broadway'),
('Hugh Jackman', 'Broadway Actor', 0, 'Created a world concert tour that combined Broadway numbers with film songs and original material', 'crossover', 'fact', 'The Man. The Music. The Show. tour'),
('Hugh Jackman', 'Broadway Actor', 0, 'Was a PE teacher at a high school before becoming a professional actor', 'personal', 'fact', 'Uppingham School in England'),
('Hugh Jackman', 'Broadway Actor', 0, 'Opened the 2009 Academy Awards ceremony with an elaborate musical number', 'crossover', 'fact', 'Performed opposite multiple nominees'),
('Hugh Jackman', 'Broadway Actor', 0, 'His Broadway revival ran for over 300 performances at the Winter Garden Theatre', 'career', 'fact', 'The Music Man, 2022-2023'),
('Hugh Jackman', 'Broadway Actor', 0, 'Won an Emmy for hosting the Tony Awards before winning his own Tony', 'award', 'fact', 'Emmy in 2005, Tony in 2004'),
('Hugh Jackman', 'Broadway Actor', 0, 'Performed opposite a co-star he personally recruited from the London stage', 'collaboration', 'fact', 'Sutton Foster in The Music Man'),
('Hugh Jackman', 'Broadway Actor', 0, 'Launched a coffee brand that donates proceeds to fair-trade farming communities', 'personal', 'fact', 'Laughing Man Coffee'),
('Hugh Jackman', 'Broadway Actor', 0, 'Sang the national anthem at an Australian rugby league grand final', 'crossover', 'fact', 'NRL Grand Final performance'),
('Hugh Jackman', 'Broadway Actor', 0, 'His concert tours have grossed over $200 million worldwide', 'career', 'fact', 'Multiple world tours since 2019'),
('Hugh Jackman', 'Broadway Actor', 0, 'Had skin cancer removed from his nose six times while continuing to perform', 'personal', 'fact', 'Basal cell carcinoma treatments'),
('Hugh Jackman', 'Broadway Actor', 0, 'Played the same superhero role for 17 years across 9 films', 'crossover', 'fact', 'Longest tenure as a Marvel character'),
('Hugh Jackman', 'Broadway Actor', 0, 'Was considered for the lead in a Sondheim musical film adaptation', 'history', 'fact', 'Sweeney Todd discussions'),
('Hugh Jackman', 'Broadway Actor', 0, 'His Tony acceptance speech was delivered partly in character', 'backstage', 'fact', 'The Boy from Oz, stayed in Peter Allen mode'),
('Hugh Jackman', 'Broadway Actor', 0, 'Studied clowning and commedia dell''arte as part of his conservatory training', 'personal', 'fact', 'WAAPA curriculum included classical techniques'),

-- ============================================================
-- NATHAN LANE
-- ============================================================
('Nathan Lane', 'Broadway Actor', 0, 'Changed his stage name because another actor in the union already had his birth name', 'personal', 'fact', 'Born Joseph Lane, took Nathan from Guys and Dolls'),
('Nathan Lane', 'Broadway Actor', 0, 'Won three Tony Awards for Best Actor in a Musical across different decades', 'award', 'fact', '1996, 2001, 2018'),
('Nathan Lane', 'Broadway Actor', 0, 'Made his Broadway debut in 1982 in a one-line role in a drama', 'history', 'fact', 'Present Laughter, tiny role'),
('Nathan Lane', 'Broadway Actor', 0, 'Voiced a meerkat in one of the highest-grossing animated films of all time', 'crossover', 'fact', 'Timon in The Lion King'),
('Nathan Lane', 'Broadway Actor', 0, 'His performance in a comedy revival was so popular it extended three times', 'career', 'fact', 'A Funny Thing Happened on the Way to the Forum'),
('Nathan Lane', 'Broadway Actor', 0, 'Performed opposite the same co-star in both the stage and film versions of a comedy', 'collaboration', 'fact', 'Matthew Broderick partnership'),
('Nathan Lane', 'Broadway Actor', 0, 'Was 40 years old when he originated the role that won him his first Tony', 'career', 'fact', 'A Funny Thing Happened...'),
('Nathan Lane', 'Broadway Actor', 0, 'Replaced a film star in a long-running musical and immediately boosted ticket sales', 'career', 'fact', 'Took over multiple roles during runs'),
('Nathan Lane', 'Broadway Actor', 0, 'Won a Tony for a role originally played by a legendary actor in the 1960s', 'award', 'fact', 'Roles with deep Broadway lineage'),
('Nathan Lane', 'Broadway Actor', 0, 'Appeared in over 20 Broadway productions spanning more than 40 years', 'career', 'fact', 'One of the most prolific Broadway careers'),
('Nathan Lane', 'Broadway Actor', 0, 'Improvised so much during one run that the stage manager kept a log of his ad-libs', 'backstage', 'fact', 'Known for never giving the same performance twice'),
('Nathan Lane', 'Broadway Actor', 0, 'Turned down multiple film roles to stay in Broadway shows', 'career', 'fact', 'Consistently prioritized stage work'),
('Nathan Lane', 'Broadway Actor', 0, 'His co-star called him the funniest person alive during a Tony broadcast', 'collaboration', 'fact', 'Multiple co-stars have said similar things'),
('Nathan Lane', 'Broadway Actor', 0, 'Grew up in Jersey City, New Jersey, the youngest of three brothers', 'personal', 'fact', 'Irish-Catholic working-class family'),
('Nathan Lane', 'Broadway Actor', 0, 'Won his third Tony at age 62 for a dramatic musical role, not a comedy', 'award', 'fact', 'Angels in America, 2018 — a departure'),
('Nathan Lane', 'Broadway Actor', 0, 'Starred in an HBO miniseries that was adapted from a two-part Broadway play', 'crossover', 'fact', 'Angels in America TV adaptation'),
('Nathan Lane', 'Broadway Actor', 0, 'Was personally chosen by a legendary playwright to star in his final Broadway production', 'collaboration', 'fact', 'Terrence McNally collaboration'),
('Nathan Lane', 'Broadway Actor', 0, 'Attended a performing arts high school but studied acting, not musical theater', 'personal', 'fact', 'St. Joseph''s in New Jersey'),
('Nathan Lane', 'Broadway Actor', 0, 'Performed the same role on Broadway, on tour, and in the film version', 'career', 'fact', 'The Producers — all three productions'),
('Nathan Lane', 'Broadway Actor', 0, 'His Broadway salary was reportedly the highest ever for a musical comedy lead at the time', 'career', 'fact', 'The Producers era'),
('Nathan Lane', 'Broadway Actor', 0, 'Recorded a solo album of classic songs produced by a Grammy-winning arranger', 'crossover', 'fact', 'Merging theater and recording careers'),
('Nathan Lane', 'Broadway Actor', 0, 'Had a recurring role on a sitcom about nothing in the 1990s', 'crossover', 'fact', 'Appeared on Seinfeld'),
('Nathan Lane', 'Broadway Actor', 0, 'Was the first actor to play both leads in a buddy musical at different points in his career', 'career', 'fact', 'Played both principal roles over time'),
('Nathan Lane', 'Broadway Actor', 0, 'Received a star on the Hollywood Walk of Fame while still primarily a stage actor', 'award', 'fact', 'Rare for a Broadway-first performer'),
('Nathan Lane', 'Broadway Actor', 0, 'Once called Broadway his church and said he felt most alive on a stage', 'personal', 'fact', 'Interviews about his devotion to live theater'),

-- ============================================================
-- IDINA MENZEL
-- ============================================================
('Idina Menzel', 'Broadway Actor', 0, 'Studied drama at NYU''s Tisch School of the Arts', 'personal', 'fact', 'BFA in Drama, graduated 1993'),
('Idina Menzel', 'Broadway Actor', 0, 'Was working as a wedding singer when she was cast in her breakout role', 'history', 'fact', 'Singing at bar mitzvahs and weddings in NYC'),
('Idina Menzel', 'Broadway Actor', 0, 'Won the Tony for Best Actress in a Musical in 2004', 'award', 'fact', 'First Tony win'),
('Idina Menzel', 'Broadway Actor', 0, 'Recorded a solo pop album that reached the Billboard Top 60', 'crossover', 'fact', 'Multiple solo albums released'),
('Idina Menzel', 'Broadway Actor', 0, 'Was introduced by a wrong name at the 2014 Academy Awards ceremony', 'personal', 'fact', 'John Travolta mispronounced her name on live TV'),
('Idina Menzel', 'Broadway Actor', 0, 'Her signature vocal belt spans over a two-and-a-half-octave range', 'backstage', 'fact', 'Known for powerful high belt'),
('Idina Menzel', 'Broadway Actor', 0, 'Voiced a Disney princess whose song became the best-selling single of 2014', 'crossover', 'fact', 'Let It Go sold over 10 million copies'),
('Idina Menzel', 'Broadway Actor', 0, 'Originated roles in two of the highest-grossing musicals of the 2000s', 'career', 'fact', 'Both ran for years on Broadway'),
('Idina Menzel', 'Broadway Actor', 0, 'Was married to her co-star from her breakout Broadway show', 'personal', 'fact', 'Met during the original cast'),
('Idina Menzel', 'Broadway Actor', 0, 'Performed at the Super Bowl halftime pregame in front of over 100 million viewers', 'crossover', 'fact', 'National anthem, Super Bowl XLIX'),
('Idina Menzel', 'Broadway Actor', 0, 'Launched a concert tour that mixed Broadway songs with pop and rock covers', 'crossover', 'fact', 'Multiple solo tours since 2015'),
('Idina Menzel', 'Broadway Actor', 0, 'Made her Broadway debut in a rock musical at age 24', 'history', 'fact', 'Original cast member'),
('Idina Menzel', 'Broadway Actor', 0, 'Returned to Broadway in a revival of a classic musical in 2014', 'career', 'fact', 'If/Then at the Richard Rodgers Theatre'),
('Idina Menzel', 'Broadway Actor', 0, 'Her original cast recording debut album went Gold', 'career', 'fact', 'RIAA Gold certification'),
('Idina Menzel', 'Broadway Actor', 0, 'Changed the spelling of her last name early in her career for professional reasons', 'personal', 'fact', 'Born Mentzel, dropped the T'),
('Idina Menzel', 'Broadway Actor', 0, 'Performed in the final Broadway performance of a landmark rock musical', 'career', 'fact', 'Returned for the closing night'),
('Idina Menzel', 'Broadway Actor', 0, 'Was offered multiple film roles based on the strength of her Broadway vocals alone', 'crossover', 'fact', 'Casting directors sought her out'),
('Idina Menzel', 'Broadway Actor', 0, 'Starred in a Lifetime holiday film that became the network''s highest-rated original movie', 'crossover', 'fact', 'Christmas film performance'),
('Idina Menzel', 'Broadway Actor', 0, 'Her concert at Madison Square Garden sold out in under 30 minutes', 'career', 'fact', 'Solo concert at MSG'),
('Idina Menzel', 'Broadway Actor', 0, 'Grew up on Long Island in a Jewish family with a mother who was a therapist', 'personal', 'fact', 'Syosset, New York'),
('Idina Menzel', 'Broadway Actor', 0, 'Was the first person to perform a now-iconic Broadway number live on the Tony broadcast', 'backstage', 'fact', 'Tony Awards live performance'),
('Idina Menzel', 'Broadway Actor', 0, 'Trained in both acting and dance before focusing on musical theater', 'personal', 'fact', 'Multi-disciplinary training'),
('Idina Menzel', 'Broadway Actor', 0, 'Her Disney voice role earned over $1.2 billion at the global box office', 'crossover', 'fact', 'Frozen franchise total'),
('Idina Menzel', 'Broadway Actor', 0, 'Performed a duet with a pop superstar at the Billboard Music Awards', 'crossover', 'fact', 'Television performance'),
('Idina Menzel', 'Broadway Actor', 0, 'Has been called the Queen of Broadway by multiple media outlets', 'career', 'fact', 'A widely used nickname'),

-- ============================================================
-- AUDRA MCDONALD
-- ============================================================
('Audra McDonald', 'Broadway Actor', 0, 'Won six Tony Awards, more than any other performer in history', 'award', 'fact', 'Record-setting achievement'),
('Audra McDonald', 'Broadway Actor', 0, 'Trained at Juilliard in the Drama Division, not the music program', 'personal', 'fact', 'Classical acting training, Group 22'),
('Audra McDonald', 'Broadway Actor', 0, 'Won her first Tony at age 24, the youngest in her category at the time', 'award', 'fact', 'Carousel revival, 1994'),
('Audra McDonald', 'Broadway Actor', 0, 'Won Tonys in all four acting categories — a feat no other performer has achieved', 'award', 'fact', 'Musical lead, musical featured, play lead, play featured'),
('Audra McDonald', 'Broadway Actor', 0, 'Grew up in Fresno, California, far from the Broadway world', 'personal', 'fact', 'Moved to New York for Juilliard'),
('Audra McDonald', 'Broadway Actor', 0, 'Has released five solo albums of classical crossover and musical theater repertoire', 'crossover', 'fact', 'Nonesuch Records'),
('Audra McDonald', 'Broadway Actor', 0, 'Performed a one-woman concert at Lincoln Center that was broadcast live on PBS', 'crossover', 'fact', 'Live from Lincoln Center'),
('Audra McDonald', 'Broadway Actor', 0, 'Starred as the first Black woman to play a role originated by a white actress in a specific revival', 'history', 'fact', 'Multiple barrier-breaking castings'),
('Audra McDonald', 'Broadway Actor', 0, 'Her vocal range spans over three octaves from mezzo-soprano to soprano', 'backstage', 'fact', 'Classically trained voice'),
('Audra McDonald', 'Broadway Actor', 0, 'Married her co-star from a Broadway musical in 2012', 'personal', 'fact', 'Met during a production'),
('Audra McDonald', 'Broadway Actor', 0, 'Was a series regular on a network television medical drama for multiple seasons', 'crossover', 'fact', 'Recurring TV role'),
('Audra McDonald', 'Broadway Actor', 0, 'Performed the national anthem at the Super Bowl to an audience of over 100 million', 'crossover', 'fact', 'Super Bowl performance'),
('Audra McDonald', 'Broadway Actor', 0, 'Won back-to-back Tonys in consecutive years early in her career', 'award', 'fact', 'Rapid early success'),
('Audra McDonald', 'Broadway Actor', 0, 'Has said she considers herself an actor who sings rather than a singer who acts', 'personal', 'fact', 'Prioritizes the dramatic work'),
('Audra McDonald', 'Broadway Actor', 0, 'Performed a concert with a full symphony orchestra at Carnegie Hall', 'career', 'fact', 'Solo Carnegie Hall concert'),
('Audra McDonald', 'Broadway Actor', 0, 'Was directed by the same director in three different Tony-winning performances', 'collaboration', 'fact', 'Repeated director partnerships'),
('Audra McDonald', 'Broadway Actor', 0, 'Received a National Medal of Arts from the President at the White House', 'award', 'fact', 'One of very few Broadway performers honored'),
('Audra McDonald', 'Broadway Actor', 0, 'Performed in a live television broadcast of a classic musical in 2016', 'crossover', 'fact', 'NBC live musical broadcast'),
('Audra McDonald', 'Broadway Actor', 0, 'Her parents were both music educators who raised her around classical and gospel music', 'personal', 'fact', 'Musical household in Fresno'),
('Audra McDonald', 'Broadway Actor', 0, 'Returned to Broadway after a hiatus to star in a revival she had championed for years', 'career', 'fact', 'Personal passion project'),
('Audra McDonald', 'Broadway Actor', 0, 'Was the youngest person inducted into the American Theater Hall of Fame', 'award', 'fact', 'Record-setting induction'),
('Audra McDonald', 'Broadway Actor', 0, 'Performed at President Obama''s inauguration ceremony', 'crossover', 'fact', 'Inaugural celebration performance'),
('Audra McDonald', 'Broadway Actor', 0, 'Has performed in plays by August Wilson, Tennessee Williams, and Terrence McNally', 'collaboration', 'fact', 'Range of dramatic playwrights'),
('Audra McDonald', 'Broadway Actor', 0, 'Her sixth Tony win made international news beyond the theater world', 'award', 'fact', 'Covered by mainstream media worldwide'),
('Audra McDonald', 'Broadway Actor', 0, 'Started performing in community theater at age 9 in central California', 'personal', 'fact', 'Early start in Fresno community productions'),

-- ============================================================
-- PATTI LUPONE
-- ============================================================
('Patti LuPone', 'Broadway Actor', 0, 'Was part of the inaugural class at Juilliard''s Drama Division in 1968', 'personal', 'fact', 'Group 1, the very first class'),
('Patti LuPone', 'Broadway Actor', 0, 'Won her first Tony at age 31 for originating a role in a British megamusical', 'award', 'fact', 'Evita, 1980'),
('Patti LuPone', 'Broadway Actor', 0, 'Once stopped a show mid-performance to confiscate an audience member''s phone', 'backstage', 'fact', 'Famously intolerant of audience disruptions'),
('Patti LuPone', 'Broadway Actor', 0, 'Was fired from a West End production via a fax sent to her dressing room', 'history', 'fact', 'Sunset Boulevard London production'),
('Patti LuPone', 'Broadway Actor', 0, 'Won her second Tony 28 years after her first', 'award', 'fact', 'Gypsy revival, 2008'),
('Patti LuPone', 'Broadway Actor', 0, 'Grew up in Northport, Long Island, in an Italian-American family', 'personal', 'fact', 'Her father was a school administrator'),
('Patti LuPone', 'Broadway Actor', 0, 'Was a founding member of a classical repertory theater company led by John Houseman', 'history', 'fact', 'The Acting Company, touring nationally'),
('Patti LuPone', 'Broadway Actor', 0, 'Banned from a major Broadway composer''s productions after a public feud', 'collaboration', 'fact', 'Well-documented creative disagreements'),
('Patti LuPone', 'Broadway Actor', 0, 'Performed a farewell concert at the Ethel Barrymore Theatre that fans lined up 12 hours for', 'career', 'fact', 'Emotional final Broadway concert'),
('Patti LuPone', 'Broadway Actor', 0, 'Has a three-octave vocal range that has been called one of Broadway''s most powerful', 'backstage', 'fact', 'Belt voice legendary in the industry'),
('Patti LuPone', 'Broadway Actor', 0, 'Wrote a memoir that became a bestseller among theater fans', 'crossover', 'fact', 'Patti LuPone: A Memoir'),
('Patti LuPone', 'Broadway Actor', 0, 'Was a regular on a Ryan Murphy television series for multiple seasons', 'crossover', 'fact', 'TV career alongside Broadway'),
('Patti LuPone', 'Broadway Actor', 0, 'Received her third Tony at age 73 for a Sondheim revival', 'award', 'fact', 'Company, 2022'),
('Patti LuPone', 'Broadway Actor', 0, 'Her Juilliard classmate became one of the most famous film actors of his generation', 'personal', 'fact', 'Trained alongside notable actors'),
('Patti LuPone', 'Broadway Actor', 0, 'Starred in the original London cast of a musical that was then recast for Broadway', 'history', 'fact', 'Replaced before the Broadway transfer'),
('Patti LuPone', 'Broadway Actor', 0, 'Performed in a gender-swapped revival that changed the role from male to female', 'career', 'fact', 'Company, 2022 — role reimagined'),
('Patti LuPone', 'Broadway Actor', 0, 'Has been nominated for 7 Tony Awards over a career spanning five decades', 'award', 'fact', 'Nominations from 1980 to 2022'),
('Patti LuPone', 'Broadway Actor', 0, 'Famously sang from the back of a Broadway theater while walking through the audience', 'backstage', 'fact', 'Iconic staging choice in multiple productions'),
('Patti LuPone', 'Broadway Actor', 0, 'Her brother is a film and television actor who appeared in The Sopranos', 'personal', 'fact', 'Robert LuPone, also a performer'),
('Patti LuPone', 'Broadway Actor', 0, 'Graduated from Juilliard alongside Kevin Kline and David Ogden Stiers', 'personal', 'fact', 'Legendary Group 1 class'),
('Patti LuPone', 'Broadway Actor', 0, 'Has performed in every decade from the 1970s through the 2020s on Broadway', 'career', 'fact', 'Over 50 years of Broadway work'),
('Patti LuPone', 'Broadway Actor', 0, 'Took a 10-year break from Broadway musicals after a bitter professional dispute', 'history', 'fact', 'Returned triumphantly years later'),
('Patti LuPone', 'Broadway Actor', 0, 'Was awarded the French rank of Commandeur de l''Ordre des Arts et des Lettres', 'award', 'fact', 'French cultural honor'),
('Patti LuPone', 'Broadway Actor', 0, 'Performed a Sondheim tribute concert that received a standing ovation lasting 5 minutes', 'career', 'fact', 'Deep connection to Sondheim repertoire'),
('Patti LuPone', 'Broadway Actor', 0, 'Announced her retirement from Broadway after her Tony win in 2022', 'career', 'fact', 'Declared Company would be her last musical'),

-- ============================================================
-- BEN PLATT
-- ============================================================
('Ben Platt', 'Broadway Actor', 0, 'Made his Broadway debut at age 9 in a children''s ensemble', 'history', 'fact', 'The Music Man, 2002 revival'),
('Ben Platt', 'Broadway Actor', 0, 'Won the Tony for Best Actor in a Musical at age 23', 'award', 'fact', 'Dear Evan Hansen, 2017'),
('Ben Platt', 'Broadway Actor', 0, 'Is the youngest solo male performer to headline a concert at Radio City Music Hall', 'career', 'fact', 'Live at Radio City concert'),
('Ben Platt', 'Broadway Actor', 0, 'His father is a Hollywood film producer who has produced multiple Broadway shows', 'personal', 'fact', 'Marc Platt, producer'),
('Ben Platt', 'Broadway Actor', 0, 'Wore a body cast prosthetic for every performance to simulate a broken arm', 'backstage', 'fact', 'Dear Evan Hansen arm cast'),
('Ben Platt', 'Broadway Actor', 0, 'Starred in a film series about competitive a cappella singing', 'crossover', 'fact', 'Pitch Perfect franchise'),
('Ben Platt', 'Broadway Actor', 0, 'Released a solo pop album that debuted in the Billboard Top 20', 'crossover', 'fact', 'Sing to Me Instead, 2019'),
('Ben Platt', 'Broadway Actor', 0, 'Grew up in Los Angeles rather than New York, unusual for a Broadway lead', 'personal', 'fact', 'LA childhood, not a theater kid from NYC'),
('Ben Platt', 'Broadway Actor', 0, 'Performed the same role for nearly two years without missing a scheduled show', 'backstage', 'fact', 'Remarkable attendance record'),
('Ben Platt', 'Broadway Actor', 0, 'Was the first actor to perform his Tony-winning role in the original cast and the film adaptation', 'career', 'fact', 'Reprised the role he originated'),
('Ben Platt', 'Broadway Actor', 0, 'His Netflix concert film was shot at Radio City Music Hall', 'crossover', 'fact', 'Ben Platt Live from Radio City'),
('Ben Platt', 'Broadway Actor', 0, 'Attended Columbia University before leaving to pursue Broadway full-time', 'personal', 'fact', 'Left college for theater'),
('Ben Platt', 'Broadway Actor', 0, 'His vocal warm-up routine before each show lasted approximately 45 minutes', 'backstage', 'fact', 'Extensive pre-show preparation'),
('Ben Platt', 'Broadway Actor', 0, 'Was personally recruited by the composers of his breakout show after a workshop reading', 'collaboration', 'fact', 'Benj Pasek and Justin Paul selected him'),
('Ben Platt', 'Broadway Actor', 0, 'Performed a duet with a former Secretary of State at a benefit concert', 'crossover', 'fact', 'Celebrity benefit performance'),
('Ben Platt', 'Broadway Actor', 0, 'His character''s anxiety attacks required him to hyperventilate on cue 8 shows per week', 'backstage', 'fact', 'Physically demanding performance technique'),
('Ben Platt', 'Broadway Actor', 0, 'Starred in a Ryan Murphy television series as a college student running for office', 'crossover', 'fact', 'The Politician, Netflix'),
('Ben Platt', 'Broadway Actor', 0, 'Received a Grammy for Best Musical Theater Album at age 24', 'award', 'fact', 'Dear Evan Hansen cast album'),
('Ben Platt', 'Broadway Actor', 0, 'His family hosted Broadway-themed dinner parties where guests performed show tunes', 'personal', 'fact', 'Theater was a family tradition'),
('Ben Platt', 'Broadway Actor', 0, 'Applied his own stage makeup for every performance rather than using a makeup artist', 'backstage', 'fact', 'Personal ritual of preparation'),
('Ben Platt', 'Broadway Actor', 0, 'Was cast in a film after sending an audition tape from his childhood bedroom', 'history', 'fact', 'Pitch Perfect audition'),
('Ben Platt', 'Broadway Actor', 0, 'Sold out a 50-date North American concert tour in his early twenties', 'career', 'fact', 'Solo concert tour success'),
('Ben Platt', 'Broadway Actor', 0, 'His departure from the show he originated was a media event covered by major news outlets', 'career', 'fact', 'Closing night became national news'),
('Ben Platt', 'Broadway Actor', 0, 'Studied musical theater at the Adderley School of Performing Arts as a child', 'personal', 'fact', 'Early formal training in LA'),
('Ben Platt', 'Broadway Actor', 0, 'Married his partner in a ceremony attended by numerous Broadway stars', 'personal', 'fact', 'High-profile theater wedding'),

-- ============================================================
-- JONATHAN GROFF
-- ============================================================
('Jonathan Groff', 'Broadway Actor', 0, 'Grew up in Lancaster, Pennsylvania, in a Mennonite community', 'personal', 'fact', 'Rural Pennsylvania upbringing'),
('Jonathan Groff', 'Broadway Actor', 0, 'Made his Broadway debut at age 21 in a rock musical', 'history', 'fact', 'Spring Awakening, 2006'),
('Jonathan Groff', 'Broadway Actor', 0, 'Was nominated for a Tony for his first Broadway role', 'award', 'fact', 'Best Actor nom at 21'),
('Jonathan Groff', 'Broadway Actor', 0, 'Voiced a reindeer''s non-verbal sounds in a Disney animated franchise', 'crossover', 'fact', 'Sven in Frozen — grunts and snorts only'),
('Jonathan Groff', 'Broadway Actor', 0, 'Starred as the lead in an HBO series about a gay man navigating San Francisco', 'crossover', 'fact', 'Looking, 2014-2015'),
('Jonathan Groff', 'Broadway Actor', 0, 'Won his first Tony Award in 2024 after being nominated three times', 'award', 'fact', 'Bobby Darin role, Just in Time'),
('Jonathan Groff', 'Broadway Actor', 0, 'Spit so much during one performance that it became an internet sensation', 'backstage', 'fact', 'Filmed version captured it in close-up'),
('Jonathan Groff', 'Broadway Actor', 0, 'Attended a performing arts high school despite his family having no theater background', 'personal', 'fact', 'First in his family to pursue acting'),
('Jonathan Groff', 'Broadway Actor', 0, 'Played an FBI agent tracking serial killers in a Netflix drama series', 'crossover', 'fact', 'Mindhunter, 2017-2019'),
('Jonathan Groff', 'Broadway Actor', 0, 'Was close friends with his co-star from his first Broadway show before they were both famous', 'collaboration', 'fact', 'Lea Michele — lifelong friendship'),
('Jonathan Groff', 'Broadway Actor', 0, 'Replaced the creator of a hit musical in the lead role on Broadway', 'career', 'fact', 'Took over after the original star departed'),
('Jonathan Groff', 'Broadway Actor', 0, 'Performed in both the original Broadway cast and the filmed version of the same show', 'career', 'fact', 'Disney+ filmed version'),
('Jonathan Groff', 'Broadway Actor', 0, 'Was the first openly gay actor to play a romantic lead in a major Broadway musical revival', 'history', 'fact', 'Barrier-breaking casting'),
('Jonathan Groff', 'Broadway Actor', 0, 'Sang a Disney villain song that he performed live at the Oscars ceremony', 'crossover', 'fact', 'Academy Awards performance'),
('Jonathan Groff', 'Broadway Actor', 0, 'Turned down multiple television contracts to return to Broadway', 'career', 'fact', 'Consistently chose stage over screen'),
('Jonathan Groff', 'Broadway Actor', 0, 'His portrayal of a British monarch used no accent, just attitude and physicality', 'backstage', 'fact', 'Comedic interpretation of royalty'),
('Jonathan Groff', 'Broadway Actor', 0, 'Received a star-making review in the New York Times for his Broadway debut', 'career', 'fact', 'Launched his career overnight'),
('Jonathan Groff', 'Broadway Actor', 0, 'Performed in a Sondheim revue concert at the New York Philharmonic', 'collaboration', 'fact', 'Company concert version'),
('Jonathan Groff', 'Broadway Actor', 0, 'Was cast in his debut role after attending an open call audition', 'history', 'fact', 'Not through an agent — walked in off the street'),
('Jonathan Groff', 'Broadway Actor', 0, 'Voiced a character in a video game sequel to a major animated franchise', 'crossover', 'fact', 'Frozen video game voicework'),
('Jonathan Groff', 'Broadway Actor', 0, 'Performed at the Grammy Awards ceremony alongside his original Broadway castmates', 'career', 'fact', 'Cast reunion performance'),
('Jonathan Groff', 'Broadway Actor', 0, 'His Broadway dressing room was known for being decorated with fan art and personal mementos', 'backstage', 'fact', 'Personal touches in the theater'),
('Jonathan Groff', 'Broadway Actor', 0, 'Took a multi-year break from Broadway before returning to win his first Tony', 'career', 'fact', 'Focused on TV and film in between'),
('Jonathan Groff', 'Broadway Actor', 0, 'Was homeschooled for part of his childhood in rural Pennsylvania', 'personal', 'fact', 'Before attending performing arts school'),
('Jonathan Groff', 'Broadway Actor', 0, 'Appeared in the Matrix franchise in a supporting role', 'crossover', 'fact', 'The Matrix Resurrections, 2021'),

-- ============================================================
-- DAVEED DIGGS
-- ============================================================
('Daveed Diggs', 'Broadway Actor', 0, 'Won the Tony for Best Featured Actor in a Musical on his Broadway debut', 'award', 'fact', 'First Broadway credit was a Tony win'),
('Daveed Diggs', 'Broadway Actor', 0, 'Is also the frontman of an experimental hip-hop group', 'crossover', 'fact', 'clipping. — avant-garde rap collective'),
('Daveed Diggs', 'Broadway Actor', 0, 'Grew up in Oakland, California, the son of a bus driver and a social worker', 'personal', 'fact', 'Working-class Bay Area upbringing'),
('Daveed Diggs', 'Broadway Actor', 0, 'Played two different historical figures in the same Broadway show', 'career', 'fact', 'Dual roles in the original production'),
('Daveed Diggs', 'Broadway Actor', 0, 'Attended Brown University, where he studied acting and ran track', 'personal', 'fact', 'Division I sprinter and theater major'),
('Daveed Diggs', 'Broadway Actor', 0, 'Was sleeping on a friend''s couch in New York when he got the call for his Broadway audition', 'history', 'fact', 'Near-broke before the life-changing role'),
('Daveed Diggs', 'Broadway Actor', 0, 'Rapped the fastest verse in the show at approximately 6.3 words per second', 'backstage', 'fact', 'One of the fastest rap performances on Broadway'),
('Daveed Diggs', 'Broadway Actor', 0, 'Co-wrote and starred in a film about a Black man in Oakland navigating gentrification', 'crossover', 'fact', 'Blindspotting, 2018'),
('Daveed Diggs', 'Broadway Actor', 0, 'Left Broadway after less than a year to pursue film and television', 'career', 'fact', 'Departed in 2016'),
('Daveed Diggs', 'Broadway Actor', 0, 'Voiced a character in a Pixar film set in a fantastical city', 'crossover', 'fact', 'Soul or related Pixar project'),
('Daveed Diggs', 'Broadway Actor', 0, 'Was a substitute teacher and telemarketer before his Broadway break', 'personal', 'fact', 'Survival jobs before stardom'),
('Daveed Diggs', 'Broadway Actor', 0, 'His hip-hop group was nominated for a Grammy for Best Rap Album', 'award', 'fact', 'clipping. Grammy nomination'),
('Daveed Diggs', 'Broadway Actor', 0, 'Starred in a TNT sci-fi series set on a perpetually moving train', 'crossover', 'fact', 'Snowpiercer TV series'),
('Daveed Diggs', 'Broadway Actor', 0, 'Co-created a television adaptation of his indie film for a streaming platform', 'crossover', 'fact', 'Blindspotting TV series on Starz'),
('Daveed Diggs', 'Broadway Actor', 0, 'Ran the 400-meter hurdles competitively while studying theater at Brown', 'personal', 'fact', 'Unusual combination of sprinting and acting'),
('Daveed Diggs', 'Broadway Actor', 0, 'Performed at the Grammy Awards ceremony with his original Broadway castmates', 'career', 'fact', '2016 Grammy performance'),
('Daveed Diggs', 'Broadway Actor', 0, 'His audition required him to rap and act in two completely different styles', 'backstage', 'fact', 'Dual-role audition process'),
('Daveed Diggs', 'Broadway Actor', 0, 'Was personally mentored by a renowned Bay Area theater director during college', 'collaboration', 'fact', 'Bay Area theater connections'),
('Daveed Diggs', 'Broadway Actor', 0, 'His Tony acceptance speech paid tribute to public school arts education', 'award', 'fact', 'Advocated for arts funding'),
('Daveed Diggs', 'Broadway Actor', 0, 'Recorded a concept album inspired by the history of his hometown', 'crossover', 'fact', 'Oakland-themed musical project'),
('Daveed Diggs', 'Broadway Actor', 0, 'Was one of Time magazine''s 100 Most Influential People in 2016', 'award', 'fact', 'Time 100 list'),
('Daveed Diggs', 'Broadway Actor', 0, 'Performed in the filmed version of his Broadway show released on Disney+', 'career', 'fact', 'Captured the original cast performance'),
('Daveed Diggs', 'Broadway Actor', 0, 'His parents named him after a Hebrew word meaning beloved', 'personal', 'fact', 'Daveed — Hebrew origin'),
('Daveed Diggs', 'Broadway Actor', 0, 'Narrated a children''s animated series for a major streaming platform', 'crossover', 'fact', 'Voice work in animation'),
('Daveed Diggs', 'Broadway Actor', 0, 'Has said that hip-hop and theater use the same muscles of rhythm and storytelling', 'personal', 'fact', 'On the connection between his two art forms'),

-- ============================================================
-- BRIAN STOKES MITCHELL
-- ============================================================
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Known backstage as the Last Leading Man of the Golden Age', 'career', 'fact', 'Nickname among Broadway insiders'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Won the Tony for Best Actor in a Musical in 2000', 'award', 'fact', 'Kiss Me, Kate revival'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'His baritone voice has been called one of the most beautiful instruments on Broadway', 'backstage', 'fact', 'Rich baritone, classically trained'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Grew up in San Diego and began performing in musicals at age 7', 'personal', 'fact', 'Early start in community theater'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Served as chairman of the board of the Actors'' Fund for over a decade', 'career', 'fact', 'Major leadership role in the theater community'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Made his television debut at age 16 on a popular detective show', 'crossover', 'fact', 'Early TV career before Broadway'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Has been nominated for four Tony Awards across musicals and plays', 'award', 'fact', 'Versatile across genres'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Performed a solo concert at Carnegie Hall backed by a full orchestra', 'career', 'fact', 'Carnegie Hall headliner'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Was the first Black actor to play certain classic leading roles on Broadway', 'history', 'fact', 'Barrier-breaking castings'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Sang nightly from his balcony during the 2020 pandemic, becoming a viral sensation', 'personal', 'fact', 'Upper West Side balcony performances'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'His parents were both educators who encouraged his interest in the arts', 'personal', 'fact', 'Supportive family background'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Performed alongside three different leading ladies in the same Broadway revival', 'career', 'fact', 'Cast changes during a run'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Starred in a television series for four seasons before transitioning to Broadway', 'crossover', 'fact', 'Trapper John, M.D.'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'His Broadway debut was in a short-lived musical that closed after a brief run', 'history', 'fact', 'Early career setback'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Received the Isabelle Stevenson Tony Award for his philanthropic work', 'award', 'fact', 'Humanitarian recognition from the Tonys'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Performed the final note of his signature song holding it for over 20 seconds', 'backstage', 'fact', 'Famous sustained note'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Has performed in concert with nearly every major American symphony orchestra', 'career', 'fact', 'Extensive concert career'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Was raised in a military family that moved frequently during his childhood', 'personal', 'fact', 'Father was in the Navy'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Played a dual role in a musical that required him to portray both a father and son', 'career', 'fact', 'Two characters in one show'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'His concert repertoire spans Broadway, jazz, classical, and American songbook', 'career', 'fact', 'Versatile concert performer'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Personally raised over $1 million for Broadway Cares/Equity Fights AIDS', 'personal', 'fact', 'Major charity fundraising'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Studied both music and visual art before choosing performing as his career', 'personal', 'fact', 'Also a skilled visual artist'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Was directed by a Pulitzer Prize-winning playwright in a non-musical role', 'collaboration', 'fact', 'Dramatic theater work'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Performed at the Kennedy Center Honors ceremony for multiple honorees', 'crossover', 'fact', 'Prestigious performance invitations'),
('Brian Stokes Mitchell', 'Broadway Actor', 0, 'Has been called the chairman of the board of Broadway by the New York Times', 'career', 'fact', 'High praise from the paper of record'),

-- ============================================================
-- RAUL ESPARZA
-- ============================================================
('Raul Esparza', 'Broadway Actor', 0, 'Has been nominated for four Tony Awards without winning', 'award', 'fact', 'One of the most-nominated actors without a win'),
('Raul Esparza', 'Broadway Actor', 0, 'Born in Wilmington, Delaware, to Cuban and Honduran immigrant parents', 'personal', 'fact', 'Latin American heritage'),
('Raul Esparza', 'Broadway Actor', 0, 'Played a recurring role as a prosecutor on a long-running NBC crime drama', 'crossover', 'fact', 'Law & Order: SVU'),
('Raul Esparza', 'Broadway Actor', 0, 'Performed in a Sondheim revival where the actors also played their own instruments', 'career', 'fact', 'John Doyle production — actors as musicians'),
('Raul Esparza', 'Broadway Actor', 0, 'Taught himself to play piano for a Broadway revival in just 8 weeks', 'backstage', 'fact', 'Learned instrument specifically for the role'),
('Raul Esparza', 'Broadway Actor', 0, 'Attended NYU''s Tisch School of the Arts and graduated with a BFA in acting', 'personal', 'fact', 'Formal theater training'),
('Raul Esparza', 'Broadway Actor', 0, 'Was one of the first openly gay Latino leading men on Broadway', 'history', 'fact', 'Barrier-breaking representation'),
('Raul Esparza', 'Broadway Actor', 0, 'Starred in a one-man show about a priest that ran Off-Broadway', 'career', 'fact', 'Solo performance piece'),
('Raul Esparza', 'Broadway Actor', 0, 'His four Tony nominations span musicals and plays across different decades', 'award', 'fact', 'Versatile across genres and eras'),
('Raul Esparza', 'Broadway Actor', 0, 'Performed in a Shakespeare in the Park production that became a political controversy', 'career', 'fact', 'Central Park performances'),
('Raul Esparza', 'Broadway Actor', 0, 'Played the same Sondheim role in three different productions', 'career', 'fact', 'Deep connection to one composer'),
('Raul Esparza', 'Broadway Actor', 0, 'Was handpicked by a legendary director to star in a musical revival', 'collaboration', 'fact', 'Director specifically sought him out'),
('Raul Esparza', 'Broadway Actor', 0, 'His performance in a dramatic play earned him a Drama Desk Award', 'award', 'fact', 'Recognized in non-musical work'),
('Raul Esparza', 'Broadway Actor', 0, 'Grew up bilingual, speaking Spanish at home and English at school', 'personal', 'fact', 'Bicultural upbringing in Delaware'),
('Raul Esparza', 'Broadway Actor', 0, 'Starred in the original cast of a Jonathan Larson musical after Larson''s death', 'history', 'fact', 'Posthumous Larson production'),
('Raul Esparza', 'Broadway Actor', 0, 'Has performed in over 15 Broadway and Off-Broadway productions', 'career', 'fact', 'Prolific stage career'),
('Raul Esparza', 'Broadway Actor', 0, 'Performed a Sondheim concert that was filmed and broadcast on PBS', 'crossover', 'fact', 'Great Performances — Company'),
('Raul Esparza', 'Broadway Actor', 0, 'His vocal range spans from baritone to a high tenor belt', 'backstage', 'fact', 'Unusual vocal flexibility'),
('Raul Esparza', 'Broadway Actor', 0, 'Took over a role mid-run in a hit musical and received better reviews than the original', 'career', 'fact', 'Replacement casting success'),
('Raul Esparza', 'Broadway Actor', 0, 'Appeared in a Hannibal television series as a psychiatrist', 'crossover', 'fact', 'NBC''s Hannibal'),
('Raul Esparza', 'Broadway Actor', 0, 'Was cast in his first Broadway show directly out of college', 'history', 'fact', 'Immediate professional career start'),
('Raul Esparza', 'Broadway Actor', 0, 'Performed in the world premiere of a new Kander and Ebb musical', 'collaboration', 'fact', 'Working with legendary composers'),
('Raul Esparza', 'Broadway Actor', 0, 'His Shakespeare in the Park performances drew over 80,000 audience members', 'career', 'fact', 'Free outdoor theater in Central Park'),
('Raul Esparza', 'Broadway Actor', 0, 'Studied voice with a teacher who also trained several other Tony nominees', 'backstage', 'fact', 'Elite vocal coaching'),
('Raul Esparza', 'Broadway Actor', 0, 'Has said that Sondheim is the composer who most deeply influenced his artistic life', 'personal', 'fact', 'Deep personal connection to the work'),

-- ============================================================
-- NORBERT LEO BUTZ
-- ============================================================
('Norbert Leo Butz', 'Broadway Actor', 0, 'Won two Tony Awards for Best Actor in a Musical', 'award', 'fact', 'Dirty Rotten Scoundrels and Catch Me If You Can'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Grew up in a Catholic family of 11 children in St. Louis, Missouri', 'personal', 'fact', 'Large Midwestern family'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Attended the Alabama Shakespeare Festival''s MFA program', 'personal', 'fact', 'Classical training in the South'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Was the original standby for a lead role in a landmark rock musical', 'history', 'fact', 'Rent — understudy before starring roles'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'His sister was murdered in 1991, an event that profoundly shaped his artistic career', 'personal', 'fact', 'Tragic family loss'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Created a one-man show about grief and family that toured internationally', 'career', 'fact', 'Personal autobiographical work'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'His physical comedy skills have been compared to a young Gene Kelly', 'backstage', 'fact', 'Athletic, high-energy performer'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Won his first Tony playing a con man in a musical comedy', 'award', 'fact', 'Dirty Rotten Scoundrels, 2005'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Starred in an NBC television musical event broadcast live', 'crossover', 'fact', 'Live TV musical performance'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'His second Tony-winning role required him to perform chase sequences across the stage', 'backstage', 'fact', 'High-energy physical performance'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Taught master classes at multiple university theater programs', 'collaboration', 'fact', 'Mentoring the next generation'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Performed in the original Broadway cast of a musical about a con man and an FBI agent', 'career', 'fact', 'Catch Me If You Can'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Was a replacement in a Kander and Ebb musical before landing originating roles', 'history', 'fact', 'Paid his dues as a replacement'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Has described his performance style as controlled recklessness', 'backstage', 'fact', 'Appears spontaneous but meticulously prepared'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Starred in a limited-run play by a Pulitzer Prize-winning playwright', 'career', 'fact', 'Dramatic theater work'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Performed the same role in a pre-Broadway tryout and the Broadway production', 'career', 'fact', 'Development process through to opening'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'His audition for a major musical required both singing and improvisational comedy', 'backstage', 'fact', 'Unusual audition requirements'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Studied at Webster University in St. Louis before moving to New York', 'personal', 'fact', 'Midwest roots before Broadway'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Has performed in Shakespeare, Chekhov, and contemporary plays alongside musicals', 'career', 'fact', 'Range across dramatic literature'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Appeared in a Netflix political drama series', 'crossover', 'fact', 'Bloodline, Netflix'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Was personally called by a composer to originate a role written with him in mind', 'collaboration', 'fact', 'Role tailored to his strengths'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Won both his Tonys within a 6-year span', 'award', 'fact', '2005 and 2011'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Performed a concert at 54 Below that was recorded as a live album', 'career', 'fact', 'Intimate cabaret venue performance'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'Is known for doing his own physical stunts on stage without a double', 'backstage', 'fact', 'No stunt performer — does it all himself'),
('Norbert Leo Butz', 'Broadway Actor', 0, 'His MFA thesis performance earned him representation by a top New York agency', 'history', 'fact', 'Launched his professional career'),

-- ============================================================
-- ALEX BRIGHTMAN
-- ============================================================
('Alex Brightman', 'Broadway Actor', 0, 'Deliberately damaged his vocal cords to create his signature raspy Broadway voice', 'backstage', 'fact', 'Developed vocal nodules intentionally for the role'),
('Alex Brightman', 'Broadway Actor', 0, 'Was nominated for the Tony for Best Actor in a Musical for his Broadway debut', 'award', 'fact', 'First leading role earned a nomination'),
('Alex Brightman', 'Broadway Actor', 0, 'Grew up in Pleasanton, California, and moved to New York to pursue theater', 'personal', 'fact', 'Bay Area suburb origin'),
('Alex Brightman', 'Broadway Actor', 0, 'Improvised extensively during every performance, never giving the same show twice', 'backstage', 'fact', 'Known for ad-libs and breaking the fourth wall'),
('Alex Brightman', 'Broadway Actor', 0, 'Attended Emerson College in Boston before transferring to NYU', 'personal', 'fact', 'Two theater programs'),
('Alex Brightman', 'Broadway Actor', 0, 'Co-wrote a musical with a Grammy-winning songwriter', 'collaboration', 'fact', 'Collaborative writing projects'),
('Alex Brightman', 'Broadway Actor', 0, 'His character required him to be in heavy prosthetic makeup for every show', 'backstage', 'fact', 'Over an hour in the makeup chair each night'),
('Alex Brightman', 'Broadway Actor', 0, 'Performed 8 shows per week while wearing a fat suit and heavy costume', 'backstage', 'fact', 'Physically demanding costume requirements'),
('Alex Brightman', 'Broadway Actor', 0, 'Was in the ensemble of a hit musical before landing his star-making lead role', 'history', 'fact', 'Worked his way up from the chorus'),
('Alex Brightman', 'Broadway Actor', 0, 'His pre-show ritual included vocal exercises designed to maintain his gravelly tone', 'backstage', 'fact', 'Unconventional vocal maintenance'),
('Alex Brightman', 'Broadway Actor', 0, 'Originated a role that had been turned down by several more established actors', 'history', 'fact', 'Other actors passed on the part'),
('Alex Brightman', 'Broadway Actor', 0, 'Interacted directly with audience members during every performance', 'backstage', 'fact', 'Fourth-wall breaking was scripted and improvised'),
('Alex Brightman', 'Broadway Actor', 0, 'Voiced characters in multiple animated television series', 'crossover', 'fact', 'Animation voiceover career'),
('Alex Brightman', 'Broadway Actor', 0, 'Was involved in the development of his most famous role from the earliest workshops', 'collaboration', 'fact', 'Years of development before Broadway'),
('Alex Brightman', 'Broadway Actor', 0, 'His vocal approach was considered so unusual that doctors studied his technique', 'backstage', 'fact', 'Otolaryngologists interested in his method'),
('Alex Brightman', 'Broadway Actor', 0, 'Performed in a Broadway musical based on a Tim Burton film', 'career', 'fact', 'Film-to-stage adaptation'),
('Alex Brightman', 'Broadway Actor', 0, 'Built a social media following by posting behind-the-scenes Broadway content', 'personal', 'fact', 'Active social media presence'),
('Alex Brightman', 'Broadway Actor', 0, 'His energy level during shows was so high that he lost weight during every run', 'backstage', 'fact', 'Physically exhausting performances'),
('Alex Brightman', 'Broadway Actor', 0, 'Was a member of the original Broadway cast of a rock musical about teenage rebellion', 'history', 'fact', 'Early career ensemble role'),
('Alex Brightman', 'Broadway Actor', 0, 'Co-wrote original comedy songs that he performed at cabaret venues in New York', 'career', 'fact', 'Songwriter in addition to performer'),
('Alex Brightman', 'Broadway Actor', 0, 'Received fan mail from children who identified with his mischievous Broadway character', 'personal', 'fact', 'Connected with young audiences'),
('Alex Brightman', 'Broadway Actor', 0, 'His audition for his most famous role lasted over 3 hours', 'backstage', 'fact', 'Extensive audition process'),
('Alex Brightman', 'Broadway Actor', 0, 'Performed a one-man comedy show at Joe''s Pub between Broadway engagements', 'career', 'fact', 'Solo cabaret performances'),
('Alex Brightman', 'Broadway Actor', 0, 'Wore a wig that weighed over 2 pounds and was styled differently every few weeks', 'backstage', 'fact', 'High-maintenance wig design'),
('Alex Brightman', 'Broadway Actor', 0, 'Has described himself as a character actor who accidentally became a leading man', 'personal', 'fact', 'Self-deprecating about his leading man status'),

-- ============================================================
-- AARON TVEIT
-- ============================================================
('Aaron Tveit', 'Broadway Actor', 0, 'Won the Tony for Best Actor in a Musical as the only nominee in his category', 'award', 'fact', 'Moulin Rouge!, 2021 — sole nominee due to COVID'),
('Aaron Tveit', 'Broadway Actor', 0, 'Grew up in Middletown, New York, a small town 70 miles north of Manhattan', 'personal', 'fact', 'Hudson Valley upbringing'),
('Aaron Tveit', 'Broadway Actor', 0, 'Made his Broadway debut as a replacement in a long-running musical at age 23', 'history', 'fact', 'Hairspray replacement cast'),
('Aaron Tveit', 'Broadway Actor', 0, 'Starred in a film adaptation of a French novel set during a 19th-century revolution', 'crossover', 'fact', 'Les Miserables film, 2012'),
('Aaron Tveit', 'Broadway Actor', 0, 'Was a series regular on a critically acclaimed USA Network drama', 'crossover', 'fact', 'Graceland, 2013-2015'),
('Aaron Tveit', 'Broadway Actor', 0, 'Performed in a live television broadcast of a classic musical on Fox', 'crossover', 'fact', 'Grease: Live, 2016'),
('Aaron Tveit', 'Broadway Actor', 0, 'Attended the Ithaca College theater program before moving to New York City', 'personal', 'fact', 'BFA in Musical Theatre'),
('Aaron Tveit', 'Broadway Actor', 0, 'Originated a leading role in a musical that closed after a very short run', 'career', 'fact', 'Catch Me If You Can — brief Broadway run'),
('Aaron Tveit', 'Broadway Actor', 0, 'His Tony win was controversial because he was the only person nominated in his category', 'award', 'fact', 'COVID reduced the 2021 season to very few shows'),
('Aaron Tveit', 'Broadway Actor', 0, 'Performed 8 shows a week while recovering from COVID during the Broadway run', 'backstage', 'fact', 'Returned to performing after illness'),
('Aaron Tveit', 'Broadway Actor', 0, 'Starred in a recurring role on the CW series Gossip Girl', 'crossover', 'fact', 'Television career alongside Broadway'),
('Aaron Tveit', 'Broadway Actor', 0, 'His vocal range extends from a low baritone to a high tenor belt', 'backstage', 'fact', 'Versatile vocal instrument'),
('Aaron Tveit', 'Broadway Actor', 0, 'Was cast in a Broadway revival after the director saw his television work', 'collaboration', 'fact', 'TV exposure led to stage casting'),
('Aaron Tveit', 'Broadway Actor', 0, 'Performed solo concerts at venues including Radio City Music Hall', 'career', 'fact', 'Concert career alongside theater'),
('Aaron Tveit', 'Broadway Actor', 0, 'His Broadway dressing room became known for pre-show dance parties with the cast', 'backstage', 'fact', 'Built ensemble camaraderie'),
('Aaron Tveit', 'Broadway Actor', 0, 'Starred in the original Broadway cast of a musical that was a jukebox adaptation', 'career', 'fact', 'Jukebox musical lead role'),
('Aaron Tveit', 'Broadway Actor', 0, 'Was offered multiple television pilot deals but continued to return to Broadway', 'career', 'fact', 'Chose stage over screen repeatedly'),
('Aaron Tveit', 'Broadway Actor', 0, 'Performed a concert version of a Sondheim musical at the New York Philharmonic', 'career', 'fact', 'Concert staging with full orchestra'),
('Aaron Tveit', 'Broadway Actor', 0, 'His performance in a film musical required him to sing live on set in period costume', 'crossover', 'fact', 'Live-sung film performance'),
('Aaron Tveit', 'Broadway Actor', 0, 'Began performing in community theater in the Hudson Valley at age 10', 'personal', 'fact', 'Early start in small-town theater'),
('Aaron Tveit', 'Broadway Actor', 0, 'Was a replacement in two different Broadway musicals before originating his own role', 'history', 'fact', 'Built experience as a replacement'),
('Aaron Tveit', 'Broadway Actor', 0, 'Trained with a Broadway vocal coach who also worked with several Tony winners', 'backstage', 'fact', 'Elite vocal training'),
('Aaron Tveit', 'Broadway Actor', 0, 'Appeared on the cover of Broadway.com''s weekly video series multiple times', 'career', 'fact', 'Prominent Broadway media presence'),
('Aaron Tveit', 'Broadway Actor', 0, 'His high school drama teacher encouraged him to audition for Ithaca College', 'personal', 'fact', 'Mentored toward a theater career'),
('Aaron Tveit', 'Broadway Actor', 0, 'Performed at the Macy''s Thanksgiving Day Parade on a Broadway float', 'career', 'fact', 'National television appearance'),

-- ============================================================
-- JEREMY JORDAN
-- ============================================================
('Jeremy Jordan', 'Broadway Actor', 0, 'Was nominated for the Tony for Best Actor in a Musical at age 27', 'award', 'fact', 'Newsies, 2012'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Grew up in Corpus Christi, Texas, before moving to New York for theater', 'personal', 'fact', 'Small-city Texas upbringing'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Originated a role in a Disney stage musical based on a 1992 film', 'career', 'fact', 'Film-to-stage Disney adaptation'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Starred as a superhero''s best friend on a television series for multiple seasons', 'crossover', 'fact', 'Supergirl, CW series'),
('Jeremy Jordan', 'Broadway Actor', 0, 'His wife is also a Broadway performer they met during a production', 'personal', 'fact', 'Ashley Spencer — met on Broadway'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Attended Ithaca College and graduated with a BFA in Musical Theatre', 'personal', 'fact', 'Same program as several other Broadway stars'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Performed at 54 Below so frequently that he became the venue''s unofficial resident artist', 'career', 'fact', 'Regular cabaret performer'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Starred in a film musical opposite a country music superstar', 'crossover', 'fact', 'The Last Five Years film, 2014'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Was a replacement in a revival before landing his star-making originating role', 'history', 'fact', 'West Side Story revival, then Newsies'),
('Jeremy Jordan', 'Broadway Actor', 0, 'His viral YouTube performance videos have collectively earned over 50 million views', 'career', 'fact', 'Social media musical content'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Performed a solo concert at Lincoln Center with a full orchestra', 'career', 'fact', 'Concert headliner'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Was handpicked by Disney Theatrical to lead a workshop before the show reached Broadway', 'collaboration', 'fact', 'Cast during development process'),
('Jeremy Jordan', 'Broadway Actor', 0, 'His tenor belt has been called one of the most powerful of his generation', 'backstage', 'fact', 'Known for vocal power and control'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Returned to Broadway in a Sondheim-inspired musical in 2024', 'career', 'fact', 'Stage comeback after TV hiatus'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Performed a mashup of Broadway songs that went viral on social media', 'career', 'fact', 'Internet-famous performance clips'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Was offered the lead in a Broadway musical after singing just 16 bars at the audition', 'backstage', 'fact', 'Instant casting decision'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Starred in a limited-run musical at Second Stage Theatre Off-Broadway', 'career', 'fact', 'Non-profit theater work'),
('Jeremy Jordan', 'Broadway Actor', 0, 'His college roommate also became a working Broadway performer', 'personal', 'fact', 'Ithaca College theater community'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Performed the national anthem at a Major League Baseball game', 'crossover', 'fact', 'Sports venue performance'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Built a following on social media by posting vocal covers recorded in his apartment', 'personal', 'fact', 'DIY social media music content'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Appeared in a recurring role on a legal drama television series', 'crossover', 'fact', 'TV work between Broadway runs'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Was cast in his breakout role after sending a self-tape from his New York apartment', 'history', 'fact', 'Video audition led to the part'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Performed in multiple concert benefits for Broadway Cares/Equity Fights AIDS', 'career', 'fact', 'Regular charity performer'),
('Jeremy Jordan', 'Broadway Actor', 0, 'His departure from his most famous role was covered by entertainment news outlets', 'career', 'fact', 'National attention on his exit'),
('Jeremy Jordan', 'Broadway Actor', 0, 'Has performed in over 1,000 individual Broadway performances across all shows', 'career', 'fact', 'Extensive performance count');
