-- SPIKE Clue Bank — Broadway Musical (Batch 3)
-- 15 subjects x 25 clues each = 375 clues

INSERT INTO clue_bank (show_name, category, level, clue_text, clue_type, specificity, notes) VALUES

-- ============================================================
-- OKLAHOMA!
-- ============================================================
('Oklahoma!', 'Broadway Musical', 0, 'The original production was the first collaboration between Rodgers and Hammerstein', 'history', 'fact', 'Rodgers & Hammerstein found each other after their previous partners'),
('Oklahoma!', 'Broadway Musical', 0, 'A dream ballet sequence lasting nearly 15 minutes was choreographed by Agnes de Mille', 'design', 'fact', 'Agnes de Mille''s Broadway debut as choreographer became legendary'),
('Oklahoma!', 'Broadway Musical', 0, 'The original production opened without a single star name in the cast', 'cast', 'fact', 'The Theatre Guild took a risk on unknowns and it paid off enormously'),
('Oklahoma!', 'Broadway Musical', 0, 'During the out-of-town tryout in New Haven, the show was still called "Away We Go!"', 'history', 'fact', 'The title was changed before the Broadway opening'),
('Oklahoma!', 'Broadway Musical', 0, 'The original production ran for 2,212 performances over more than five years', 'numbers', 'fact', 'A record-breaking run for its era'),
('Oklahoma!', 'Broadway Musical', 0, 'The show is based on a 1931 play called "Green Grow the Lilacs" by Lynn Riggs', 'history', 'fact', 'Riggs was a Cherokee Nation citizen from Oklahoma'),
('Oklahoma!', 'Broadway Musical', 0, 'The Theatre Guild was nearly bankrupt and bet its survival on producing this show', 'production', 'fact', 'It was a desperate gamble that saved the organization'),
('Oklahoma!', 'Broadway Musical', 0, 'The original cast recording was the first complete Broadway cast album ever released as a commercial LP', 'culture', 'fact', 'Decca Records released it and it became a massive bestseller'),
('Oklahoma!', 'Broadway Musical', 0, 'A 2019 revival stripped the production to a bare community-hall setting with visible musicians onstage', 'production', 'fact', 'Daniel Fish''s radical reimagining won the Tony for Best Revival'),
('Oklahoma!', 'Broadway Musical', 0, 'The dream ballet required hiring a separate set of dancers to portray the lead characters'' subconscious selves', 'backstage', 'fact', 'The leads did not dance their own dream sequence'),
('Oklahoma!', 'Broadway Musical', 0, 'The original orchestration called for a 28-piece orchestra that blended pit band with lush string writing', 'orchestra', 'fact', 'Robert Russell Bennett''s orchestrations set the standard for the golden age'),
('Oklahoma!', 'Broadway Musical', 0, 'It was the first musical where every song and dance advanced the plot or developed character', 'history', 'fact', 'Often cited as the birth of the integrated book musical'),
('Oklahoma!', 'Broadway Musical', 0, 'The original set designer used minimal painted drops and translucent scrims instead of realistic scenery', 'design', 'fact', 'Lemuel Ayers created an impressionistic prairie landscape'),
('Oklahoma!', 'Broadway Musical', 0, 'The national tour launched in 1943 and played for over 10 years across more than 250 cities', 'numbers', 'fact', 'One of the longest and most extensive early Broadway tours'),
('Oklahoma!', 'Broadway Musical', 0, 'The 2019 revival served chili and cornbread to the audience before the show', 'culture', 'fact', 'Blurring the line between audience and community event'),
('Oklahoma!', 'Broadway Musical', 0, 'Investors in the original production received a return of over 3,000% on their money', 'numbers', 'fact', 'One of the most profitable investments in Broadway history'),
('Oklahoma!', 'Broadway Musical', 0, 'The 1955 film adaptation was shot in both standard 35mm and the Todd-AO 70mm widescreen process simultaneously', 'history', 'fact', 'Two complete versions were filmed with different cameras'),
('Oklahoma!', 'Broadway Musical', 0, 'Agnes de Mille''s ballet company rehearsed separately from the main cast for weeks before integration', 'backstage', 'fact', 'The ballet was essentially a show within the show'),
('Oklahoma!', 'Broadway Musical', 0, 'The costume designer created over 75 period costumes evoking Indian Territory in the early 1900s', 'design', 'fact', 'Miles White won a Tony for his designs'),
('Oklahoma!', 'Broadway Musical', 0, 'A special Tony Award was created in 1944 partly to honor this production', 'award', 'fact', 'The Tony Awards weren''t established until 1949'),
('Oklahoma!', 'Broadway Musical', 0, 'The 2019 revival used on-stage video monitors showing live close-up feeds of the actors'' faces', 'technical', 'fact', 'An unsettling surveillance-style effect that reframed the intimacy'),
('Oklahoma!', 'Broadway Musical', 0, 'The original production''s surrey with the fringe on top was a practical prop wheeled on stage by the cast', 'design', 'fact', 'The surrey became one of the most iconic props in musical theater'),
('Oklahoma!', 'Broadway Musical', 0, 'During the New Haven tryout, word of mouth was so strong that standees packed the theater by the second night', 'culture', 'fact', 'The buzz began before Broadway even saw it'),
('Oklahoma!', 'Broadway Musical', 0, 'The show won a special Pulitzer Prize in 1944', 'award', 'fact', 'Given for its contribution to American theater, not as a Drama winner'),
('Oklahoma!', 'Broadway Musical', 0, 'The original production opened at the St. James Theatre on March 31, 1943', 'production', 'fact', 'It ran at the St. James for its entire original engagement'),

-- ============================================================
-- SOUTH PACIFIC
-- ============================================================
('South Pacific', 'Broadway Musical', 0, 'The female lead famously washed her hair on stage every performance during a number', 'backstage', 'fact', 'Mary Martin insisted on doing it live every show — the crew had to waterproof the stage'),
('South Pacific', 'Broadway Musical', 0, 'Based on stories from a Pulitzer Prize-winning collection of short fiction set during World War II', 'history', 'fact', 'James Michener''s "Tales of the South Pacific" won the 1948 Pulitzer for Fiction'),
('South Pacific', 'Broadway Musical', 0, 'The show itself won the 1950 Pulitzer Prize for Drama, making it one of few musicals to receive the honor', 'award', 'fact', 'At that time, musicals rarely won the Pulitzer'),
('South Pacific', 'Broadway Musical', 0, 'The original production ran for 1,925 performances at the Majestic Theatre', 'numbers', 'fact', 'A massive hit that ran from 1949 to 1954'),
('South Pacific', 'Broadway Musical', 0, 'The orchestrations required a 30-piece orchestra blending military brass with lush romanticism', 'orchestra', 'fact', 'Robert Russell Bennett''s orchestrations captured both war and love'),
('South Pacific', 'Broadway Musical', 0, 'A state legislator in Georgia introduced a bill to outlaw the show because of its racial integration themes', 'culture', 'fact', 'The show''s anti-racism message was politically controversial in 1949'),
('South Pacific', 'Broadway Musical', 0, 'The original production used a series of painted scrims and translucent drops to create tropical island', 'design', 'fact', 'Jo Mielziner''s scenic design avoided realistic sets in favor of atmospheric washes'),
('South Pacific', 'Broadway Musical', 0, 'The 2008 Lincoln Center revival ran for 996 performances and was the first major revival in nearly 60 years', 'numbers', 'fact', 'Bartlett Sher''s production brought it back to Broadway in a big way'),
('South Pacific', 'Broadway Musical', 0, 'The original cast recording became the best-selling album in America for 69 consecutive weeks', 'numbers', 'fact', 'The longest run at number one for any album at that time'),
('South Pacific', 'Broadway Musical', 0, 'The last musical that the composing team completed before one of them died in 1960', 'history', 'fact', 'Actually their second-to-last — The Sound of Music was their final collaboration'),
('South Pacific', 'Broadway Musical', 0, 'The 2008 revival used a 30-piece orchestra, the largest pit orchestra on Broadway at the time', 'orchestra', 'fact', 'Lincoln Center insisted on honoring the original orchestrations fully'),
('South Pacific', 'Broadway Musical', 0, 'The original advance ticket sales set a Broadway record of over $500,000 before opening night', 'numbers', 'fact', 'An enormous sum in 1949'),
('South Pacific', 'Broadway Musical', 0, 'The costume department maintained over 100 costumes including military uniforms, island wear', 'design', 'fact', 'Period-accurate WWII military attire alongside tropical costumes'),
('South Pacific', 'Broadway Musical', 0, 'One song was deliberately written to address the idea that racism is taught rather than innate', 'history', 'fact', 'The creative team intentionally used the score to challenge prejudice'),
('South Pacific', 'Broadway Musical', 0, 'The female lead wore no shoes for the majority of the performance to convey island authenticity', 'backstage', 'fact', 'This was unusual for a leading lady on Broadway in 1949'),
('South Pacific', 'Broadway Musical', 0, 'Won 9 Tony Awards in 1950 including every musical category available that year', 'award', 'fact', 'A near-complete sweep of the musical categories'),
('South Pacific', 'Broadway Musical', 0, 'The 2008 revival added a 40-foot curved cyclorama painted to suggest ocean and sky', 'design', 'fact', 'Replaced the original''s scrim technique with a single massive backdrop'),
('South Pacific', 'Broadway Musical', 0, 'The original production''s lighting used colored gels to create distinct mood shifts between scenes', 'technical', 'fact', 'The contrast between warm island light and cold wartime light was deliberate'),
('South Pacific', 'Broadway Musical', 0, 'The show''s London production at the Drury Lane Theatre ran for 802 performances starting in 1951', 'numbers', 'fact', 'A hit in London as well as New York'),
('South Pacific', 'Broadway Musical', 0, 'The female lead was 36 years old when she originated the role, playing a character described as much younger', 'cast', 'fact', 'Mary Martin''s charisma made the age difference irrelevant'),
('South Pacific', 'Broadway Musical', 0, 'The 1958 film adaptation used heavy color filters on the camera lenses to represent emotional states', 'history', 'fact', 'A controversial creative choice that audiences found distracting'),
('South Pacific', 'Broadway Musical', 0, 'The original male lead was an opera singer making his Broadway debut', 'cast', 'fact', 'Ezio Pinza came directly from the Metropolitan Opera'),
('South Pacific', 'Broadway Musical', 0, 'The prop department built a practical shower unit that had to drain and reset between every performance', 'backstage', 'fact', 'The hair-washing scene required plumbing built into the set'),
('South Pacific', 'Broadway Musical', 0, 'The original book was co-written by the director and the lyricist together', 'production', 'fact', 'Joshua Logan and Oscar Hammerstein II collaborated on the libretto'),
('South Pacific', 'Broadway Musical', 0, 'More than 20 national and international productions were running simultaneously at the show''s peak popularity', 'numbers', 'fact', 'A global phenomenon in the early 1950s'),

-- ============================================================
-- THE KING AND I
-- ============================================================
('The King and I', 'Broadway Musical', 0, 'The leading man performed the role over 4,600 times across the original run, revivals, tours, and a film', 'cast', 'fact', 'Yul Brynner became inseparable from the role over three decades'),
('The King and I', 'Broadway Musical', 0, 'The original production featured over 50 costumes designed by Irene Sharaff', 'design', 'fact', 'Sharaff won a Tony for the elaborate Thai and Victorian designs'),
('The King and I', 'Broadway Musical', 0, 'A 20-minute narrative ballet sequence called "The Small House of Uncle Thomas" was choreographed by Jerome', 'backstage', 'fact', 'The ballet retells an American novel through Thai classical dance'),
('The King and I', 'Broadway Musical', 0, 'The leading man shaved his head for the role in 1951 and kept it shaved for the rest of his life', 'cast', 'fact', 'The look became his permanent signature'),
('The King and I', 'Broadway Musical', 0, 'Based on the fictionalized memoirs of a British governess who served in the Siamese royal court', 'history', 'fact', 'The memoirs were later shown to contain significant embellishments'),
('The King and I', 'Broadway Musical', 0, 'The original production ran for 1,246 performances at the St. James Theatre', 'numbers', 'fact', 'A major hit from 1951 to 1954'),
('The King and I', 'Broadway Musical', 0, 'The ballroom scene required a massive polka sequence choreographed for the two leads who had no dance', 'backstage', 'fact', 'The logistics of the full-skirted gown in the polka were a backstage challenge'),
('The King and I', 'Broadway Musical', 0, 'Jo Mielziner''s set design used painted silk panels and lacquered surfaces to evoke the Royal Palace of Bangkok', 'design', 'fact', 'The design avoided literal realism in favor of theatrical suggestion'),
('The King and I', 'Broadway Musical', 0, 'The government of Thailand has banned all productions of the show from being performed in the country', 'culture', 'fact', 'Considered an inaccurate and disrespectful portrayal of the Thai monarchy'),
('The King and I', 'Broadway Musical', 0, 'Won 5 Tony Awards in 1952 including Best Musical and Best Actress for Gertrude Lawrence', 'award', 'fact', 'Lawrence died during the run, less than two years after opening'),
('The King and I', 'Broadway Musical', 0, 'The 2015 Lincoln Center revival ran for 538 performances and featured a 28-piece orchestra', 'numbers', 'fact', 'Bartlett Sher''s production restored the full orchestrations'),
('The King and I', 'Broadway Musical', 0, 'The original leading lady collapsed during a performance and was later diagnosed with cancer', 'cast', 'fact', 'Gertrude Lawrence passed away on September 6, 1952, while still in the show'),
('The King and I', 'Broadway Musical', 0, 'The children''s cast in the original production included more than a dozen child actors playing the royal', 'cast', 'fact', 'Managing the children''s schedules and performances was a major stage management challenge'),
('The King and I', 'Broadway Musical', 0, 'Margaret Landon''s 1944 novel "Anna and the King of Siam" served as the direct source', 'history', 'fact', 'The show is two adaptations removed from the original account'),
('The King and I', 'Broadway Musical', 0, 'The 2015 revival won 4 Tony Awards including Best Revival of a Musical', 'award', 'fact', 'Kelli O''Hara won her first Tony after six previous nominations'),
('The King and I', 'Broadway Musical', 0, 'The original orchestra of 30 musicians incorporated Thai percussion alongside Western strings', 'orchestra', 'fact', 'The orchestrations by Robert Russell Bennett blended Eastern and Western sounds'),
('The King and I', 'Broadway Musical', 0, 'The costume shop maintained the leading lady''s iconic ballgown', 'design', 'fact', 'The actress had to learn to move and dance in the enormous garment'),
('The King and I', 'Broadway Musical', 0, 'The 1956 film adaptation was shot on the Fox studio lot using some of the largest interior sets ever', 'history', 'fact', 'The palace set filled an entire soundstage'),
('The King and I', 'Broadway Musical', 0, 'During the original run, over 40 pairs of ballet slippers were used per week for the "Small House of Uncle', 'backstage', 'fact', 'The dancers went through shoes at an enormous rate'),
('The King and I', 'Broadway Musical', 0, 'The show was Rodgers and Hammerstein''s fifth collaboration, after Oklahoma!, Carousel, Allegro, South Pacific', 'production', 'fact', 'By this point they were the dominant creative force on Broadway'),
('The King and I', 'Broadway Musical', 0, 'A national tour in 1954 carried over 15 tons of scenery and costumes across 30 cities', 'numbers', 'fact', 'One of the most elaborate touring productions of the 1950s'),
('The King and I', 'Broadway Musical', 0, 'The leading man''s 1985 farewell tour grossed over $20 million and played to sold-out houses in every city', 'numbers', 'fact', 'His final victory lap after decades in the role'),
('The King and I', 'Broadway Musical', 0, 'The original stage manager had to coordinate over 50 scene transitions including scrim reveals and painted', 'backstage', 'fact', 'The show required precise backstage choreography'),
('The King and I', 'Broadway Musical', 0, 'The 2015 revival''s production budget exceeded $12 million', 'numbers', 'fact', 'A major investment that paid off with strong reviews and ticket sales'),
('The King and I', 'Broadway Musical', 0, 'The lighting design for the original production used over 200 colored gel changes to shift between day, night', 'technical', 'fact', 'Precise color changes helped establish location without set changes'),

-- ============================================================
-- MY FAIR LADY
-- ============================================================
('My Fair Lady', 'Broadway Musical', 0, 'The original production ran for 2,717 performances, a record for longest-running musical at the time', 'numbers', 'fact', 'The record stood from 1956 until Hello, Dolly! and then Fiddler surpassed it'),
('My Fair Lady', 'Broadway Musical', 0, 'The leading man pioneered a talk-singing technique because he could not sustain traditional vocal lines', 'cast', 'fact', 'Rex Harrison''s Sprechstimme style became iconic and influential'),
('My Fair Lady', 'Broadway Musical', 0, 'Based on George Bernard Shaw''s 1913 play "Pygmalion" and a 1938 film adaptation of the same work', 'history', 'fact', 'Shaw''s estate initially refused to grant musical adaptation rights'),
('My Fair Lady', 'Broadway Musical', 0, 'The Ascot Gavotte scene featured an entire ensemble dressed exclusively in black and white by costume', 'design', 'fact', 'Beaton''s monochromatic Ascot became one of the most famous costume designs in theater history'),
('My Fair Lady', 'Broadway Musical', 0, 'Over 100 costumes were created for the original production', 'design', 'fact', 'Cecil Beaton brought his film and fashion expertise to Broadway'),
('My Fair Lady', 'Broadway Musical', 0, 'The composing team spent five years trying to crack the adaptation before finally writing a workable version', 'history', 'fact', 'Lerner and Loewe abandoned the project twice before completing it'),
('My Fair Lady', 'Broadway Musical', 0, 'Oliver Smith''s set design used a turntable stage to transition seamlessly between multiple London locations', 'technical', 'fact', 'The revolving stage allowed fluid scene changes without blackouts'),
('My Fair Lady', 'Broadway Musical', 0, 'The original cast recording sold over 5 million copies', 'numbers', 'fact', 'Columbia Records released it and it dominated the charts'),
('My Fair Lady', 'Broadway Musical', 0, 'The original orchestra comprised 30 musicians with orchestrations by Robert Russell Bennett and Phil Lang', 'orchestra', 'fact', 'The lush orchestrations became the gold standard for musical theater'),
('My Fair Lady', 'Broadway Musical', 0, 'Won 6 Tony Awards in 1957 including Best Musical, and the original director also won for Best Direction', 'award', 'fact', 'Moss Hart directed with meticulous precision'),
('My Fair Lady', 'Broadway Musical', 0, 'The leading man had a personal microphone concealed in his necktie because he refused to project', 'technical', 'fact', 'An early and innovative use of body microphones on Broadway'),
('My Fair Lady', 'Broadway Musical', 0, 'The Embassy Ball scene required 40 extras in full Edwardian formal wear for a single sequence', 'design', 'fact', 'The visual spectacle of the ball was a production highlight'),
('My Fair Lady', 'Broadway Musical', 0, 'Before the current composing team succeeded, Rodgers and Hammerstein had attempted and abandoned their own', 'history', 'fact', 'R&H concluded the play couldn''t be musicalized — Lerner and Loewe proved them wrong'),
('My Fair Lady', 'Broadway Musical', 0, 'The original production opened at the Mark Hellinger Theatre on March 15, 1956', 'production', 'fact', 'It was one of the most anticipated openings in Broadway history'),
('My Fair Lady', 'Broadway Musical', 0, 'The London production at the Theatre Royal Drury Lane ran for 2,281 performances starting in 1958', 'numbers', 'fact', 'A smash hit on both sides of the Atlantic'),
('My Fair Lady', 'Broadway Musical', 0, 'The 2018 Lincoln Center revival was directed by Bartlett Sher and ran for 548 performances', 'production', 'fact', 'The first major Broadway revival in over 25 years'),
('My Fair Lady', 'Broadway Musical', 0, 'Moss Hart rehearsed the cast for 8 weeks, unusually long for the era, insisting on perfecting every detail', 'production', 'fact', 'His meticulous direction was considered obsessive even by 1950s standards'),
('My Fair Lady', 'Broadway Musical', 0, 'The property department maintained over 200 hand props including period-accurate books, china', 'backstage', 'fact', 'The study scene alone required dozens of precisely placed props'),
('My Fair Lady', 'Broadway Musical', 0, 'The lighting design used over 300 cues to shift between the gritty streets and the elegant drawing rooms', 'technical', 'fact', 'Precise lighting helped define the class divisions at the heart of the show'),
('My Fair Lady', 'Broadway Musical', 0, 'Cecil Beaton also designed the costumes for the 1964 film adaptation and won an Academy Award for them', 'history', 'fact', 'He recreated and expanded his stage designs for the screen'),
('My Fair Lady', 'Broadway Musical', 0, 'The show''s advance ticket sales exceeded $3 million before opening, a record for 1956', 'numbers', 'fact', 'An unprecedented demand driven by word of mouth from tryouts'),
('My Fair Lady', 'Broadway Musical', 0, 'George Bernard Shaw stipulated in his will that no adaptation could alter his play''s ending', 'history', 'fact', 'The musical''s ending was carefully crafted to be ambiguous enough to satisfy the estate'),
('My Fair Lady', 'Broadway Musical', 0, 'The original production''s stage crew numbered over 30 stagehands to manage the turntable and fly system', 'backstage', 'fact', 'A large crew for the era, reflecting the production''s scale'),
('My Fair Lady', 'Broadway Musical', 0, 'Hanya Holm choreographed the original production, including a full ballroom waltz sequence for 20 couples', 'backstage', 'fact', 'The Embassy Ball waltz was one of the most demanding ensemble pieces'),
('My Fair Lady', 'Broadway Musical', 0, 'The original production grossed over $10 million during its Broadway run, an astronomical figure for the 1950s', 'numbers', 'fact', 'It was the most profitable Broadway show of its generation'),

-- ============================================================
-- GYPSY
-- ============================================================
('Gypsy', 'Broadway Musical', 0, 'Based on the memoirs of a famous burlesque performer, adapted with significant creative liberties', 'history', 'fact', 'Gypsy Rose Lee''s autobiography was the source material'),
('Gypsy', 'Broadway Musical', 0, 'The original production ran for 702 performances at the Broadway Theatre starting in 1959', 'numbers', 'fact', 'Considered a moderate run for a show now regarded as one of the greatest ever'),
('Gypsy', 'Broadway Musical', 0, 'The original leading lady was 51 years old and demanded specific contractual control over the production', 'cast', 'fact', 'Ethel Merman negotiated extraordinary power over creative decisions'),
('Gypsy', 'Broadway Musical', 0, 'The original set design by Jo Mielziner used a series of vaudeville-style painted drops that flew in and out', 'design', 'fact', 'The drops evoked the fading world of vaudeville touring'),
('Gypsy', 'Broadway Musical', 0, 'The book writer also directed four subsequent revivals of the show', 'production', 'fact', 'Arthur Laurents directed revivals in 1974, 1989, 2003, and 2008'),
('Gypsy', 'Broadway Musical', 0, 'The lyrics were written by a 27-year-old making only his second Broadway appearance as a lyricist', 'production', 'fact', 'Stephen Sondheim went on to become the most celebrated composer-lyricist in musical theater'),
('Gypsy', 'Broadway Musical', 0, 'Lost the 1960 Tony for Best Musical to two other shows that tied for the award', 'award', 'fact', 'The Sound of Music and Fiorello! shared the prize, leaving this show empty-handed'),
('Gypsy', 'Broadway Musical', 0, 'Jerome Robbins directed and choreographed, staging an iconic 11 o''clock number', 'backstage', 'fact', 'The climactic breakdown is a marathon of physical and emotional acting'),
('Gypsy', 'Broadway Musical', 0, 'The original orchestra consisted of 27 musicians playing Jule Styne''s jazz-inflected, brass-heavy score', 'orchestra', 'fact', 'The orchestrations by Sid Ramin and Robert Ginzler gave the score a driving, vaudeville energy'),
('Gypsy', 'Broadway Musical', 0, 'Four major Broadway revivals have been mounted, each built around a different legendary leading lady', 'production', 'fact', 'Angela Lansbury, Tyne Daly, Bernadette Peters, and Patti LuPone each headlined'),
('Gypsy', 'Broadway Musical', 0, 'The burlesque strip sequence required carefully choreographed lighting to suggest more than was actually shown', 'technical', 'fact', 'The lighting design was essential to making the sequence work within Broadway standards'),
('Gypsy', 'Broadway Musical', 0, 'The costume department created over 80 costumes spanning three decades of American entertainment', 'design', 'fact', 'The show''s timeline required aging characters and evolving fashion'),
('Gypsy', 'Broadway Musical', 0, 'The vaudeville act sequences featured live prop comedy including a trained lamb and baby balloon gags', 'backstage', 'fact', 'Real animals and novelty props were used in the vaudeville scenes'),
('Gypsy', 'Broadway Musical', 0, 'The 2008 revival at the St. James Theatre ran for 332 performances', 'numbers', 'fact', 'Patti LuPone won the Tony for Best Actress in a Musical'),
('Gypsy', 'Broadway Musical', 0, 'The original production''s lighting plot used over 150 cues to transition between backstage, onstage', 'technical', 'fact', 'The show moves rapidly between performance and private moments'),
('Gypsy', 'Broadway Musical', 0, 'The 2003 revival was the first to use a woman of color in the lead role', 'cast', 'fact', 'Bernadette Peters brought a different vulnerability to the part'),
('Gypsy', 'Broadway Musical', 0, 'The original production''s sound design was among the first to use concealed wireless microphones', 'technical', 'fact', 'Early body mic technology was still being developed in 1959'),
('Gypsy', 'Broadway Musical', 0, 'The show is frequently called the greatest American musical ever written by critics and theater historians', 'culture', 'fact', 'It regularly tops all-time lists despite never having won the Best Musical Tony'),
('Gypsy', 'Broadway Musical', 0, 'The stage manager had to coordinate three onstage vaudeville acts, a strip routine', 'backstage', 'fact', 'The last act is among the most demanding sequences to stage manage'),
('Gypsy', 'Broadway Musical', 0, 'Jule Styne composed the entire score in just a few months after being selected over several other composers', 'production', 'fact', 'Irving Berlin and Cole Porter were both considered before Styne'),
('Gypsy', 'Broadway Musical', 0, 'The property master maintained a collection of vintage vaudeville props sourced from actual defunct', 'design', 'fact', 'Authentic props helped ground the show in historical reality'),
('Gypsy', 'Broadway Musical', 0, 'The 1974 London premiere at the Piccadilly Theatre was the show''s first West End production', 'numbers', 'fact', 'Angela Lansbury starred in the London debut'),
('Gypsy', 'Broadway Musical', 0, 'The original leading lady famously never missed a single performance during the entire Broadway run', 'cast', 'fact', 'Ethel Merman was legendary for her reliability and stamina'),
('Gypsy', 'Broadway Musical', 0, 'The flying scenery included over a dozen painted vaudeville act backdrops that had to change in under 15', 'backstage', 'fact', 'Quick fly changes were essential to the show''s pacing'),
('Gypsy', 'Broadway Musical', 0, 'The original creative team clashed repeatedly during development', 'production', 'fact', 'Jerome Robbins and Ethel Merman had a famously contentious working relationship'),

-- ============================================================
-- THE SOUND OF MUSIC
-- ============================================================
('The Sound of Music', 'Broadway Musical', 0, 'The lyricist died of stomach cancer just nine months after opening night, making this his final Broadway show', 'history', 'fact', 'Oscar Hammerstein II passed away on August 23, 1960'),
('The Sound of Music', 'Broadway Musical', 0, 'Based on the true story of a novice nun who became governess to a naval captain''s seven children in 1930s', 'history', 'fact', 'Maria von Trapp''s memoir "The Story of the Trapp Family Singers" was the source'),
('The Sound of Music', 'Broadway Musical', 0, 'The original production ran for 1,443 performances at the Lunt-Fontanne Theatre', 'numbers', 'fact', 'A substantial hit from 1959 to 1963'),
('The Sound of Music', 'Broadway Musical', 0, 'Oliver Smith''s set design included a working abbey interior, a villa with a staircase', 'design', 'fact', 'Multiple large-scale sets had to transition smoothly'),
('The Sound of Music', 'Broadway Musical', 0, 'Won 5 Tony Awards in 1960 including Best Musical, beating a show many critics considered superior', 'award', 'fact', 'It triumphed over Gypsy and Fiorello! in the Best Musical race'),
('The Sound of Music', 'Broadway Musical', 0, 'The original leading lady was 46 years old when she originated the role of a young postulant', 'cast', 'fact', 'Mary Martin brought star power despite the age discrepancy'),
('The Sound of Music', 'Broadway Musical', 0, 'Seven child actors performed eight shows a week', 'backstage', 'fact', 'The children alternated performances to comply with the law'),
('The Sound of Music', 'Broadway Musical', 0, 'The original orchestra comprised 28 musicians playing orchestrations ranging from hymns to full symphonic', 'orchestra', 'fact', 'Robert Russell Bennett''s orchestrations captured both sacred and secular music'),
('The Sound of Music', 'Broadway Musical', 0, 'The costume department created over 90 costumes including nun habits, children''s play clothes', 'design', 'fact', 'The famous play clothes made from curtain fabric were a real costume challenge'),
('The Sound of Music', 'Broadway Musical', 0, 'The 1965 film adaptation became the highest-grossing film in history at that time', 'culture', 'fact', 'The film earned over $286 million worldwide'),
('The Sound of Music', 'Broadway Musical', 0, 'The show was the final collaboration between the most successful composing partnership in Broadway history', 'production', 'fact', 'Rodgers and Hammerstein wrote 9 musicals together over 17 years'),
('The Sound of Music', 'Broadway Musical', 0, 'The real family fled Austria in 1938 by taking a train to Italy, not by hiking over the Alps as dramatized', 'history', 'fact', 'The theatrical escape over the mountains was a dramatic invention'),
('The Sound of Music', 'Broadway Musical', 0, 'The abbey scene used a pipe organ effect produced by the orchestra pit, not an actual organ on stage', 'orchestra', 'fact', 'The organ sound was achieved through orchestration rather than an instrument'),
('The Sound of Music', 'Broadway Musical', 0, 'Lindsay and Crouse wrote the book, their last major Broadway collaboration', 'production', 'fact', 'Howard Lindsay and Russel Crouse were legendary book writers'),
('The Sound of Music', 'Broadway Musical', 0, 'The original production''s lighting design used over 200 cues', 'technical', 'fact', 'The transition from daylight to night across the mountain was a standout technical moment'),
('The Sound of Music', 'Broadway Musical', 0, 'The 1998 Broadway revival starring Rebecca Luker ran for 533 performances', 'numbers', 'fact', 'The first major Broadway revival nearly 40 years after the original'),
('The Sound of Music', 'Broadway Musical', 0, 'The real Maria von Trapp attended the opening night and was reportedly moved to tears', 'culture', 'fact', 'She lived to see her story become a Broadway phenomenon'),
('The Sound of Music', 'Broadway Musical', 0, 'The concert sequence required child actors to sing in three-part harmony live every performance', 'backstage', 'fact', 'Training child performers to maintain vocal harmony eight shows a week was challenging'),
('The Sound of Music', 'Broadway Musical', 0, 'It is one of the most frequently produced musicals in the world, performed by schools, community theaters', 'culture', 'fact', 'Licensing revenues make it one of the most performed musicals globally'),
('The Sound of Music', 'Broadway Musical', 0, 'The original production''s fly system operated 14 scenic drops including the abbey, the villa garden', 'technical', 'fact', 'Quick fly changes kept the episodic story moving without blackouts'),
('The Sound of Music', 'Broadway Musical', 0, 'A German-language film about the von Trapp family had already been made in 1956', 'history', 'fact', 'The stage musical drew from both the memoir and the earlier film'),
('The Sound of Music', 'Broadway Musical', 0, 'The original cast recording spent 16 weeks on the Billboard charts', 'numbers', 'fact', 'The album was a strong seller though overshadowed by the later film soundtrack'),
('The Sound of Music', 'Broadway Musical', 0, 'The wardrobe department used over 200 yards of fabric for the children''s costumes alone', 'design', 'fact', 'Each child had multiple costume changes throughout the show'),
('The Sound of Music', 'Broadway Musical', 0, 'Joe Layton choreographed the original, staging a puppet show and folk dance festival onstage', 'backstage', 'fact', 'The marionette sequence was a self-contained theatrical event'),
('The Sound of Music', 'Broadway Musical', 0, 'The production opened on November 16, 1959, at the Lunt-Fontanne Theatre on West 46th Street', 'production', 'fact', 'One of the grand Broadway houses hosted the show for its entire run'),

-- ============================================================
-- HELLO, DOLLY!
-- ============================================================
('Hello, Dolly!', 'Broadway Musical', 0, 'The original production won 10 Tony Awards in 1964, a record that stood for 37 years', 'award', 'fact', 'The Producers tied the record in 2001 with 12 wins'),
('Hello, Dolly!', 'Broadway Musical', 0, 'Based on Thornton Wilder''s 1955 play "The Matchmaker', 'history', 'fact', 'The source material went through multiple versions before becoming a musical'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The original production ran for 2,844 performances at the St. James Theatre', 'numbers', 'fact', 'It held the longest-running musical record until surpassed in 1970'),
('Hello, Dolly!', 'Broadway Musical', 0, 'An all-Black cast production starring Pearl Bailey and Cab Calloway opened on Broadway in 1967', 'cast', 'fact', 'Both companies played simultaneously — an unprecedented move'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The director and choreographer died on opening night', 'production', 'fact', 'Gower Champion''s death was revealed by David Merrick in one of Broadway''s most shocking moments'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The title number features a ramp-like walkway extending toward the audience, with a line of singing waiters', 'design', 'fact', 'The Harmonia Gardens sequence is one of the most iconic staging moments in Broadway history'),
('Hello, Dolly!', 'Broadway Musical', 0, 'A recording of the title song by Louis Armstrong knocked the Beatles off the Billboard Hot 100', 'culture', 'fact', 'Armstrong was 62 years old when he scored the number one hit'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The 2017 revival starring Bette Midler broke the St. James Theatre single-day box office record', 'numbers', 'fact', 'Midler''s star power drove unprecedented demand'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The original costume designer created over 120 period costumes evoking 1890s New York', 'design', 'fact', 'Freddy Wittop''s designs captured turn-of-the-century American fashion'),
('Hello, Dolly!', 'Broadway Musical', 0, 'Oliver Smith''s set design featured a moving train, a hat shop, and the elaborate Harmonia Gardens restaurant', 'design', 'fact', 'Multiple full-stage sets required extensive backstage logistics'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The original orchestra comprised 26 musicians performing Jerry Herman''s brassy, march-inflected score', 'orchestra', 'fact', 'Philip J. Lang''s orchestrations emphasized brass and percussion'),
('Hello, Dolly!', 'Broadway Musical', 0, 'Producer David Merrick was famous for publicity stunts', 'production', 'fact', 'Merrick was the most notorious showman-producer of his era'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The 2017 revival won 4 Tony Awards including Best Revival, and ran for 504 performances', 'numbers', 'fact', 'Both Bette Midler and later Bernadette Peters headlined the revival'),
('Hello, Dolly!', 'Broadway Musical', 0, 'During the original run, six different leading ladies took over the title role including Phyllis Diller', 'cast', 'fact', 'An unusually high number of celebrity replacements kept the box office strong'),
('Hello, Dolly!', 'Broadway Musical', 0, 'Gower Champion''s choreography included a waiters'' gallop sequence requiring 12 male dancers to slide across', 'backstage', 'fact', 'The precision of the waiters'' choreography became the show''s signature'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The parade sequence before the title number used the full depth of the stage with a forced-perspective street', 'technical', 'fact', 'The illusion of distance was achieved through scenic painting and lighting'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The 2017 revival''s production budget was approximately $12 million', 'numbers', 'fact', 'A significant investment that reflected Bette Midler''s salary demands'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The hat shop scene required the prop department to maintain over 30 individually decorated period hats', 'backstage', 'fact', 'Each hat was a hand-crafted 1890s reproduction'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The score was composed by a songwriter who wrote the entire show on speculation before it was optioned', 'production', 'fact', 'Jerry Herman wrote the score before David Merrick signed on'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The original production''s lighting design required over 250 cues for the multiple location changes', 'technical', 'fact', 'Jean Rosenthal''s lighting was crucial to establishing each setting'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The 1969 film adaptation cost $25 million', 'history', 'fact', 'The massive budget contributed to the end of the Hollywood musical era'),
('Hello, Dolly!', 'Broadway Musical', 0, 'A lawsuit alleged the title song plagiarized a 1948 composition, resulting in an out-of-court settlement', 'history', 'fact', 'Songwriter Mack David claimed the melody was stolen from his song "Sunflower"'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The show''s national tour in the 1960s visited over 100 cities and grossed more than $60 million', 'numbers', 'fact', 'One of the most lucrative touring productions of the 1960s'),
('Hello, Dolly!', 'Broadway Musical', 0, 'The Harmonia Gardens set featured a grand staircase that split into two curved sections for the star''s', 'design', 'fact', 'The staircase descent was timed to the musical climax of the title number'),
('Hello, Dolly!', 'Broadway Musical', 0, 'Thornton Wilder''s source material was itself inspired by a 19th-century Viennese farce by Johann Nestroy', 'history', 'fact', 'The story has roots stretching back to 1842 Austrian comedy'),

-- ============================================================
-- HAIR
-- ============================================================
('Hair', 'Broadway Musical', 0, 'The first Broadway musical to feature a live rock band on stage instead of a traditional pit orchestra', 'orchestra', 'fact', 'The band was placed onstage, visible to the audience, with full amplification'),
('Hair', 'Broadway Musical', 0, 'A nude scene at the end of the first act lasted approximately 30 seconds and was lit in near-total darkness', 'technical', 'fact', 'The dim lighting was a deliberate choice to make the nudity more symbolic than explicit'),
('Hair', 'Broadway Musical', 0, 'Originally developed at Joseph Papp''s Public Theater in October 1967, then moved to Broadway in April 1968', 'history', 'fact', 'The Off-Broadway version was significantly reworked before the Broadway transfer'),
('Hair', 'Broadway Musical', 0, 'Director Tom O''Horgan extended the stage into the audience with ramps and platforms', 'design', 'fact', 'Actors routinely moved into the house, sitting on laps and dancing in the aisles'),
('Hair', 'Broadway Musical', 0, 'The original Broadway production ran for 1,750 performances at the Biltmore Theatre', 'numbers', 'fact', 'A major commercial hit despite — or because of — the controversy'),
('Hair', 'Broadway Musical', 0, 'The sound system was one of the most powerful ever installed in a Broadway theater at that time', 'technical', 'fact', 'The volume levels were shocking to traditional theatergoers'),
('Hair', 'Broadway Musical', 0, 'The lighting design used psychedelic color washes, strobes', 'technical', 'fact', 'The lighting was meant to replicate the experience of a be-in or festival'),
('Hair', 'Broadway Musical', 0, 'Written by two actors who were also in the original cast, performing alongside the characters they had created', 'production', 'fact', 'Gerome Ragni and James Rado wrote and starred in their own musical'),
('Hair', 'Broadway Musical', 0, 'The original production had no formal choreographer credited', 'backstage', 'fact', 'The free-form movement was intentional, reflecting the counterculture ethos'),
('Hair', 'Broadway Musical', 0, 'The score mixed rock, pop, folk, gospel, psychedelia, and classical influences in a single evening', 'orchestra', 'fact', 'Galt MacDermot''s eclectic score was unlike anything Broadway had heard'),
('Hair', 'Broadway Musical', 0, 'A 2009 revival at the Al Hirschfeld Theatre ran for 519 performances after starting in Central Park', 'numbers', 'fact', 'Diane Paulus directed the revival, which transferred from the Delacorte'),
('Hair', 'Broadway Musical', 0, 'The show was banned in multiple cities and countries, including Boston, where a judge declared it obscene', 'culture', 'fact', 'Legal battles over the show reached the U.S. Supreme Court'),
('Hair', 'Broadway Musical', 0, 'Cast members were encouraged to bring personal clothing and accessories to wear on stage', 'design', 'fact', 'The costumes were largely sourced from thrift shops and the actors'' own wardrobes'),
('Hair', 'Broadway Musical', 0, 'The burning of a draft card on stage during performances provoked audience walk-outs and standing ovations', 'culture', 'fact', 'The anti-Vietnam War content was deliberately provocative'),
('Hair', 'Broadway Musical', 0, 'The original band was 8 musicians: electric guitar, bass, drums, keyboards, saxophone, and more', 'orchestra', 'fact', 'A rock combo augmented with horns, far smaller than traditional pit orchestras'),
('Hair', 'Broadway Musical', 0, 'An American flag was used on stage in a scene that led to formal protests from veterans'' organizations', 'culture', 'fact', 'The flag''s presence in the context of the show was considered desecration by some'),
('Hair', 'Broadway Musical', 0, 'The set design by Robin Wagner featured a scrap-metal and junk environment with no traditional scenery', 'design', 'fact', 'The raw, industrial aesthetic reflected the anti-establishment message'),
('Hair', 'Broadway Musical', 0, 'The show introduced the concept of audience participation in a Broadway musical', 'backstage', 'fact', 'Breaking the fourth wall was central to the show''s philosophy'),
('Hair', 'Broadway Musical', 0, 'The Off-Broadway version at the Public Theater ran only 8 weeks before being reimagined for Broadway', 'history', 'fact', 'Gerald Freedman directed the original; Tom O''Horgan completely restaged it'),
('Hair', 'Broadway Musical', 0, 'The 2009 revival won the Tony for Best Revival of a Musical', 'award', 'fact', 'The show finally received Tony recognition 40 years after its debut'),
('Hair', 'Broadway Musical', 0, 'Over 20 international productions opened within two years of the Broadway premiere', 'numbers', 'fact', 'The show became a worldwide cultural phenomenon almost instantly'),
('Hair', 'Broadway Musical', 0, 'The prop department had to replace burned draft cards, incense, and flowers at every performance', 'backstage', 'fact', 'The show consumed its own props nightly'),
('Hair', 'Broadway Musical', 0, 'The original production used no curtain — the stage was exposed as the audience entered', 'technical', 'fact', 'The absence of a curtain was a radical choice in 1968'),
('Hair', 'Broadway Musical', 0, 'The cast recording became a multi-platinum album, with several songs crossing over to mainstream pop radio', 'numbers', 'fact', 'The recording reached number one on the Billboard album chart'),
('Hair', 'Broadway Musical', 0, 'The composer had a classical music background and wrote the score at his piano in his home in Staten Island', 'production', 'fact', 'Galt MacDermot studied at the University of Cape Town and was classically trained'),

-- ============================================================
-- GREASE
-- ============================================================
('Grease', 'Broadway Musical', 0, 'The original Broadway production ran for 3,388 performances', 'numbers', 'fact', 'It held the record from 1979 until A Chorus Line surpassed it'),
('Grease', 'Broadway Musical', 0, 'Originally developed as an amateur production in a converted trolley barn in Chicago in 1971', 'history', 'fact', 'Jim Jacobs and Warren Casey created the show for a small Chicago theater company'),
('Grease', 'Broadway Musical', 0, 'The show moved through three different Broadway theaters during its run: the Eden, Broadhurst, and Royale', 'production', 'fact', 'Unusual for a show to transfer between multiple Broadway houses'),
('Grease', 'Broadway Musical', 0, 'The original cast included several future stars who later became major film names', 'cast', 'fact', 'John Travolta joined the Broadway company as a replacement in 1972'),
('Grease', 'Broadway Musical', 0, 'The on-stage band played 1950s rock and roll using period-appropriate instruments including a stand-up bass', 'orchestra', 'fact', 'The band was kept small and raw to match the doo-wop and rockabilly sound'),
('Grease', 'Broadway Musical', 0, 'Patricia Birch choreographed the original production', 'backstage', 'fact', 'The hand jive required precise synchronization from the entire ensemble'),
('Grease', 'Broadway Musical', 0, 'The set design by Douglas W. Schmidt depicted a stylized 1950s high school gymnasium and drive-in', 'design', 'fact', 'The set used period signage and chrome accents to evoke the era'),
('Grease', 'Broadway Musical', 0, 'The 1978 film adaptation added several new songs not in the original Broadway score', 'history', 'fact', 'Songs like "Hopelessly Devoted to You" and "You''re the One That I Want" were written for the film'),
('Grease', 'Broadway Musical', 0, 'The original production opened at the Eden Theatre on February 14, 1972 — Valentine''s Day', 'production', 'fact', 'The romantic holiday opening was a deliberate choice'),
('Grease', 'Broadway Musical', 0, 'The show is one of the most frequently licensed musicals for high school and community theater productions', 'culture', 'fact', 'Its accessible score and large ensemble cast make it ideal for amateur groups'),
('Grease', 'Broadway Musical', 0, 'Over 20 replacement cast members cycled through leading roles during the original 8-year Broadway run', 'cast', 'fact', 'The revolving cast included Peter Gallagher, Treat Williams, and Patrick Swayze'),
('Grease', 'Broadway Musical', 0, 'The 1994 revival directed by Tommy Tune ran for 1,503 performances at the Eugene O''Neill Theatre', 'numbers', 'fact', 'The revival was almost as successful as the original'),
('Grease', 'Broadway Musical', 0, 'The costume department maintained over 60 costumes including leather jackets, poodle skirts', 'design', 'fact', 'Period authenticity in the costumes was essential to the show''s nostalgia appeal'),
('Grease', 'Broadway Musical', 0, 'The original production had no out-of-town tryout — it went directly from Off-Broadway to Broadway', 'history', 'fact', 'It opened Off-Broadway at the Eden Theatre before the venue was classified as Broadway'),
('Grease', 'Broadway Musical', 0, 'The show received zero Tony nominations when it opened in 1972', 'award', 'fact', 'Despite becoming the longest-running show, it was ignored by the Tonys'),
('Grease', 'Broadway Musical', 0, 'The original score was written for a small rock combo of only 5 musicians', 'orchestra', 'fact', 'The stripped-down band gave the show a garage-band energy'),
('Grease', 'Broadway Musical', 0, 'The car scene used a cutaway automobile frame that the cast sat in and rocked to simulate driving', 'design', 'fact', 'The practical car prop became one of the show''s most recognizable elements'),
('Grease', 'Broadway Musical', 0, 'The 1994 revival featured a television-style casting promotion where audiences voted on leads', 'culture', 'fact', 'An early version of reality TV casting — "Grease: You''re the One That I Want" came later in 2007'),
('Grease', 'Broadway Musical', 0, 'Co-creator Warren Casey died in 1988 at age 53, never seeing the revival of his show', 'production', 'fact', 'Jim Jacobs continued to represent the show''s interests'),
('Grease', 'Broadway Musical', 0, 'The original lighting design used saturated colors and spotlights to evoke a 1950s sock hop atmosphere', 'technical', 'fact', 'The lighting was deliberately nostalgic rather than naturalistic'),
('Grease', 'Broadway Musical', 0, 'The show''s national tours have collectively played to over 100 million audience members worldwide', 'numbers', 'fact', 'One of the most widely seen musicals in history'),
('Grease', 'Broadway Musical', 0, 'The property master maintained a collection of 1950s-era props including milkshake glasses, vinyl records', 'backstage', 'fact', 'Period props were essential to selling the retro setting'),
('Grease', 'Broadway Musical', 0, 'The original producers invested only $150,000 to mount the production', 'numbers', 'fact', 'An incredibly low budget even for 1972, yielding an enormous return'),
('Grease', 'Broadway Musical', 0, 'Both creators drew directly from their own experiences growing up in working-class Chicago in the 1950s', 'history', 'fact', 'The show''s authenticity came from the writers'' real adolescence'),
('Grease', 'Broadway Musical', 0, 'A 2007 NBC reality show cast the leads for a Broadway revival through audience voting', 'culture', 'fact', 'Max Crumm and Laura Osnes were selected by viewer votes'),

-- ============================================================
-- ANNIE
-- ============================================================
('Annie', 'Broadway Musical', 0, 'The show features a trained dog who performs live in every performance', 'backstage', 'fact', 'Multiple dogs are typically trained to alternate performances'),
('Annie', 'Broadway Musical', 0, 'Based on Harold Gray''s "Little Orphan Annie" comic strip, which ran from 1924 to 2010', 'history', 'fact', 'The comic strip was a Depression-era institution for decades'),
('Annie', 'Broadway Musical', 0, 'The original production ran for 2,377 performances at the Alvin Theatre starting in 1977', 'numbers', 'fact', 'A major hit that ran for over six years'),
('Annie', 'Broadway Musical', 0, 'The show was developed at the Goodspeed Opera House in East Haddam', 'history', 'fact', 'The Goodspeed has been a launching pad for many Broadway musicals'),
('Annie', 'Broadway Musical', 0, 'The child actress in the lead role was required to perform 8 shows a week', 'backstage', 'fact', 'Child labor laws required a complete alternate child cast'),
('Annie', 'Broadway Musical', 0, 'David Mitchell''s set design included a collapsible bridge and an orphanage-to-mansion transformation', 'design', 'fact', 'The visual contrast between poverty and wealth was central to the design'),
('Annie', 'Broadway Musical', 0, 'Won 7 Tony Awards in 1977 including Best Musical, Best Book, and Best Score', 'award', 'fact', 'Charles Strouse and Martin Charnin won for music and lyrics'),
('Annie', 'Broadway Musical', 0, 'The original orchestra comprised 22 musicians playing a score that ranged from vaudeville-style novelty', 'orchestra', 'fact', 'The orchestrations captured the eclectic musical landscape of the 1930s'),
('Annie', 'Broadway Musical', 0, 'Theoni V. Aldredge designed over 80 costumes spanning Depression-era rags and opulent 1930s high fashion', 'design', 'fact', 'Aldredge won the Tony for her costume designs'),
('Annie', 'Broadway Musical', 0, 'The show was originally conceived as a two-character concept piece before expanding into a full-scale musical', 'history', 'fact', 'Martin Charnin''s initial idea was much smaller in scope'),
('Annie', 'Broadway Musical', 0, 'Peter Gennaro choreographed the original production, creating ensemble tap sequences for the orphan children', 'backstage', 'fact', 'Training child performers in tap dance was a major rehearsal undertaking'),
('Annie', 'Broadway Musical', 0, 'A 1982 film adaptation directed by John Huston cost $50 million, one of the most expensive films at that time', 'history', 'fact', 'The film was a commercial disappointment relative to its enormous budget'),
('Annie', 'Broadway Musical', 0, 'The original production''s lighting used warm amber tones for mansions and cold blues for the orphanage', 'technical', 'fact', 'The color palette visually coded the emotional journey from misery to hope'),
('Annie', 'Broadway Musical', 0, 'Over 5,000 girls auditioned for the original Broadway production''s title role', 'cast', 'fact', 'The nationwide talent search was itself a publicity event'),
('Annie', 'Broadway Musical', 0, 'The 2012 revival at the Palace Theatre ran for 487 performances', 'numbers', 'fact', 'A well-received production with a new approach to the staging'),
('Annie', 'Broadway Musical', 0, 'The dog performing in the show is traditionally a mixed-breed rescue adopted from a shelter', 'cast', 'fact', 'The use of rescue dogs became part of the show''s identity and marketing'),
('Annie', 'Broadway Musical', 0, 'The show''s national tours have played continuously since the original production', 'numbers', 'fact', 'There has almost always been at least one Annie tour running somewhere in the country'),
('Annie', 'Broadway Musical', 0, 'The property department maintained a working radio that played a presidential address live nightly', 'backstage', 'fact', 'The radio was a key prop in scenes set during the FDR era'),
('Annie', 'Broadway Musical', 0, 'The original production''s set included a working trapdoor used for a chase sequence', 'technical', 'fact', 'The physical comedy required precise backstage coordination'),
('Annie', 'Broadway Musical', 0, 'The stage crew managed over a dozen scene changes including the transformation from orphanage to Warbucks', 'backstage', 'fact', 'The rapid scenic transitions were choreographed as precisely as the dance numbers'),
('Annie', 'Broadway Musical', 0, 'Mike Nichols was originally attached to direct but dropped out, with Martin Charnin taking over as director', 'production', 'fact', 'The loss of Nichols could have derailed the project'),
('Annie', 'Broadway Musical', 0, 'The show is set during the Great Depression and includes a sequence at the White House with a fictionalized', 'history', 'fact', 'Depicting a sitting president on stage was a bold creative choice'),
('Annie', 'Broadway Musical', 0, 'The original production''s fly system managed 8 painted scenic drops representing different Manhattan locations', 'technical', 'fact', 'The drops provided quick transitions between the many settings'),
('Annie', 'Broadway Musical', 0, 'The 2014 film adaptation reimagined the setting in modern-day New York with a score produced by Jay-Z', 'culture', 'fact', 'The update changed the era but kept the core story'),
('Annie', 'Broadway Musical', 0, 'The original creative team held open auditions in 7 cities before finding their cast of child performers', 'cast', 'fact', 'The nationwide search was unprecedented for a Broadway musical in 1976'),

-- ============================================================
-- 42ND STREET
-- ============================================================
('42nd Street', 'Broadway Musical', 0, 'The director and choreographer died on opening night, August 25, 1980, hours before the curtain rose', 'production', 'fact', 'Gower Champion''s death was unknown to the cast until after the show'),
('42nd Street', 'Broadway Musical', 0, 'The producer announced the director''s death to the audience from the stage during the curtain call', 'culture', 'fact', 'David Merrick''s announcement turned opening night into front-page news worldwide'),
('42nd Street', 'Broadway Musical', 0, 'The original production ran for 3,486 performances at the Winter Garden and then the Majestic Theatre', 'numbers', 'fact', 'One of the longest-running shows of the 1980s'),
('42nd Street', 'Broadway Musical', 0, 'Based on a 1933 Warner Bros. backstage film musical, itself adapted from a 1932 novel by Bradford Ropes', 'history', 'fact', 'The show is an adaptation of an adaptation'),
('42nd Street', 'Broadway Musical', 0, 'The tap dancing sequences used over 40 pairs of tap shoes per week across the ensemble', 'backstage', 'fact', 'The intense choreography destroyed shoes at an extraordinary rate'),
('42nd Street', 'Broadway Musical', 0, 'Robin Wagner''s set design included a massive Art Deco arch and a giant coin that rotated to reveal different', 'design', 'fact', 'The coin turntable became the show''s signature scenic device'),
('42nd Street', 'Broadway Musical', 0, 'The ensemble cast of 36 dancers performed precision tap choreography requiring 8 weeks of rehearsal', 'cast', 'fact', 'The choreographic demands were among the most rigorous on Broadway'),
('42nd Street', 'Broadway Musical', 0, 'Won the Tony Award for Best Musical in 1981 over a field that included a show about cats', 'award', 'fact', 'It beat Woman of the Year, which starred Lauren Bacall'),
('42nd Street', 'Broadway Musical', 0, 'The score uses songs from the original 1933 film composed by Harry Warren and Al Dubin', 'production', 'fact', 'The stage show preserved the classic film songs rather than writing new ones'),
('42nd Street', 'Broadway Musical', 0, 'A giant mirror angled over the stage reflected the tap choreography from above', 'technical', 'fact', 'The overhead mirror recreated the geometric patterns of the film''s famous camera shots'),
('42nd Street', 'Broadway Musical', 0, 'The original production''s orchestra comprised 22 musicians playing orchestrations that evoked 1930s big band', 'orchestra', 'fact', 'The brassy, swinging sound captured the feel of Depression-era showbiz'),
('42nd Street', 'Broadway Musical', 0, 'The finale featured the entire cast tapping on a multi-level staircase structure that extended the full width', 'design', 'fact', 'The staircase was the show''s most iconic visual image'),
('42nd Street', 'Broadway Musical', 0, 'The property department maintained over 200 props including period telephones, cigarette holders', 'backstage', 'fact', 'The backstage-of-a-show setting required authentic 1930s theatrical props'),
('42nd Street', 'Broadway Musical', 0, 'Producer David Merrick invested $2.5 million of his own money in the original production', 'numbers', 'fact', 'A huge personal financial bet that paid off enormously'),
('42nd Street', 'Broadway Musical', 0, 'The 2001 revival ran for 1,524 performances at the Ford Center for the Performing Arts', 'numbers', 'fact', 'The revival was nearly as successful as the original'),
('42nd Street', 'Broadway Musical', 0, 'Theoni V. Aldredge designed over 150 costumes including sequined showgirl outfits, rehearsal clothes', 'design', 'fact', 'The contrast between backstage scruff and onstage glamour drove the costume design'),
('42nd Street', 'Broadway Musical', 0, 'The original lighting design used over 400 lighting instruments to create the contrast between gritty', 'technical', 'fact', 'Tharon Musser''s lighting shifted dramatically between reality and fantasy'),
('42nd Street', 'Broadway Musical', 0, 'The choreography required every ensemble member to execute a minimum of 12 different tap combinations per', 'backstage', 'fact', 'The show was essentially a showcase for elite tap dancers'),
('42nd Street', 'Broadway Musical', 0, 'The opening night audience included Broadway luminaries unknowingly attending a memorial', 'culture', 'fact', 'The double meaning of the evening made it uniquely unforgettable'),
('42nd Street', 'Broadway Musical', 0, 'The national tour carried over 12 tons of scenery and visited more than 60 cities', 'numbers', 'fact', 'The touring production was nearly as elaborate as the Broadway version'),
('42nd Street', 'Broadway Musical', 0, 'The original sound design had to balance amplified tap shoes with a live 22-piece orchestra in a pre-digital', 'technical', 'fact', 'Getting tap sounds to read clearly over a full orchestra was a major sound challenge'),
('42nd Street', 'Broadway Musical', 0, 'Gower Champion choreographed the show from a wheelchair during final rehearsals while battling the illness', 'production', 'fact', 'His final creative act was completing this show'),
('42nd Street', 'Broadway Musical', 0, 'The show''s London production opened in 1984 at the Theatre Royal Drury Lane and ran for over 4 years', 'numbers', 'fact', 'A hit in the West End as well as on Broadway'),
('42nd Street', 'Broadway Musical', 0, 'The wardrobe crew executed over 100 quick changes per performance', 'backstage', 'fact', 'The backstage choreography of quick changes rivaled the onstage dancing'),
('42nd Street', 'Broadway Musical', 0, 'The original production grossed over $200 million during its Broadway run', 'numbers', 'fact', 'An enormous commercial success spanning nearly a decade'),

-- ============================================================
-- CATS
-- ============================================================
('Cats', 'Broadway Musical', 0, 'The original Broadway production ran for 7,485 performances over 18 years', 'numbers', 'fact', 'The Phantom of the Opera eventually broke the record'),
('Cats', 'Broadway Musical', 0, 'The entire Winter Garden Theatre was transformed into a junkyard', 'design', 'fact', 'John Napier''s set made the audience feel like they had shrunk to cat size'),
('Cats', 'Broadway Musical', 0, 'Each actor spent approximately 90 minutes in the makeup chair before every performance', 'backstage', 'fact', 'Over 3,000 pounds of yak hair were used for wigs during the original run'),
('Cats', 'Broadway Musical', 0, 'Based on T.S. Eliot''s 1939 poetry collection "Old Possum''s Book of Practical Cats"', 'history', 'fact', 'The poems were originally written for Eliot''s godchildren'),
('Cats', 'Broadway Musical', 0, 'A giant tire ascends 30 feet into the air during the finale', 'technical', 'fact', 'The ascending tire is one of the most iconic technical effects in musical theater'),
('Cats', 'Broadway Musical', 0, 'The original choreographer trained the cast in actual feline movement for 6 weeks before staging any dance', 'backstage', 'fact', 'Gillian Lynne studied real cats to develop the show''s movement vocabulary'),
('Cats', 'Broadway Musical', 0, 'Over 250 pairs of leg warmers were used per year during the original run', 'design', 'fact', 'The knitted leg warmers and unitards became the show''s signature look'),
('Cats', 'Broadway Musical', 0, 'The oversized junkyard props included a 6-foot-tall boot, a giant tire, and a car hood', 'design', 'fact', 'Everything on stage was built approximately 3 times normal human scale'),
('Cats', 'Broadway Musical', 0, 'The original lighting design by David Hersey used over 1', 'technical', 'fact', 'Pairs of glowing eyes appeared throughout the junkyard throughout the show'),
('Cats', 'Broadway Musical', 0, 'The cast of 30+ actors performed entirely on a raked stage angled toward the audience', 'technical', 'fact', 'The raked stage added physical difficulty to the already demanding choreography'),
('Cats', 'Broadway Musical', 0, 'No spoken dialogue exists in the entire show — it is entirely sung and danced', 'production', 'fact', 'The through-sung format was unusual for Broadway at the time of its 1982 opening'),
('Cats', 'Broadway Musical', 0, 'T.S. Eliot''s widow Valerie provided unpublished poems and fragments that were incorporated into the show', 'history', 'fact', 'Previously unseen Eliot material helped flesh out the story'),
('Cats', 'Broadway Musical', 0, 'The orchestra comprised 18 musicians blending synthesizers with traditional acoustic instruments', 'orchestra', 'fact', 'The synthesizer-heavy sound was characteristic of early 1980s musical theater'),
('Cats', 'Broadway Musical', 0, 'The show grossed over $3.5 billion worldwide across all productions during its initial decades', 'numbers', 'fact', 'One of the most commercially successful entertainment properties in history'),
('Cats', 'Broadway Musical', 0, 'The costume department maintained over 200 hand-painted unitards, each unique to its character', 'design', 'fact', 'Every cat''s costume was individually designed to reflect that character''s personality'),
('Cats', 'Broadway Musical', 0, 'The Winter Garden Theatre had seats removed from the front orchestra to extend the junkyard set', 'design', 'fact', 'Audience members sat among the trash, blurring the line between stage and house'),
('Cats', 'Broadway Musical', 0, 'A 2016 revival at the Neil Simon Theatre ran for 596 performances', 'numbers', 'fact', 'Andy Blankenbuehler choreographed the revival with updated movement'),
('Cats', 'Broadway Musical', 0, 'The show opened in London''s West End in 1981 before Broadway, running for 21 years and 8,949 performances', 'numbers', 'fact', 'The London production was the longest-running West End show for years'),
('Cats', 'Broadway Musical', 0, 'The original production used no traditional scenery flats', 'design', 'fact', 'All action took place in a single, unchanging setting'),
('Cats', 'Broadway Musical', 0, 'The show originally had no plot — the composer and director had to create a narrative structure', 'history', 'fact', 'Trevor Nunn suggested the throughline about redemption and selection'),
('Cats', 'Broadway Musical', 0, 'The sound design used body microphones on every cast member', 'technical', 'fact', 'Maintaining clear sound for 30+ wireless microphones simultaneously was a major challenge'),
('Cats', 'Broadway Musical', 0, 'National and international touring productions collectively played in over 300 cities and 26 countries', 'numbers', 'fact', 'One of the most widely toured shows in theatrical history'),
('Cats', 'Broadway Musical', 0, 'The original production budget was approximately $5 million, recouped within the first year', 'numbers', 'fact', 'A strong return on investment that launched a mega-musical era'),
('Cats', 'Broadway Musical', 0, 'Actors performed on hard surfaces for the entire show without intermission seating', 'backstage', 'fact', 'The physical demands led to a higher-than-average injury rate'),
('Cats', 'Broadway Musical', 0, 'A makeup bible was created with step-by-step instructions for every character''s elaborate look', 'backstage', 'fact', 'The makeup bible ensured consistency across thousands of performances worldwide'),

-- ============================================================
-- MISS SAIGON
-- ============================================================
('Miss Saigon', 'Broadway Musical', 0, 'A full-size helicopter appears to land on stage using a hydraulic platform and a descending fuselage weighing', 'technical', 'fact', 'The helicopter evacuation scene became one of the most famous special effects in theater history'),
('Miss Saigon', 'Broadway Musical', 0, 'Based on Puccini''s "Madama Butterfly," transposed from 1900s Japan to 1970s Vietnam', 'history', 'fact', 'The same team behind Les Miserables adapted the classic opera into a modern setting'),
('Miss Saigon', 'Broadway Musical', 0, 'The original Broadway production ran for 4,092 performances at the Broadway Theatre from 1991 to 2001', 'numbers', 'fact', 'The sixth-longest-running show in Broadway history at the time of its closing'),
('Miss Saigon', 'Broadway Musical', 0, 'Advance ticket sales totaled $37 million before the first Broadway performance — a record at the time', 'numbers', 'fact', 'The hype from the London production drove unprecedented demand'),
('Miss Saigon', 'Broadway Musical', 0, 'A casting controversy erupted when the Actors'' Equity Association initially refused to allow the original', 'culture', 'fact', 'The debate over casting a white actor in an Asian role made international headlines'),
('Miss Saigon', 'Broadway Musical', 0, 'The set by John Napier included a 3-story structure that transformed from a Saigon nightclub to a reeducation', 'design', 'fact', 'Massive automated scenic elements reshaped the stage for each location'),
('Miss Saigon', 'Broadway Musical', 0, 'The production used over 6,000 rounds of blank ammunition per week for the battle sequences', 'backstage', 'fact', 'Pyrotechnic effects required a dedicated special effects operator at every performance'),
('Miss Saigon', 'Broadway Musical', 0, 'The original orchestra comprised 24 musicians blending a Western pit band with synthesizers emulating', 'orchestra', 'fact', 'Claude-Michel Schonberg''s score mixed Western pop with Asian-influenced melodies'),
('Miss Saigon', 'Broadway Musical', 0, 'The helicopter sequence required 7 automated winches, 3 hydraulic platforms, and a dedicated effects crew of 4', 'technical', 'fact', 'The engineering behind the helicopter was one of the most complex effects ever staged on Broadway'),
('Miss Saigon', 'Broadway Musical', 0, 'The costume department maintained over 350 costumes per production including military uniforms', 'design', 'fact', 'The costume changes spanned multiple eras and locations'),
('Miss Saigon', 'Broadway Musical', 0, 'The show''s producers conducted an international talent search across Asia to cast the lead female roles', 'cast', 'fact', 'Lea Salonga was discovered performing in Manila and was cast at age 17'),
('Miss Saigon', 'Broadway Musical', 0, 'Alain Boublil conceived the idea after seeing a photo of a Vietnamese mother sending her child away', 'history', 'fact', 'A single photograph inspired the entire musical'),
('Miss Saigon', 'Broadway Musical', 0, 'The fall-of-Saigon sequence used strobe lighting, fog machines', 'technical', 'fact', 'Multiple technical effects combined to create controlled on-stage pandemonium'),
('Miss Saigon', 'Broadway Musical', 0, 'The production budget for the original Broadway staging exceeded $10 million', 'numbers', 'fact', 'Among the most expensive Broadway productions of the early 1990s'),
('Miss Saigon', 'Broadway Musical', 0, 'The 2017 Broadway revival updated the helicopter sequence with LED screens and projection mapping', 'technical', 'fact', 'New technology replaced the original mechanical effect'),
('Miss Saigon', 'Broadway Musical', 0, 'Cameron Mackintosh produced the show, continuing his streak after Les Miserables and The Phantom of the Opera', 'production', 'fact', 'Three of the biggest mega-musicals were produced by the same person'),
('Miss Saigon', 'Broadway Musical', 0, 'The London production opened in 1989 at the Theatre Royal Drury Lane and ran for 4,264 performances', 'numbers', 'fact', 'The London run actually exceeded the Broadway run'),
('Miss Saigon', 'Broadway Musical', 0, 'The backstage crew numbered over 50, including dedicated pyrotechnics operators, fly crew', 'backstage', 'fact', 'One of the most crew-intensive shows on Broadway'),
('Miss Saigon', 'Broadway Musical', 0, 'The original lighting design used over 800 instruments to simulate everything from neon bars to jungles', 'technical', 'fact', 'David Hersey''s lighting captured the full range from intimacy to warfare'),
('Miss Saigon', 'Broadway Musical', 0, 'The lead actress won the 1991 Tony for Best Actress in a Musical at just 20 years old', 'award', 'fact', 'One of the youngest Tony winners in the leading actress category'),
('Miss Saigon', 'Broadway Musical', 0, 'The 2017 revival ran for 759 performances at the Broadway Theatre — the same venue as the original', 'numbers', 'fact', 'Returning to the same theater 16 years after the original closed'),
('Miss Saigon', 'Broadway Musical', 0, 'The show toured continuously for over a decade', 'numbers', 'fact', 'At peak, multiple tours were playing around the world at the same time'),
('Miss Saigon', 'Broadway Musical', 0, 'The sound design used over 40 wireless microphones and complex mixing to balance ballads with battle scenes', 'technical', 'fact', 'The dynamic range from whispered love songs to explosive battle scenes was extreme'),
('Miss Saigon', 'Broadway Musical', 0, 'The property department maintained real dog tags, period military equipment', 'backstage', 'fact', 'Historical accuracy in props grounded the spectacle in reality'),
('Miss Saigon', 'Broadway Musical', 0, 'The composing team spent 3 years researching the Vietnam War and the fall of Saigon before writing the score', 'production', 'fact', 'Boublil and Schonberg immersed themselves in historical documentation'),

-- ============================================================
-- BEAUTY AND THE BEAST
-- ============================================================
('Beauty and the Beast', 'Broadway Musical', 0, 'The first theatrical production from a film studio''s newly created stage division', 'history', 'fact', 'Disney Theatrical Productions was created specifically to bring this show to Broadway'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The original production ran for 5,461 performances over 13 years at the Palace and Lunt-Fontanne Theatres', 'numbers', 'fact', 'The ninth-longest-running show in Broadway history'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The lead actor''s prosthetic makeup and costume required over 90 minutes to apply before each performance', 'backstage', 'fact', 'The full beast makeup included a heavy prosthetic headpiece, body suit, and mechanical jaw'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Ann Hould-Ward won the Tony Award for Best Costume Design for creating the enchanted objects'' costumes', 'award', 'fact', 'The costumes turned human actors into a candelabra, clock, teapot, and other household items'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The transformation scene used a combination of pyrotechnics, fog, strobe lighting', 'technical', 'fact', 'The climactic transformation was the show''s most complex technical moment'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Based on the 1991 animated film, which was itself based on Jeanne-Marie Leprince de Beaumont''s 1756 fairy tale', 'history', 'fact', 'The stage version expanded the film with additional songs and scenes'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Eight new songs were written by Alan Menken and Tim Rice for the stage production', 'production', 'fact', 'The expanded score gave depth to characters who had limited screen time'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The enchanted objects costumes weighed up to 40 pounds each and required actors to perform complex', 'design', 'fact', 'The candelabra costume alone had working flame effects in the fingertips'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Stan Meyer''s set design included a library with over 1', 'design', 'fact', 'The castle interior sets were among the most elaborate on Broadway'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The original orchestra comprised 27 musicians performing Alan Menken''s expanded orchestrations', 'orchestra', 'fact', 'Michael Starobin''s orchestrations added richness beyond the film''s score'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The show helped catalyze the revitalization of Times Square and 42nd Street in the mid-1990s', 'culture', 'fact', 'Disney''s investment in the New Amsterdam Theatre was part of the neighborhood''s transformation'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Natasha Katz''s lighting design used over 600 lighting instruments to create the enchanted castle effects', 'technical', 'fact', 'Shifting light was essential to conveying the curse and the magic'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The prop department maintained a rose under a glass dome that featured an internally lit practical wilting', 'design', 'fact', 'The enchanted rose was a signature prop that required careful maintenance'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The show grossed over $1.4 billion worldwide across all productions', 'numbers', 'fact', 'One of the highest-grossing stage productions in entertainment history'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Touring productions visited over 100 cities worldwide', 'numbers', 'fact', 'The show became a truly global theatrical franchise'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The wardrobe department maintained over 300 costumes including the iconic yellow ballgown', 'design', 'fact', 'The ballgown required a dedicated quick-change team of three dressers'),
('Beauty and the Beast', 'Broadway Musical', 0, 'Robert Jess Roth directed the original production, which had its world premiere in Houston before Broadway', 'production', 'fact', 'The Houston tryout at the Music Hall ran for 6 weeks in 1993'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The tavern scene required the prop department to maintain 40 beer steins, 12 plates of fake food', 'backstage', 'fact', 'The boisterous pub set was one of the most prop-heavy scenes'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The automation system controlled over 20 flying scenic elements including a magic mirror and enchanted forest', 'technical', 'fact', 'The show''s scenic movement was among the most complex of its era'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The opening night on April 18, 1994, was attended by the head of the film studio', 'culture', 'fact', 'Michael Eisner''s presence symbolized a new era of corporate Broadway'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The show received mixed critical reviews but became a box office juggernaut driven by family audiences', 'culture', 'fact', 'Critical skepticism about Disney on Broadway was overwhelmed by commercial success'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The backstage crew numbered over 40, with specialized operators for automation, pyrotechnics, and flying rigs', 'backstage', 'fact', 'The technical demands required a larger crew than most Broadway shows'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The original production received 9 Tony Award nominations but won only one', 'award', 'fact', 'Despite commercial success, the Tony voters gave most awards elsewhere'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The dinner service sequence featured mechanical props including a self-pouring teapot and spinning plates', 'technical', 'fact', 'Custom-built mechanical props created the illusion of enchanted objects serving dinner'),
('Beauty and the Beast', 'Broadway Musical', 0, 'The show''s original production budget was approximately $12 million', 'numbers', 'fact', 'Disney spared no expense on their Broadway debut'),

-- ============================================================
-- JESUS CHRIST SUPERSTAR
-- ============================================================
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The concept album was released in 1970, a full year before any stage production existed', 'history', 'fact', 'The music came first — listeners experienced the show as a double LP before anyone staged it'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The composers were 21 and 25 years old when they wrote the album', 'production', 'fact', 'Andrew Lloyd Webber and Tim Rice were remarkably young when they created it'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The concept album sold over 7 million copies worldwide before the show opened on any stage', 'numbers', 'fact', 'An unprecedented commercial success for a cast album with no production'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The original 1971 Broadway production at the Mark Hellinger Theatre ran for 711 performances', 'numbers', 'fact', 'A relatively modest run for a show with such enormous cultural impact'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The show was entirely sung-through with no spoken dialogue — one of the first rock operas on Broadway', 'production', 'fact', 'The through-sung format was radical for Broadway in 1971'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'Tom O''Horgan''s original staging featured massive scaffolding and actors descending from the flies', 'design', 'fact', 'Robin Wagner''s industrial set design was deliberately confrontational'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'Religious groups picketed the theater throughout the run, protesting the show''s portrayal of biblical events', 'culture', 'fact', 'The controversy actually boosted ticket sales'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The original Broadway production used a rock band of 8 musicians augmented by a small string and brass section', 'orchestra', 'fact', 'The hybrid rock-orchestral sound was groundbreaking for Broadway'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The original staging included actors rolling across the stage on wheeled platforms and scaffolding towers', 'technical', 'fact', 'The kinetic set was in constant motion throughout the performance'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'Randy Barcelo''s costumes mixed biblical robes with glam rock, science fiction, and modern military imagery', 'design', 'fact', 'The anachronistic costume design was deliberately provocative'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'Before reaching Broadway, unauthorized concert productions were already being staged across the country based', 'history', 'fact', 'The album was so popular that fans staged their own versions without permission'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'A 1973 film adaptation was shot entirely on location in Israel', 'history', 'fact', 'Norman Jewison directed the film in authentic Middle Eastern landscapes'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'A 2000 Broadway revival ran for 161 performances and earned a Tony nomination for Best Revival', 'numbers', 'fact', 'The revival took a stripped-down approach compared to the original spectacle'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The sound system for the original production was one of the loudest ever installed in a Broadway theater', 'technical', 'fact', 'The rock music demanded amplification far beyond traditional Broadway levels'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'Arena concert tours of the show have played stadiums and arenas worldwide since the 1970s', 'culture', 'fact', 'The show works as a concert event as well as a theatrical production'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The score tells its story entirely from the perspective of Judas rather than Jesus', 'history', 'fact', 'The narrative point of view was considered theologically radical'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The original Broadway cast included Ben Vereen in a key role before he became a major star', 'cast', 'fact', 'Vereen went on to win a Tony for Pippin two years later'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The lighting design by Jules Fisher used over 300 instruments including early moving lights and concert-style', 'technical', 'fact', 'The lighting bridged rock concert aesthetics and theatrical design'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'A 2018 NBC live television broadcast attracted over 9 million viewers', 'culture', 'fact', 'John Legend starred in the live broadcast, introducing the show to a new generation'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The original concept album was recorded at Olympic Studios in London with a full rock band and 60-piece', 'orchestra', 'fact', 'The recording featured session musicians from some of the era''s biggest rock bands'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The original Broadway production''s pyrotechnic effects included flash pots and smoke bombs onstage', 'technical', 'fact', 'The climactic scene used shock effects to heighten the drama'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'Multiple countries banned the show entirely, including South Africa under apartheid', 'culture', 'fact', 'The show''s religious content provoked government censorship worldwide'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The 2012 UK arena tour used a 120-foot LED screen backdrop and concert-scale production values', 'technical', 'fact', 'Modern revivals have leaned into the show''s concert origins'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The composing team first collaborated on a short musical about a biblical figure while still students', 'history', 'fact', 'Their earlier piece "Joseph and the Amazing Technicolor Dreamcoat" started as a school concert'),
('Jesus Christ Superstar', 'Broadway Musical', 0, 'The show has been translated into over 20 languages and performed in more than 50 countries', 'numbers', 'fact', 'One of the most internationally performed musicals in history');
