-- SPIKE Clue Bank — Broadway Musical (Technical-First)
-- 15 subjects x 25 clues each = 375 clues

INSERT INTO clue_bank (show_name, category, level, clue_text, clue_type, specificity, notes) VALUES

-- ============================================================
-- HAMILTON
-- ============================================================
('Hamilton', 'Broadway Musical', 0, 'The double concentric turntable was built on top of the stage on an 8-inch raised deck', 'backstage', 'fact', 'Both rings rotate independently or together'),
('Hamilton', 'Broadway Musical', 0, 'The production runs over 100,000 individual automation cues for the turntable alone', 'technical', 'fact', 'Each start/stop of each ring is a separate cue'),
('Hamilton', 'Broadway Musical', 0, 'The touring production uses over 350 lighting instruments and more than 1,000 light cues', 'technical', 'fact', 'Broadway production uses 856 lighting cues'),
('Hamilton', 'Broadway Musical', 0, 'The drummer is isolated in a room behind the pit and syncs with the conductor via live video feed', 'orchestra', 'fact', 'Prevents drum bleed into vocal mics'),
('Hamilton', 'Broadway Musical', 0, 'The 10-piece orchestra includes two keyboards, drums, percussion, bass, guitar, and a string quartet', 'orchestra', 'fact', 'Conductor plays the first keyboard part'),
('Hamilton', 'Broadway Musical', 0, 'The costume shop created a proprietary fabric color called HAMIL-TAN for the show', 'design', 'fact', 'A camel-colored custom weave'),
('Hamilton', 'Broadway Musical', 0, 'All costume fabrics were custom-woven and dyed in France and England', 'design', 'fact', 'Military wools hand-woven for ensemble'),
('Hamilton', 'Broadway Musical', 0, 'Every pair of shoes in the production is custom-made for each performer', 'design', 'fact', 'Period-accurate but built for dancing'),
('Hamilton', 'Broadway Musical', 0, 'David Korins considered 33 different shades of brick for the set walls before choosing the final color', 'design', 'fact', 'Most surfaces are actually painted homasote and vacuform, not real brick'),
('Hamilton', 'Broadway Musical', 0, 'The set took over 500 person-days to engineer, build, paint, and automate', 'backstage', 'fact', 'Back wall is a soft drop painted to look like real brick'),
('Hamilton', 'Broadway Musical', 0, 'The sound design uses speakers that can electronically direct where sound is physically aimed', 'technical', 'fact', 'Some of the first of their kind in a Broadway production'),
('Hamilton', 'Broadway Musical', 0, 'Received a record-setting 16 Tony nominations in 2016', 'award', 'fact', 'Won 11, the second most wins ever behind The Producers'),
('Hamilton', 'Broadway Musical', 0, 'Won the 2016 Pulitzer Prize for Drama', 'award', 'fact', 'Only the second musical ever to win the Pulitzer after A Chorus Line'),
('Hamilton', 'Broadway Musical', 0, 'The cast album was certified Diamond by the RIAA with 10 million units sold', 'numbers', 'fact', 'Achieved in June 2023'),
('Hamilton', 'Broadway Musical', 0, 'Has grossed over $1.143 billion on Broadway alone', 'numbers', 'fact', 'One of the highest-grossing productions in Broadway history'),
('Hamilton', 'Broadway Musical', 0, 'Six original crew members from the Public Theater run still work the show after a decade', 'backstage', 'fact', 'Plus 6 musicians, 2 wardrobe, 2 box office'),
('Hamilton', 'Broadway Musical', 0, 'Men''s shirts were made by Darcy Clothing, the same company that makes Pride and Prejudice costumes', 'design', 'fact', 'Period-appropriate high-collar design'),
('Hamilton', 'Broadway Musical', 0, 'Opened August 6, 2015, at the Richard Rodgers Theatre', 'production', 'fact', 'After a sold-out run at the Public Theater'),
('Hamilton', 'Broadway Musical', 0, 'Lighting design by Howell Binkley who also designed Come From Away', 'production', 'fact', 'Binkley won the Tony for Hamilton''s lighting'),
('Hamilton', 'Broadway Musical', 0, 'Andy Blankenbuehler''s choreography integrates hip-hop, jazz, and period movement styles', 'production', 'fact', 'Won Tony for Best Choreography'),
('Hamilton', 'Broadway Musical', 0, 'The show was inspired by Ron Chernow''s 2004 biography of Alexander Hamilton', 'history', 'fact', 'Miranda read it on vacation in 2008'),
('Hamilton', 'Broadway Musical', 0, 'The original concept was a hip-hop concept album, not a stage musical', 'history', 'fact', 'Miranda performed the opening number at the White House in 2009'),
('Hamilton', 'Broadway Musical', 0, 'Played a sold-out workshop run at Vassar''s Powerhouse Theater before the Public', 'history', 'fact', 'Summer 2013 workshop'),
('Hamilton', 'Broadway Musical', 0, 'Paul Tazewell won his second Tony Award for the costume design', 'award', 'fact', 'Designs blend 18th-century silhouettes with modern streetwear'),
('Hamilton', 'Broadway Musical', 0, 'Nevin Steinberg''s sound design won the Tony, his first of multiple Broadway sound awards', 'award', 'fact', 'Later won for Hadestown as well'),

-- ============================================================
-- WICKED
-- ============================================================
('Wicked', 'Broadway Musical', 0, 'The production uses 62 motorized steel bars that can be automatically raised and lowered', 'technical', 'fact', 'Part of the extensive fly automation system'),
('Wicked', 'Broadway Musical', 0, 'The show deck features 7 automated tracks lined with steel for moving scenery on rails', 'backstage', 'fact', 'Deck carts pulled by steel cables; crew pins scenery manually'),
('Wicked', 'Broadway Musical', 0, 'Over 800 lights are used to give each of 54 distinct scenes its own mood', 'technical', 'fact', 'Lighting design by Kenneth Posner'),
('Wicked', 'Broadway Musical', 0, 'Glinda''s bubble dress is adorned with 68,200 individual sequins', 'design', 'fact', 'Hand-applied to the costume'),
('Wicked', 'Broadway Musical', 0, 'Elphaba''s skirt uses 290 yards of bias-cut ruffles in 37 different fabrics', 'design', 'fact', 'Susan Hilferty''s Tony-winning design'),
('Wicked', 'Broadway Musical', 0, 'The production maintains 120 wigs, with 3 wigs per role valued at $3,000-$4,000 each', 'design', 'fact', 'Tom Watson''s wig design'),
('Wicked', 'Broadway Musical', 0, 'Every Elphaba applies MAC Chromacake in Landscape Green for consistency under stage lighting', 'design', 'fact', 'Product chosen specifically for how it reads under theatrical light'),
('Wicked', 'Broadway Musical', 0, 'Elphaba''s flying rig for Defying Gravity is a boom lift with a custom basket built by ZFX', 'backstage', 'fact', 'A Plan B no-fly sequence exists in case of hydraulic failure'),
('Wicked', 'Broadway Musical', 0, 'Spaces under the stage house quick-change areas, sound equipment, automation controls, and hydraulic machinery', 'backstage', 'fact', 'The understage is nearly as busy as the stage'),
('Wicked', 'Broadway Musical', 0, 'The 23-member orchestra is one of the largest currently on Broadway', 'orchestra', 'fact', 'Includes 4 keyboard synthesizers'),
('Wicked', 'Broadway Musical', 0, 'Over 200 costumes in a twisted Edwardian style are maintained for each production', 'design', 'fact', 'Susan Hilferty won the Tony for Best Costume Design'),
('Wicked', 'Broadway Musical', 0, 'Surpassed 7,486 performances as of April 2023, making it the fourth longest-running Broadway show', 'numbers', 'fact', 'Behind Phantom, Chicago, and The Lion King'),
('Wicked', 'Broadway Musical', 0, 'Became the first Broadway show to earn over $5 million in a single week in late 2024', 'numbers', 'fact', 'Driven by the film release'),
('Wicked', 'Broadway Musical', 0, 'Surpassed $1 billion in Broadway revenue in 2016', 'numbers', 'fact', 'One of the highest-grossing productions ever'),
('Wicked', 'Broadway Musical', 0, 'Received 10 Tony nominations and won 3: Best Actress, Best Scenic Design, and Best Costume Design', 'award', 'fact', 'Idina Menzel won Best Actress for originating Elphaba'),
('Wicked', 'Broadway Musical', 0, 'Eugene Lee''s set design centers on a massive clock/gear motif with exposed mechanical elements', 'design', 'fact', 'Tony-winning scenic design'),
('Wicked', 'Broadway Musical', 0, 'The flying monkey puppets and Glinda''s bubble machine require multiple aerial rigs simultaneously', 'backstage', 'fact', 'Several independent fly tracks in operation'),
('Wicked', 'Broadway Musical', 0, 'Opened October 30, 2003, at the Gershwin Theatre where it still runs', 'production', 'fact', 'Gershwin is Broadway''s largest theater at 1,933 seats'),
('Wicked', 'Broadway Musical', 0, 'Directed by Joe Mantello with choreography by Wayne Cilento', 'production', 'fact', 'Mantello also directed Assassins revival and Dear Evan Hansen'),
('Wicked', 'Broadway Musical', 0, 'Music and lyrics by Stephen Schwartz, who also wrote Godspell and Pippin', 'production', 'fact', 'Schwartz also wrote lyrics for Disney''s Pocahontas and Enchanted'),
('Wicked', 'Broadway Musical', 0, 'Elaine J. McCarthy''s projection design enhances the clock tower and Emerald City sequences', 'technical', 'fact', 'Projections layer over physical scenery'),
('Wicked', 'Broadway Musical', 0, 'Over 30 performers appear on stage during large ensemble numbers', 'cast', 'fact', 'One of the larger casts on Broadway'),
('Wicked', 'Broadway Musical', 0, 'Based on Gregory Maguire''s 1995 novel reimagining the Land of Oz', 'history', 'fact', 'Book adapted by Winnie Holzman'),
('Wicked', 'Broadway Musical', 0, 'The 2024 film adaptation expanded the orchestra from 23 to 80 players', 'culture', 'fact', 'Universal Pictures production'),
('Wicked', 'Broadway Musical', 0, 'Tony Meola''s sound design manages the complex mix of 23 orchestra members and 30+ vocal mics', 'technical', 'fact', 'One of the most complex sound mixes on Broadway'),

-- ============================================================
-- THE PHANTOM OF THE OPERA
-- ============================================================
('The Phantom of the Opera', 'Broadway Musical', 0, 'The chandelier named Ruthie II weighs 1 ton and features 6,000 beads and 20 globe lights', 'backstage', 'fact', 'Named after a crew member; original London version built by 5 people in 4 weeks'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Fifty pyro elements fire with 5 different effects during each performance', 'technical', 'fact', 'Prepping pyrotechnics takes 30 minutes before every show'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Ten fog and smoke machines run throughout each performance', 'technical', 'fact', 'Plus 250 kg of dry ice per show'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Two hundred and eighty-one candles are used per performance', 'backstage', 'fact', 'Mix of real flame and electric effects'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'The Venetian gondola is remote-controlled wirelessly from offstage using a device resembling a large Atari joystick', 'backstage', 'fact', 'Steered by a single operator for the underground lake scene'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Over the Broadway run the production consumed 791,250 gallons of shot powder for flash pots', 'numbers', 'fact', 'Plus 10,550 sheets of flash paper and 37,980 lbs of dry ice'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'The production maintained 230 costumes designed by Maria Bjornson', 'design', 'fact', 'Bjornson designed both sets and costumes, a rarity on Broadway'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'One hundred and eleven wigs made of human, yak, and synthetic hair were used in each production', 'design', 'fact', 'Wig maintenance was a full-time operation'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Wrapping the chandelier in silk after pyro prep takes an additional 30 minutes each show', 'backstage', 'fact', 'Combined with pyro prep, chandelier alone needs an hour of pre-show work'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'When the chandelier crashes, fake glass shards made of safe soft polymer shower the audience', 'backstage', 'fact', 'Designed to look dangerous but be completely harmless'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'The 27-piece orchestra was one of the largest on Broadway', 'orchestra', 'fact', 'Full symphonic orchestration by David Cullen and Andrew Lloyd Webber'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Approximately 150 people worked each performance including cast, orchestra, crew, and staff', 'backstage', 'fact', 'One of the largest companies on Broadway'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Closed April 16, 2023, after 13,981 performances, the most in Broadway history', 'numbers', 'fact', 'Over 35 years on Broadway'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Grossed over $1.3 billion lifetime on Broadway with audiences exceeding 20 million', 'numbers', 'fact', 'Final week set an all-time gross record of $3.7 million'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Received 10 Tony nominations and won 7 including Best Musical', 'award', 'fact', 'Also won Best Direction for Harold Prince'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Andrew Bridge''s lighting design won the Tony and managed the complex candle and chandelier effects', 'award', 'fact', 'Pioneered theatrical candlelight simulation'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Opened January 26, 1988, at the Majestic Theatre where it ran for its entire Broadway life', 'production', 'fact', 'Previews began January 9, 1988'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Directed by Harold Prince with musical staging by Gillian Lynne', 'production', 'fact', 'Prince also directed Sweeney Todd and Evita'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Maria Bjornson served as both set and costume designer, winning Tonys for both', 'production', 'fact', 'Unusual for one designer to handle both disciplines'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'The candelabra that rise from the stage during the lake sequence use hydraulic lifts built into the stage floor', 'technical', 'fact', 'Synchronized with the gondola movement'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Martin Levan''s sound design balanced a 27-piece orchestra with intimate vocal moments in a 1,681-seat house', 'technical', 'fact', 'Pioneered techniques for mixing large orchestras in Broadway theaters'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'The original London production opened in 1986 at Her Majesty''s Theatre and is still running', 'history', 'fact', 'The longest-running show in West End history'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'Based on Gaston Leroux''s 1910 French novel', 'history', 'fact', 'Andrew Lloyd Webber composed the score'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'The masquerade ball sequence features nearly the entire company in elaborate period costumes', 'design', 'fact', 'One of the largest costume reveals on Broadway'),
('The Phantom of the Opera', 'Broadway Musical', 0, 'At the special September 29, 1983 gala, Harold Prince directed a 338-performer finale', 'culture', 'fact', 'For A Chorus Line''s record-breaking performance, but Prince''s staging methods carried to Phantom'),

-- ============================================================
-- LES MISERABLES
-- ============================================================
('Les Miserables', 'Broadway Musical', 0, 'The iconic revolving stage makes 63 rotations per performance', 'backstage', 'fact', 'Used for rapid location changes and cinematic perspective shifts'),
('Les Miserables', 'Broadway Musical', 0, 'Cast members walk against the revolve to create dramatic motion effects', 'backstage', 'fact', 'A signature staging technique of the production'),
('Les Miserables', 'Broadway Musical', 0, 'The touring production travels with its own stage installed 6-8 inches above each venue''s floor for automation', 'technical', 'fact', 'Electronics, winches, and cables run underneath'),
('Les Miserables', 'Broadway Musical', 0, 'Load-in at each touring city requires 60-70 local crew members over a 2-day build', 'backstage', 'fact', 'Plus 30 additional local crew for the run'),
('Les Miserables', 'Broadway Musical', 0, 'The barricade and Paris tower sets are a single hydraulic unit that transforms between configurations', 'technical', 'fact', 'Stored in the wings between scenes'),
('Les Miserables', 'Broadway Musical', 0, 'Uses dry ice and CO2 fog machines extensively for the sewer and waterside scenes', 'technical', 'fact', 'Atmospheric effects are critical to the storytelling'),
('Les Miserables', 'Broadway Musical', 0, 'The original production featured a 22-musician orchestra', 'orchestra', 'fact', 'One of the larger Broadway pit orchestras of its era'),
('Les Miserables', 'Broadway Musical', 0, 'Recent touring productions use a 13-player orchestra playing 24 different instruments', 'orchestra', 'fact', 'Including cor anglais, tuba, and recorder'),
('Les Miserables', 'Broadway Musical', 0, 'The 2006 revival reduced the orchestra to approximately 14 musicians', 'orchestra', 'fact', 'Smaller than the original''s 22-piece ensemble'),
('Les Miserables', 'Broadway Musical', 0, 'John Napier''s turntable-based set design became one of the most recognizable in musical theater history', 'design', 'fact', 'Napier also designed the sets for Cats and Starlight Express'),
('Les Miserables', 'Broadway Musical', 0, 'David Hersey''s lighting design uses dramatic shafts of light to create mood in the mostly bare stage', 'technical', 'fact', 'The turntable demanded flexible, dynamic lighting positions'),
('Les Miserables', 'Broadway Musical', 0, 'The original Broadway run played 6,680 performances before closing May 18, 2003', 'numbers', 'fact', 'Opened March 12, 1987, at the Broadway Theatre'),
('Les Miserables', 'Broadway Musical', 0, 'Received 12 Tony nominations and won 8 including Best Musical and Best Original Score', 'award', 'fact', 'Swept the major categories in 1987'),
('Les Miserables', 'Broadway Musical', 0, 'Music by Claude-Michel Schonberg with English lyrics by Herbert Kretzmer', 'production', 'fact', 'Original French text by Alain Boublil'),
('Les Miserables', 'Broadway Musical', 0, 'Co-directed by Trevor Nunn and John Caird', 'production', 'fact', 'Nunn also directed Cats and Sunset Boulevard'),
('Les Miserables', 'Broadway Musical', 0, 'Andreane Neofitou''s costume design spans decades of 19th-century French fashion', 'design', 'fact', 'From the Napoleonic era through the 1832 June Rebellion'),
('Les Miserables', 'Broadway Musical', 0, 'The show is entirely sung-through with no spoken dialogue', 'song', 'fact', 'One of the first major pop-opera musicals on Broadway'),
('Les Miserables', 'Broadway Musical', 0, 'Based on Victor Hugo''s 1862 novel, one of the longest novels ever written', 'history', 'fact', 'The musical covers the novel''s major storylines over a 17-year span'),
('Les Miserables', 'Broadway Musical', 0, 'Originally premiered as a French concept album in 1980 before becoming a stage musical', 'history', 'fact', 'Cameron Mackintosh produced the English adaptation'),
('Les Miserables', 'Broadway Musical', 0, 'The 2014 Broadway revival featured new staging and set design while keeping the turntable', 'history', 'fact', 'Ran at the Imperial Theatre'),
('Les Miserables', 'Broadway Musical', 0, 'Over 130 million people have seen the show worldwide across 53 countries and 22 languages', 'culture', 'fact', 'One of the most performed musicals in history'),
('Les Miserables', 'Broadway Musical', 0, 'Colm Wilkinson originated the role of Jean Valjean in both London and Broadway', 'cast', 'fact', 'Also played the Bishop in the 2012 film'),
('Les Miserables', 'Broadway Musical', 0, 'The production requires a large ensemble to fill barricade and street scenes', 'cast', 'fact', 'One of the larger casts in the touring musical repertoire'),
('Les Miserables', 'Broadway Musical', 0, 'Audience members in the front rows often feel the floor vibrate during the turntable sequences', 'backstage', 'fact', 'The mechanical revolve generates significant low-frequency vibration'),
('Les Miserables', 'Broadway Musical', 0, 'The barricade scene requires precise crew choreography to assemble furniture and props in under 60 seconds', 'backstage', 'fact', 'Timed to the musical transition between scenes'),

-- ============================================================
-- RENT
-- ============================================================
('Rent', 'Broadway Musical', 0, 'The 5-piece band is positioned visibly on stage rather than in a traditional orchestra pit', 'orchestra', 'fact', 'Keyboards, bass, guitar, drums, and piano/synth/organ'),
('Rent', 'Broadway Musical', 0, 'The industrial warehouse set uses scaffolding and raw metalwork as the primary scenic elements', 'design', 'fact', 'Paul Clay''s design evokes a real East Village loft'),
('Rent', 'Broadway Musical', 0, 'The production uses 68 costumes for 15 performers', 'design', 'fact', 'Angela Wendt''s contemporary costume design'),
('Rent', 'Broadway Musical', 0, 'The band conductor Tim Weil played keyboards on stage for the entire original run', 'orchestra', 'fact', 'One of Broadway''s longest tenures by a music director'),
('Rent', 'Broadway Musical', 0, 'Eight principal performers plus 7 ensemble members play all characters in the show', 'cast', 'fact', 'Ensemble covers dozens of minor roles'),
('Rent', 'Broadway Musical', 0, 'Blake Burba''s lighting design uses concert-style rock lighting with saturated color washes', 'technical', 'fact', 'Deliberately evokes a rock club atmosphere'),
('Rent', 'Broadway Musical', 0, 'Kurt Fischer''s sound design balances a rock band with unamplified vocal moments', 'technical', 'fact', 'The mix shifts between concert and intimate styles'),
('Rent', 'Broadway Musical', 0, 'The dark, gray, industrial color palette deliberately avoids bright theatrical colors', 'design', 'fact', 'Matches the show''s East Village setting'),
('Rent', 'Broadway Musical', 0, 'The scaffolding set allows performers to play scenes on multiple vertical levels simultaneously', 'design', 'fact', 'Creates visual depth on a single stage'),
('Rent', 'Broadway Musical', 0, 'Ran for 5,123 performances before closing September 7, 2008', 'numbers', 'fact', 'At the Nederlander Theatre for its entire run'),
('Rent', 'Broadway Musical', 0, 'Won 4 Tony Awards including Best Musical, Best Book, and Best Original Score', 'award', 'fact', 'Wilson Jermaine Heredia won Best Featured Actor'),
('Rent', 'Broadway Musical', 0, 'Won the 1996 Pulitzer Prize for Drama', 'award', 'fact', 'One of the few musicals to win the Pulitzer'),
('Rent', 'Broadway Musical', 0, 'Opened April 29, 1996, at the Nederlander Theatre', 'production', 'fact', 'After an Off-Broadway run at New York Theatre Workshop'),
('Rent', 'Broadway Musical', 0, 'Directed by Michael Greif who later directed Dear Evan Hansen', 'production', 'fact', 'Greif''s direction defined the downtown aesthetic'),
('Rent', 'Broadway Musical', 0, 'Choreographed by Marlies Yearby who incorporated street dance and everyday movement', 'production', 'fact', 'Deliberately anti-traditional Broadway choreography'),
('Rent', 'Broadway Musical', 0, 'Creator Jonathan Larson died of an aortic aneurysm the night before the Off-Broadway opening', 'history', 'fact', 'January 25, 1996, at age 35'),
('Rent', 'Broadway Musical', 0, 'Originally workshopped at New York Theatre Workshop starting in 1994', 'history', 'fact', 'Larson spent seven years writing and revising the show'),
('Rent', 'Broadway Musical', 0, 'The front rows of the Nederlander were sold as $20 rush tickets for every performance', 'culture', 'fact', 'Created a new model for accessible Broadway pricing'),
('Rent', 'Broadway Musical', 0, 'Loosely based on Puccini''s opera La Boheme, transposed to 1990s New York', 'history', 'fact', 'Both stories center on artists struggling with poverty and illness'),
('Rent', 'Broadway Musical', 0, 'Received 10 Tony nominations in 1996', 'award', 'fact', 'Competed against Bring in ''da Noise, Bring in ''da Funk'),
('Rent', 'Broadway Musical', 0, 'The show popularized the rock musical format that influenced Spring Awakening and Hadestown', 'culture', 'fact', 'Proved rock scores could succeed on Broadway'),
('Rent', 'Broadway Musical', 0, 'Original cast included Daphne Rubin-Vega, Adam Pascal, Anthony Rapp, and Idina Menzel', 'cast', 'fact', 'Many went on to major film and Broadway careers'),
('Rent', 'Broadway Musical', 0, 'Taye Diggs made his Broadway debut as Benny in the original cast', 'cast', 'fact', 'Launched his film career'),
('Rent', 'Broadway Musical', 0, 'The song Seasons of Love became a pop-culture standard, performed at countless memorials and events', 'song', 'fact', 'Opens Act 2 with the full cast lined up at the front of the stage'),
('Rent', 'Broadway Musical', 0, 'Set design deliberately leaves the backstage walls and rigging visible to the audience', 'design', 'fact', 'Breaking the fourth wall is built into the scenic concept'),

-- ============================================================
-- DEAR EVAN HANSEN
-- ============================================================
('Dear Evan Hansen', 'Broadway Musical', 0, 'Peter Nigrini''s projection design creates a cast of three dozen virtual characters on stage', 'technical', 'fact', 'Social media posts and texts projected in real-time'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Three Disguise vx 4 and four gx 1 media servers power the projection system', 'technical', 'fact', 'Seven total media servers for a single production'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Every surface of the playing space can be covered by projected content including the stage floor', 'technical', 'fact', 'Uses front projection, portals, tracking panels, and LCD monitors'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'The real-time projection workflow accommodates rotating cast members who appear in pre-recorded video footage', 'technical', 'fact', 'System updates when new cast members join'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'The arm cast prop is made of woven plastic tape wrapped around a stockinette sleeve', 'design', 'fact', 'Applied by the wig/hair supervisor at half-hour call before every show'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'The arm cast is sawed off during intermission and rebuilt fresh for each performance', 'backstage', 'fact', 'Connor written in black marker each time'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'The 8-piece orchestra includes violin, viola, cello, two guitars, bass, drums, and keyboards', 'orchestra', 'fact', 'Intimate instrumentation matching the show''s personal scale'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Japhy Weideman''s lighting design shifts between warm domestic scenes and cold digital isolation', 'technical', 'fact', 'Lighting mirrors Evan''s emotional state throughout'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Nevin Steinberg''s sound design blends live vocals with the digitally projected social media world', 'technical', 'fact', 'Sound reinforcement keeps the intimate feel despite digital elements'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'David Korins''s set transforms from domestic interiors to a vast digital landscape using projections', 'design', 'fact', 'Korins also designed Hamilton and Beetlejuice'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Won 6 Tony Awards including Best Musical, Best Score, Best Book, and Best Actor', 'award', 'fact', 'Ben Platt and Rachel Bay Jones both won acting awards'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Alex Lacamoire won his second Tony for Best Orchestrations after winning for Hamilton', 'award', 'fact', 'Back-to-back wins in consecutive years'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Received 9 Tony nominations in 2017', 'award', 'fact', 'Dominated the musical categories'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Ran approximately 1,678 performances before closing September 18, 2022', 'numbers', 'fact', 'At the Music Box Theatre for its entire run'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Opened December 4, 2016, at the Music Box Theatre', 'production', 'fact', 'Previews began November 14, 2016'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Music and lyrics by Benj Pasek and Justin Paul who also wrote La La Land and The Greatest Showman', 'production', 'fact', 'Won both Tony and Oscar in the same year'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Directed by Michael Greif who also directed Rent', 'production', 'fact', 'Both shows deal with youth, loss, and community'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Book by Steven Levenson adapted from an original concept, not a pre-existing source', 'history', 'fact', 'Rare for a major musical to have a completely original story'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Workshopped at Arena Stage in Washington, D.C. before moving to Off-Broadway', 'history', 'fact', 'Second Stage Theatre production preceded Broadway'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Ben Platt originated the role at age 22 and won the Tony for Best Actor in a Musical', 'cast', 'fact', 'One of the youngest Best Actor winners in Tony history'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Rachel Bay Jones won the Tony for Best Featured Actress originating the role of Heidi Hansen', 'cast', 'fact', 'Her first Tony nomination and win'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'The show addressed social media, teen mental health, and anxiety before these became mainstream topics', 'culture', 'fact', 'Resonated strongly with younger audiences'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Waving Through a Window became a viral hit with over 100 million streams', 'song', 'fact', 'Crossed over from cast album to mainstream pop'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'The 2021 film adaptation starred Ben Platt reprising his stage role', 'culture', 'fact', 'Universal Pictures production'),
('Dear Evan Hansen', 'Broadway Musical', 0, 'Emily Rebholz''s costume design uses everyday teen clothing to ground the characters in reality', 'design', 'fact', 'Deliberately anti-theatrical to match the naturalistic tone'),

-- ============================================================
-- HADESTOWN
-- ============================================================
('Hadestown', 'Broadway Musical', 0, 'The stage splits apart and moves back approximately 7 feet to expose a third turntable for the underworld descent', 'backstage', 'fact', 'Multiple turntable elements create the journey between worlds'),
('Hadestown', 'Broadway Musical', 0, 'Bradley King''s lighting rig features a circular truss over the stage with Martin MAC Encore Spots and Viper Washes', 'technical', 'fact', 'Won the Tony for Best Lighting Design'),
('Hadestown', 'Broadway Musical', 0, 'MAC III AirFXs in the grid create shaft-of-light effects for the underworld sequences', 'technical', 'fact', 'Dramatic narrow beams cut through haze'),
('Hadestown', 'Broadway Musical', 0, 'The Wait for Me sequence features swinging lamps inspired by highway headlights', 'technical', 'fact', 'Director Rachel Chavkin''s original vision from early workshops'),
('Hadestown', 'Broadway Musical', 0, 'Four-lite blinder units are embedded in the back and side walls of the set', 'technical', 'fact', 'Create harsh industrial lighting for Hades'' factory'),
('Hadestown', 'Broadway Musical', 0, 'X-Bar fixtures wash the exposed back wall for atmosphere changes between worlds', 'technical', 'fact', 'Part of Bradley King''s integrated lighting/set approach'),
('Hadestown', 'Broadway Musical', 0, 'The 7-piece band performs on stage throughout the show with the percussionist backstage', 'orchestra', 'fact', 'Musicians are treated as characters in the storytelling'),
('Hadestown', 'Broadway Musical', 0, 'In Our Lady of the Underground, Persephone introduces each musician by name for solo applause', 'orchestra', 'fact', 'Breaking the fourth wall as a deliberate theatrical device'),
('Hadestown', 'Broadway Musical', 0, 'Rachel Hauck''s industrial-aesthetic set features a central revolving platform', 'design', 'fact', 'Won the Tony for Best Scenic Design'),
('Hadestown', 'Broadway Musical', 0, 'The turntable serves as a visual motif representing the descent to the underworld', 'design', 'fact', 'Rotation accelerates during key dramatic moments'),
('Hadestown', 'Broadway Musical', 0, 'Nevin Steinberg and Jessica Paz''s sound design won the Tony for mixing an onstage band with vocals', 'technical', 'fact', 'Steinberg also won for Hamilton'),
('Hadestown', 'Broadway Musical', 0, 'Received 14 Tony nominations and won 8 including Best Musical and Best Direction', 'award', 'fact', 'The most nominated new musical of the 2018-2019 season'),
('Hadestown', 'Broadway Musical', 0, 'Andre De Shields won the Tony for Best Featured Actor as Hermes at age 73', 'award', 'fact', 'His first Tony win after a 50+ year career'),
('Hadestown', 'Broadway Musical', 0, 'Won the 2020 Grammy Award for Best Musical Theater Album', 'award', 'fact', 'Anais Mitchell''s score'),
('Hadestown', 'Broadway Musical', 0, 'Michael Chorney and Todd Sickafoose won the Tony for Best Orchestrations', 'award', 'fact', 'New Orleans jazz-folk-indie rock fusion'),
('Hadestown', 'Broadway Musical', 0, 'Ran approximately 2,236 performances, the longest run in Walter Kerr Theatre history', 'numbers', 'fact', 'Closed September 6, 2025'),
('Hadestown', 'Broadway Musical', 0, 'Opened April 17, 2019, at the Walter Kerr Theatre', 'production', 'fact', 'Previews began March 22, 2019'),
('Hadestown', 'Broadway Musical', 0, 'Directed by Rachel Chavkin who also directed Natasha, Pierre & The Great Comet of 1812', 'production', 'fact', 'Won the Tony for Best Direction'),
('Hadestown', 'Broadway Musical', 0, 'Music, lyrics, and book by Anais Mitchell, originally conceived as a folk opera concept album in 2010', 'history', 'fact', 'Evolved from album to stage show over nearly a decade'),
('Hadestown', 'Broadway Musical', 0, 'Developed at New York Theatre Workshop before transferring to Broadway', 'history', 'fact', 'Also staged in Edmonton and London'),
('Hadestown', 'Broadway Musical', 0, 'Approximately 13 performers on stage: 5 principals, 3 Fates, and 5 Workers', 'cast', 'fact', 'Intimate cast for a Tony-winning Best Musical'),
('Hadestown', 'Broadway Musical', 0, 'Michael Krass''s costume design blends Depression-era workwear with mythological elements', 'design', 'fact', 'Hades in a sharp suit, workers in industrial coveralls'),
('Hadestown', 'Broadway Musical', 0, 'David Neumann''s choreography incorporates repetitive labor movements for the workers', 'production', 'fact', 'Physical storytelling reinforces the factory setting'),
('Hadestown', 'Broadway Musical', 0, 'Retells the Greek myth of Orpheus and Eurydice set in a Depression-era underworld', 'plot', 'fact', 'Hades runs the underworld as an industrial operation'),
('Hadestown', 'Broadway Musical', 0, 'The show''s circular narrative structure mirrors the myth''s eternal recurrence', 'song', 'fact', 'Road to Hell opens and closes the show'),

-- ============================================================
-- THE LION KING
-- ============================================================
('The Lion King', 'Broadway Musical', 0, 'The production uses 232 puppets including rod puppets, shadow puppets, full-body puppets, and bunraku-style figures', 'design', 'fact', 'Designed by Julie Taymor and Michael Curry'),
('The Lion King', 'Broadway Musical', 0, 'It took 37,000 hours to create the original masks and puppets', 'backstage', 'fact', 'Three puppeteers travel with the show for maintenance and actor training'),
('The Lion King', 'Broadway Musical', 0, 'Mufasa and Scar''s mechanical headpieces use cables that raise and lower to simulate lunging', 'backstage', 'fact', 'Reduced from 10 cables to about 4 over the years for reliability'),
('The Lion King', 'Broadway Musical', 0, 'Pride Rock is mechanically operated from 35 feet up in the wings and collapses to only 8 feet long', 'technical', 'fact', 'Moves and turns in multiple directions'),
('The Lion King', 'Broadway Musical', 0, 'The 23-member orchestra plays 132 different instruments during each performance', 'orchestra', 'fact', 'One of the largest and most diverse Broadway orchestras'),
('The Lion King', 'Broadway Musical', 0, 'Four percussionists alone play 87 different instruments', 'orchestra', 'fact', 'Including African drums, marimbas, and found percussion'),
('The Lion King', 'Broadway Musical', 0, 'Two percussion players are positioned at the sides of the stage rather than in the pit', 'orchestra', 'fact', 'Creates spatial sound surrounding the audience'),
('The Lion King', 'Broadway Musical', 0, 'Over 350 costumes are maintained, some decorated with thousands of individually hand-sewn beads', 'design', 'fact', 'Julie Taymor won the Tony for Best Costume Design'),
('The Lion King', 'Broadway Musical', 0, 'Timon''s puppet design is based on the Japanese bunraku puppet tradition', 'design', 'fact', 'The puppeteer is fully visible in traditional bunraku style'),
('The Lion King', 'Broadway Musical', 0, 'Approximately 50 performers appear on stage with about 100 staff working backstage', 'backstage', 'fact', 'Total company of 162 including cast, crew, orchestra, and staff'),
('The Lion King', 'Broadway Musical', 0, 'Richard Hudson''s set design won the Tony and centers on a sun-disc backdrop and Pride Rock', 'design', 'fact', 'Minimal set allows puppetry to define the space'),
('The Lion King', 'Broadway Musical', 0, 'Donald Holder''s lighting design won the Tony for creating African savanna light', 'technical', 'fact', 'Shifts from golden sunrise to cool moonlight throughout'),
('The Lion King', 'Broadway Musical', 0, 'Has grossed over $2 billion on Broadway, the highest of any production in history', 'numbers', 'fact', 'Worldwide gross exceeds any entertainment title in history'),
('The Lion King', 'Broadway Musical', 0, 'Celebrated its 11,000th Broadway performance in September 2025', 'numbers', 'fact', 'Running since 1997'),
('The Lion King', 'Broadway Musical', 0, 'Over 100 million people have seen the show worldwide', 'numbers', 'fact', 'Across 100+ cities in 21 countries'),
('The Lion King', 'Broadway Musical', 0, 'Won 6 Tony Awards including Best Musical and Best Direction', 'award', 'fact', 'Julie Taymor was the first woman to win Tony for Best Direction'),
('The Lion King', 'Broadway Musical', 0, 'Garth Fagan won the Tony for Best Choreography blending African dance with modern movement', 'award', 'fact', 'Fagan had no prior Broadway experience'),
('The Lion King', 'Broadway Musical', 0, 'Opened November 13, 1997, at the New Amsterdam Theatre, moved to the Minskoff in 2006', 'production', 'fact', 'Anchored Disney''s 42nd Street renovation'),
('The Lion King', 'Broadway Musical', 0, 'Directed by Julie Taymor who also designed costumes and co-designed puppets', 'production', 'fact', 'Rare triple creative role on Broadway'),
('The Lion King', 'Broadway Musical', 0, 'Lebo M contributes original South African choral arrangements and vocals', 'production', 'fact', 'His vocal work defines the show''s sound'),
('The Lion King', 'Broadway Musical', 0, 'The opening Circle of Life sequence features a procession of animal puppets through the audience', 'backstage', 'fact', 'One of Broadway''s most iconic opening moments'),
('The Lion King', 'Broadway Musical', 0, 'Shadow puppetry is used for the wildebeest stampede sequence', 'design', 'fact', 'Creates the illusion of a vast herd'),
('The Lion King', 'Broadway Musical', 0, 'The grasslands are represented by performers wearing grass-like headdresses that sway in unison', 'design', 'fact', 'Actors become the environment through Taymor''s design'),
('The Lion King', 'Broadway Musical', 0, 'Instrumentation includes wood flute, concertmistress, French horns, trombone, tuba, and 3 keyboard synthesizers', 'orchestra', 'fact', 'Blends Western orchestral and African instruments'),
('The Lion King', 'Broadway Musical', 0, 'Received 11 Tony nominations in 1998', 'award', 'fact', 'Competed against Ragtime for Best Musical'),

-- ============================================================
-- COME FROM AWAY
-- ============================================================
('Come From Away', 'Broadway Musical', 0, 'The entire set consists of a wood floor, wood wall backdrop, a turntable, and approximately 12 chairs plus tables', 'design', 'fact', 'One of the most minimal sets for a major Broadway musical'),
('Come From Away', 'Broadway Musical', 0, 'The 12 chairs become everything: airplane cabins, buses, Tim Hortons, and the Gander Legion hall', 'backstage', 'fact', 'Actors transform the space through choreographed chair movement'),
('Come From Away', 'Broadway Musical', 0, 'Character transformations are achieved with one or two costume pieces maximum: hats, glasses, or scarves', 'design', 'fact', 'Each actor has a single base costume'),
('Come From Away', 'Broadway Musical', 0, '12 actors play approximately 100 real people from Gander, Newfoundland and stranded passengers', 'cast', 'fact', 'Characters based on real people the writers interviewed'),
('Come From Away', 'Broadway Musical', 0, 'The 8-piece onstage folk and Celtic band is situated behind the set''s trees', 'orchestra', 'fact', 'Visible to the audience throughout the performance'),
('Come From Away', 'Broadway Musical', 0, 'The turntable rotates as actors pass off glasses and hats to transform between characters', 'backstage', 'fact', 'Seamless transitions driven by Kelly Devine''s staging'),
('Come From Away', 'Broadway Musical', 0, 'Howell Binkley''s lighting design shifts between warm Gander hospitality and cold airport anxiety', 'technical', 'fact', 'Binkley also designed Hamilton''s lighting'),
('Come From Away', 'Broadway Musical', 0, 'Gareth Owen''s sound design mixes 8 onstage musicians with 12 actors in a 1,079-seat house', 'technical', 'fact', 'Must balance folk instruments with vocal clarity'),
('Come From Away', 'Broadway Musical', 0, 'Beowulf Boritt''s set uses tall trees that evoke Gander''s Newfoundland landscape', 'design', 'fact', 'Trees frame the performance space'),
('Come From Away', 'Broadway Musical', 0, 'The show runs 100 minutes with no intermission', 'numbers', 'fact', 'One of Broadway''s tightest running times'),
('Come From Away', 'Broadway Musical', 0, 'Ran 1,669 performances before closing October 2, 2022', 'numbers', 'fact', 'At the Gerald Schoenfeld Theatre'),
('Come From Away', 'Broadway Musical', 0, 'Received 7 Tony nominations and won 1: Best Direction for Christopher Ashley', 'award', 'fact', 'Competed in a strong year against Dear Evan Hansen'),
('Come From Away', 'Broadway Musical', 0, 'Opened March 12, 2017, at the Gerald Schoenfeld Theatre', 'production', 'fact', 'Previews began February 18, 2017'),
('Come From Away', 'Broadway Musical', 0, 'Book, music, and lyrics by Irene Sankoff and David Hein, a married couple', 'production', 'fact', 'They traveled to Gander for the 10th anniversary of 9/11 to interview residents'),
('Come From Away', 'Broadway Musical', 0, 'Directed by Christopher Ashley with choreography by Kelly Devine', 'production', 'fact', 'Ashley is also artistic director of La Jolla Playhouse'),
('Come From Away', 'Broadway Musical', 0, 'August Eriksmoen''s orchestrations blend Celtic fiddle, bodhran, and accordion with guitar and keyboards', 'orchestra', 'fact', 'Captures the Newfoundland musical tradition'),
('Come From Away', 'Broadway Musical', 0, 'Toni-Leslie James''s costume design uses practical everyday clothing appropriate for 2001', 'design', 'fact', 'Designed for rapid character switches'),
('Come From Away', 'Broadway Musical', 0, 'Based on the true story of 7,000 airline passengers stranded in Gander, Newfoundland on September 11, 2001', 'history', 'fact', '38 planes diverted to the small town'),
('Come From Away', 'Broadway Musical', 0, 'Developed at Sheridan College in Ontario, Canada before transferring to Broadway', 'history', 'fact', 'Also staged at Seattle Rep and Ford''s Theatre in D.C.'),
('Come From Away', 'Broadway Musical', 0, 'Kelly Devine''s movement design uses the turntable and chairs to create fluid scene transitions', 'backstage', 'fact', 'No traditional blackouts between scenes'),
('Come From Away', 'Broadway Musical', 0, 'The Apple TV+ filmed version captured the original Broadway cast before closing', 'culture', 'fact', 'Released in September 2021'),
('Come From Away', 'Broadway Musical', 0, 'Real Gander residents attended the Broadway opening and were recognized from the stage', 'culture', 'fact', 'Many maintained friendships with the stranded passengers'),
('Come From Away', 'Broadway Musical', 0, 'The entire show takes place over approximately 5 days in September 2001', 'plot', 'fact', 'Compresses real events into a continuous narrative'),
('Come From Away', 'Broadway Musical', 0, 'The Screech-In ceremony scene recreates a real Newfoundland tradition of kissing a cod fish', 'plot', 'fact', 'Audience members sometimes receive actual Screech rum at special events'),
('Come From Away', 'Broadway Musical', 0, 'The production grossed over $15 million annually on Broadway at its peak', 'numbers', 'fact', 'Strong word-of-mouth drove consistent sales'),

-- ============================================================
-- SIX
-- ============================================================
('Six', 'Broadway Musical', 0, 'The Queens use handheld radio microphones inspired by Beyonce at Roseland rather than typical head-worn mics', 'technical', 'fact', 'Costumes feature a loop to hold the mic when not in use'),
('Six', 'Broadway Musical', 0, 'All Queens wear in-ear monitors in addition to their handheld mics', 'technical', 'fact', 'Concert-style audio setup unusual for Broadway'),
('Six', 'Broadway Musical', 0, 'The 4-piece all-female onstage band is called The Ladies in Waiting', 'orchestra', 'fact', 'Characters named Maria (drums), Bessie (bass), Maggie (guitar), Joan (keys)'),
('Six', 'Broadway Musical', 0, 'Band members execute musical cues, acting choices, and subtle choreography during the show', 'orchestra', 'fact', 'They are performers, not just musicians'),
('Six', 'Broadway Musical', 0, 'Tim Deiling''s lighting design uses arena-style concert lighting with heavy use of moving heads and color', 'technical', 'fact', 'Evokes a pop concert rather than traditional theater'),
('Six', 'Broadway Musical', 0, 'Paul Gatehouse''s sound design delivers concert-level volume unusual for a Broadway house', 'technical', 'fact', 'The show is designed to feel like a stadium concert'),
('Six', 'Broadway Musical', 0, 'Gabriella Slade''s costumes fuse contemporary pop fashion with Tudor-era historical details', 'design', 'fact', 'Won the Tony for Best Costume Design'),
('Six', 'Broadway Musical', 0, 'Costumes use sequins, holographic foils, PVC, leathers, and pleathers for vibrancy under concert lighting', 'design', 'fact', 'Materials chosen specifically for how they catch light'),
('Six', 'Broadway Musical', 0, 'Emma Bailey''s minimalist concert-stage set design leaves the focus entirely on performers', 'design', 'fact', 'No traditional scenic elements, just a concert platform'),
('Six', 'Broadway Musical', 0, 'Runs approximately 80 minutes with no intermission', 'numbers', 'fact', 'One of the shortest running times on Broadway'),
('Six', 'Broadway Musical', 0, 'Only 6 principal actresses plus 4 band members and alternates comprise the entire company', 'cast', 'fact', 'One of the smallest casts on Broadway'),
('Six', 'Broadway Musical', 0, 'Reached 1,545 performances by June 2025 at the Lena Horne Theatre', 'numbers', 'fact', 'Longest-running show at that theater'),
('Six', 'Broadway Musical', 0, 'Received 8 Tony nominations and won 2: Best Original Score and Best Costume Design', 'award', 'fact', 'Toby Marlow and Lucy Moss won for Score'),
('Six', 'Broadway Musical', 0, 'Original opening night was March 12, 2020, cancelled hours before curtain due to COVID shutdown', 'history', 'fact', 'Officially opened October 3, 2021, after 18-month delay'),
('Six', 'Broadway Musical', 0, 'Written by Toby Marlow and Lucy Moss while students at Cambridge University', 'history', 'fact', 'Originally performed at the Edinburgh Festival Fringe in 2017'),
('Six', 'Broadway Musical', 0, 'Co-directed by Lucy Moss and Jamie Armitage', 'production', 'fact', 'Moss was the youngest woman to direct a Broadway musical'),
('Six', 'Broadway Musical', 0, 'Choreographed by Carrie-Anne Ingrouille with pop concert-inspired movement', 'production', 'fact', 'Movement blends pop performance with theatrical staging'),
('Six', 'Broadway Musical', 0, 'Each Queen''s musical style references a different modern pop artist', 'song', 'fact', 'Beyonce, Adele, Lily Allen, Alicia Keys, Ariana Grande, and more'),
('Six', 'Broadway Musical', 0, 'The six wives of Henry VIII compete to determine who had the worst experience', 'plot', 'fact', 'Structured as a concert where each queen performs a solo'),
('Six', 'Broadway Musical', 0, 'Alternates rotate in regularly, with some performances featuring entirely different casts', 'cast', 'fact', 'Designed for flexible casting from the start'),
('Six', 'Broadway Musical', 0, 'The show became a TikTok phenomenon with cast members posting performance clips', 'culture', 'fact', 'Social media drove younger audience attendance'),
('Six', 'Broadway Musical', 0, 'Played at the Brooks Atkinson Theatre before it was renamed the Lena Horne Theatre', 'production', 'fact', 'Renamed in November 2022'),
('Six', 'Broadway Musical', 0, 'Carrie-Anne Ingrouille''s choreography includes audience-facing poses drawn from pop concert conventions', 'backstage', 'fact', 'Queens break the fourth wall constantly'),
('Six', 'Broadway Musical', 0, 'The production''s compact size makes it one of the most economical shows to tour', 'numbers', 'fact', 'Minimal set, small cast, small band'),
('Six', 'Broadway Musical', 0, 'The lighting rig includes a prominent crown-shaped truss that frames the concert stage', 'technical', 'fact', 'Reinforces the royal theme visually'),

-- ============================================================
-- BEETLEJUICE
-- ============================================================
('Beetlejuice', 'Broadway Musical', 0, 'David Korins called it the most complicated set he has ever done, by a magnitude of 10', 'design', 'fact', 'Korins also designed Hamilton and Dear Evan Hansen'),
('Beetlejuice', 'Broadway Musical', 0, 'Every piece of scenery contains a light, special effect, trap door, smoke machine, projection surface, speaker, or automation element', 'technical', 'fact', 'No purely decorative scenic pieces'),
('Beetlejuice', 'Broadway Musical', 0, 'Three versions of every set piece exist to accommodate all versions of the haunted house', 'backstage', 'fact', 'Living, dead, and in-between states'),
('Beetlejuice', 'Broadway Musical', 0, 'Crew assembles and transforms sets live on stage during the show', 'backstage', 'fact', 'Visible stagecraft is part of the design concept'),
('Beetlejuice', 'Broadway Musical', 0, 'The sandworm is one of the largest puppets in Broadway history, designed by Michael Curry', 'design', 'fact', 'Curry also designed The Lion King puppets'),
('Beetlejuice', 'Broadway Musical', 0, 'Actors playing the title character use ventricular fold phonation to sustain the gravelly voice without vocal cord damage', 'technical', 'fact', 'A specialized vocal technique for the demanding role'),
('Beetlejuice', 'Broadway Musical', 0, 'Look Solutions fog machines create slow eerie fog for supernatural sequences', 'technical', 'fact', 'Fog effects run nearly continuously'),
('Beetlejuice', 'Broadway Musical', 0, 'The production uses trap doors, on-stage pyrotechnics, and strobe lighting effects', 'technical', 'fact', 'Jeremy Chernick designed the special effects'),
('Beetlejuice', 'Broadway Musical', 0, 'All wallpaper was hand-drawn and every floorboard was hand-painted', 'design', 'fact', 'Extreme attention to scenic detail'),
('Beetlejuice', 'Broadway Musical', 0, 'Peter Nigrini''s projection design layers digital effects over every physical surface', 'technical', 'fact', 'Nigrini also designed Dear Evan Hansen''s projections'),
('Beetlejuice', 'Broadway Musical', 0, 'Kenneth Posner''s lighting design includes over-the-top concert and horror effects', 'technical', 'fact', 'Posner also designed Wicked''s lighting'),
('Beetlejuice', 'Broadway Musical', 0, 'At the Winter Garden, the rhythm section was isolated in a back room with clear glass panels for sightlines', 'orchestra', 'fact', 'Drums, percussion, bass, and 2 guitars behind glass'),
('Beetlejuice', 'Broadway Musical', 0, 'The full orchestra includes reeds, 3 trumpets, 3 trombones, horn, 2 percussion, drums, 2 keyboards, and strings', 'orchestra', 'fact', 'One of the larger pit orchestras for a contemporary musical'),
('Beetlejuice', 'Broadway Musical', 0, 'Michael Weber designed stage illusions including disappearances and transformations', 'backstage', 'fact', 'Weber is a renowned magic consultant for Broadway'),
('Beetlejuice', 'Broadway Musical', 0, 'Received 8 Tony nominations in 2019 but won zero', 'award', 'fact', 'Lost across all categories to Hadestown and others'),
('Beetlejuice', 'Broadway Musical', 0, 'The original run played 366 performances at the Winter Garden before COVID closed it March 2020', 'numbers', 'fact', 'Returned at the Marquis Theatre in April 2022'),
('Beetlejuice', 'Broadway Musical', 0, 'Directed by Alex Timbers who also directed Moulin Rouge!', 'production', 'fact', 'Known for maximalist, visually extravagant productions'),
('Beetlejuice', 'Broadway Musical', 0, 'Music and lyrics by Eddie Perfect, an Australian performer and composer', 'production', 'fact', 'His Broadway debut as a composer'),
('Beetlejuice', 'Broadway Musical', 0, 'Book by Scott Brown and Anthony King', 'production', 'fact', 'Adapted from the 1988 Tim Burton film'),
('Beetlejuice', 'Broadway Musical', 0, 'Choreographed by Connor Gallagher who incorporates physical comedy and horror-movie movement', 'production', 'fact', 'Gallagher also choreographed The Play That Goes Wrong'),
('Beetlejuice', 'Broadway Musical', 0, 'Alex Brightman originated the title role and was nominated for the Tony', 'cast', 'fact', 'Known for his extreme physical and vocal performance'),
('Beetlejuice', 'Broadway Musical', 0, 'William Ivey Long''s costume design includes over-the-top versions of afterlife attire', 'design', 'fact', 'Long has won 6 Tony Awards for costume design'),
('Beetlejuice', 'Broadway Musical', 0, 'The show developed a massive social media following on TikTok that helped save it from closing', 'culture', 'fact', 'Fan campaign contributed to the show''s return post-COVID'),
('Beetlejuice', 'Broadway Musical', 0, 'Peter Hylenski''s sound design manages an extraordinary number of simultaneous effects and music cues', 'technical', 'fact', 'One of the most effects-heavy sound designs on Broadway'),
('Beetlejuice', 'Broadway Musical', 0, 'Opened April 25, 2019, at the Winter Garden Theatre', 'production', 'fact', 'Previews began March 28, 2019'),

-- ============================================================
-- CHICAGO
-- ============================================================
('Chicago', 'Broadway Musical', 0, 'The revival uses the same golden bandstand frame from the original 1996 Encores! concert staging, still in use today', 'design', 'fact', 'The frame has been used for nearly 30 years'),
('Chicago', 'Broadway Musical', 0, 'The full jazz orchestra performs on stage throughout the show rather than in a pit', 'orchestra', 'fact', 'A defining feature of the revival''s staging'),
('Chicago', 'Broadway Musical', 0, 'The orchestra sits within the golden frame center stage, visually evoking a jury box', 'design', 'fact', 'John Lee Beatty''s minimalist set design'),
('Chicago', 'Broadway Musical', 0, 'Ken Billington''s lighting uses heavy spotlights and vaudeville-style theatrical effects', 'technical', 'fact', 'Won the Tony for Best Lighting Design'),
('Chicago', 'Broadway Musical', 0, 'The set has no traditional scenery: only black chairs and the bandstand frame', 'design', 'fact', 'Deliberate concert staging carried from Encores!'),
('Chicago', 'Broadway Musical', 0, 'William Ivey Long''s costumes are sexy, sheer, and black to match the concert-style staging', 'design', 'fact', 'Deliberately minimal costuming'),
('Chicago', 'Broadway Musical', 0, 'Ann Reinking''s choreography recreates Bob Fosse''s style through the credit in the style of Bob Fosse', 'backstage', 'fact', 'The first major use of this attribution on Broadway'),
('Chicago', 'Broadway Musical', 0, 'Over 11,000 performances makes it the longest-running American musical in Broadway history', 'numbers', 'fact', 'Surpassed A Chorus Line and is currently Broadway''s longest-running show'),
('Chicago', 'Broadway Musical', 0, 'The 1996 revival won 6 Tony Awards including Best Revival and Best Direction', 'award', 'fact', 'Bebe Neuwirth and James Naughton won acting awards'),
('Chicago', 'Broadway Musical', 0, 'The original 1975 production was directed and choreographed by Bob Fosse', 'production', 'fact', 'Music by John Kander, lyrics by Fred Ebb'),
('Chicago', 'Broadway Musical', 0, 'The revival directed by Walter Bobbie originated as an Encores! concert in 1996', 'history', 'fact', 'The concert was so successful it transferred to Broadway'),
('Chicago', 'Broadway Musical', 0, 'The original 1975 production lost most Tony categories to A Chorus Line', 'history', 'fact', '11 nominations, won Best Musical but lost Best Direction and Choreography'),
('Chicago', 'Broadway Musical', 0, 'Scott Lehrer''s sound design balances an onstage jazz band with vocal performances at close range', 'technical', 'fact', 'Musicians and actors share the same stage space'),
('Chicago', 'Broadway Musical', 0, 'David Brian Brown designs and maintains wigs for the long-running cast rotations', 'design', 'fact', 'Wigs must be consistent across decades of performances'),
('Chicago', 'Broadway Musical', 0, 'The revival opened November 14, 1996, at the Richard Rodgers Theatre', 'production', 'fact', 'Has moved between multiple theaters during its run'),
('Chicago', 'Broadway Musical', 0, 'Has employed more celebrity replacement leads than any other Broadway show', 'cast', 'fact', 'Including athletes, pop stars, and TV personalities'),
('Chicago', 'Broadway Musical', 0, 'Fosse''s signature style includes turned-in knees, rolled shoulders, jazz hands, and bowler hats', 'backstage', 'fact', 'Every performer must master this specific vocabulary'),
('Chicago', 'Broadway Musical', 0, 'Gwen Verdon and Chita Rivera originated the roles of Roxie and Velma in 1975', 'cast', 'fact', 'Two of Broadway''s greatest dancers'),
('Chicago', 'Broadway Musical', 0, 'The 2002 film adaptation won the Academy Award for Best Picture', 'culture', 'fact', 'First musical to win Best Picture since Oliver! in 1968'),
('Chicago', 'Broadway Musical', 0, 'Based on a 1926 play by reporter Maurine Dallas Watkins about real Chicago criminals', 'history', 'fact', 'Watkins covered the original murder trials'),
('Chicago', 'Broadway Musical', 0, 'The revival''s concert staging was revolutionary, proving minimalism could sell on Broadway', 'culture', 'fact', 'Influenced many subsequent stripped-down productions'),
('Chicago', 'Broadway Musical', 0, 'Each vaudeville number in the show parallels a real courtroom or tabloid event', 'song', 'fact', 'The structural device was Fosse''s concept'),
('Chicago', 'Broadway Musical', 0, 'The show uses a small cast of approximately 26 performers', 'cast', 'fact', 'Ensemble performs all vaudeville numbers'),
('Chicago', 'Broadway Musical', 0, 'The Cell Block Tango features 6 women telling murder stories with chairs and minimal props', 'backstage', 'fact', 'One of Broadway''s most iconic ensemble numbers'),
('Chicago', 'Broadway Musical', 0, 'The musical instruments on stage include piano, brass, reeds, bass, drums, and percussion', 'orchestra', 'fact', 'Standard jazz big-band configuration'),

-- ============================================================
-- A CHORUS LINE
-- ============================================================
('A Chorus Line', 'Broadway Musical', 0, 'Tharon Musser''s lighting design was the first Broadway show to use a computerized electronic lighting board', 'technical', 'fact', 'The LS8 memory board changed theatrical lighting permanently'),
('A Chorus Line', 'Broadway Musical', 0, 'Robin Wagner''s set features mirrored Mylar panels that serve as both scenic and dramatic devices', 'design', 'fact', 'Mirrors are used powerfully in The Music and the Mirror'),
('A Chorus Line', 'Broadway Musical', 0, 'The set is essentially a bare Broadway stage, the rehearsal space, making minimalism the storytelling choice', 'design', 'fact', 'One of the most influential set designs in Broadway history'),
('A Chorus Line', 'Broadway Musical', 0, 'The iconic One finale features the ensemble in identical spangled gold top hats and tuxedo costumes', 'design', 'fact', 'Theoni V. Aldredge''s most recognizable Broadway image'),
('A Chorus Line', 'Broadway Musical', 0, 'At the September 29, 1983 gala, 338 dancers from all global companies performed the finale together', 'culture', 'fact', 'For the show''s record-breaking 3,389th performance'),
('A Chorus Line', 'Broadway Musical', 0, 'The lighting transforms the bare stage from a harsh audition room to a glamorous finale in the final moments', 'technical', 'fact', 'The shift from work lights to full theatrical lighting is the show''s climax'),
('A Chorus Line', 'Broadway Musical', 0, 'Conceived, directed, and choreographed by Michael Bennett with co-choreographer Bob Avian', 'production', 'fact', 'Bennett developed the show from tape-recorded interviews with real dancers'),
('A Chorus Line', 'Broadway Musical', 0, 'Ran for 6,137 performances, the longest-running show until surpassed by Cats in 1997', 'numbers', 'fact', 'At the Shubert Theatre from 1975 to 1990'),
('A Chorus Line', 'Broadway Musical', 0, 'Won 9 Tony Awards from 12 nominations including Best Musical', 'award', 'fact', 'Swept nearly every major category in 1976'),
('A Chorus Line', 'Broadway Musical', 0, 'Won the 1976 Pulitzer Prize for Drama', 'award', 'fact', 'One of the few musicals to win the Pulitzer'),
('A Chorus Line', 'Broadway Musical', 0, 'Music by Marvin Hamlisch with lyrics by Edward Kleban', 'production', 'fact', 'Hamlisch was already an Oscar winner for The Way We Were'),
('A Chorus Line', 'Broadway Musical', 0, 'Book by James Kirkwood Jr. and Nicholas Dante, both drawing from real dancer experiences', 'production', 'fact', 'Dante was himself a chorus dancer'),
('A Chorus Line', 'Broadway Musical', 0, 'Opened July 25, 1975, at the Shubert Theatre after transferring from the Public Theater', 'production', 'fact', 'Joseph Papp''s New York Shakespeare Festival produced the original'),
('A Chorus Line', 'Broadway Musical', 0, 'The 2006 revival ran at the Gerald Schoenfeld Theatre', 'history', 'fact', 'Directed by Bob Avian, Bennett''s original co-choreographer'),
('A Chorus Line', 'Broadway Musical', 0, 'Bennett developed the show from taped conversations with 24 real Broadway dancers over two midnight sessions', 'history', 'fact', 'The dancers were promised anonymity; some later revealed themselves'),
('A Chorus Line', 'Broadway Musical', 0, 'The workshop process for the show helped pioneer the modern Broadway development workshop system', 'history', 'fact', 'Bennett''s collaborative method became industry standard'),
('A Chorus Line', 'Broadway Musical', 0, '17 dancers audition for 8 spots on the line, mirroring real Broadway audition stakes', 'plot', 'fact', 'The entire show takes place during one audition'),
('A Chorus Line', 'Broadway Musical', 0, 'The orchestra pit is used traditionally but the sound design emphasizes the raw rehearsal room feel', 'technical', 'fact', 'Music director plays rehearsal piano before full orchestration kicks in'),
('A Chorus Line', 'Broadway Musical', 0, 'Aldredge''s costume design transitions from individual rehearsal clothes to uniform gold for the finale', 'design', 'fact', 'The individual-to-uniform shift is the show''s visual thesis'),
('A Chorus Line', 'Broadway Musical', 0, 'The show has no traditional intermission set change since the set never changes', 'backstage', 'fact', 'The white line on the floor is the only scenic marking'),
('A Chorus Line', 'Broadway Musical', 0, 'Bennett''s original staging placed dancers on the actual white audition line marked on the stage floor', 'backstage', 'fact', 'The line became the show''s iconic image'),
('A Chorus Line', 'Broadway Musical', 0, 'The mirror reveal at the end turns the audience into part of the reflection', 'technical', 'fact', 'A stunning visual effect achieved with simple technology'),
('A Chorus Line', 'Broadway Musical', 0, 'What I Did for Love became a pop standard, covered by hundreds of artists', 'song', 'fact', 'The show''s most commercially successful song'),
('A Chorus Line', 'Broadway Musical', 0, 'The show revolutionized how dancers were perceived, giving chorus members individual stories', 'culture', 'fact', 'Changed the status of ensemble performers on Broadway'),
('A Chorus Line', 'Broadway Musical', 0, 'Donna McKechnie won the Tony for Best Actress originating Cassie', 'cast', 'fact', 'Her performance in The Music and the Mirror is legendary'),

-- ============================================================
-- SWEENEY TODD
-- ============================================================
('Sweeney Todd', 'Broadway Musical', 0, 'Eugene Lee dismantled a real factory and rebuilt parts of it inside the theater for the original 1979 production', 'design', 'fact', 'Created the largest single stage set in Broadway history at that time'),
('Sweeney Todd', 'Broadway Musical', 0, 'The original set could rotate 360 degrees with moving grids and removable bridges in near-constant motion', 'backstage', 'fact', 'Mechanical elements ran throughout the entire performance'),
('Sweeney Todd', 'Broadway Musical', 0, 'Jonathan Tunick''s original orchestration uses a 26-player orchestra, one of the largest in Broadway musical history', 'orchestra', 'fact', 'Instrumentation includes harp, organ, celesta, and harmonium'),
('Sweeney Todd', 'Broadway Musical', 0, 'The 2023 revival restored Tunick''s full 26-player orchestration for the first time since 1980', 'orchestra', 'fact', 'Starring Josh Groban and Annaleigh Ashford'),
('Sweeney Todd', 'Broadway Musical', 0, 'The orchestra includes flute/piccolo/recorder, oboe/English horn, clarinets, bassoon, horns, trumpets, trombones, percussion, harp, and strings', 'orchestra', 'fact', 'Plus organ, celesta, and harmonium for the keyboard book'),
('Sweeney Todd', 'Broadway Musical', 0, 'The 2023 revival features a massive steel crane that delivers the barber chair in Act 2', 'backstage', 'fact', 'Dramatic mechanical staging element'),
('Sweeney Todd', 'Broadway Musical', 0, 'The 2023 set includes a rotating staircase and moving pie shop that transform between scenes', 'technical', 'fact', 'Upper platform shifts in two dimensions'),
('Sweeney Todd', 'Broadway Musical', 0, 'Natasha Katz won the 2023 Tony for Best Lighting Design for the revival', 'award', 'fact', 'Her seventh Tony win'),
('Sweeney Todd', 'Broadway Musical', 0, 'Nevin Steinberg won the 2023 Tony for Best Sound Design for the revival', 'award', 'fact', 'Also won for Hamilton and Hadestown'),
('Sweeney Todd', 'Broadway Musical', 0, 'The original 1979 production won 8 Tony Awards from 9 nominations including Best Musical', 'award', 'fact', 'One of Sondheim''s most honored scores'),
('Sweeney Todd', 'Broadway Musical', 0, 'The 2023 revival received 8 Tony nominations', 'award', 'fact', 'At the Lunt-Fontanne Theatre'),
('Sweeney Todd', 'Broadway Musical', 0, 'Ken Billington designed the original lighting, managing the complex rotating factory set', 'technical', 'fact', 'Billington later designed Chicago revival''s lighting'),
('Sweeney Todd', 'Broadway Musical', 0, 'The original production opened March 1, 1979, at the Uris Theatre, now the Gershwin', 'production', 'fact', 'Ran 557 performances before closing June 29, 1980'),
('Sweeney Todd', 'Broadway Musical', 0, 'Music and lyrics by Stephen Sondheim with book by Hugh Wheeler', 'production', 'fact', 'Based on Christopher Bond''s 1973 play'),
('Sweeney Todd', 'Broadway Musical', 0, 'Directed by Harold Prince who also directed Phantom and Evita', 'production', 'fact', 'Prince conceived the factory setting'),
('Sweeney Todd', 'Broadway Musical', 0, 'Franne Lee''s costume design for the original won the Tony Award', 'design', 'fact', 'Victorian-era costumes contrasted with the industrial set'),
('Sweeney Todd', 'Broadway Musical', 0, 'Len Cariou originated the title role and Angela Lansbury played Mrs. Lovett', 'cast', 'fact', 'Both won Tony Awards for their performances'),
('Sweeney Todd', 'Broadway Musical', 0, 'The 2005 John Doyle revival had the actors play their own instruments on stage', 'history', 'fact', 'Reduced to a 10-person cast/orchestra'),
('Sweeney Todd', 'Broadway Musical', 0, 'The show has been revived on Broadway three times: 1989 concert, 2005, and 2023', 'history', 'fact', 'Each with radically different staging concepts'),
('Sweeney Todd', 'Broadway Musical', 0, 'Tim Burton directed a 2007 film adaptation starring Johnny Depp and Helena Bonham Carter', 'culture', 'fact', 'Won the Oscar for Best Art Direction'),
('Sweeney Todd', 'Broadway Musical', 0, 'The barber chair mechanism that drops victims to the bakehouse is the show''s signature prop', 'backstage', 'fact', 'Each production designs its own version of the chair trap'),
('Sweeney Todd', 'Broadway Musical', 0, 'The score is considered one of the most complex and operatic in the Broadway canon', 'song', 'fact', 'Sondheim''s most musically ambitious work'),
('Sweeney Todd', 'Broadway Musical', 0, 'The Ballad of Sweeney Todd serves as a Greek chorus narrating and commenting on the action', 'song', 'fact', 'Recurs throughout the show in various forms'),
('Sweeney Todd', 'Broadway Musical', 0, 'Based on a Victorian penny dreadful serial about the Demon Barber of Fleet Street', 'history', 'fact', 'The character dates to an 1846 serial in The String of Pearls'),
('Sweeney Todd', 'Broadway Musical', 0, 'The 2023 revival grossed over $1.7 million in its first week', 'numbers', 'fact', 'Strong box office driven by Josh Groban''s star power'),

-- ============================================================
-- INTO THE WOODS
-- ============================================================
('Into the Woods', 'Broadway Musical', 0, 'The 2022 revival placed the orchestra on stage as a central design element', 'orchestra', 'fact', 'The live onstage orchestra defined the revival''s intimate aesthetic'),
('Into the Woods', 'Broadway Musical', 0, 'Tony Straiges''s original set design featured a storybook forest that transformed into a darker landscape in Act 2', 'design', 'fact', 'Trees and scenic elements physically changed between acts'),
('Into the Woods', 'Broadway Musical', 0, 'James Ortiz designed puppets for the 2022 revival including Milky White the cow', 'design', 'fact', 'Puppet design brought a new tactile quality to the revival'),
('Into the Woods', 'Broadway Musical', 0, 'Ann Hould-Ward won the Tony for Best Costume Design for the original production', 'award', 'fact', 'Based on concepts by Patricia Zipprodt who died before opening'),
('Into the Woods', 'Broadway Musical', 0, 'The original production''s orchestra included violin, violas, cello, bass, flute, clarinet, bassoon, trumpet, 2 French horns, and 2 keyboards', 'orchestra', 'fact', 'Jonathan Tunick''s orchestration'),
('Into the Woods', 'Broadway Musical', 0, 'Paul Gemignani served as music director, his frequent collaboration with Sondheim', 'orchestra', 'fact', 'Gemignani MD''d most of Sondheim''s major works'),
('Into the Woods', 'Broadway Musical', 0, 'Richard Nelson''s lighting design for the original shifted from fairy-tale warmth to ominous shadow in Act 2', 'technical', 'fact', 'The tonal shift is one of the show''s signature theatrical moments'),
('Into the Woods', 'Broadway Musical', 0, 'Tyler Micoleau''s lighting design for the 2022 revival created an intimate woodland glow', 'technical', 'fact', 'Complementing the onstage orchestra setup'),
('Into the Woods', 'Broadway Musical', 0, 'David Rockwell''s set for the 2022 revival transformed the St. James Theatre stage into an intimate playing space', 'design', 'fact', 'Integrated the orchestra into the scenic design'),
('Into the Woods', 'Broadway Musical', 0, 'Charles Reynolds served as magic consultant for the original production', 'backstage', 'fact', 'Created effects for the Witch''s transformation and magic bean sequences'),
('Into the Woods', 'Broadway Musical', 0, 'The Witch''s transformation from hag to beautiful woman requires a quick-change backstage assist', 'backstage', 'fact', 'One of the show''s most challenging costume moments'),
('Into the Woods', 'Broadway Musical', 0, 'Breakaway props are used for Jack''s beanstalk and other fairy tale elements', 'backstage', 'fact', 'Must be rebuilt for each performance'),
('Into the Woods', 'Broadway Musical', 0, 'The original production ran 765 performances at the Martin Beck Theatre, now the Al Hirschfeld', 'numbers', 'fact', 'Opened November 5, 1987'),
('Into the Woods', 'Broadway Musical', 0, 'Won 3 Tony Awards from 10 nominations: Best Score, Best Book, and Best Actress', 'award', 'fact', 'Joanna Gleason won for the Baker''s Wife'),
('Into the Woods', 'Broadway Musical', 0, 'The 2022 revival received 6 Tony nominations including Best Revival', 'award', 'fact', 'At the St. James Theatre'),
('Into the Woods', 'Broadway Musical', 0, 'Music and lyrics by Stephen Sondheim with book by James Lapine', 'production', 'fact', 'Lapine also directed both original and later productions'),
('Into the Woods', 'Broadway Musical', 0, 'Directed and written by James Lapine who also directed Sunday in the Park with George', 'production', 'fact', 'His second Sondheim collaboration'),
('Into the Woods', 'Broadway Musical', 0, 'Bernadette Peters originated the role of the Witch in the 1987 production', 'cast', 'fact', 'One of her most iconic Broadway roles'),
('Into the Woods', 'Broadway Musical', 0, 'The 2022 revival starred Sara Bareilles as the Baker''s Wife', 'cast', 'fact', 'Bareilles also wrote Waitress the Musical'),
('Into the Woods', 'Broadway Musical', 0, 'The show interweaves multiple Grimm fairy tales into a single narrative', 'plot', 'fact', 'Cinderella, Jack and the Beanstalk, Little Red, and Rapunzel'),
('Into the Woods', 'Broadway Musical', 0, 'Act 2 deconstructs the happily ever after endings from Act 1', 'plot', 'fact', 'The structural reversal is the show''s central innovation'),
('Into the Woods', 'Broadway Musical', 0, 'Rob Berman served as music director for the 2022 revival', 'production', 'fact', 'Managed the onstage orchestra placement'),
('Into the Woods', 'Broadway Musical', 0, 'Andrea Hood''s costume design for the 2022 revival used a modern, casual aesthetic', 'design', 'fact', 'Deliberate contrast with the fairy-tale setting'),
('Into the Woods', 'Broadway Musical', 0, 'A 2014 Disney film adaptation was directed by Rob Marshall', 'culture', 'fact', 'Starred Meryl Streep as the Witch'),
('Into the Woods', 'Broadway Musical', 0, 'The 2022 revival ran from June 28, 2022, to January 8, 2023, at the St. James Theatre', 'numbers', 'fact', 'Limited engagement that extended multiple times due to demand');
