-- SPIKE Clue Bank — Broadway Play (Technical-First)
-- 15 subjects x 25 clues each = 375 clues

INSERT INTO clue_bank (show_name, category, level, clue_text, clue_type, specificity, notes) VALUES

-- ============================================================
-- DEATH OF A SALESMAN
-- ============================================================
('Death of a Salesman', 'Broadway Play', 0, 'Jo Mielziner''s original set used transparent scrim walls that became solid or see-through depending', 'design', 'fact', 'Pioneering use of scrims to show memory vs reality'),
('Death of a Salesman', 'Broadway Play', 0, 'The original production used elevator platforms built into the stage floor for flashback sequences', 'technical', 'fact', 'Actors rose from below to enter memory scenes'),
('Death of a Salesman', 'Broadway Play', 0, 'Jo Mielziner served as both scenic and lighting designer for the 1949 original, an unusual dual role', 'design', 'fact', 'Allowed him to integrate the scrim effects with precise lighting cues'),
('Death of a Salesman', 'Broadway Play', 0, 'Alex North composed the original incidental music', 'technical', 'fact', 'North later became a major Hollywood film composer'),
('Death of a Salesman', 'Broadway Play', 0, 'The set featured a skeletal two-story house with no fourth wall', 'design', 'fact', 'Influenced decades of Broadway scenic design'),
('Death of a Salesman', 'Broadway Play', 0, 'Lighting cues transitioned between present-day and memory sequences by shifting from warm naturalistic tones', 'technical', 'fact', 'The play moves fluidly between time periods without blackouts'),
('Death of a Salesman', 'Broadway Play', 0, 'The 2022 revival directed by Miranda Cromwell featured real grass and earth covering the stage floor', 'design', 'fact', 'First Broadway revival to cast Black actors as the Loman family'),
('Death of a Salesman', 'Broadway Play', 0, 'Sound design in revivals typically includes distant highway traffic and refrigerator hum to evoke suburban', 'technical', 'fact', 'Environmental sound creates the world beyond the set walls'),
('Death of a Salesman', 'Broadway Play', 0, 'The original production ran for 742 performances at the Morosco Theatre', 'numbers', 'fact', 'The Morosco was demolished in 1982'),
('Death of a Salesman', 'Broadway Play', 0, 'Won 6 Tony Awards in 1949 including Best Play, Best Director, and Best Author', 'award', 'fact', 'Swept the major categories at the third annual Tony ceremony'),
('Death of a Salesman', 'Broadway Play', 0, 'Won the Pulitzer Prize for Drama in 1949', 'award', 'fact', 'Arthur Miller was 33 years old at the time'),
('Death of a Salesman', 'Broadway Play', 0, 'Elia Kazan directed the original 1949 Broadway production', 'production', 'fact', 'Kazan also directed A Streetcar Named Desire two years earlier'),
('Death of a Salesman', 'Broadway Play', 0, 'Lee J. Cobb originated the role of the traveling protagonist at age 37', 'cast', 'fact', 'Cobb used makeup and physicality to age himself'),
('Death of a Salesman', 'Broadway Play', 0, 'Philip Seymour Hoffman starred in the 2012 revival directed by Mike Nichols', 'cast', 'fact', 'Hoffman received a Tony nomination for the role'),
('Death of a Salesman', 'Broadway Play', 0, 'Brian Dennehy won the Tony Award for Best Actor in the 1999 revival directed by Robert Falls', 'cast', 'fact', 'Elizabeth Franz also won for Best Featured Actress'),
('Death of a Salesman', 'Broadway Play', 0, 'Dustin Hoffman starred in the 1984 revival and subsequent TV film', 'cast', 'fact', 'John Malkovich played Biff opposite Hoffman'),
('Death of a Salesman', 'Broadway Play', 0, 'Has been revived on Broadway 5 times: 1975, 1984, 1999, 2012, and 2022', 'history', 'fact', 'One of the most frequently revived American plays'),
('Death of a Salesman', 'Broadway Play', 0, 'Arthur Miller wrote the first act in a single day at a Connecticut studio he built himself', 'playwright', 'fact', 'Completed the full script in approximately 6 weeks'),
('Death of a Salesman', 'Broadway Play', 0, 'The working title was "The Inside of His Head"', 'history', 'fact', 'Miller originally envisioned a giant head as the set piece'),
('Death of a Salesman', 'Broadway Play', 0, 'Wendell Pierce and Sharon D Clarke starred in the 2022 revival', 'cast', 'fact', 'First Black actors to play Willy and Linda on Broadway'),
('Death of a Salesman', 'Broadway Play', 0, 'The 1999 revival won the Tony for Best Revival of a Play', 'award', 'fact', 'Featured a more realistic scenic design than the 1949 original'),
('Death of a Salesman', 'Broadway Play', 0, 'The play contains two acts and a requiem epilogue scene', 'plot', 'fact', 'One of the earliest uses of a requiem structure in American drama'),
('Death of a Salesman', 'Broadway Play', 0, 'Arthur Miller originally envisioned the set as a giant head before Mielziner proposed the house concept', 'history', 'fact', 'Reflects the play''s exploration of interior psychology'),
('Death of a Salesman', 'Broadway Play', 0, 'The original Broadway poster featured a minimalist illustration of a man carrying two suitcases', 'culture', 'fact', 'Became one of the most iconic images in American theater'),
('Death of a Salesman', 'Broadway Play', 0, 'Opened February 10, 1949, at the Morosco Theatre on West 45th Street', 'production', 'fact', 'Kermit Bloomgarden produced the original production'),

-- ============================================================
-- A STREETCAR NAMED DESIRE
-- ============================================================
('A Streetcar Named Desire', 'Broadway Play', 0, 'Jo Mielziner''s set used translucent walls that allowed the exterior New Orleans streetscape to bleed', 'design', 'fact', 'Created a sense of the protagonist''s dissolving grip on reality'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Alex North composed an original jazz score, one of the first Broadway plays with a fully original underscore', 'technical', 'fact', 'North adapted the score for the 1951 film version'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The original lighting design shifted from warm amber tones to harsh blue-white as the play progressed', 'technical', 'fact', 'Mirrored the protagonist''s psychological deterioration over the course of the drama'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The original sound design included offstage locomotive sounds, jazz from nearby bars', 'technical', 'fact', 'Tennessee Williams specified many of these sounds in his stage directions'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The set required a working bathtub visible to the audience', 'backstage', 'fact', 'The protagonist''s frequent bathing is a key dramatic motif'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The paper lantern covering a naked light bulb is both a key prop and central metaphor in the production', 'design', 'fact', 'Its removal near the end is one of the most devastating moments in American drama'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Lucinda Ballard''s costume design dressed Blanche in fading whites and pastels while Stanley wore work-stained', 'design', 'fact', 'Ballard won the Tony for her costume work in 1948'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The poker game scenes require a practical table with a functioning overhead lamp', 'design', 'fact', 'The lamp creates a harsh pool of light contrasting with surrounding shadows'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Mielziner''s design placed the apartment so surrounding French Quarter architecture was visible', 'design', 'fact', 'Audiences could see street life happening outside the Kowalski home'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The original production ran for 855 performances at the Ethel Barrymore Theatre', 'numbers', 'fact', 'An exceptional run for a drama in the late 1940s'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Won the Pulitzer Prize for Drama in 1948', 'award', 'fact', 'Tennessee Williams'' first Pulitzer'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Won 2 Tony Awards in 1948 including Best Play', 'award', 'fact', 'Jessica Tandy won Best Actress at only the second Tony ceremony'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Elia Kazan directed the original 1947 production', 'production', 'fact', 'Kazan''s Method-influenced direction helped define postwar American theater'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Marlon Brando originated the role of Stanley Kowalski at age 23', 'cast', 'fact', 'The role launched Brando to stardom before his film career'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Jessica Tandy originated the role of Blanche DuBois on Broadway', 'cast', 'fact', 'Despite critical acclaim, Vivien Leigh replaced her for the 1951 film'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Kim Hunter originated the role of Stella and reprised it in the 1951 film, winning the Academy Award', 'cast', 'fact', 'One of few actors to originate a role on Broadway and win an Oscar for the film version'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The 1992 revival starred Alec Baldwin as Stanley and Jessica Lange as Blanche', 'cast', 'fact', 'Directed by Gregory Mosher'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Tennessee Williams wrote the play while living in New Orleans, drawing directly on the city''s atmosphere', 'playwright', 'fact', 'The title references an actual streetcar line that ran through the French Quarter'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The real-life transit line referenced in the title operated from 1920 to 1948', 'history', 'fact', 'It ran through the French Quarter along Royal and then Desire streets'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Tennessee Williams drew on his sister Rose''s institutionalization when writing the character of Blanche', 'playwright', 'fact', 'Rose Williams underwent a lobotomy in 1943'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Premiered at the Ethel Barrymore Theatre on December 3, 1947', 'production', 'fact', 'Irene Mayer Selznick produced the original Broadway run'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Won the New York Drama Critics'' Circle Award for Best Play in 1948', 'award', 'fact', 'Swept the major drama prizes that season'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The play originally contained 11 scenes across three acts', 'plot', 'fact', 'Williams later revised the structure for a more flowing production style'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The 2005 revival starred Natasha Richardson as Blanche and John C. Reilly as Mitch', 'cast', 'fact', 'Edward Hall directed the production at Studio 54'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Stage managers for the original kept a detailed prompt book that became a template for all subsequent revivals', 'backstage', 'fact', 'Preserved precise blocking and cue notes from the 1947 production'),

-- ============================================================
-- A RAISIN IN THE SUN
-- ============================================================
('A Raisin in the Sun', 'Broadway Play', 0, 'Ralph Alswang''s original set depicted a cramped Southside Chicago apartment with worn furniture and a single', 'design', 'fact', 'The claustrophobic space is essential to the play''s tensions'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The original lighting design used a shaft of sunlight through the apartment window as a recurring visual motif', 'technical', 'fact', 'The plant on the windowsill is lit differently in each scene to mark time passing'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The set featured a functioning kitchen with a practical stove and sink that actors used during scenes', 'design', 'fact', 'Ruth''s morning routine opens the play with realistic kitchen business'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The 2014 revival used a revolving set that showed the apartment from multiple angles', 'design', 'fact', 'Allowed the audience to see different rooms as the turntable shifted'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Costume design in the original carefully distinguished each character''s aspirations through wardrobe choices', 'design', 'fact', 'Beneatha''s African robe in the dance scene is a key costume moment'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Sound design in revivals typically includes elevated train sounds from outside the apartment', 'technical', 'fact', 'The Chicago L train establishes the urban Southside location'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The production requires a practical ironing board and iron that Ruth uses throughout Act 1', 'backstage', 'fact', 'Domestic props ground the play in everyday working-class life'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The 2004 revival''s scenic design by Alexander Dodge featured peeling wallpaper and cracked plaster for added', 'design', 'fact', 'Physical deterioration of the apartment mirrors the family''s frustrations'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Lloyd Richards became the first Black director of a Broadway play when he staged the 1959 original', 'production', 'fact', 'Richards later became dean of the Yale School of Drama'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The original production ran for 530 performances at the Ethel Barrymore Theatre', 'numbers', 'fact', 'An impressive run for a drama by a debut playwright in 1959'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Won the New York Drama Critics'' Circle Award for Best Play in 1959', 'award', 'fact', 'Lorraine Hansberry was the first Black playwright to win the award'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Phylicia Rashad won the Tony for Best Actress in the 2004 revival', 'award', 'fact', 'A historic achievement in Tony Award history'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Audra McDonald won a Tony for Best Featured Actress in the 2004 revival', 'award', 'fact', 'One of her record six career Tony wins'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Sidney Poitier originated the role of Walter Lee Younger in the 1959 production', 'cast', 'fact', 'Poitier reprised the role in the 1961 Columbia Pictures film'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Ruby Dee originated the role of Ruth Younger opposite Poitier', 'cast', 'fact', 'Dee also starred in the 1961 film adaptation'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Claudia McNeil originated the role of Lena, known as Mama, in the 1959 original', 'cast', 'fact', 'McNeil was a former nightclub singer before turning to stage acting'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Sean Combs made his Broadway debut as Walter Lee in the 2004 revival alongside Rashad and McDonald', 'cast', 'fact', 'His casting drew significant media attention and new audiences'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Lorraine Hansberry was 29 when the play opened', 'playwright', 'fact', 'Also became the youngest to win the Drama Critics'' Circle Award'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The title comes from a Langston Hughes poem that asks what happens to a dream deferred', 'history', 'fact', 'Hughes'' poem was published in his 1951 collection Montage of a Dream Deferred'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Hansberry drew on her own family''s experience fighting housing discrimination in Chicago', 'playwright', 'fact', 'The Hansberry family''s 1940 Supreme Court case challenged restrictive covenants'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Opened March 11, 1959, after an out-of-town tryout in New Haven', 'production', 'fact', 'The New Haven tryout was so successful that producers expanded the Broadway booking'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The 2014 revival starred Denzel Washington as Walter Lee at the same Ethel Barrymore Theatre as the 1959', 'cast', 'fact', 'The revival set box office records for the theater'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The 2004 revival won the Tony Award for Best Revival of a Play', 'award', 'fact', 'First all-Black cast revival to win the Tony in that category'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Hansberry completed the play at age 28 and died of pancreatic cancer at 34', 'playwright', 'fact', 'She left behind several unfinished works that were adapted posthumously'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The play is set entirely in the Younger family''s apartment over a period of several weeks', 'plot', 'fact', 'The single-set structure intensifies the sense of confinement'),

-- ============================================================
-- THE CRUCIBLE
-- ============================================================
('The Crucible', 'Broadway Play', 0, 'The 2016 Ivo van Hove revival used live video cameras on stage with real-time footage projected onto screens', 'technical', 'fact', 'Tal Yarden designed the video, creating an invasive surveillance atmosphere'),
('The Crucible', 'Broadway Play', 0, 'Philip Glass composed an original score for the 2016 revival, performed live during the production', 'technical', 'fact', 'Glass''s minimalist music heightened the ritualistic intensity'),
('The Crucible', 'Broadway Play', 0, 'Jan Versweyveld''s 2016 set design placed a single long wooden table center stage with bleacher seating', 'design', 'fact', 'On-stage audience created a courtroom tribunal atmosphere'),
('The Crucible', 'Broadway Play', 0, 'The 2016 revival used modern dress costumes designed by Wojciech Dziedzic', 'design', 'fact', 'Deliberately rejected period clothing to emphasize contemporary parallels'),
('The Crucible', 'Broadway Play', 0, 'Boris Aronson designed the original 1953 set with dark wooden beams and stark puritanical interiors', 'design', 'fact', 'Aronson later became known for designing Cabaret and Company'),
('The Crucible', 'Broadway Play', 0, 'The original production used overhead lighting from naked bulbs to simulate harsh courtroom illumination', 'technical', 'fact', 'Stark lighting contrasted with shadow-filled domestic scenes in the Proctor home'),
('The Crucible', 'Broadway Play', 0, 'The 2002 revival''s scenic design by Tim Hatley featured a towering wooden wall that loomed over the actors', 'design', 'fact', 'Richard Eyre directed the 2002 production'),
('The Crucible', 'Broadway Play', 0, 'Tom Gibbons designed the sound for the 2016 revival', 'technical', 'fact', 'Actors wore microphones that fed into the live video system'),
('The Crucible', 'Broadway Play', 0, 'The original 1953 production ran for 197 performances at the Martin Beck Theatre', 'numbers', 'fact', 'Considered a commercial disappointment compared to Arthur Miller''s previous work'),
('The Crucible', 'Broadway Play', 0, 'The 2002 revival won the Tony Award for Best Revival of a Play', 'award', 'fact', 'Liam Neeson was nominated for Best Actor as John Proctor'),
('The Crucible', 'Broadway Play', 0, 'The 2016 revival received 3 Tony nominations including Best Revival and Best Director', 'award', 'fact', 'Ben Whishaw starred as John Proctor and Saoirse Ronan as Abigail'),
('The Crucible', 'Broadway Play', 0, 'Jed Harris directed the original 1953 Broadway production', 'production', 'fact', 'Harris was known as one of Broadway''s most demanding directors'),
('The Crucible', 'Broadway Play', 0, 'Arthur Kennedy originated the role of John Proctor in the 1953 production', 'cast', 'fact', 'Kennedy was already a Tony winner for his work in other Arthur Miller plays'),
('The Crucible', 'Broadway Play', 0, 'Liam Neeson starred as John Proctor in the 2002 revival directed by Richard Eyre', 'cast', 'fact', 'Laura Linney played Elizabeth Proctor opposite Neeson'),
('The Crucible', 'Broadway Play', 0, 'Ben Whishaw and Sophie Okonedo starred in the 2016 Ivo van Hove revival', 'cast', 'fact', 'Ciaran Hinds played Deputy Governor Danforth'),
('The Crucible', 'Broadway Play', 0, 'Arthur Miller wrote the play in 1952-53 as a direct allegory for McCarthyism and the House Un-American', 'playwright', 'fact', 'Miller himself was called before HUAC in 1956'),
('The Crucible', 'Broadway Play', 0, 'Miller researched the 1692 Salem witch trial court records at the Essex County courthouse before writing', 'history', 'fact', 'He used actual names and some real testimony from the historical record'),
('The Crucible', 'Broadway Play', 0, 'The play has become the most-produced Arthur Miller work in American high schools and colleges', 'culture', 'fact', 'Its themes of mass hysteria resonate with each new generation'),
('The Crucible', 'Broadway Play', 0, 'Opened January 22, 1953, at the Martin Beck Theatre on West 45th Street', 'production', 'fact', 'The theater is now known as the Al Hirschfeld Theatre'),
('The Crucible', 'Broadway Play', 0, 'The play is structured in four acts set across multiple locations in Salem, Massachusetts', 'plot', 'fact', 'Locations include the Parris home, the Proctor farm, and the courthouse'),
('The Crucible', 'Broadway Play', 0, 'The 2016 revival ran at the Walter Kerr Theatre for a limited 17-week engagement', 'numbers', 'fact', 'One of the most critically acclaimed productions of the 2015-16 season'),
('The Crucible', 'Broadway Play', 0, 'The original production was initially considered a failure but grew in stature through regional', 'history', 'fact', 'Now considered one of the greatest American plays ever written'),
('The Crucible', 'Broadway Play', 0, 'Miller changed the age of the real Abigail Williams from 11 to 17 to create the affair subplot with Proctor', 'playwright', 'fact', 'This dramatic license became one of the play''s most controversial choices'),
('The Crucible', 'Broadway Play', 0, 'The 2002 revival at the Virginia Theatre ran for 101 performances', 'numbers', 'fact', 'Despite the short run, it won critical acclaim and the Tony for Best Revival'),
('The Crucible', 'Broadway Play', 0, 'The 2016 van Hove production''s use of live cameras allowed audiences to see extreme close-ups of actors''', 'technical', 'fact', 'Created an interrogation-room intensity impossible with traditional staging'),

-- ============================================================
-- THE GLASS MENAGERIE
-- ============================================================
('The Glass Menagerie', 'Broadway Play', 0, 'The prop department stocks multiple breakaway glass unicorn figurines for each production run', 'backstage', 'fact', 'The fragile unicorn breaks on stage every performance and must be replaced nightly'),
('The Glass Menagerie', 'Broadway Play', 0, 'Tennessee Williams''s stage directions call for screen projections displaying titles and images', 'technical', 'fact', 'The original 1945 production cut the projections during out-of-town tryouts'),
('The Glass Menagerie', 'Broadway Play', 0, 'Jo Mielziner designed the original 1945 set as a transparent tenement interior with a fire escape', 'design', 'fact', 'The fire escape doubles as the narrator''s performance space'),
('The Glass Menagerie', 'Broadway Play', 0, 'The 2013 John Tiffany revival featured a reflective black liquid pool covering the entire stage floor', 'design', 'fact', 'Bob Crowley designed the stark white set that reflected in the dark surface'),
('The Glass Menagerie', 'Broadway Play', 0, 'The 2017 Sam Gold revival used an in-the-round staging that broke the traditional proscenium framing', 'design', 'fact', 'Sally Field starred as Amanda in the Belasco Theatre production'),
('The Glass Menagerie', 'Broadway Play', 0, 'Lighting for memory play productions typically uses a soft amber palette that shifts to cooler tones', 'technical', 'fact', 'Williams''s text specifies non-realistic lighting throughout'),
('The Glass Menagerie', 'Broadway Play', 0, 'The collection of glass animals that gives the play its name requires careful backstage prop management', 'backstage', 'fact', 'Each figurine must be pre-set in exact positions for continuity'),
('The Glass Menagerie', 'Broadway Play', 0, 'Sound design typically incorporates a recurring musical theme played on a distant dance hall piano or violin', 'technical', 'fact', 'Williams specifies "The Glass Menagerie" as a recurring musical cue in his text'),
('The Glass Menagerie', 'Broadway Play', 0, 'The 2013 revival used a single candelabra as the primary light source for the dinner scene', 'technical', 'fact', 'The power outage scene is a lighting design signature moment'),
('The Glass Menagerie', 'Broadway Play', 0, 'The fire escape set piece must support an actor''s weight for extended monologues while appearing fragile', 'backstage', 'fact', 'Tom delivers his opening and closing narration from the fire escape'),
('The Glass Menagerie', 'Broadway Play', 0, 'Laurette Taylor''s performance as Amanda in the 1945 original is considered one of the greatest in Broadway', 'cast', 'fact', 'Taylor died the following year; the role was her final Broadway appearance'),
('The Glass Menagerie', 'Broadway Play', 0, 'Eddie Dowling both directed and starred as Tom in the original 1945 production', 'production', 'fact', 'An unusual dual role that was common in earlier Broadway eras'),
('The Glass Menagerie', 'Broadway Play', 0, 'Cherry Jones starred as Amanda in the 2005 revival directed by David Leveaux', 'cast', 'fact', 'Jones won a Tony nomination for the performance'),
('The Glass Menagerie', 'Broadway Play', 0, 'Zachary Quinto played Tom in the 2013 John Tiffany revival alongside Cherry Jones as Amanda', 'cast', 'fact', 'Quinto''s Broadway debut in the role'),
('The Glass Menagerie', 'Broadway Play', 0, 'The original production premiered in Chicago at the Civic Theatre before transferring to Broadway', 'history', 'fact', 'Chicago critic Claudia Cassidy championed the play, helping it survive poor initial ticket sales'),
('The Glass Menagerie', 'Broadway Play', 0, 'Opened on Broadway March 31, 1945, at the Playhouse Theatre', 'production', 'fact', 'Tennessee Williams''s first major Broadway success'),
('The Glass Menagerie', 'Broadway Play', 0, 'Won the New York Drama Critics'' Circle Award for Best Play in 1945', 'award', 'fact', 'Established Williams as a major American playwright'),
('The Glass Menagerie', 'Broadway Play', 0, 'The play is semi-autobiographical, with Tom representing Williams himself and the absent father mirroring', 'playwright', 'fact', 'Williams''s real name was Thomas Lanier Williams III'),
('The Glass Menagerie', 'Broadway Play', 0, 'Williams based the character of Laura on his sister Rose, who struggled with mental illness', 'playwright', 'fact', 'Rose underwent a lobotomy in 1943, two years before the play premiered'),
('The Glass Menagerie', 'Broadway Play', 0, 'The play pioneered the "memory play" form, told through the narrator''s subjective recollection', 'history', 'fact', 'Williams coined the term in his production notes'),
('The Glass Menagerie', 'Broadway Play', 0, 'The original Broadway run lasted 561 performances', 'numbers', 'fact', 'A remarkable run that established Williams as commercially viable'),
('The Glass Menagerie', 'Broadway Play', 0, 'Has been revived on Broadway at least 5 times, most recently in 2017', 'numbers', 'fact', 'Major revivals in 1965, 1983, 2005, 2013, and 2017'),
('The Glass Menagerie', 'Broadway Play', 0, 'The 2013 revival won the Tony for Best Revival of a Play', 'award', 'fact', 'John Tiffany won Best Direction of a Play the same year'),
('The Glass Menagerie', 'Broadway Play', 0, 'The play has 4 characters and a single set: a St. Louis tenement apartment in the 1930s', 'plot', 'fact', 'One of the most intimate casts in the American dramatic canon'),
('The Glass Menagerie', 'Broadway Play', 0, 'Williams wrote the original screenplay for the story before adapting it into the stage play', 'history', 'fact', 'The screenplay, titled "The Gentleman Caller," was never produced as a film first'),

-- ============================================================
-- LONG DAY'S JOURNEY INTO NIGHT
-- ============================================================
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The production runs approximately 3 hours and 40 minutes', 'numbers', 'fact', 'Most productions run with a single intermission'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Sound design relies heavily on a foghorn as a recurring motif throughout the play', 'technical', 'fact', 'The fog and foghorn create an increasingly claustrophobic atmosphere as the day progresses'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The single set requires lighting that tracks the passage of an entire day from morning to midnight', 'technical', 'fact', 'Lighting does all the temporal work since the set never changes'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The production uses only 5 actors: 4 principals and a maid with a brief appearance', 'cast', 'fact', 'One of the most demanding ensemble pieces in American theater'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The set is a single room in a Connecticut summer house, requiring minute period detail for the 1912 setting', 'design', 'fact', 'Furniture, books, and personal objects must tell the family''s story silently'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The fog effect that gradually envelops the house requires sustained haze output throughout Acts 3 and 4', 'technical', 'fact', 'Represents both literal New London fog and the characters'' morphine-and-whiskey haze'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Lighting transitions from bright morning sun to dim evening lamplight are achieved without blackouts or scene', 'technical', 'fact', 'The continuous passage of time is central to the play''s structure'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The liquor bottles on stage must be practical props that actors drink from throughout the long performance', 'backstage', 'fact', 'Whiskey consumption increases visibly as the play progresses'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The 2003 revival''s set by Santo Loquasto filled the stage with heavy Victorian furniture and dark wood', 'design', 'fact', 'Robert Falls directed Brian Dennehy and Vanessa Redgrave'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The 2016 revival''s lighting by Natasha Katz tracked the full arc of a single day using precise color', 'technical', 'fact', 'Jonathan Kent directed the revival starring Jessica Lange'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The original 1956 production ran for 390 performances', 'numbers', 'fact', 'A strong run for a nearly 4-hour drama'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Won the Tony Award for Best Play in 1957', 'award', 'fact', 'Also won for Best Actor for Fredric March'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Won the Pulitzer Prize for Drama in 1957, awarded posthumously', 'award', 'fact', 'Eugene O''Neill had died in 1953, four years before the Broadway premiere'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Fredric March and Florence Eldridge, a real-life married couple, originated the roles of the parents', 'cast', 'fact', 'Their real marriage added layers to the onstage dynamic'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Jason Robards originated the role of Jamie, launching his career as a leading O''Neill interpreter', 'cast', 'fact', 'Robards later starred in multiple O''Neill plays on Broadway'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Brian Dennehy won the Tony for Best Actor in the 2003 revival', 'cast', 'fact', 'His second Tony win after his earlier performance in another Arthur Miller play'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Jessica Lange starred as Mary Tyrone in the 2016 revival', 'cast', 'fact', 'Gabriel Byrne played James Tyrone opposite Lange'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Eugene O''Neill wrote the play between 1939 and 1941 but barred its production during his lifetime', 'playwright', 'fact', 'He instructed his wife Carlotta to destroy the manuscript'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Carlotta O''Neill gave the manuscript to Yale University and authorized the Swedish premiere instead', 'history', 'fact', 'The Royal Dramatic Theatre in Stockholm gave the world premiere in 1956'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The play is autobiographical, depicting O''Neill''s own family during the summer of 1912', 'playwright', 'fact', 'The characters correspond to O''Neill, his parents, and his brother Jamie'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Directed by Jose Quintero in its original Broadway production at the Helen Hayes Theatre', 'production', 'fact', 'Quintero became the foremost interpreter of O''Neill on Broadway'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'O''Neill''s dedication reads "written in tears and blood" and was addressed to Carlotta on their 12th wedding', 'history', 'fact', 'One of the most famous dedications in dramatic literature'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The play premiered on Broadway February 10, 1956, three years after O''Neill''s death', 'production', 'fact', 'The Swedish production opened just weeks before the Broadway premiere'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The play unfolds in real time across a single day, from 8:30 AM to approximately midnight', 'plot', 'fact', 'Unities of time and place create relentless dramatic pressure'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The 2003 revival won the Tony for Best Revival of a Play', 'award', 'fact', 'Vanessa Redgrave was nominated for Best Actress as Mary Tyrone'),

-- ============================================================
-- WHO'S AFRAID OF VIRGINIA WOOLF?
-- ============================================================
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The production requires extensive fight choreography for the verbal and physical confrontations', 'backstage', 'fact', 'Dedicated fight directors have staged the violence in every major revival'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Ben Edwards designed the original 1962 set as a cluttered faculty home filled with books, bottles', 'design', 'fact', 'The lived-in mess reflects the characters'' deteriorating marriage'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The set must include a functioning bar area with practical bottles that the cast depletes throughout', 'backstage', 'fact', 'Alcohol consumption is a central dramatic element requiring precise prop management'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Lighting design traditionally starts warm and convivial', 'technical', 'fact', 'The final act often strips away atmosphere for stark, unsparing illumination'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The 2005 revival directed by Anthony Page used a detailed set by John Lee Beatty with an exposed brick wall', 'design', 'fact', 'Kathleen Turner and Bill Irwin starred'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The 2012 revival''s fight choreography by Thomas Schall included moments of physical contact that intensified', 'backstage', 'fact', 'Pam MacKinnon directed Tracy Letts and Amy Morton'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The production uses only 4 actors for the entire show', 'cast', 'fact', 'All four actors are on stage for nearly the entire 3-hour running time'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Sound design is minimal by intent, relying on silence, ice clinking, and the occasional ring of a doorbell', 'technical', 'fact', 'Edward Albee''s text does the heavy lifting without underscoring'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The original production ran for 664 performances at the Billy Rose Theatre', 'numbers', 'fact', 'The theater is now known as the Nederlander Theatre'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Won the Tony Award for Best Play in 1963', 'award', 'fact', 'Arthur Hill and Uta Hagen won Best Actor and Best Actress'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The Pulitzer Prize board overruled its own jury to give no drama prize in 1963 rather than award it', 'award', 'fact', 'The jury had unanimously recommended it; two board members resigned in protest'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The 2012 revival won the Tony for Best Revival and Best Direction for Pam MacKinnon', 'award', 'fact', 'Tracy Letts and Amy Morton, both Steppenwolf members, led the cast'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Alan Schneider directed the original 1962 Broadway production', 'production', 'fact', 'Schneider became Albee''s most trusted director'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Uta Hagen originated the role of Martha in the 1962 production', 'cast', 'fact', 'Hagen''s ferocious performance set the standard for all future Marthas'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Arthur Hill originated the role of George opposite Hagen', 'cast', 'fact', 'Hill won the Tony for Best Actor for the role'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Kathleen Turner starred as Martha in the 2005 revival, bringing her film star power to the stage', 'cast', 'fact', 'Bill Irwin played George opposite Turner'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Tracy Letts played George in the 2012 revival', 'cast', 'fact', 'Letts won the Pulitzer for August: Osage County'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Edward Albee was 34 when the play premiered', 'playwright', 'fact', 'The Zoo Story and The American Dream had premiered Off-Broadway'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The play is structured in three acts titled "Fun and Games," "Walpurgisnacht," and "The Exorcism"', 'plot', 'fact', 'The act titles trace the evening''s descent from social games to psychological purging'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Opened October 13, 1962, during the Cuban Missile Crisis', 'history', 'fact', 'Cold War anxiety may have intensified the play''s themes of existential dread'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The play takes place in real time over one evening from 2 AM to dawn', 'plot', 'fact', 'Near-unity of time creates suffocating dramatic pressure'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The 2005 revival ran for 177 performances at the Longacre Theatre', 'numbers', 'fact', 'Kathleen Turner received a Tony nomination for Martha'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Albee reportedly wrote the title on a bar mirror after seeing the phrase scrawled in a Greenwich Village bar', 'history', 'fact', 'A play on the children''s song that became the play''s dark refrain'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The 2012 revival ran for 121 performances at the Booth Theatre', 'numbers', 'fact', 'Despite the short run, it was one of the most critically acclaimed productions of the season'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Costume design must reflect the characters'' academic New England lifestyle while allowing for the physical', 'design', 'fact', 'Martha''s wardrobe changes subtly from glamorous hostess to disheveled wreck'),

-- ============================================================
-- ANGELS IN AMERICA
-- ============================================================
('Angels in America', 'Broadway Play', 0, 'The production requires a wire flying rig for the Angel''s entrances', 'technical', 'fact', 'The flying system must support the weight of an actor in full angel costume with wings'),
('Angels in America', 'Broadway Play', 0, 'Eight actors play over 30 roles through extensive doubling', 'backstage', 'fact', 'The doubling scheme is specified by the playwright'),
('Angels in America', 'Broadway Play', 0, 'The full two-part production runs approximately 7 hours and 30 minutes', 'numbers', 'fact', 'Millennium Approaches and Perestroika are typically performed on separate days or as a marathon'),
('Angels in America', 'Broadway Play', 0, 'The set design must transform rapidly between over 20 locations including a hospital, courtroom, Antarctica', 'design', 'fact', 'Tony Kushner''s stage directions encourage theatrical rather than realistic transitions'),
('Angels in America', 'Broadway Play', 0, 'The Angel''s wings in the 2018 revival spanned approximately 10 feet and were constructed with articulated', 'design', 'fact', 'Each wing panel moved independently for dramatic effect'),
('Angels in America', 'Broadway Play', 0, 'Prosthetic makeup for Kaposi''s sarcoma lesions must be applied and tracked across multiple scenes', 'backstage', 'fact', 'The lesions appear on Prior Walter and grow more visible throughout the play'),
('Angels in America', 'Broadway Play', 0, 'The 2018 revival''s lighting design by Paule Constable used over 600 lighting cues across both parts', 'technical', 'fact', 'Constable won the Tony for her work on the production'),
('Angels in America', 'Broadway Play', 0, 'Ian MacNeil designed the 2018 revival set with a revolving structure that allowed rapid scene transitions', 'design', 'fact', 'Marianne Elliott directed the National Theatre transfer'),
('Angels in America', 'Broadway Play', 0, 'The Continental Principalities scene in Heaven requires complex projection or scenic effects to create', 'technical', 'fact', 'One of the most technically demanding sequences in modern American drama'),
('Angels in America', 'Broadway Play', 0, 'Millennium Approaches won the Tony Award for Best Play in 1993', 'award', 'fact', 'Also won the Pulitzer Prize for Drama the same year'),
('Angels in America', 'Broadway Play', 0, 'Perestroika won the Tony Award for Best Play in 1994, making it consecutive Tony wins for the two parts', 'award', 'fact', 'An unprecedented achievement for a multi-part play'),
('Angels in America', 'Broadway Play', 0, 'The 2018 revival received 11 Tony nominations, winning Best Revival', 'award', 'fact', 'Andrew Garfield and Nathan Lane both won acting Tonys'),
('Angels in America', 'Broadway Play', 0, 'George C. Wolfe directed both parts of the original Broadway production', 'production', 'fact', 'The original Millennium Approaches ran for 367 performances'),
('Angels in America', 'Broadway Play', 0, 'Andrew Garfield won the Tony for Best Actor in the 2018 revival as Prior Walter', 'cast', 'fact', 'Garfield''s Broadway debut in a dramatic role'),
('Angels in America', 'Broadway Play', 0, 'Nathan Lane won the Tony for Best Featured Actor in the 2018 revival as Roy Cohn', 'cast', 'fact', 'Lane''s third career Tony Award'),
('Angels in America', 'Broadway Play', 0, 'Ron Leibman originated the role of Roy Cohn in the 1993 original and won the Tony for Best Actor', 'cast', 'fact', 'Al Pacino later played Cohn in the 2003 HBO adaptation'),
('Angels in America', 'Broadway Play', 0, 'Stephen Spinella originated the role of Prior Walter and won consecutive Tonys for both parts', 'cast', 'fact', 'Best Actor Tonys in 1993 and 1994'),
('Angels in America', 'Broadway Play', 0, 'Tony Kushner worked on the play for over 5 years, with workshops at the Eureka Theatre in San Francisco', 'playwright', 'fact', 'The play evolved significantly through workshop productions before Broadway'),
('Angels in America', 'Broadway Play', 0, 'The subtitle is "A Gay Fantasia on National Themes," signaling its blend of realism, fantasy', 'history', 'fact', 'Kushner insisted on the subtitle for all productions'),
('Angels in America', 'Broadway Play', 0, 'Set design relies on Brechtian theatrical conventions rather than realism', 'design', 'fact', 'Kushner''s notes explicitly call for a non-illusionistic approach'),
('Angels in America', 'Broadway Play', 0, 'Robin Wagner designed the original Broadway set using a system of rolling platforms and flying scenic pieces', 'design', 'fact', 'Allowed the 20+ locations to flow without heavy scene changes'),
('Angels in America', 'Broadway Play', 0, 'The play is set in 1985-86 during the AIDS crisis and the Reagan administration', 'plot', 'fact', 'Roy Cohn, a real historical figure, is a central character'),
('Angels in America', 'Broadway Play', 0, 'The original Perestroika ran for 216 performances beginning in November 1993', 'numbers', 'fact', 'Shorter run than Millennium Approaches due to its later opening'),
('Angels in America', 'Broadway Play', 0, 'Millennium Approaches also won the Pulitzer Prize for Drama in 1993', 'award', 'fact', 'One of few plays to win both the Tony and the Pulitzer in the same year'),
('Angels in America', 'Broadway Play', 0, 'The 2018 revival transferred from the National Theatre in London to the Neil Simon Theatre', 'production', 'fact', 'The London production opened in 2017 to rapturous reviews'),

-- ============================================================
-- AUGUST: OSAGE COUNTY
-- ============================================================
('August: Osage County', 'Broadway Play', 0, 'Todd Rosenthal''s set design was a 3-story dollhouse cross-section showing all rooms of the Weston home', 'design', 'fact', 'Rosenthal won the Tony for Best Scenic Design for the production'),
('August: Osage County', 'Broadway Play', 0, 'The set weighed several tons and required custom steel framing to support the multi-level structure', 'backstage', 'fact', 'Load-in took multiple days at the Imperial Theatre'),
('August: Osage County', 'Broadway Play', 0, 'The production runs approximately 3 hours and 20 minutes with two intermissions', 'numbers', 'fact', 'One of the longest new plays to open on Broadway in recent decades'),
('August: Osage County', 'Broadway Play', 0, 'Lighting design by Ann G. Wrightson illuminated individual rooms of the 3-story set to guide audience focus', 'technical', 'fact', 'Rooms went dark or lit up to indicate where the action was happening'),
('August: Osage County', 'Broadway Play', 0, 'The house has no air conditioning as a plot point', 'backstage', 'fact', 'Costume and makeup choices reinforced the oppressive atmosphere'),
('August: Osage County', 'Broadway Play', 0, 'Ann Roth designed the costumes, differentiating three generations of women through wardrobe choices', 'design', 'fact', 'Each character''s clothing reflects their relationship to the family''s dysfunction'),
('August: Osage County', 'Broadway Play', 0, 'The dinner table scene in Act 2 requires a fully set table with practical food that 13 actors interact', 'backstage', 'fact', 'One of the most complex ensemble staging sequences in modern Broadway drama'),
('August: Osage County', 'Broadway Play', 0, 'Violet''s pill bottles are practical props that the actress handles throughout the show', 'backstage', 'fact', 'The pills become increasingly prominent as the play progresses'),
('August: Osage County', 'Broadway Play', 0, 'Sound design by David Van Tieghem included cicadas, distant thunder, and the ambient sounds of rural Oklahoma', 'technical', 'fact', 'The oppressive summer heat is conveyed partly through sound'),
('August: Osage County', 'Broadway Play', 0, 'The original production ran for 648 performances at the Imperial Theatre', 'numbers', 'fact', 'An unusually long run for a 3-plus-hour drama'),
('August: Osage County', 'Broadway Play', 0, 'Won the Tony Award for Best Play in 2008', 'award', 'fact', 'Also won 4 additional Tonys including Best Director and Best Actress'),
('August: Osage County', 'Broadway Play', 0, 'Won the Pulitzer Prize for Drama in 2008', 'award', 'fact', 'Tracy Letts became the first actor-playwright to win the Pulitzer in decades'),
('August: Osage County', 'Broadway Play', 0, 'Deanna Dunagan won the Tony for Best Actress as Violet Weston', 'award', 'fact', 'Her Broadway debut performance at age 67'),
('August: Osage County', 'Broadway Play', 0, 'Anna D. Shapiro directed both the Steppenwolf and Broadway productions', 'production', 'fact', 'She won the Tony for Best Direction of a Play'),
('August: Osage County', 'Broadway Play', 0, 'Transferred to Broadway from Steppenwolf Theatre Company in Chicago', 'history', 'fact', 'One of the most successful Steppenwolf-to-Broadway transfers in history'),
('August: Osage County', 'Broadway Play', 0, 'The cast of 13 actors makes it one of the largest ensembles for a new American play in the 21st century', 'cast', 'fact', 'The three-generation Weston family plus in-laws and outsiders'),
('August: Osage County', 'Broadway Play', 0, 'Tracy Letts wrote the play while working as an ensemble member at Steppenwolf', 'playwright', 'fact', 'Letts had previously written Bug and Killer Joe'),
('August: Osage County', 'Broadway Play', 0, 'The play is set in a large house outside Pawhuska, Oklahoma, in August', 'plot', 'fact', 'The Osage Nation territory setting adds layers of American displacement'),
('August: Osage County', 'Broadway Play', 0, 'Amy Morton played Barbara Fordham in the original cast, earning a Tony nomination', 'cast', 'fact', 'Morton later starred opposite Tracy Letts in the 2012 Virginia Woolf revival'),
('August: Osage County', 'Broadway Play', 0, 'The play opened December 4, 2007, at the Imperial Theatre on West 45th Street', 'production', 'fact', 'Produced by Jeffrey Richards and others'),
('August: Osage County', 'Broadway Play', 0, 'The set''s 3-story structure required audience members in the orchestra to look upward for scenes on the top', 'design', 'fact', 'A unique sightline challenge for a Broadway house'),
('August: Osage County', 'Broadway Play', 0, 'Rondi Reed won the Tony for Best Featured Actress as Mattie Fae Aiken', 'cast', 'fact', 'Another Steppenwolf ensemble member making her Broadway debut'),
('August: Osage County', 'Broadway Play', 0, 'The Steppenwolf premiere in June 2007 received unanimous raves from Chicago critics', 'history', 'fact', 'Transferred to Broadway within 6 months of its Chicago opening'),
('August: Osage County', 'Broadway Play', 0, 'The play is structured in three acts, each escalating the family''s revelations and confrontations', 'plot', 'fact', 'The dinner scene at the end of Act 2 is the dramatic centerpiece'),
('August: Osage County', 'Broadway Play', 0, 'Letts drew inspiration from the plays of Chekhov, O''Neill, and Albee for the family drama structure', 'playwright', 'fact', 'The large-family ensemble and multi-act structure echo classic American plays'),

-- ============================================================
-- FENCES
-- ============================================================
('Fences', 'Broadway Play', 0, 'The production requires actors to use real lumber and hammers to build a physical structure on stage', 'backstage', 'fact', 'The gradual construction is visible across multiple scenes'),
('Fences', 'Broadway Play', 0, 'The scenic design depicts a 1950s Pittsburgh backyard with a partially completed wooden structure', 'design', 'fact', 'The set evolves over the play''s timeline as construction progresses'),
('Fences', 'Broadway Play', 0, 'The ending requires a specific lighting effect triggered by the sound of Gabriel''s trumpet to suggest', 'technical', 'fact', 'One of the most debated staging moments in the August Wilson canon'),
('Fences', 'Broadway Play', 0, 'Santo Loquasto designed the 2010 revival set with meticulous period detail for the Hill District backyard', 'design', 'fact', 'Loquasto researched 1950s Pittsburgh working-class homes extensively'),
('Fences', 'Broadway Play', 0, 'The baseball bat that Troy carries and swings is a key practical prop used throughout the production', 'backstage', 'fact', 'Baseball metaphors are central to the character''s worldview'),
('Fences', 'Broadway Play', 0, 'Costume design must distinguish the characters'' working-class 1950s Pittsburgh wardrobe across a timeline', 'design', 'fact', 'Subtle wardrobe changes mark the passage of time between scenes'),
('Fences', 'Broadway Play', 0, 'Sound design for the play relies primarily on natural ambient sounds: birds, distant traffic', 'technical', 'fact', 'No musical underscoring is used; Wilson''s language provides all the rhythm'),
('Fences', 'Broadway Play', 0, 'The play requires a real screen door that actors slam, open, and exit through repeatedly', 'backstage', 'fact', 'The door''s sound punctuates key emotional moments'),
('Fences', 'Broadway Play', 0, 'The original 1987 production ran for 525 performances at the 46th Street Theatre', 'numbers', 'fact', 'The theater is now called the Richard Rodgers Theatre'),
('Fences', 'Broadway Play', 0, 'Won the Tony Award for Best Play in 1987', 'award', 'fact', 'Also won for Best Actor, Best Featured Actress, and Best Director'),
('Fences', 'Broadway Play', 0, 'Won the Pulitzer Prize for Drama in 1987', 'award', 'fact', 'August Wilson''s first Pulitzer; he won a second for The Piano Lesson'),
('Fences', 'Broadway Play', 0, 'James Earl Jones originated the role of Troy Maxson in the 1987 production', 'cast', 'fact', 'Jones brought his legendary vocal presence to Wilson''s language'),
('Fences', 'Broadway Play', 0, 'Mary Alice won the Tony for Best Featured Actress as Rose in the original cast', 'cast', 'fact', 'Her performance set the standard for the role'),
('Fences', 'Broadway Play', 0, 'Denzel Washington won the Tony for Best Actor in the 2010 revival', 'cast', 'fact', 'Washington later directed and starred in the 2016 film adaptation'),
('Fences', 'Broadway Play', 0, 'Viola Davis won the Tony for Best Actress in the 2010 revival as Rose', 'cast', 'fact', 'Davis also won the Oscar for the same role in the 2016 film'),
('Fences', 'Broadway Play', 0, 'Lloyd Richards directed the original 1987 Broadway production', 'production', 'fact', 'Richards directed 6 of August Wilson''s 10 plays in the Pittsburgh Cycle'),
('Fences', 'Broadway Play', 0, 'Kenny Leon directed the 2010 revival at the Cort Theatre', 'production', 'fact', 'Leon became Wilson''s primary director after Richards'' retirement'),
('Fences', 'Broadway Play', 0, 'The play is the sixth installment in August Wilson''s Century Cycle, set in the 1950s', 'history', 'fact', 'Each play in the 10-play cycle covers a different decade of African American experience'),
('Fences', 'Broadway Play', 0, 'Wilson set all but one of his Century Cycle plays in the Hill District of Pittsburgh', 'playwright', 'fact', 'The neighborhood was the center of Black cultural life in Pittsburgh'),
('Fences', 'Broadway Play', 0, 'The play premiered at the Yale Repertory Theatre in 1985 before regional runs and Broadway', 'history', 'fact', 'Went through productions in Chicago, San Francisco, and Seattle first'),
('Fences', 'Broadway Play', 0, 'The 2010 revival won the Tony for Best Revival of a Play', 'award', 'fact', 'All three acting nominees from the production won their categories'),
('Fences', 'Broadway Play', 0, 'The play takes place between 1957 and 1965 in the Maxson backyard', 'plot', 'fact', 'The 8-year span is marked primarily through the backyard''s physical changes'),
('Fences', 'Broadway Play', 0, 'Stephen McKinley Henderson played Jim Bono in both the 2010 revival and the 2016 film', 'cast', 'fact', 'Henderson was nominated for the Tony for Featured Actor'),
('Fences', 'Broadway Play', 0, 'The 2010 revival ran for 113 performances in a limited engagement', 'numbers', 'fact', 'Every performance sold out due to Washington and Davis''s star power'),
('Fences', 'Broadway Play', 0, 'Wilson based Troy Maxson partly on his own stepfather, David Bedford', 'playwright', 'fact', 'The character draws from multiple real-life inspirations'),

-- ============================================================
-- THE CURIOUS INCIDENT OF THE DOG IN THE NIGHT-TIME
-- ============================================================
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Bunny Christie''s set design features an LED-embedded floor grid that displays mathematical equations, maps', 'design', 'fact', 'Christie won the Tony for Best Scenic Design'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Paule Constable''s lighting design uses over 300 LED fixtures embedded in the floor, walls, and ceiling', 'technical', 'fact', 'Constable won the Tony for Best Lighting Design'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Finn Ross designed the video projections that display the protagonist''s mental processes on the LED walls', 'technical', 'fact', 'Mathematical formulas, maps, and visual patterns appear in real time'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Movement direction by Frantic Assembly''s Scott Graham and Steven Hoggett created a physical language', 'backstage', 'fact', 'Actors create environments like trains, city streets, and escalators using only their bodies'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The ensemble physically constructs a moving train, a crowded London Underground station', 'backstage', 'fact', 'No physical set pieces are used for these sequences'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Adrian Sutton composed an original electronic and orchestral score that plays live during performances', 'technical', 'fact', 'The score integrates with the LED floor and projection system'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The set is essentially a black box with an LED grid covering the floor, walls', 'design', 'fact', 'The minimalist physical set contrasts with the dense digital projections'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'A small rat puppet operated by an ensemble member is a recurring character in the production', 'design', 'fact', 'The puppet is deliberately simple, fitting the protagonist''s perspective'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The climactic math proof scene fills the entire LED grid with cascading equations while the actor performs', 'technical', 'fact', 'One of the most technically complex sequences in the show'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Won 5 Tony Awards in 2015 including Best Play', 'award', 'fact', 'Also won for Direction, Scenic Design, Lighting Design, and Lead Actor'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Alex Sharp won the Tony for Best Actor in his Broadway debut', 'cast', 'fact', 'Sharp was 25 years old and a Juilliard graduate'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Marianne Elliott directed both the National Theatre London production and the Broadway transfer', 'production', 'fact', 'Elliott later directed the 2018 Broadway Angels in America revival'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The production ran for approximately 800 performances at the Ethel Barrymore Theatre', 'numbers', 'fact', 'A strong commercial run for a play transfer from the National Theatre'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Transferred from the National Theatre in London, where it premiered in 2012', 'history', 'fact', 'Won 7 Olivier Awards in London before the Broadway transfer'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Simon Stephens adapted Mark Haddon''s 2003 novel for the stage', 'history', 'fact', 'Stephens chose to make the school play framing device central to the adaptation'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The cast includes approximately 9 actors who play multiple roles through physical transformation', 'cast', 'fact', 'Ensemble members shift between characters using movement rather than costume changes'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Ian Barford, Francesca Faridany, and Enid Graham were among the original Broadway ensemble', 'cast', 'fact', 'The ensemble''s physical stamina was tested by Frantic Assembly''s movement vocabulary'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Opened on Broadway October 5, 2014, at the Ethel Barrymore Theatre', 'production', 'fact', 'Produced by the National Theatre, Stuart Thompson, and others'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The production technology requires a dedicated video programmer running cues in sync with actors'' movements', 'technical', 'fact', 'Video cues must be timed precisely with the movement choreography'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The LED floor can display a full street map of London that the protagonist traces in real time', 'technical', 'fact', 'The route from Swindon to London is mapped on the floor as Christopher travels'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Haddon''s novel was a bestseller in both the adult and young adult markets before the stage adaptation', 'culture', 'fact', 'One of the rare cases of a novel succeeding in both categories and then on stage'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The play is told from the neurodivergent protagonist''s perspective', 'plot', 'fact', 'Every technical choice serves the subjective experience of the character'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Costume design by Bunny Christie kept the ensemble in simple contemporary clothes that allowed free movement', 'design', 'fact', 'Christie designed both set and costumes, winning Tonys for both'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Christopher James Sherrat designed sound that blends Sutton''s score with environmental audio processed', 'technical', 'fact', 'Sensory overload scenes use distorted sound to convey the protagonist''s experience'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The National Theatre production won the Olivier Award for Best New Play in 2013', 'award', 'fact', 'Part of a sweep of 7 Olivier Awards for the production'),

-- ============================================================
-- DOUBT
-- ============================================================
('Doubt', 'Broadway Play', 0, 'The production uses only 4 actors for the entire 90-minute performance', 'cast', 'fact', 'One of the smallest casts on Broadway, creating intense dramatic focus'),
('Doubt', 'Broadway Play', 0, 'John Lee Beatty designed a minimalist set depicting a school office and garden in the Bronx', 'design', 'fact', 'The spare design keeps the focus on the verbal confrontations'),
('Doubt', 'Broadway Play', 0, 'Pat Collins''s lighting design uses subtle shifts to suggest moral ambiguity', 'technical', 'fact', 'Shadow and partial light reflect the play''s central theme of uncertainty'),
('Doubt', 'Broadway Play', 0, 'Sound design relies on wind, church bells, and silence rather than underscoring', 'technical', 'fact', 'The austerity of the soundscape mirrors the convent setting'),
('Doubt', 'Broadway Play', 0, 'The production runs 90 minutes with no intermission', 'numbers', 'fact', 'The compressed format intensifies the dramatic confrontation'),
('Doubt', 'Broadway Play', 0, 'The set transitions between three locations: the principal''s office, the rectory, and a garden', 'design', 'fact', 'Beatty used minimal scenic elements to shift between spaces'),
('Doubt', 'Broadway Play', 0, 'Costume design by Catherine Zuber dressed the nuns in full traditional habits and the priest', 'design', 'fact', 'The 1964 setting required specific Catholic wardrobe research'),
('Doubt', 'Broadway Play', 0, 'Lighting cues create a cold, institutional atmosphere using fluorescent-toned fixtures above the office scenes', 'technical', 'fact', 'The garden scenes use warmer, natural-looking light by contrast'),
('Doubt', 'Broadway Play', 0, 'The original production ran for 525 performances at the Walter Kerr Theatre', 'numbers', 'fact', 'An impressive run for a 4-person, 90-minute play'),
('Doubt', 'Broadway Play', 0, 'Won the Tony Award for Best Play in 2005', 'award', 'fact', 'Swept the major categories in a season full of strong competition'),
('Doubt', 'Broadway Play', 0, 'Won the Pulitzer Prize for Drama in 2005', 'award', 'fact', 'John Patrick Shanley''s first and only Pulitzer'),
('Doubt', 'Broadway Play', 0, 'Cherry Jones won the Tony for Best Actress as Sister Aloysius', 'award', 'fact', 'Her performance became the definitive interpretation of the role'),
('Doubt', 'Broadway Play', 0, 'Adriane Lenox won the Tony for Best Featured Actress as Mrs. Muller', 'award', 'fact', 'Her single scene is considered one of the most powerful in the play'),
('Doubt', 'Broadway Play', 0, 'Doug Hughes directed the original 2005 Broadway production', 'production', 'fact', 'Hughes won the Tony for Best Direction of a Play'),
('Doubt', 'Broadway Play', 0, 'Brian F. O''Byrne originated the role of Father Flynn', 'cast', 'fact', 'O''Byrne received a Tony nomination for the role'),
('Doubt', 'Broadway Play', 0, 'Heather Goldenhersh completed the original 4-person cast as the younger Sister James', 'cast', 'fact', 'Goldenhersh was also nominated for the Tony for Featured Actress'),
('Doubt', 'Broadway Play', 0, 'The 2024 revival starred Liev Schreiber as Father Flynn and Amy Ryan as Sister Aloysius', 'cast', 'fact', 'Scott Ellis directed the revival at the Todd Haimes Theatre'),
('Doubt', 'Broadway Play', 0, 'John Patrick Shanley wrote the play as part of a trilogy about the Bronx Catholic community he grew up in', 'playwright', 'fact', 'The subtitle is "A Parable," signaling its allegorical intent'),
('Doubt', 'Broadway Play', 0, 'Shanley had previously won the Academy Award for his Moonstruck screenplay before writing this play', 'playwright', 'fact', 'His return to theater was a departure from his screenwriting career'),
('Doubt', 'Broadway Play', 0, 'The play is set in a Catholic school in the Bronx in 1964, during the post-Vatican II era', 'history', 'fact', 'The changing Church provides a backdrop of institutional upheaval'),
('Doubt', 'Broadway Play', 0, 'Shanley deliberately wrote an ending that provides no resolution, forcing the audience to sit with uncertainty', 'plot', 'fact', 'The final line has become one of the most discussed in modern American drama'),
('Doubt', 'Broadway Play', 0, 'Opened March 31, 2005, at the Walter Kerr Theatre on West 48th Street', 'production', 'fact', 'Transferred from Manhattan Theatre Club''s off-Broadway production'),
('Doubt', 'Broadway Play', 0, 'Originally premiered at MTC''s Stage I before the commercial Broadway transfer', 'history', 'fact', 'The off-Broadway run began in November 2004'),
('Doubt', 'Broadway Play', 0, 'The play''s technical simplicity allows it to be staged in almost any theater space worldwide', 'culture', 'fact', 'One of the most widely produced new American plays of the 21st century'),
('Doubt', 'Broadway Play', 0, 'The sermon scenes that open each act are delivered directly to the audience, breaking the fourth wall', 'plot', 'fact', 'This device implicates the audience in the moral questions'),

-- ============================================================
-- THE INHERITANCE
-- ============================================================
('The Inheritance', 'Broadway Play', 0, 'The full two-part production runs approximately 6 hours and 35 minutes', 'numbers', 'fact', 'Typically performed as two separate evenings or a weekend marathon'),
('The Inheritance', 'Broadway Play', 0, 'Bob Crowley''s minimalist set design used a bare stage with simple wooden chairs and a few key furniture pieces', 'design', 'fact', 'Crowley won the Tony for Best Scenic Design'),
('The Inheritance', 'Broadway Play', 0, 'Scene changes are performed by the actors themselves, with no crew visible during transitions', 'backstage', 'fact', 'The actor-driven staging keeps the storytelling theatrical and immediate'),
('The Inheritance', 'Broadway Play', 0, 'Bob Crowley designed both the set and costumes, integrating a cohesive visual language across the production', 'design', 'fact', 'The dual role allowed complete control of the production''s visual world'),
('The Inheritance', 'Broadway Play', 0, 'The lighting design by Jon Clark shifts between warm domestic scenes and stark, exposed theatrical space', 'technical', 'fact', 'Clark''s work emphasizes the play''s movement between realism and storytelling'),
('The Inheritance', 'Broadway Play', 0, 'Paul Arditti designed the sound, incorporating period music and ambient sound that evokes different New York', 'technical', 'fact', 'The soundscape spans from Upper West Side apartments to Fire Island beach houses'),
('The Inheritance', 'Broadway Play', 0, 'The production requires 13 actors playing multiple roles with minimal costume changes', 'cast', 'fact', 'The doubling creates thematic connections between generations of characters'),
('The Inheritance', 'Broadway Play', 0, 'The storytelling uses a narrator device where characters describe scenes before they happen', 'backstage', 'fact', 'Actors shift between narration and character seamlessly'),
('The Inheritance', 'Broadway Play', 0, 'Stephen Daldry directed both the Young Vic London premiere and the Broadway production', 'production', 'fact', 'Daldry is known for directing Billy Elliot and The Audience'),
('The Inheritance', 'Broadway Play', 0, 'Won the Tony Award for Best Play in the 2019-20 season, awarded at the 2021 ceremony', 'award', 'fact', 'The ceremony was delayed due to the COVID-19 pandemic'),
('The Inheritance', 'Broadway Play', 0, 'Andrew Burnap won the Tony for Best Actor in a Play', 'award', 'fact', 'His Broadway debut performance as the lead character Toby Darling'),
('The Inheritance', 'Broadway Play', 0, 'The production closed abruptly in March 2020 due to COVID-19, having run only about 4 months on Broadway', 'numbers', 'fact', 'One of the most acclaimed productions cut short by the pandemic shutdown'),
('The Inheritance', 'Broadway Play', 0, 'Matthew Lopez wrote the play, inspired by E.M. Forster''s novel Howards End', 'playwright', 'fact', 'Lopez transposed Forster''s class themes onto contemporary gay male life in New York'),
('The Inheritance', 'Broadway Play', 0, 'The play features E.M. Forster as a character who guides the narrative', 'plot', 'fact', 'Forster appears as a kind of ghost narrator connecting past and present'),
('The Inheritance', 'Broadway Play', 0, 'Transferred to Broadway from the Young Vic in London, where it premiered in 2018', 'history', 'fact', 'The London production was extended multiple times due to demand'),
('The Inheritance', 'Broadway Play', 0, 'The play spans three decades of gay American life from the 1980s AIDS crisis to the present', 'history', 'fact', 'The title refers to what one generation passes to the next'),
('The Inheritance', 'Broadway Play', 0, 'Opened at the Ethel Barrymore Theatre on November 17, 2019', 'production', 'fact', 'Part 1 and Part 2 alternated in the theater schedule'),
('The Inheritance', 'Broadway Play', 0, 'John Benjamin Hickey starred as Henry Wilcox in the original Broadway cast', 'cast', 'fact', 'Hickey was previously known for his Tony-winning turn in The Normal Heart'),
('The Inheritance', 'Broadway Play', 0, 'Kyle Soller originated the role of Eric Glass in the London production and received Olivier nominations', 'cast', 'fact', 'Soller won the Olivier Award for Best Actor'),
('The Inheritance', 'Broadway Play', 0, 'The London production won the Olivier Award for Best New Play in 2019', 'award', 'fact', 'It received widespread critical acclaim as the most important new play in years'),
('The Inheritance', 'Broadway Play', 0, 'Lopez wrote the first draft in 2015, and the play went through extensive workshops before the Young Vic', 'history', 'fact', 'The development process took approximately 3 years'),
('The Inheritance', 'Broadway Play', 0, 'The play uses direct address to the audience, with characters speaking their interior thoughts aloud', 'plot', 'fact', 'Blurs the line between novel narration and theatrical performance'),
('The Inheritance', 'Broadway Play', 0, 'Lois Smith played the role of Margaret in the Broadway production at age 89', 'cast', 'fact', 'One of the most veteran actors in the cast'),
('The Inheritance', 'Broadway Play', 0, 'The production''s minimal set allowed it to be staged in the Barrymore without extensive load-in', 'backstage', 'fact', 'A deliberate choice to keep the focus on actors and text'),
('The Inheritance', 'Broadway Play', 0, 'Lopez described the play as asking what gay men owe to the generation that survived the AIDS crisis', 'playwright', 'fact', 'The intergenerational theme drives both parts of the play'),

-- ============================================================
-- SLAVE PLAY
-- ============================================================
('Slave Play', 'Broadway Play', 0, 'Clint Ramos designed a mirrored set that forced the audience to see their own reflections', 'design', 'fact', 'The mirrors implicated the audience as participants in the play''s racial dynamics'),
('Slave Play', 'Broadway Play', 0, 'Jiyoun Chang''s lighting design created stark contrasts between the antebellum fantasy scenes and the therapy', 'technical', 'fact', 'Warm plantation lighting gave way to harsh clinical fluorescents'),
('Slave Play', 'Broadway Play', 0, 'Lindsay Jones designed the sound, incorporating period music and contemporary songs that collided across time', 'technical', 'fact', 'The soundscape blurred boundaries between past and present'),
('Slave Play', 'Broadway Play', 0, 'Dede Ayite designed the costumes, creating antebellum-era outfits for the opening scenes that gave way', 'design', 'fact', 'The costume transformation marks the shift from fantasy to therapy'),
('Slave Play', 'Broadway Play', 0, 'The mirrored back wall was a massive scenic element that required careful sightline engineering', 'design', 'fact', 'Audience members in different sections saw different reflections'),
('Slave Play', 'Broadway Play', 0, 'The production staged "Black Out" performances where all 804 seats were given exclusively to Black audience', 'culture', 'fact', 'A groundbreaking and controversial experiment in audience composition'),
('Slave Play', 'Broadway Play', 0, 'The sound design included field recordings and period instrumentation for the antebellum scenes', 'technical', 'fact', 'Acoustic choices reinforced the uncanny blend of historical and contemporary'),
('Slave Play', 'Broadway Play', 0, 'The play''s structure places three couples in antebellum settings before revealing the modern therapeutic', 'backstage', 'fact', 'The theatrical twist requires precise timing in scenic, lighting, and costume transitions'),
('Slave Play', 'Broadway Play', 0, 'Received 12 Tony nominations in 2020, the most of any play that season', 'award', 'fact', 'Did not win in any category, setting a record for most nominations without a win'),
('Slave Play', 'Broadway Play', 0, 'The original Broadway run lasted only 17 previews and 120 regular performances', 'numbers', 'fact', 'Opened December 2019 and closed January 2020'),
('Slave Play', 'Broadway Play', 0, 'Robert O''Hara directed the Broadway production', 'production', 'fact', 'O''Hara received a Tony nomination for Best Direction'),
('Slave Play', 'Broadway Play', 0, 'Jeremy O. Harris wrote the play as part of his MFA thesis at Yale School of Drama', 'playwright', 'fact', 'Harris was 29 when the play opened on Broadway'),
('Slave Play', 'Broadway Play', 0, 'Transferred to Broadway from New York Theatre Workshop, where it premiered in late 2018', 'history', 'fact', 'The NYTW production generated intense critical and public discourse'),
('Slave Play', 'Broadway Play', 0, 'Opened at the John Golden Theatre on October 6, 2019', 'production', 'fact', 'One of the most discussed Broadway openings of the decade'),
('Slave Play', 'Broadway Play', 0, 'The cast featured Joaquina Kalukango, who later won a Tony for Paradise Square', 'cast', 'fact', 'Kalukango played Kaneisha in the Broadway production'),
('Slave Play', 'Broadway Play', 0, 'Paul Alexander Nolan and James Cusati-Moyer were among the original Broadway ensemble', 'cast', 'fact', 'Cusati-Moyer received a Tony nomination for Featured Actor'),
('Slave Play', 'Broadway Play', 0, 'The play is structured as three "Antebellum Sexual Performance Therapy" sessions', 'plot', 'fact', 'Each couple engages in role-playing rooted in plantation-era power dynamics'),
('Slave Play', 'Broadway Play', 0, 'Harris became one of the youngest playwrights to have a play produced on Broadway in the 21st century', 'playwright', 'fact', 'His meteoric rise from MFA student to Broadway drew widespread attention'),
('Slave Play', 'Broadway Play', 0, 'The production sparked intense debate about race, sexuality, and spectatorship in American theater', 'culture', 'fact', 'It became one of the most discussed Broadway plays in years'),
('Slave Play', 'Broadway Play', 0, 'The play was influenced by the work of visual artists Kara Walker and Dread Scott', 'history', 'fact', 'Harris cited visual art as a primary inspiration alongside theatrical traditions'),
('Slave Play', 'Broadway Play', 0, 'Ari''el Stachel and Annie McNamara were also part of the original Broadway cast', 'cast', 'fact', 'The ensemble of 8 actors played the 3 couples plus therapists'),
('Slave Play', 'Broadway Play', 0, 'The New York Theatre Workshop production sold out its entire run before opening night', 'numbers', 'fact', 'Demand for tickets was unprecedented for a new play at NYTW'),
('Slave Play', 'Broadway Play', 0, 'The "Black Out" nights generated national media coverage and debate about representation in theater audiences', 'culture', 'fact', 'Some praised the initiative while others questioned the segregation of audiences'),
('Slave Play', 'Broadway Play', 0, 'Ramos also designed the costumes for the NYTW production before the Broadway transfer', 'design', 'fact', 'He maintained design continuity between the two productions'),
('Slave Play', 'Broadway Play', 0, 'The play runs approximately 90 minutes without intermission', 'numbers', 'fact', 'The tight structure builds relentless tension through its three-part framework'),

-- ============================================================
-- TO KILL A MOCKINGBIRD
-- ============================================================
('To Kill a Mockingbird', 'Broadway Play', 0, 'Miriam Buether designed a rotating set with 10 moving scenic pieces that create the courtroom, street', 'design', 'fact', 'The revolving elements allow seamless transitions between Maycomb locations'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The production performed at Madison Square Garden for an audience of 18', 'backstage', 'fact', 'The MSG stage was 90 feet wide by 40 feet deep and required 105 stagehands'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Jennifer Tipton designed the lighting at age 81', 'technical', 'fact', 'Tipton is one of the most honored lighting designers in Broadway history'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Adam Guettel composed original incidental music for the production', 'technical', 'fact', 'Guettel is best known for composing The Light in the Piazza'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The courtroom scenes use a full audience gallery built into the set, with actors seated as townspeople', 'design', 'fact', 'Creates the immersive feeling of a packed Southern courtroom'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Buether''s set includes a towering tree and a full front porch that serve as the production''s anchor points', 'design', 'fact', 'The porch and tree evoke small-town Southern life without literal realism'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The MSG student performance required building a custom temporary stage and relocating the entire production', 'backstage', 'fact', 'The largest single performance of a play in history'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Scott Lehrer designed the sound, creating the ambient world of 1930s Alabama with crickets, birds', 'technical', 'fact', 'Environmental sound builds the small-town atmosphere around the courtroom drama'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Ann Roth designed the period costumes, researching Depression-era Alabama wardrobe for accuracy', 'design', 'fact', 'Each character''s clothing communicates their social status in Maycomb'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The original Broadway production ran for 626 performances before COVID-19 forced its closure', 'numbers', 'fact', 'Returned post-pandemic but eventually closed in 2022'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Broke the Shubert Theatre''s all-time box office record', 'numbers', 'fact', 'The highest-grossing production in the theater''s history at that time'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Jeff Daniels originated the role of Atticus Finch in the 2018 production', 'cast', 'fact', 'Daniels was later replaced by Ed Harris and then Greg Kinnear'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Celia Keenan-Bolger won the Tony for Best Featured Actress as Scout', 'award', 'fact', 'An adult actress playing the child narrator'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Aaron Sorkin adapted Harper Lee''s novel for the stage', 'production', 'fact', 'Sorkin restructured the narrative to begin with the trial and use flashbacks'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Bartlett Sher directed the Broadway production at the Shubert Theatre', 'production', 'fact', 'Sher is known for directing large-scale revivals at Lincoln Center'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The production faced a lawsuit from the Harper Lee estate over Sorkin''s changes to the characters', 'history', 'fact', 'The estate objected to Atticus being portrayed as initially flawed'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Opened December 13, 2018, at the Shubert Theatre on West 44th Street', 'production', 'fact', 'Produced by Scott Rudin and others'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Gbenga Akinnagbe originated the role of Tom Robinson in the Broadway production', 'cast', 'fact', 'Akinnagbe brought a powerful physical presence to the wrongly accused character'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The three children — Scout, Jem, and Dill — are played by adult actors throughout the production', 'cast', 'fact', 'Sorkin''s script addresses the adult-playing-child convention directly'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Ed Harris replaced Jeff Daniels as Atticus in 2019, bringing a different energy to the role', 'cast', 'fact', 'The role has attracted major film actors to Broadway'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Sorkin''s adaptation restructures Lee''s novel to open with the trial verdict', 'history', 'fact', 'A significant structural departure from the book''s chronological narration'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The MSG performance on February 26, 2020, was free for all 18,000 students in attendance', 'culture', 'fact', 'Students from all five boroughs attended the landmark event'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Received 9 Tony nominations in 2019 including Best Play', 'award', 'fact', 'The production faced stiff competition from The Ferryman that season'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The national tour launched in 2022, making it one of the first major play tours post-pandemic', 'numbers', 'fact', 'Richard Thomas starred as Atticus on the tour'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The production is set in Maycomb, Alabama, in 1934 during the Great Depression', 'plot', 'fact', 'The racial injustice of the era drives the central trial narrative');
