-- SPIKE Clue Bank — Touring City
-- 15 subjects x ~33 clues each

INSERT INTO clue_bank (show_name, category, level, clue_text, clue_type, specificity, notes) VALUES

-- ============================================================
-- CHICAGO
-- ============================================================
('Chicago', 'Touring City', 1, 'This city is located on the shores of one of North America''s Great Lakes', 'geography', 'very_broad', 'Could describe several touring markets; establishes lakeside location'),
('Chicago', 'Touring City', 1, 'Known for cold winters and a famous wind phenomenon', 'culture', 'very_broad', 'Applies to multiple Midwest cities'),
('Chicago', 'Touring City', 1, 'This city has a world-famous architectural style with tall buildings', 'landmark', 'very_broad', 'Many cities known for distinctive architecture'),
('Chicago', 'Touring City', 1, 'Deep-dish pizza originated in this city', 'culture', 'very_broad', 'Regional culinary signature, but relatively specific'),
('Chicago', 'Touring City', 1, 'Home to a legendary improvisational comedy institution founded in 1959', 'culture', 'very_broad', 'Second City is famous but reference is indirect'),
('Chicago', 'Touring City', 1, 'This major U.S. city is the second-largest touring market for Broadway productions', 'theater_scene', 'very_broad', 'Describes ranking but doesn''t name the city'),
('Chicago', 'Touring City', 2, 'The CIBC Theatre (formerly PrivateBank Theatre) hosts touring Broadway shows in this city', 'venue', 'broad', 'Specific venue name requires theater knowledge'),
('Chicago', 'Touring City', 2, 'Broadway In [City] is one of the largest touring production series in the country', 'theater_scene', 'broad', 'Refers to touring brand without naming city'),
('Chicago', 'Touring City', 2, 'The Cadillac Palace Theatre and James M. Nederlander Theatre are major touring venues here', 'venue', 'broad', 'Multiple venue names, requires research to connect'),
('Chicago', 'Touring City', 2, 'The Oriental Theatre, originally designed in an ornate style, now operates under a new corporate name', 'venue', 'broad', 'Historical venue reference with name change'),
('Chicago', 'Touring City', 2, 'This city hosted the first-ever production of "Hamilton" outside of New York City on Broadway''s national tour', 'history', 'broad', 'Significant Broadway touring milestone'),
('Chicago', 'Touring City', 2, 'The Blues are a major professional sports team in this city', 'culture', 'broad', 'Hockey reference, parallel to major touring city infrastructure'),
('Chicago', 'Touring City', 3, 'Lake Michigan borders this Windy City home to Broadway touring shows', 'geography', 'narrowing', 'Combines "Windy City" reference with geographic detail'),
('Chicago', 'Touring City', 3, 'The CIBC Theatre is located in the Loop, the downtown district of this city known for elevated trains', 'venue', 'narrowing', 'Specific district detail plus venue specificity'),
('Chicago', 'Touring City', 3, 'This city''s second-largest performing arts complex is at the Civic Opera House, built in 1929', 'venue', 'narrowing', 'Specific date and building detail'),
('Chicago', 'Touring City', 3, 'The improv comedy sketch style originating from Second City in this location influenced Saturday Night Live', 'theater_scene', 'narrowing', 'Specific cultural connection to SNL'),
('Chicago', 'Touring City', 3, 'This city is home to Frank Lloyd Wright''s most concentrated collection of residential architecture', 'landmark', 'narrowing', 'Architectural detail specific to city''s identity'),
('Chicago', 'Touring City', 3, 'The 95-story building that was the world''s tallest from 1973-1998 is located here', 'landmark', 'narrowing', 'Sears Tower reference with specific historical dates'),
('Chicago', 'Touring City', 4, 'The CIBC Theatre stages Broadway productions in a building that once housed the LaSalle Bank offices', 'venue', 'recognition', 'Direct venue-to-building history, requires specific knowledge'),
('Chicago', 'Touring City', 4, 'Second City Theatre on North Avenue has trained performers like Tina Fey, Amy Poehler, and Steve Carell', 'theater_scene', 'recognition', 'Specific venue with recognizable alumni'),
('Chicago', 'Touring City', 4, 'The Chicago River is dyed green annually on Saint Patrick''s Day in this city''s downtown', 'culture', 'recognition', 'Distinctive annual event'),
('Chicago', 'Touring City', 4, 'This city''s skyline features the Willis Tower (formerly Sears Tower) and is dominated by Art Deco skyscrapers', 'landmark', 'recognition', 'Multiple specific architectural references'),
('Chicago', 'Touring City', 4, 'The Cadillac Palace Theatre is located on West Randolph Street', 'venue', 'recognition', 'Specific address and historical significance'),
('Chicago', 'Touring City', 4, 'This city hosted every major touring production including "The Lion King," "Hamilton', 'theater_scene', 'recognition', 'Mentions multiple Broadway blockbuster tours'),
('Chicago', 'Touring City', 5, 'CIBC Theatre in [City] has hosted Broadway''s biggest touring productions', 'venue', 'giveaway', 'Direct venue identification'),
('Chicago', 'Touring City', 5, 'This is the only U.S. city with two active historic opera houses (Civic Opera House and Athenaeum Theatre)', 'venue', 'giveaway', 'Distinctive venue distinction'),
('Chicago', 'Touring City', 5, 'The Windy City is home to Second City, the improv comedy institution that inspired Saturday Night Live', 'culture', 'giveaway', 'Windy City epithet makes identification clear'),
('Chicago', 'Touring City', 5, 'This city serves as Broadway''s second-largest touring market after New York', 'theater_scene', 'giveaway', 'Definitive ranking statement'),
('Chicago', 'Touring City', 0, 'The Oriental Theatre (now CIBC Theatre) was designed in 1926 with ornate Gothic Revival and Asian-inspired', 'interesting_fact', 'fact', 'Theater venue technical history'),
('Chicago', 'Touring City', 0, 'The Civic Opera House, completed in 1929, cost $20 million to build and is a National Historic Landmark', 'interesting_fact', 'fact', 'Venue construction and historic designation'),
('Chicago', 'Touring City', 0, 'Second City Theatre has a storied training program that has produced hundreds of comedians and actors', 'interesting_fact', 'fact', 'Theater institution legacy'),
('Chicago', 'Touring City', 0, 'The Chicago theatre district consists of over 200 theatres', 'interesting_fact', 'fact', 'Theater concentration and scope'),
('Chicago', 'Touring City', 0, 'Lake Michigan provides a natural cooling system that allowed development of the Loop''s early skyscraper', 'interesting_fact', 'fact', 'Geographic-architectural connection'),

-- ============================================================
-- LOS ANGELES
-- ============================================================
('Los Angeles', 'Touring City', 1, 'This city is known for consistent year-round sunny weather and a thriving entertainment industry', 'culture', 'very_broad', 'Could describe multiple California cities'),
('Los Angeles', 'Touring City', 1, 'The second-largest city in the United States by population is located in this state', 'geography', 'very_broad', 'Generic size descriptor'),
('Los Angeles', 'Touring City', 1, 'This West Coast city is home to major film and television production studios', 'culture', 'very_broad', 'Applies to multiple West Coast locations'),
('Los Angeles', 'Touring City', 1, 'A famous sign on a hillside spells out the name of this city in the Hollywood Hills', 'landmark', 'very_broad', 'Famous sign is distinctive but reference is indirect'),
('Los Angeles', 'Touring City', 1, 'This city hosts major touring Broadway productions as a pre-Broadway testing ground', 'theater_scene', 'very_broad', 'Describes function without naming'),
('Los Angeles', 'Touring City', 1, 'Beautiful beaches and a Mediterranean climate characterize this Southern California metropolis', 'geography', 'very_broad', 'Could apply to multiple SoCal cities'),
('Los Angeles', 'Touring City', 2, 'The Pantages Theatre in Hollywood hosts major touring Broadway productions', 'venue', 'broad', 'Specific venue name requires theater knowledge'),
('Los Angeles', 'Touring City', 2, 'The Dolby Theatre, home to the Academy Awards ceremony, occasionally hosts touring Broadway shows', 'venue', 'broad', 'Famous venue with awards show connection'),
('Los Angeles', 'Touring City', 2, 'The Ahmanson Theatre and Mark Taper Forum are part of the Music Center in downtown this city', 'venue', 'broad', 'Multiple venue names and cultural center'),
('Los Angeles', 'Touring City', 2, 'This city is the birthplace of the film industry and hosts the Hollywood Walk of Fame', 'culture', 'broad', 'Entertainment history connection'),
('Los Angeles', 'Touring City', 2, 'The Pantages Theatre was built in 1930 as a movie palace and now hosts Broadway touring productions', 'venue', 'broad', 'Venue conversion history'),
('Los Angeles', 'Touring City', 2, 'Many Broadway shows do pre-Broadway tryouts in this city before moving to Broadway', 'theater_scene', 'broad', 'Describes pre-Broadway function'),
('Los Angeles', 'Touring City', 3, 'The Pantages Theatre, built by Alexander Pantages, is located on Hollywood Boulevard in this city', 'venue', 'narrowing', 'Specific street and builder reference'),
('Los Angeles', 'Touring City', 3, 'This city''s Dolby Theatre hosts Broadway touring productions and is famous for its red carpet', 'venue', 'narrowing', 'Specific venue with awards ceremony detail'),
('Los Angeles', 'Touring City', 3, 'The Mark Taper Forum was founded in 1967 as a regional theater venue in downtown this city', 'venue', 'narrowing', 'Specific founding date and location detail'),
('Los Angeles', 'Touring City', 3, 'This sprawling city extends from the Hollywood Hills down to beaches along the Pacific Ocean', 'geography', 'narrowing', 'Geographic spread detail'),
('Los Angeles', 'Touring City', 3, 'The Hollywood sign was erected in 1923 on Mount Lee in this city as an advertisement for a local development', 'landmark', 'narrowing', 'Specific date and original purpose'),
('Los Angeles', 'Touring City', 3, 'This city has more theaters than any other touring city except New York', 'theater_scene', 'narrowing', 'Quantifies theater concentration'),
('Los Angeles', 'Touring City', 4, 'The Pantages Theatre on Hollywood Boulevard features a stunning Art Deco interior and chandelier', 'venue', 'recognition', 'Specific architectural style and historical context'),
('Los Angeles', 'Touring City', 4, 'The Ahmanson Theatre and Mark Taper Forum are part of the Music Center, which opened in 1964 downtown', 'venue', 'recognition', 'Specific opening date for cultural complex'),
('Los Angeles', 'Touring City', 4, 'This city has hosted every major Broadway touring production including "The Lion King," "Wicked', 'theater_scene', 'recognition', 'Mentions major touring hits'),
('Los Angeles', 'Touring City', 4, 'The Hollywood Walk of Fame contains over 2,700 brass stars embedded in the sidewalks of this city', 'landmark', 'recognition', 'Specific feature count'),
('Los Angeles', 'Touring City', 4, 'Universal Studios, Disneyland, and Six Flags Magic Mountain are all located in or near this city', 'landmark', 'recognition', 'Multiple major attractions'),
('Los Angeles', 'Touring City', 4, 'This city is home to the Getty Center, a world-famous art museum perched on a hillside overlooking', 'landmark', 'recognition', 'Specific cultural institution'),
('Los Angeles', 'Touring City', 5, 'The Pantages Theatre in Hollywood is a major touring venue in this city', 'venue', 'giveaway', 'Direct venue-to-city identification'),
('Los Angeles', 'Touring City', 5, 'This city is famous for the Hollywood sign and hosts major film industry events like the Academy Awards', 'landmark', 'giveaway', 'Combination of distinctive features'),
('Los Angeles', 'Touring City', 5, 'The Dolby Theatre, Pantages Theatre, and Ahmanson Theatre make this one of the largest touring Broadway', 'venue', 'giveaway', 'Multiple iconic venue names'),
('Los Angeles', 'Touring City', 5, 'This Southern California city is home to Disneyland and the Getty Center', 'landmark', 'giveaway', 'Distinctive major attractions'),
('Los Angeles', 'Touring City', 0, 'The Pantages Theatre''s original 1930 chandelier weighs over 5 tons and is a centerpiece of the Art Deco', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Los Angeles', 'Touring City', 0, 'The Music Center campus includes four major theaters totaling over 3,000 seats for theatrical productions', 'interesting_fact', 'fact', 'Theater complex capacity information'),
('Los Angeles', 'Touring City', 0, 'The Ahmanson Theatre has a single largest single span in the world without internal supports', 'interesting_fact', 'fact', 'Theater architectural innovation'),
('Los Angeles', 'Touring City', 0, 'Universal Studios, founded in 1915, is the oldest and largest film studio in this city still operating', 'interesting_fact', 'fact', 'Studio history and ongoing operation'),
('Los Angeles', 'Touring City', 0, 'The Pacific Ocean provides a scenic backdrop and temperate climate that has made this city a year-round', 'interesting_fact', 'fact', 'Geographic and climate advantages'),

-- ============================================================
-- BOSTON
-- =========================================================
('Boston', 'Touring City', 1, 'This historic East Coast city is home to one of the oldest universities in the United States', 'culture', 'very_broad', 'Could describe multiple northeastern cities'),
('Boston', 'Touring City', 1, 'Known for strong accents, clam chowder, and maritime history, this city is located in New England', 'culture', 'very_broad', 'Regional characteristics apply to broader area'),
('Boston', 'Touring City', 1, 'A major professional sports city with teams known for championship victories in recent decades', 'culture', 'very_broad', 'Could describe multiple successful sports cities'),
('Boston', 'Touring City', 1, 'The Freedom Trail is a famous walking path through this historic American city', 'landmark', 'very_broad', 'Historic trail is well-known but reference indirect'),
('Boston', 'Touring City', 1, 'This city has a strong tradition of pre-Broadway theatrical tryouts', 'theater_scene', 'very_broad', 'Describes function without naming'),
('Boston', 'Touring City', 1, 'A colonial-era city on the Atlantic coast with significant American Revolutionary War history', 'history', 'very_broad', 'Could describe multiple northeastern cities'),
('Boston', 'Touring City', 2, 'The Citizens Bank Opera House (formerly Paramount Theatre) hosts touring Broadway productions', 'venue', 'broad', 'Specific venue name with recent history'),
('Boston', 'Touring City', 2, 'The Emerson Colonial Theatre is the oldest continuously operating theater in this city', 'venue', 'broad', 'Historic venue designation requires research'),
('Boston', 'Touring City', 2, 'The Boch Center Shubert Theatre is home to touring Broadway productions in this New England city', 'venue', 'broad', 'Specific venue within cultural center'),
('Boston', 'Touring City', 2, 'Harvard University, founded in 1636, is located in Cambridge, adjacent to this major touring city', 'culture', 'broad', 'Educational prestige connection'),
('Boston', 'Touring City', 2, 'This city hosted legendary pre-Broadway tryouts for shows like "A Chorus Line" and "Sweeney Todd"', 'history', 'broad', 'Specific theatrical productions'),
('Boston', 'Touring City', 2, 'The Freedom Trail passes through major historic sites including the Old State House and USS Constitution', 'landmark', 'broad', 'Trail details without naming city directly'),
('Boston', 'Touring City', 3, 'The Citizens Bank Opera House is located on Washington Street in downtown this city', 'venue', 'narrowing', 'Specific street and previous name'),
('Boston', 'Touring City', 3, 'The Emerson Colonial Theatre, opened in 1900, is the oldest continuously operating theater in New England', 'venue', 'narrowing', 'Specific opening date and regional designation'),
('Boston', 'Touring City', 3, 'The Boch Center, a major arts complex, is part of Emerson College and includes multiple theaters in this city', 'venue', 'narrowing', 'Cultural center affiliation detail'),
('Boston', 'Touring City', 3, 'This city is bordered by the Charles River and sits on a peninsula that was fortified during the American', 'geography', 'narrowing', 'Geographic and historical detail'),
('Boston', 'Touring City', 3, 'The Green Monster is a famous wall at Fenway Park, the home stadium of the Red Sox in this city', 'landmark', 'narrowing', 'Sports landmark specific to this city'),
('Boston', 'Touring City', 3, 'This city''s theater scene has historically served as a testing ground for Broadway-bound shows before moving', 'theater_scene', 'narrowing', 'Function-specific historical role'),
('Boston', 'Touring City', 4, 'The Citizens Bank Opera House features a Renaissance Revival interior with ornate decorations and a large', 'venue', 'recognition', 'Specific architectural style and features'),
('Boston', 'Touring City', 4, 'The Emerson Colonial Theatre has maintained its original interior design and layout since its opening in 1900', 'venue', 'recognition', 'Specific historic preservation claim'),
('Boston', 'Touring City', 4, 'This city is home to the Museum of Science, which sits on the Charles River between this city and Cambridge', 'landmark', 'recognition', 'Specific cultural institution location'),
('Boston', 'Touring City', 4, 'The Red Sox are one of the most famous Major League Baseball teams and play at Fenway Park in this historic', 'culture', 'recognition', 'Sports team identification'),
('Boston', 'Touring City', 4, 'This city hosted the tryout for "Company" (Sondheim) before its Broadway success in 1970', 'history', 'recognition', 'Specific pre-Broadway production detail'),
('Boston', 'Touring City', 4, 'The Boch Center is home to the Boston Ballet and Boston Opera productions alongside Broadway touring shows', 'venue', 'recognition', 'Multiple resident company detail'),
('Boston', 'Touring City', 5, 'The Citizens Bank Opera House and Emerson Colonial Theatre are major touring venues in this historic New', 'venue', 'giveaway', 'Multiple iconic venue names'),
('Boston', 'Touring City', 5, 'The Freedom Trail passes through this city''s downtown, connecting 16 historic Revolutionary War-era sites', 'landmark', 'giveaway', 'Distinctive historic walking path'),
('Boston', 'Touring City', 5, 'Harvard University in Cambridge and the Red Sox at Fenway Park are cultural icons of this city', 'culture', 'giveaway', 'Combination of distinctive features'),
('Boston', 'Touring City', 5, 'This city has a centuries-old tradition of pre-Broadway theatrical tryouts and regional theater production', 'theater_scene', 'giveaway', 'Specific theatrical legacy claim'),
('Boston', 'Touring City', 0, 'The Emerson Colonial Theatre features a gold-leaf ornamental ceiling and Italian Renaissance-style interior', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Boston', 'Touring City', 0, 'The Boch Center is one of the largest theater complexes in New England with four major performance spaces', 'interesting_fact', 'fact', 'Theater complex scale information'),
('Boston', 'Touring City', 0, 'Harvard University, founded in 1636, is the oldest institution of higher education in the United States', 'interesting_fact', 'fact', 'Educational institution historic significance'),
('Boston', 'Touring City', 0, 'Fenway Park, opened in 1912, is the oldest continuously operated Major League Baseball stadium in the United', 'interesting_fact', 'fact', 'Sports venue historic designation'),
('Boston', 'Touring City', 0, 'The Charles River, which borders this city', 'interesting_fact', 'fact', 'Geographic feature and utility'),

-- ============================================================
-- SAN FRANCISCO
-- ============================================================
('San Francisco', 'Touring City', 1, 'This West Coast city is famous for a distinctive red suspension bridge spanning its iconic bay', 'landmark', 'very_broad', 'Famous bridge reference but indirect'),
('San Francisco', 'Touring City', 1, 'Known for steep hills, cable cars, and fog, this city is home to major tech industry headquarters', 'culture', 'very_broad', 'Could describe multiple Bay Area locations'),
('San Francisco', 'Touring City', 1, 'This city is characterized by Victorian architecture and a countercultural heritage from the 1960s', 'culture', 'very_broad', 'Could describe multiple California cities'),
('San Francisco', 'Touring City', 1, 'Located in Northern California, this city sits on a peninsula surrounded by water on three sides', 'geography', 'very_broad', 'Geographic descriptor applies to several cities'),
('San Francisco', 'Touring City', 1, 'BroadwaySF presents touring Broadway productions in this coastal city', 'theater_scene', 'very_broad', 'Describes touring function without naming'),
('San Francisco', 'Touring City', 1, 'Haight-Ashbury is a famous neighborhood in this city known for its 1960s hippie counterculture history', 'culture', 'very_broad', 'Historic district reference is indirect'),
('San Francisco', 'Touring City', 2, 'The Orpheum Theatre hosts Broadway touring productions and concerts in this city', 'venue', 'broad', 'Specific venue name requires research'),
('San Francisco', 'Touring City', 2, 'The Golden Gate Theatre is located in the Financial District of this West Coast city', 'venue', 'broad', 'Venue and district detail'),
('San Francisco', 'Touring City', 2, 'The Curran Theatre (now Curran) is a historic Broadway touring venue in this city', 'venue', 'broad', 'Specific theater name and function'),
('San Francisco', 'Touring City', 2, 'This city is home to tech companies like Apple, Google, and Facebook nearby in Silicon Valley', 'culture', 'broad', 'Tech industry concentration reference'),
('San Francisco', 'Touring City', 2, 'The Golden Gate Bridge was completed in 1937 and connects this city to Marin County', 'landmark', 'broad', 'Specific bridge opening date'),
('San Francisco', 'Touring City', 2, 'Cable cars have been a distinctive form of public transportation in this city since 1873', 'culture', 'broad', 'Specific transport invention date'),
('San Francisco', 'Touring City', 3, 'The Orpheum Theatre, built in 1911, is a historic venue that hosts Broadway touring productions downtown', 'venue', 'narrowing', 'Specific opening date and location'),
('San Francisco', 'Touring City', 3, 'The Golden Gate Theatre is located on Market Street in the Financial District', 'venue', 'narrowing', 'Specific street and district'),
('San Francisco', 'Touring City', 3, 'The Curran Theatre features an ornate interior and is located near the Financial District in this city', 'venue', 'narrowing', 'Location and architectural detail'),
('San Francisco', 'Touring City', 3, 'This city is surrounded by the Pacific Ocean and the San Francisco Bay', 'geography', 'narrowing', 'Water geography detail'),
('San Francisco', 'Touring City', 3, 'The Golden Gate Bridge is painted a distinctive International Orange color, not traditional bridge red', 'landmark', 'narrowing', 'Specific color detail about famous bridge'),
('San Francisco', 'Touring City', 3, 'This city is home to Alcatraz Island, a former federal penitentiary now operated as a historical tourist', 'landmark', 'narrowing', 'Specific island landmark detail'),
('San Francisco', 'Touring City', 4, 'The Orpheum Theatre features a Baroque-style interior with a large dome and ornate plasterwork throughout', 'venue', 'recognition', 'Specific architectural details'),
('San Francisco', 'Touring City', 4, 'The Golden Gate Theatre is managed by BroadwaySF and presents rotating Broadway touring productions', 'venue', 'recognition', 'Venue management and function'),
('San Francisco', 'Touring City', 4, 'This city''s theater scene is managed primarily through BroadwaySF', 'theater_scene', 'recognition', 'Touring organization detail'),
('San Francisco', 'Touring City', 4, 'The Golden Gate Bridge''s main span stretches 4', 'landmark', 'recognition', 'Specific bridge engineering detail'),
('San Francisco', 'Touring City', 4, 'This city is famous for its fog phenomenon', 'culture', 'recognition', 'Distinctive cultural detail about weather'),
('San Francisco', 'Touring City', 4, 'Haight-Ashbury neighborhood is home to the Haight-Ashbury Free Clinic', 'culture', 'recognition', 'Specific neighborhood history'),
('San Francisco', 'Touring City', 5, 'The Orpheum Theatre and Golden Gate Theatre are major touring venues in this city known for the Golden Gate', 'venue', 'giveaway', 'Landmark-venue combination'),
('San Francisco', 'Touring City', 5, 'This city is famous for its cable cars, steep hills, and the International Orange Golden Gate Bridge', 'landmark', 'giveaway', 'Multiple distinctive features'),
('San Francisco', 'Touring City', 5, 'BroadwaySF presents major touring productions in this Northern California city', 'theater_scene', 'giveaway', 'Touring organization direct identification'),
('San Francisco', 'Touring City', 5, 'This city is the center of the tech industry and home to Silicon Valley nearby', 'culture', 'giveaway', 'Tech hub identification'),
('San Francisco', 'Touring City', 0, 'The Orpheum Theatre''s dome is one of the largest unsupported domes in theater architecture', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('San Francisco', 'Touring City', 0, 'The Golden Gate Bridge''s cable system uses 27,572 individual wires bundled into 4 main suspension cables', 'interesting_fact', 'fact', 'Engineering technical detail'),
('San Francisco', 'Touring City', 0, 'Cable cars operate on a patented system where moving cables beneath the street pull stationary cars along', 'interesting_fact', 'fact', 'Transportation system technical detail'),
('San Francisco', 'Touring City', 0, 'The Haight-Ashbury neighborhood was the epicenter of the 1967 Summer of Love counterculture movement', 'interesting_fact', 'fact', 'Historical cultural significance'),
('San Francisco', 'Touring City', 0, 'This city''s famous fog rolling in from the ocean creates a natural air conditioning system that keeps', 'interesting_fact', 'fact', 'Geographic-climate feature'),

-- ============================================================
-- WASHINGTON, D.C.
-- ============================================================
('Washington, D.C.', 'Touring City', 1, 'This city is the capital of the United States and home to numerous government buildings', 'culture', 'very_broad', 'Capital designation is well-known but basic'),
('Washington, D.C.', 'Touring City', 1, 'Known for monumental architecture and the world''s largest free museum system', 'landmark', 'very_broad', 'Museum reference applies to few cities'),
('Washington, D.C.', 'Touring City', 1, 'The Kennedy Center is a major performing arts venue in this important American city', 'venue', 'very_broad', 'Venue reference without city name'),
('Washington, D.C.', 'Touring City', 1, 'Located on the Potomac River, this city is the political center of the United States', 'geography', 'very_broad', 'Generic capital descriptor'),
('Washington, D.C.', 'Touring City', 1, 'This city is home to the National Theatre, one of the oldest continuously operating theaters in the country', 'venue', 'very_broad', 'Historic theater reference indirect'),
('Washington, D.C.', 'Touring City', 1, 'Cherry blossoms bloom annually around the Tidal Basin in this city, drawing visitors from around the world', 'culture', 'very_broad', 'Famous spring phenomenon but location indirect'),
('Washington, D.C.', 'Touring City', 2, 'The Kennedy Center Opera House and Eisenhower Theater host major Broadway touring productions', 'venue', 'broad', 'Specific venue names'),
('Washington, D.C.', 'Touring City', 2, 'The National Theatre, founded in 1835, is the oldest continuously operating theater in this city', 'venue', 'broad', 'Specific founding date and distinction'),
('Washington, D.C.', 'Touring City', 2, 'The Smithsonian Institution operates 19 museums in this city, all offering free admission', 'landmark', 'broad', 'Museum system detail'),
('Washington, D.C.', 'Touring City', 2, 'The Lincoln Memorial, Washington Monument, and U.S. Capitol are iconic structures in this city', 'landmark', 'broad', 'Multiple famous monuments'),
('Washington, D.C.', 'Touring City', 2, 'This city''s theater district is centered around downtown venues that present Broadway touring shows', 'theater_scene', 'broad', 'Theater district focus'),
('Washington, D.C.', 'Touring City', 2, 'The Potomac River divides this city from Virginia and provides a scenic backdrop to major monuments', 'geography', 'broad', 'Water feature and border detail'),
('Washington, D.C.', 'Touring City', 3, 'The Kennedy Center was opened in 1971 and is named after President John F. Kennedy', 'venue', 'narrowing', 'Specific opening date and naming'),
('Washington, D.C.', 'Touring City', 3, 'The National Theatre is located on Pennsylvania Avenue and has hosted every U.S. president since its founding', 'venue', 'narrowing', 'Specific location and historical claim'),
('Washington, D.C.', 'Touring City', 3, 'The Eisenhower Theater is part of the Kennedy Center and is one of the largest stages in the region', 'venue', 'narrowing', 'Venue within complex detail'),
('Washington, D.C.', 'Touring City', 3, 'This city was designed by Pierre L''Enfant in 1791 with a grid pattern and diagonal avenues radiating', 'landmark', 'narrowing', 'Specific urban planning detail'),
('Washington, D.C.', 'Touring City', 3, 'The Library of Congress, built in 1897, is the largest library in the world by number of items', 'landmark', 'narrowing', 'Specific building date and distinction'),
('Washington, D.C.', 'Touring City', 3, 'This city hosts the National Mall, a two-mile stretch of parkland flanked by museums and monuments', 'landmark', 'narrowing', 'Specific landmark geography'),
('Washington, D.C.', 'Touring City', 4, 'The Kennedy Center features three theaters (Eisenhower, Concert Hall, Terrace)', 'venue', 'recognition', 'Theater count and status detail'),
('Washington, D.C.', 'Touring City', 4, 'The National Theatre has hosted performances by every U.S. president since 1835 and is America''s oldest', 'venue', 'recognition', 'Specific presidential and historic claims'),
('Washington, D.C.', 'Touring City', 4, 'The Lincoln Memorial houses a seated statue of Abraham Lincoln by sculptor Daniel Chester French', 'landmark', 'recognition', 'Specific sculpture detail'),
('Washington, D.C.', 'Touring City', 4, 'The U.S. Capitol building has been the meeting place of the U.S. Congress since 1800', 'landmark', 'recognition', 'Specific date and function'),
('Washington, D.C.', 'Touring City', 4, 'This city is home to the White House, the residence and workplace of the President of the United States since', 'landmark', 'recognition', 'Executive residence fact'),
('Washington, D.C.', 'Touring City', 4, 'The Washington Monument is a 555-foot tall obelisk built between 1848-1884 to honor George Washington', 'landmark', 'recognition', 'Specific height and construction dates'),
('Washington, D.C.', 'Touring City', 5, 'The Kennedy Center Opera House and National Theatre host Broadway touring productions in this capital city', 'venue', 'giveaway', 'Multiple iconic venues'),
('Washington, D.C.', 'Touring City', 5, 'This city is home to the White House, U.S. Capitol, and Lincoln Memorial', 'landmark', 'giveaway', 'Trio of iconic landmarks'),
('Washington, D.C.', 'Touring City', 5, 'The Kennedy Center has hosted major Broadway touring productions since its opening in 1971', 'venue', 'giveaway', 'Specific venue opening date'),
('Washington, D.C.', 'Touring City', 5, 'This city is the political capital of the United States with iconic monuments on the National Mall', 'culture', 'giveaway', 'Political center identification'),
('Washington, D.C.', 'Touring City', 0, 'The Kennedy Center Opera House has a 2,300-seat capacity and features a massive crystal chandelier', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Washington, D.C.', 'Touring City', 0, 'The National Theatre has a floor system with individual elevator platforms to accommodate various stage', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Washington, D.C.', 'Touring City', 0, 'The Washington Monument''s aluminum capstone was installed in 1884 as the tallest point of the structure', 'interesting_fact', 'fact', 'Monument construction detail'),
('Washington, D.C.', 'Touring City', 0, 'The Smithsonian Institution was founded in 1846 with a bequest from British scientist James Smithson', 'interesting_fact', 'fact', 'Museum system founding history'),
('Washington, D.C.', 'Touring City', 0, 'This city has more theaters per capita than any other American city except New York', 'interesting_fact', 'fact', 'Theater density statistic'),

-- ============================================================
-- PHILADELPHIA
-- ============================================================
('Philadelphia', 'Touring City', 1, 'This historic city is home to the Liberty Bell, a symbol of American independence', 'landmark', 'very_broad', 'Famous artifact reference but location indirect'),
('Philadelphia', 'Touring City', 1, 'Known for its iconic cheesesteaks and pretzels, this East Coast city is America''s sixth-largest city', 'culture', 'very_broad', 'Food culture reference is specific but indirect'),
('Philadelphia', 'Touring City', 1, 'The Academy of Music, opened in 1857, is the oldest opera house still in use in the United States', 'venue', 'very_broad', 'Historic theater reference without naming city'),
('Philadelphia', 'Touring City', 1, 'This city is home to Independence Hall and played a crucial role in the American Revolutionary War', 'landmark', 'very_broad', 'Historic site reference applies broadly'),
('Philadelphia', 'Touring City', 1, 'The Kimmel Center for the Performing Arts hosts major touring Broadway productions in this city', 'venue', 'very_broad', 'Venue reference without city name'),
('Philadelphia', 'Touring City', 1, 'Located on the Delaware River, this city was the birthplace of the United States Constitution', 'geography', 'very_broad', 'Historical descriptor applies broadly'),
('Philadelphia', 'Touring City', 2, 'The Academy of Music, built in 1857, is the oldest opera house in the United States still used', 'venue', 'broad', 'Specific designation and date'),
('Philadelphia', 'Touring City', 2, 'The Kimmel Center for the Performing Arts opened in 2001 and is a modern hub for Broadway touring shows', 'venue', 'broad', 'Specific opening date and function'),
('Philadelphia', 'Touring City', 2, 'The Forrest Theatre is a historic Broadway touring venue named after actor Edwin Forrest', 'venue', 'broad', 'Venue naming detail'),
('Philadelphia', 'Touring City', 2, 'Independence Hall is a Georgian-style building where the Declaration of Independence and U.S. Constitution', 'landmark', 'broad', 'Specific architectural style and historical events'),
('Philadelphia', 'Touring City', 2, 'The Liberty Bell is displayed in the Liberty Bell Center, a museum dedicated to its history', 'landmark', 'broad', 'Artifact and museum location'),
('Philadelphia', 'Touring City', 2, 'This city is home to numerous theaters clustered in the Theater District downtown', 'theater_scene', 'broad', 'Theater district concentration'),
('Philadelphia', 'Touring City', 3, 'The Academy of Music, built in 1857, features an ornate interior with a chandelier and gilt boxes', 'venue', 'narrowing', 'Specific architectural feature detail'),
('Philadelphia', 'Touring City', 3, 'The Kimmel Center for the Performing Arts is located on Broad Street downtown and includes multiple', 'venue', 'narrowing', 'Specific street location'),
('Philadelphia', 'Touring City', 3, 'The Forrest Theatre is located on East Camelot Avenue and was named to honor actor Edwin Forrest', 'venue', 'narrowing', 'Specific street location and naming'),
('Philadelphia', 'Touring City', 3, 'Independence Hall sits in the center of the Independence Hall Historic District, a UNESCO World Heritage Site', 'landmark', 'narrowing', 'Specific historic designation'),
('Philadelphia', 'Touring City', 3, 'The Reading Terminal Market, opened in 1893, is a historic public market in this city', 'landmark', 'narrowing', 'Specific landmark opening date'),
('Philadelphia', 'Touring City', 3, 'This city''s Theater District contains more theaters than any other region outside of New York and Broadway', 'theater_scene', 'narrowing', 'Theater concentration claim'),
('Philadelphia', 'Touring City', 4, 'The Academy of Music features a 2,000-seat capacity and has hosted every major American opera and ballet', 'venue', 'recognition', 'Specific capacity and performance history'),
('Philadelphia', 'Touring City', 4, 'The Kimmel Center for the Performing Arts includes the Verizon Hall, a 2,500-seat main theater', 'venue', 'recognition', 'Specific theater names and capacities'),
('Philadelphia', 'Touring City', 4, 'This city''s Theater District includes the Walnut Street Theatre', 'venue', 'recognition', 'Historic theater designation'),
('Philadelphia', 'Touring City', 4, 'The Liberty Bell, cast in 1752 in London', 'landmark', 'recognition', 'Specific casting and historical event'),
('Philadelphia', 'Touring City', 4, 'Benjamin Franklin resided in this city and is celebrated throughout the city''s historic districts', 'culture', 'recognition', 'Historic figure association'),
('Philadelphia', 'Touring City', 4, 'This city hosted the first Continental Congress and the Constitutional Convention', 'history', 'recognition', 'Specific historical events'),
('Philadelphia', 'Touring City', 5, 'The Academy of Music and Kimmel Center are major Broadway touring venues in this historic East Coast city', 'venue', 'giveaway', 'Multiple iconic venue names'),
('Philadelphia', 'Touring City', 5, 'The Liberty Bell, Independence Hall, and Constitution Hall make this city a landmark of American history', 'landmark', 'giveaway', 'Multiple iconic historic sites'),
('Philadelphia', 'Touring City', 5, 'This city is home to the Academy of Music, the oldest opera house in the United States still in use', 'venue', 'giveaway', 'Specific historic venue distinction'),
('Philadelphia', 'Touring City', 5, 'Cheesesteaks and pretzels are iconic foods from this historic East Coast city', 'culture', 'giveaway', 'Distinctive food culture'),
('Philadelphia', 'Touring City', 0, 'The Academy of Music''s original chandelier weighs 5 tons and was fabricated in Europe specifically', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Philadelphia', 'Touring City', 0, 'The Kimmel Center''s Perelman Theater features a retractable orchestra pit that can transform the space', 'interesting_fact', 'fact', 'Theater venue technical feature'),
('Philadelphia', 'Touring City', 0, 'The Walnut Street Theatre, founded in 1809, is the oldest continuously operating theater in the United States', 'interesting_fact', 'fact', 'Historic theater founding date'),
('Philadelphia', 'Touring City', 0, 'The Liberty Bell is 12 feet in circumference and weighs 2,080 pounds; its famous crack appeared in the 1840s', 'interesting_fact', 'fact', 'Artifact specification detail'),
('Philadelphia', 'Touring City', 0, 'The Reading Terminal Market operates as a public market with over 100 vendors selling produce, food', 'interesting_fact', 'fact', 'Market operation detail'),

-- ============================================================
-- DENVER
-- ============================================================
('Denver', 'Touring City', 1, 'Known as the Mile High City, this city sits at an elevation of exactly 5,280 feet above sea level', 'geography', 'very_broad', 'Could describe other mountain cities'),
('Denver', 'Touring City', 1, 'Located in the Rocky Mountains, this city is surrounded by scenic mountain peaks and high-altitude terrain', 'geography', 'very_broad', 'Could describe multiple mountain cities'),
('Denver', 'Touring City', 1, 'This city is home to one of the largest performing arts complexes in the United States', 'venue', 'very_broad', 'Venue reference without naming city'),
('Denver', 'Touring City', 1, 'Famous for its 300 days of annual sunshine, this city has a distinct mountain climate', 'geography', 'very_broad', 'Applies to other high-altitude cities'),
('Denver', 'Touring City', 1, 'The Denver Center for the Performing Arts is one of the largest theater facilities in the nation', 'venue', 'very_broad', 'Facility reference without naming'),
('Denver', 'Touring City', 1, 'Red Rocks Amphitheatre, a famous outdoor concert venue carved from red sandstone, is located near this city', 'landmark', 'very_broad', 'Venue reference without city name'),
('Denver', 'Touring City', 2, 'The Denver Center for the Performing Arts features the Buell Theatre as its main Broadway touring venue', 'venue', 'broad', 'Specific theater name within complex'),
('Denver', 'Touring City', 2, 'This city''s major performing arts complex includes 10 theaters within a four-block downtown area', 'venue', 'broad', 'Theater count and location specificity'),
('Denver', 'Touring City', 2, 'The Mile High City sits at 5,280 feet elevation, causing visitors to experience lower oxygen levels', 'geography', 'broad', 'Elevation detail with effect'),
('Denver', 'Touring City', 2, 'Red Rocks Amphitheatre, located at 6,450 feet elevation, is a national historic landmark', 'landmark', 'broad', 'Specific elevation and designation'),
('Denver', 'Touring City', 2, 'This city is home to Great Divide Brewing Company and numerous craft breweries', 'culture', 'broad', 'Brewing culture reference'),
('Denver', 'Touring City', 2, 'The Tivoli Student Center, built in 1856, is a historic brewery turned student center in this city', 'landmark', 'broad', 'Historic building repurpose detail'),
('Denver', 'Touring City', 3, 'The Denver Center for the Performing Arts was completed in 1979 and is the 10th-largest performing arts', 'venue', 'narrowing', 'Specific opening date and ranking'),
('Denver', 'Touring City', 3, 'The Buell Theatre, part of the Denver Center complex, seats 2', 'venue', 'narrowing', 'Specific theater capacity'),
('Denver', 'Touring City', 3, 'The Denver Center for the Performing Arts includes 10 theaters with a total of 15,000 seats', 'venue', 'narrowing', 'Comprehensive facility detail'),
('Denver', 'Touring City', 3, 'The Rocky Mountains provide a dramatic backdrop to this city and contain numerous hiking trails', 'geography', 'narrowing', 'Mountain geography detail'),
('Denver', 'Touring City', 3, 'This city''s thin air at high altitude affects performance and physical exertion', 'geography', 'narrowing', 'Altitude effect on performance'),
('Denver', 'Touring City', 3, 'Red Rocks Amphitheatre, with naturally formed red sandstone walls, has hosted concerts for over 100 years', 'landmark', 'narrowing', 'Venue age and geology detail'),
('Denver', 'Touring City', 4, 'The Denver Center for the Performing Arts is one of the second-largest performing arts centers in the United', 'venue', 'recognition', 'Specific ranking detail'),
('Denver', 'Touring City', 4, 'The Buell Theatre features a 2,800-seat capacity and is the flagship Broadway touring venue in this city', 'venue', 'recognition', 'Specific capacity and status'),
('Denver', 'Touring City', 4, 'This city is home to the Denver Museum of Art and Denver Zoo, both major cultural attractions', 'landmark', 'recognition', 'Multiple cultural institutions'),
('Denver', 'Touring City', 4, 'The South Platte River runs through downtown, providing scenic parks and recreation opportunities', 'geography', 'recognition', 'Water feature detail'),
('Denver', 'Touring City', 4, 'This city is a major hub for outdoor recreation with access to skiing, hiking', 'culture', 'recognition', 'Outdoor recreation emphasis'),
('Denver', 'Touring City', 4, 'The Gold Rush of 1859 led to the founding of this city as a mining settlement', 'history', 'recognition', 'Historical founding detail'),
('Denver', 'Touring City', 5, 'The Denver Center for the Performing Arts is a massive complex with the Buell Theatre hosting Broadway tours', 'venue', 'giveaway', 'Specific venue identification'),
('Denver', 'Touring City', 5, 'The Mile High City is famous for its 300 days of sunshine and proximity to the Rocky Mountains', 'geography', 'giveaway', 'Multiple distinctive features'),
('Denver', 'Touring City', 5, 'Red Rocks Amphitheatre, a famous natural music venue carved from red sandstone, is near this city', 'landmark', 'giveaway', 'Distinctive landmark identification'),
('Denver', 'Touring City', 5, 'This city sits at exactly 5,280 feet elevation, giving it its famous nickname', 'geography', 'giveaway', 'Specific elevation-nickname connection'),
('Denver', 'Touring City', 0, 'The Denver Center for the Performing Arts features a 110-foot tall glass space frame structure as its main', 'interesting_fact', 'fact', 'Theater complex architectural detail'),
('Denver', 'Touring City', 0, 'The Buell Theatre''s stage can accommodate the largest Broadway productions with over 5', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Denver', 'Touring City', 0, 'Red Rocks Amphitheatre''s natural acoustics are so precise that conversations on stage can be heard clearly', 'interesting_fact', 'fact', 'Venue acoustic property detail'),
('Denver', 'Touring City', 0, 'The thin air at Denver''s high altitude means visitors typically feel effects within hours of arrival', 'interesting_fact', 'fact', 'Geographic-physiological effect'),
('Denver', 'Touring City', 0, 'The Denver Center''s 10-theater complex was designed by renowned architect James Polshek', 'interesting_fact', 'fact', 'Architectural designer credit'),

-- ============================================================
-- SEATTLE
-- ============================================================
('Seattle', 'Touring City', 1, 'Known for rain, coffee culture, and tech companies', 'culture', 'very_broad', 'Could apply to other Pacific NW cities'),
('Seattle', 'Touring City', 1, 'The Space Needle is an iconic landmark in this city, built for the 1962 World''s Fair', 'landmark', 'very_broad', 'Famous landmark reference but indirect'),
('Seattle', 'Touring City', 1, 'Amazon and Microsoft headquarters are located in or near this major tech hub city', 'culture', 'very_broad', 'Tech company location without city name'),
('Seattle', 'Touring City', 1, 'Pike Place Market is a famous public market in this city known for fresh seafood and produce', 'landmark', 'very_broad', 'Market reference without city identification'),
('Seattle', 'Touring City', 1, 'Grunge music movement originated in this Pacific Northwest city in the 1980s-1990s', 'culture', 'very_broad', 'Music genre reference without naming'),
('Seattle', 'Touring City', 1, 'The Paramount Theatre hosts Broadway touring productions in this city', 'venue', 'very_broad', 'Venue reference without city name'),
('Seattle', 'Touring City', 2, 'The Paramount Theatre is a historic venue hosting Broadway touring shows in this city', 'venue', 'broad', 'Specific theater name'),
('Seattle', 'Touring City', 2, 'The 5th Avenue Theatre features a stunning Chinese-inspired interior and hosts Broadway touring productions', 'venue', 'broad', 'Specific architectural style and function'),
('Seattle', 'Touring City', 2, 'Puget Sound surrounds this city on multiple sides, providing scenic water views and recreation', 'geography', 'broad', 'Water feature detail'),
('Seattle', 'Touring City', 2, 'The Space Needle stands 605 feet tall and was built as the centerpiece of the 1962 World''s Fair', 'landmark', 'broad', 'Specific height and historical event'),
('Seattle', 'Touring City', 2, 'Starbucks Coffee was founded in this city at Pike Place Market in 1971', 'culture', 'broad', 'Specific company founding detail'),
('Seattle', 'Touring City', 2, 'This city is home to Mount Rainier, a 14,410-foot active volcano visible on clear days', 'landmark', 'broad', 'Specific geographic feature and elevation'),
('Seattle', 'Touring City', 3, 'The Paramount Theatre, built in 1928, features an ornate Art Deco interior with a stunning chandelier', 'venue', 'narrowing', 'Specific opening date and architectural style'),
('Seattle', 'Touring City', 3, 'The 5th Avenue Theatre''s interior features intricate Chinese art deco design and a fully retractable ornate', 'venue', 'narrowing', 'Specific architectural features'),
('Seattle', 'Touring City', 3, 'Pike Place Market, established in 1907, covers nine acres and includes over 400 vendors', 'landmark', 'narrowing', 'Specific establishment date and vendor count'),
('Seattle', 'Touring City', 3, 'The Space Needle offers a rotating restaurant at 520 feet elevation with 360-degree views', 'landmark', 'narrowing', 'Specific feature detail'),
('Seattle', 'Touring City', 3, 'This city is bordered by Puget Sound to the west and Lake Washington to the east', 'geography', 'narrowing', 'Water geography detail'),
('Seattle', 'Touring City', 3, 'Nirvana, Pearl Jam, and Soundgarden pioneered the grunge movement in this Pacific Northwest city', 'culture', 'narrowing', 'Specific band locations'),
('Seattle', 'Touring City', 4, 'The Paramount Theatre seats 2,300 patrons and features a fully restored ornate interior from its 1928 opening', 'venue', 'recognition', 'Specific capacity and restoration detail'),
('Seattle', 'Touring City', 4, 'The 5th Avenue Theatre''s dome features an intricate hand-painted Chinese art design that can be lowered', 'venue', 'recognition', 'Specific technical feature'),
('Seattle', 'Touring City', 4, 'Pike Place Market''s iconic neon sign has been a landmark since its installation in 1910', 'landmark', 'recognition', 'Specific sign installation detail'),
('Seattle', 'Touring City', 4, 'The Space Needle has 41 elevators and a foundation that goes 30 feet underground to withstand earthquakes', 'landmark', 'recognition', 'Specific engineering detail'),
('Seattle', 'Touring City', 4, 'This city is the birthplace of Starbucks Coffee, now a global company with thousands of locations', 'culture', 'recognition', 'Founding company detail'),
('Seattle', 'Touring City', 4, 'The Chihuly Garden and Glass museum near the Space Needle features glass art installations by Dale Chihuly', 'landmark', 'recognition', 'Specific museum and artist detail'),
('Seattle', 'Touring City', 5, 'The Paramount Theatre and 5th Avenue Theatre host Broadway touring productions in this Pacific Northwest city', 'venue', 'giveaway', 'Multiple iconic theater names'),
('Seattle', 'Touring City', 5, 'The Space Needle, Pike Place Market, and rainy weather are iconic features of this city', 'landmark', 'giveaway', 'Multiple distinctive landmarks'),
('Seattle', 'Touring City', 5, 'This city is famous for coffee culture (Starbucks), grunge music, and tech companies like Amazon and Microsoft', 'culture', 'giveaway', 'Multiple cultural identifiers'),
('Seattle', 'Touring City', 5, 'The Space Needle stands 605 feet tall and was built for the 1962 World''s Fair in this city', 'landmark', 'giveaway', 'Specific landmark identification'),
('Seattle', 'Touring City', 0, 'The Paramount Theatre''s 2,300-seat auditorium features a fully restored 1928 interior with a massive', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Seattle', 'Touring City', 0, 'The 5th Avenue Theatre''s Chinese-inspired dome has a 90-foot span and is hand-painted with detailed artwork', 'interesting_fact', 'fact', 'Theater venue architectural detail'),
('Seattle', 'Touring City', 0, 'Pike Place Market''s fish vendors famously throw fish across counters', 'interesting_fact', 'fact', 'Market cultural practice'),
('Seattle', 'Touring City', 0, 'The Space Needle''s rotating restaurant at 500 feet elevation completes one full rotation every 47 minutes', 'interesting_fact', 'fact', 'Landmark technical detail'),
('Seattle', 'Touring City', 0, 'Seattle receives about 38 inches of rain annually but in the form of frequent drizzle rather than heavy', 'interesting_fact', 'fact', 'Climate characteristic detail'),

-- ============================================================
-- HOUSTON
-- ============================================================
('Houston', 'Touring City', 1, 'Known as Space City, this city is home to NASA''s Mission Control facility', 'culture', 'very_broad', 'Could reference other NASA-related cities'),
('Houston', 'Touring City', 1, 'This major Texas city is the fourth-largest in the United States by population', 'geography', 'very_broad', 'Generic size descriptor'),
('Houston', 'Touring City', 1, 'The oil and petrochemical industry has historically dominated this city''s economy', 'culture', 'very_broad', 'Could apply to other Texas cities'),
('Houston', 'Touring City', 1, 'The Hobby Center for the Performing Arts hosts Broadway touring productions in this city', 'venue', 'very_broad', 'Venue reference without city name'),
('Houston', 'Touring City', 1, 'This city''s Theater District has the second-largest number of theater seats in the United States', 'venue', 'very_broad', 'Theater seat count reference without naming'),
('Houston', 'Touring City', 1, 'Bayou City is a nickname for this coastal Texas city with numerous waterways', 'culture', 'very_broad', 'Nickname reference without direct naming'),
('Houston', 'Touring City', 2, 'The Hobby Center for the Performing Arts, built in 1998, features the Sarofim Hall for Broadway touring shows', 'venue', 'broad', 'Specific venue and opening date'),
('Houston', 'Touring City', 2, 'This city''s Theater District includes five major theatrical venues with nearly 10,000 seats total', 'venue', 'broad', 'Theater count and capacity detail'),
('Houston', 'Touring City', 2, 'NASA''s Johnson Space Center is located in this city and oversees all U.S. manned space missions', 'landmark', 'broad', 'Specific NASA facility detail'),
('Houston', 'Touring City', 2, 'The Alley Theatre, founded in 1947, is a regional theater producing classical and contemporary works', 'venue', 'broad', 'Historic theater founding date'),
('Houston', 'Touring City', 2, 'Buffalo Bayou runs through the heart of downtown this city, providing scenic parks and trails', 'geography', 'broad', 'Water feature detail'),
('Houston', 'Touring City', 2, 'Diverse ethnic communities create a multicultural city that reflects many cuisines and traditions', 'culture', 'broad', 'Cultural diversity reference'),
('Houston', 'Touring City', 3, 'The Hobby Center for the Performing Arts is located in the Theater District downtown and includes the Sarofim', 'venue', 'narrowing', 'Specific venue names and location'),
('Houston', 'Touring City', 3, 'The Sarofim Hall seats approximately 2,400 patrons and hosts Broadway touring productions', 'venue', 'narrowing', 'Specific capacity detail'),
('Houston', 'Touring City', 3, 'NASA''s Johnson Space Center sits south of this city near Galveston Bay', 'landmark', 'narrowing', 'Specific location detail'),
('Houston', 'Touring City', 3, 'The Museum of Fine Arts and Museum of Natural Science are major cultural institutions in this city', 'landmark', 'narrowing', 'Multiple museum detail'),
('Houston', 'Touring City', 3, 'The Astrodome, completed in 1965, was the first domed stadium in the United States', 'landmark', 'narrowing', 'Historic sports venue detail'),
('Houston', 'Touring City', 3, 'This city experiences a hot, humid subtropical climate with temperatures often exceeding 90 degrees in summer', 'geography', 'narrowing', 'Climate characteristic detail'),
('Houston', 'Touring City', 4, 'The Hobby Center for the Performing Arts was built in 1998 and is one of the most technologically advanced', 'venue', 'recognition', 'Specific venue innovation detail'),
('Houston', 'Touring City', 4, 'The Sarofim Hall features a 2,400-seat capacity and state-of-the-art stage equipment for Broadway productions', 'venue', 'recognition', 'Specific technical capability'),
('Houston', 'Touring City', 4, 'The Alley Theatre produces approximately 10 productions annually and is one of the oldest resident theaters', 'venue', 'recognition', 'Theater production scale detail'),
('Houston', 'Touring City', 4, 'This city''s Theater District is the second-largest by number of seats outside of New York City and London', 'venue', 'recognition', 'Theater concentration claim'),
('Houston', 'Touring City', 4, 'NASA''s Mission Control facility in this city communicates with all U.S. spacewalks and space missions', 'landmark', 'recognition', 'Specific NASA operational detail'),
('Houston', 'Touring City', 4, 'The Museum of Fine Arts Houston includes over 70,000 artworks spanning 6,000 years of history', 'landmark', 'recognition', 'Specific collection size'),
('Houston', 'Touring City', 5, 'The Hobby Center for the Performing Arts is a major Broadway touring venue in this Space City', 'venue', 'giveaway', 'Specific venue and city identification'),
('Houston', 'Touring City', 5, 'This city''s Theater District has the second-largest number of theatrical seats in the United States', 'venue', 'giveaway', 'Distinctive seat count claim'),
('Houston', 'Touring City', 5, 'NASA''s Johnson Space Center and the Hobby Center make this city a major touring Broadway destination', 'landmark', 'giveaway', 'Multiple distinctive features'),
('Houston', 'Touring City', 5, 'This Texas city is known as Space City and has the fourth-largest population in the United States', 'culture', 'giveaway', 'Multiple identifying features'),
('Houston', 'Touring City', 0, 'The Hobby Center for the Performing Arts has a 2,400-seat Sarofim Hall with a soaring barrel-vaulted ceiling', 'interesting_fact', 'fact', 'Theater venue architectural detail'),
('Houston', 'Touring City', 0, 'The Hobby Center''s two theaters can be configured in multiple ways including an end-stage or thrust', 'interesting_fact', 'fact', 'Theater venue technical flexibility'),
('Houston', 'Touring City', 0, 'The Astrodome was the world''s first air-conditioned domed stadium and was a marvel of 1960s engineering', 'interesting_fact', 'fact', 'Sports venue architectural innovation'),
('Houston', 'Touring City', 0, 'The Museum of Fine Arts Houston has free admission on Thursday evenings, making it accessible to the community', 'interesting_fact', 'fact', 'Cultural institution accessibility'),
('Houston', 'Touring City', 0, 'Buffalo Bayou was the original reason for Houston''s founding and development as a major port city', 'interesting_fact', 'fact', 'Geographic-historical connection'),

-- ============================================================
-- ATLANTA
-- ============================================================
('Atlanta', 'Touring City', 1, 'Known as the Peach State capital, this city is a major hub of the modern South', 'culture', 'very_broad', 'Could describe other Southern cities'),
('Atlanta', 'Touring City', 1, 'The Fox Theatre, with its Moorish and Egyptian architectural style, is a famous venue in this city', 'venue', 'very_broad', 'Venue reference without city name'),
('Atlanta', 'Touring City', 1, 'Home to Coca-Cola headquarters and CNN, this city is a major media and corporate center', 'culture', 'very_broad', 'Could apply to other major cities'),
('Atlanta', 'Touring City', 1, 'This city was the birthplace of Martin Luther King Jr. and plays an important role in American Civil Rights', 'culture', 'very_broad', 'Historic civil rights reference without naming'),
('Atlanta', 'Touring City', 1, 'The Georgia Aquarium, one of the world''s largest, is located in this city', 'landmark', 'very_broad', 'Major attraction reference without city name'),
('Atlanta', 'Touring City', 1, 'Broadway in Atlanta produces major touring shows in this dynamic Southern city', 'theater_scene', 'very_broad', 'Touring brand reference without naming'),
('Atlanta', 'Touring City', 2, 'The Fox Theatre, built in 1929, is a magnificent example of Moorish architecture with Egyptian influences', 'venue', 'broad', 'Specific architectural style and opening date'),
('Atlanta', 'Touring City', 2, 'The Atlanta Symphony Orchestra performs at Symphony Hall, adjacent to the Woodruff Arts Center', 'venue', 'broad', 'Orchestra and venue location detail'),
('Atlanta', 'Touring City', 2, 'The Georgia Aquarium houses whale sharks, beluga whales, and is one of the world''s largest aquariums', 'landmark', 'broad', 'Specific animal collections'),
('Atlanta', 'Touring City', 2, 'Martin Luther King Jr. was born in this city at Auburn Avenue in the Sweet Auburn district', 'culture', 'broad', 'Historic birthplace detail'),
('Atlanta', 'Touring City', 2, 'This city is home to the World of Coca-Cola museum showcasing the company''s global history', 'landmark', 'broad', 'Specific museum detail'),
('Atlanta', 'Touring City', 2, 'Peach trees originally grew abundantly in Georgia, earning the state the nickname "Peach State"', 'culture', 'broad', 'State nickname origin detail'),
('Atlanta', 'Touring City', 3, 'The Fox Theatre features a spectacular two-story lobby, ornate balconies, and a capacity of 4,678 seats', 'venue', 'narrowing', 'Specific architectural features and capacity'),
('Atlanta', 'Touring City', 3, 'The Fabulous Fox Theatre is located on Peachtree Street in downtown, a major Broadway touring venue', 'venue', 'narrowing', 'Specific location detail'),
('Atlanta', 'Touring City', 3, 'The Woodruff Arts Center, built in 1968, is one of the largest arts centers in the Southeast', 'venue', 'narrowing', 'Specific opening date and regional significance'),
('Atlanta', 'Touring City', 3, 'The Sweet Auburn district, historically known as "the richest Negro street in the South', 'culture', 'narrowing', 'Historic district detail'),
('Atlanta', 'Touring City', 3, 'The Georgia Aquarium, opened in 2005, covers 10 acres and contains 10 million gallons of water', 'landmark', 'narrowing', 'Specific opening date and capacity'),
('Atlanta', 'Touring City', 3, 'The Martin Luther King Jr. National Historical Site includes his birth home and the Ebenezer Baptist Church', 'landmark', 'narrowing', 'Specific site components'),
('Atlanta', 'Touring City', 4, 'The Fox Theatre, called "The Fabulous Fox," has a 4,678-seat capacity and features an ornate Moorish interior', 'venue', 'recognition', 'Specific nickname and capacity'),
('Atlanta', 'Touring City', 4, 'The Fox Theatre''s interior features intricate tilework, a painted ceiling', 'venue', 'recognition', 'Specific architectural details'),
('Atlanta', 'Touring City', 4, 'The Georgia Aquarium opened in 2005 and held the record for the world''s largest aquarium', 'landmark', 'recognition', 'Historic record claim'),
('Atlanta', 'Touring City', 4, 'The Martin Luther King Jr. National Historical Site preserves the locations central to the Civil Rights', 'landmark', 'recognition', 'Historic preservation detail'),
('Atlanta', 'Touring City', 4, 'Coca-Cola was invented in this city in 1886 by pharmacist John Pemberton', 'culture', 'recognition', 'Specific invention detail'),
('Atlanta', 'Touring City', 4, 'CNN (Cable News Network) was founded in this city in 1980 by Ted Turner', 'culture', 'recognition', 'Network founding detail'),
('Atlanta', 'Touring City', 5, 'The Fox Theatre, called "The Fabulous Fox," is a major Broadway touring venue in this Southern city', 'venue', 'giveaway', 'Specific venue nickname'),
('Atlanta', 'Touring City', 5, 'This city is home to the Coca-Cola Company, CNN, and the Georgia Aquarium', 'culture', 'giveaway', 'Multiple corporate and landmark identifiers'),
('Atlanta', 'Touring City', 5, 'The Fox Theatre''s Moorish and Egyptian architecture makes it one of the most distinctive theaters', 'venue', 'giveaway', 'Distinctive architectural style identification'),
('Atlanta', 'Touring City', 5, 'Martin Luther King Jr. was born and preached in this city that played a central role in the Civil Rights', 'culture', 'giveaway', 'Multiple historical identifiers'),
('Atlanta', 'Touring City', 0, 'The Fox Theatre''s ornate chandelier weighs over 1,000 pounds and is hand-painted with intricate designs', 'interesting_fact', 'fact', 'Theater venue technical detail'),
('Atlanta', 'Touring City', 0, 'The Fox Theatre''s ceiling is painted with images of clouds and sky to create an outdoor theater effect', 'interesting_fact', 'fact', 'Theater venue artistic design'),
('Atlanta', 'Touring City', 0, 'The Georgia Aquarium''s whale shark tank holds 6.3 million gallons of water and contains four whale sharks', 'interesting_fact', 'fact', 'Aquarium technical specification'),
('Atlanta', 'Touring City', 0, 'The World of Coca-Cola museum displays the secret formula vault and offers tastings of drinks from around', 'interesting_fact', 'fact', 'Museum experience detail'),
('Atlanta', 'Touring City', 0, 'Peachtree Street in this city is one of the longest streets in the nation', 'interesting_fact', 'fact', 'Geographic feature detail'),

-- ============================================================
-- MINNEAPOLIS
-- ============================================================
('Minneapolis', 'Touring City', 1, 'Known as the City of Lakes, this city is part of the Twin Cities region', 'culture', 'very_broad', 'Could apply to other lake-based cities'),
('Minneapolis', 'Touring City', 1, 'The Orpheum Theatre hosts Broadway touring productions in this Midwest city', 'venue', 'very_broad', 'Venue reference without city name'),
('Minneapolis', 'Touring City', 1, 'Minnesota is famous as the land of 10,000 lakes, and this city is surrounded by many of them', 'geography', 'very_broad', 'State feature reference without city identification'),
('Minneapolis', 'Touring City', 1, 'Prince, a legendary musician, was born and based his career in this city', 'culture', 'very_broad', 'Artist reference without city name'),
('Minneapolis', 'Touring City', 1, 'The Mall of America, one of the largest shopping centers in the world, is located near this city', 'landmark', 'very_broad', 'Landmark reference without city identification'),
('Minneapolis', 'Touring City', 1, 'This city hosts a strong regional theater scene including the famous Guthrie Theater', 'theater_scene', 'very_broad', 'Theater reference without city name'),
('Minneapolis', 'Touring City', 2, 'The Orpheum Theatre, built in 1913, is a historic venue hosting Broadway touring shows', 'venue', 'broad', 'Specific theater opening date'),
('Minneapolis', 'Touring City', 2, 'The Hennepin Theatre Trust manages five theaters in downtown this city for Broadway touring productions', 'venue', 'broad', 'Theater management detail'),
('Minneapolis', 'Touring City', 2, 'The Guthrie Theater, founded in 1963, is a regional theater producing classical and contemporary plays', 'venue', 'broad', 'Historic founding date for regional theater'),
('Minneapolis', 'Touring City', 2, 'Minnesota has more lakes than any other state, with over 10,000 lakes throughout the region', 'geography', 'broad', 'State lake count detail'),
('Minneapolis', 'Touring City', 2, 'Prince''s Paisley Park, his recording studio and home, is located in this city''s suburb', 'culture', 'broad', 'Artist venue and residence detail'),
('Minneapolis', 'Touring City', 2, 'The Walker Art Center is a major contemporary art museum in this city', 'landmark', 'broad', 'Museum reference'),
('Minneapolis', 'Touring City', 3, 'The Orpheum Theatre is located on Hennepin Avenue downtown and seats 2,500 patrons', 'venue', 'narrowing', 'Specific location and capacity'),
('Minneapolis', 'Touring City', 3, 'The Hennepin Theatre Trust manages the Orpheum, State Theatre, Fitzgerald Theatre, and other venues downtown', 'venue', 'narrowing', 'Multiple theater name detail'),
('Minneapolis', 'Touring City', 3, 'The Guthrie Theater, located on the banks of the Mississippi River', 'venue', 'narrowing', 'Geographic location detail'),
('Minneapolis', 'Touring City', 3, 'This city is bordered by the Mississippi River and surrounded by numerous lakes including Lake Calhoun', 'geography', 'narrowing', 'Water feature detail'),
('Minneapolis', 'Touring City', 3, 'The Twin Cities of Minneapolis and Saint Paul sit across the Mississippi River from each other', 'geography', 'narrowing', 'Regional geographic detail'),
('Minneapolis', 'Touring City', 3, 'Prince (Prince Rogers Nelson) was born in this city in 1958 and created his signature sound with Minneapolis', 'culture', 'narrowing', 'Artist biographical detail'),
('Minneapolis', 'Touring City', 4, 'The Orpheum Theatre features a 2,500-seat capacity and ornate Italian Renaissance-style interior', 'venue', 'recognition', 'Specific capacity and architectural style'),
('Minneapolis', 'Touring City', 4, 'The Hennepin Theatre Trust manages five historic theaters including the Orpheum', 'venue', 'recognition', 'Theater management and count detail'),
('Minneapolis', 'Touring City', 4, 'The Guthrie Theater was founded in 1963 by Tyrone Guthrie and is one of the oldest resident theaters', 'venue', 'recognition', 'Founder and historic claim'),
('Minneapolis', 'Touring City', 4, 'The Walker Art Center, founded in 1879, is one of the oldest art museums in the nation', 'landmark', 'recognition', 'Museum founding date'),
('Minneapolis', 'Touring City', 4, 'Prince''s Paisley Park, located in Chanhaska just outside this city', 'culture', 'recognition', 'Artist venue museum conversion'),
('Minneapolis', 'Touring City', 4, 'Minnesota has more than 10,000 lakes, earning it the nickname "Land of 10,000 Lakes"', 'geography', 'recognition', 'State nickname origin detail'),
('Minneapolis', 'Touring City', 5, 'The Orpheum Theatre is a major Broadway touring venue in this City of Lakes', 'venue', 'giveaway', 'Specific theater and city nickname'),
('Minneapolis', 'Touring City', 5, 'This city is the Twin Cities partner with Saint Paul across the Mississippi River', 'geography', 'giveaway', 'Regional identification'),
('Minneapolis', 'Touring City', 5, 'Prince was born and recorded his music in this city that is famous for lakes', 'culture', 'giveaway', 'Multiple cultural identifiers'),
('Minneapolis', 'Touring City', 5, 'The Mall of America and Guthrie Theater are major attractions in the Minneapolis-Saint Paul region', 'landmark', 'giveaway', 'Regional major attractions'),
('Minneapolis', 'Touring City', 0, 'The Orpheum Theatre''s ceiling features hand-painted murals and an ornate plaster dome from its original 1913', 'interesting_fact', 'fact', 'Theater venue artistic detail'),
('Minneapolis', 'Touring City', 0, 'The Guthrie Theater''s iconic building features a cantilevered stage over the Mississippi River', 'interesting_fact', 'fact', 'Theater venue architectural innovation'),
('Minneapolis', 'Touring City', 0, 'Paisley Park''s original 27,000-square-foot complex included recording studios, a concert venue', 'interesting_fact', 'fact', 'Artist venue scale detail'),
('Minneapolis', 'Touring City', 0, 'Minnesota''s many lakes were created by glacial activity during the last ice age', 'interesting_fact', 'fact', 'Geographic formation detail'),
('Minneapolis', 'Touring City', 0, 'The Walker Art Center was founded as a memorial to philanthropist Thomas Walker and his family contributions', 'interesting_fact', 'fact', 'Museum founding purpose'),

-- ============================================================
-- DALLAS
-- ============================================================
('Dallas', 'Touring City', 1, 'This Texas city is known for its iconic skyline with modern glass and steel skyscrapers', 'geography', 'very_broad', 'Could apply to other major cities'),
('Dallas', 'Touring City', 1, 'The Music Hall at Fair Park is a famous venue hosting Broadway touring productions', 'venue', 'very_broad', 'Venue reference without city name'),
('Dallas', 'Touring City', 1, 'Dallas Summer Musicals is one of the oldest touring music theater series in the nation', 'theater_scene', 'very_broad', 'Theater series reference without naming'),
('Dallas', 'Touring City', 1, 'This city is famous as "Big D" and is known for its cowboy heritage and cattle industry history', 'culture', 'very_broad', 'Regional culture reference'),
('Dallas', 'Touring City', 1, 'The Fort Worth area and Dallas form a major metropolitan region in North Texas', 'geography', 'very_broad', 'Regional reference without specific naming'),
('Dallas', 'Touring City', 1, 'This Texas city hosted a historic presidential motorcade in 1963 that changed American history', 'history', 'very_broad', 'Historical event reference without naming'),
('Dallas', 'Touring City', 2, 'The Music Hall at Fair Park, built in 1925, features Art Deco architecture and a 3,420-seat capacity', 'venue', 'broad', 'Specific opening date and architectural style'),
('Dallas', 'Touring City', 2, 'The AT&T Performing Arts Center opened in 2009 and hosts Broadway touring productions', 'venue', 'broad', 'Specific opening date for modern venue'),
('Dallas', 'Touring City', 2, 'The Winspear Opera House is part of the AT&T Performing Arts Center with a 2,200-seat capacity', 'venue', 'broad', 'Specific theater name and capacity'),
('Dallas', 'Touring City', 2, 'Dallas Summer Musicals has been presenting touring shows since 1941', 'theater_scene', 'broad', 'Specific founding date for touring series'),
('Dallas', 'Touring City', 2, 'The Kennedy Memorial in downtown this city commemorates President John F. Kennedy', 'landmark', 'broad', 'Historic memorial detail'),
('Dallas', 'Touring City', 2, 'Reunion Tower, completed in 1978, offers 360-degree views of the city and surrounding region', 'landmark', 'broad', 'Specific landmark opening date'),
('Dallas', 'Touring City', 3, 'The Music Hall at Fair Park is located within Fair Park, an 277-acre expo space hosting annual State Fair', 'venue', 'narrowing', 'Specific location and park size detail'),
('Dallas', 'Touring City', 3, 'The AT&T Performing Arts Center is located in downtown and includes the Winspear Opera House and Dee', 'venue', 'narrowing', 'Specific theater names and location'),
('Dallas', 'Touring City', 3, 'The Winspear Opera House features a dramatic all-glass south wall and a 2,200-seat capacity', 'venue', 'narrowing', 'Specific architectural feature'),
('Dallas', 'Touring City', 3, 'Fair Park was built for the 1936 Texas Centennial Exposition and now hosts the State Fair of Texas annually', 'landmark', 'narrowing', 'Specific historical opening and current use'),
('Dallas', 'Touring City', 3, 'The Sixth Floor Museum at Dealey Plaza documents the JFK assassination and its historical impact', 'landmark', 'narrowing', 'Specific museum location and focus'),
('Dallas', 'Touring City', 3, 'This city is part of the Dallas-Fort Worth Metroplex, one of the largest metropolitan areas in the nation', 'geography', 'narrowing', 'Regional metropolitan designation'),
('Dallas', 'Touring City', 4, 'The Music Hall at Fair Park features an ornate Art Deco facade with intricate tilework and interior details', 'venue', 'recognition', 'Specific architectural detail'),
('Dallas', 'Touring City', 4, 'The AT&T Performing Arts Center''s Winspear Opera House features state-of-the-art acoustics and a dramatic', 'venue', 'recognition', 'Specific technical feature'),
('Dallas', 'Touring City', 4, 'Dallas Summer Musicals is the oldest continuously operating touring music theater series in the United States', 'theater_scene', 'recognition', 'Specific historic claim'),
('Dallas', 'Touring City', 4, 'The Sixth Floor Museum at Dealey Plaza explores the JFK assassination and its impact on American history', 'landmark', 'recognition', 'Museum historical focus'),
('Dallas', 'Touring City', 4, 'Reunion Tower''s rotating restaurant and observation deck provides 360-degree views of downtown', 'landmark', 'recognition', 'Landmark feature detail'),
('Dallas', 'Touring City', 4, 'The Dallas Cowboys have been one of the most successful NFL teams, with multiple Super Bowl victories', 'culture', 'recognition', 'Sports team achievement detail'),
('Dallas', 'Touring City', 5, 'The Music Hall at Fair Park and AT&T Performing Arts Center host Broadway tours in this Texas city', 'venue', 'giveaway', 'Multiple iconic venue names'),
('Dallas', 'Touring City', 5, 'Dallas Summer Musicals and the Winspear Opera House make this a major Broadway touring destination', 'theater_scene', 'giveaway', 'Multiple touring identifiers'),
('Dallas', 'Touring City', 5, 'This "Big D" Texas city is famous for cowboys, the JFK assassination, and the Reunion Tower', 'culture', 'giveaway', 'Multiple cultural identifiers'),
('Dallas', 'Touring City', 5, 'The Music Hall at Fair Park, built in 1925, is a major Broadway touring venue in this city', 'venue', 'giveaway', 'Specific venue identification'),
('Dallas', 'Touring City', 0, 'The Music Hall at Fair Park''s auditorium features a suspended ornamental ceiling with elaborate tilework', 'interesting_fact', 'fact', 'Theater venue artistic detail'),
('Dallas', 'Touring City', 0, 'The AT&T Performing Arts Center''s Winspear Opera House features a 50-degree sloped orchestra pit for optimal', 'interesting_fact', 'fact', 'Theater venue technical feature'),
('Dallas', 'Touring City', 0, 'Fair Park''s Art Deco architecture was designed for the 1936 Texas Centennial and has been preserved', 'interesting_fact', 'fact', 'Historic district designation'),
('Dallas', 'Touring City', 0, 'Reunion Tower stands 560 feet tall and its distinctive ball design makes it one of the most recognizable', 'interesting_fact', 'fact', 'Landmark architectural distinction'),
('Dallas', 'Touring City', 0, 'The State Fair of Texas, held annually since 1886, takes place in Fair Park and draws over 2 million visitors', 'interesting_fact', 'fact', 'Fair history and attendance detail'),

-- ============================================================
-- CLEVELAND
-- ============================================================
('Cleveland', 'Touring City', 1, 'The Rock and Roll Hall of Fame is located in this Great Lakes city', 'landmark', 'very_broad', 'Landmark reference without city name'),
('Cleveland', 'Touring City', 1, 'This city sits on Lake Erie, one of the five Great Lakes', 'geography', 'very_broad', 'Geographic descriptor applies to several cities'),
('Cleveland', 'Touring City', 1, 'Playhouse Square is the second-largest performing arts center in the United States by capacity', 'venue', 'very_broad', 'Venue reference without city name'),
('Cleveland', 'Touring City', 1, 'Known for the Rust Belt, this city has a strong industrial heritage and recent revitalization', 'culture', 'very_broad', 'Regional designation applies to several cities'),
('Cleveland', 'Touring City', 1, 'The Cleveland Cavaliers is an NBA team that won a championship in 2016', 'culture', 'very_broad', 'Sports team reference without city name'),
('Cleveland', 'Touring City', 1, 'This city is home to the Cleveland Orchestra, one of the finest orchestras in the nation', 'culture', 'very_broad', 'Musical ensemble reference without naming'),
('Cleveland', 'Touring City', 2, 'Playhouse Square includes the KeyBank State Theatre, Palace Theatre', 'venue', 'broad', 'Specific venue names'),
('Cleveland', 'Touring City', 2, 'The Rock and Roll Hall of Fame features exhibits on the history of rock and roll music', 'landmark', 'broad', 'Museum detail'),
('Cleveland', 'Touring City', 2, 'This city was a major industrial center for steel production and manufacturing in the 19th and 20th centuries', 'culture', 'broad', 'Industrial history detail'),
('Cleveland', 'Touring City', 2, 'Lake Erie borders this city to the north, providing scenic views and water recreation', 'geography', 'broad', 'Water feature detail'),
('Cleveland', 'Touring City', 2, 'The Cleveland Museum of Art offers free admission and houses over 30,000 artworks', 'landmark', 'broad', 'Museum collection detail'),
('Cleveland', 'Touring City', 2, 'The Terminal Tower, completed in 1930, is an iconic Art Deco skyscraper in this city''s downtown', 'landmark', 'broad', 'Specific building opening date'),
('Cleveland', 'Touring City', 3, 'Playhouse Square was built in the 1920s with nine theaters and remains a thriving entertainment district', 'venue', 'narrowing', 'Theater count and construction era detail'),
('Cleveland', 'Touring City', 3, 'The KeyBank State Theatre is Playhouse Square''s largest venue with a 3,600-seat capacity', 'venue', 'narrowing', 'Specific theater capacity'),
('Cleveland', 'Touring City', 3, 'The Palace Theatre, built in 1922, is the second-largest theater in Playhouse Square with 2,200 seats', 'venue', 'narrowing', 'Specific opening date and capacity'),
('Cleveland', 'Touring City', 3, 'The Rock and Roll Hall of Fame is housed in a distinctive glass pyramid building designed by architect I.M.', 'landmark', 'narrowing', 'Specific architectural design'),
('Cleveland', 'Touring City', 3, 'The Terminal Tower, at 708 feet tall, was briefly the second-tallest building in the United States when', 'landmark', 'narrowing', 'Specific height and historical ranking'),
('Cleveland', 'Touring City', 3, 'This city sits on the southern shore of Lake Erie, providing access to water-based recreation and tourism', 'geography', 'narrowing', 'Specific water geography'),
('Cleveland', 'Touring City', 4, 'Playhouse Square is the second-largest performing arts center in the nation by seating capacity', 'venue', 'recognition', 'Specific seating capacity claim'),
('Cleveland', 'Touring City', 4, 'The KeyBank State Theatre features ornate murals and a 3,600-seat capacity', 'venue', 'recognition', 'Specific capacity and artistic detail'),
('Cleveland', 'Touring City', 4, 'Playhouse Square''s theaters were built between 1921-1925 during a period of cultural prosperity in this city', 'venue', 'recognition', 'Construction period detail'),
('Cleveland', 'Touring City', 4, 'The Rock and Roll Hall of Fame opened in 1995 and includes exhibits on artists from Elvis to recent acts', 'landmark', 'recognition', 'Specific opening date and content range'),
('Cleveland', 'Touring City', 4, 'The Cleveland Orchestra is considered one of the top five symphonies in the United States', 'culture', 'recognition', 'Orchestra ranking detail'),
('Cleveland', 'Touring City', 4, 'This city was a major center of the steel industry and the manufacturing boom of the 20th century', 'history', 'recognition', 'Industrial history claim'),
('Cleveland', 'Touring City', 5, 'Playhouse Square with the KeyBank State Theatre is the second-largest performing arts center in the nation', 'venue', 'giveaway', 'Specific venue-to-ranking identification'),
('Cleveland', 'Touring City', 5, 'The Rock and Roll Hall of Fame and Playhouse Square make this city famous for arts and music', 'landmark', 'giveaway', 'Multiple cultural identifiers'),
('Cleveland', 'Touring City', 5, 'This Great Lakes city is home to the Rock and Roll Hall of Fame and Playhouse Square theaters', 'landmark', 'giveaway', 'Multiple iconic features'),
('Cleveland', 'Touring City', 5, 'Playhouse Square is the second-largest performing arts center in the United States by seating capacity', 'venue', 'giveaway', 'Distinctive seating claim'),
('Cleveland', 'Touring City', 0, 'The KeyBank State Theatre''s ceiling features 27 ornamental domes with intricate painted murals', 'interesting_fact', 'fact', 'Theater venue artistic detail'),
('Cleveland', 'Touring City', 0, 'The Palace Theatre features original ornamental plasterwork and a fully restored 1922 interior', 'interesting_fact', 'fact', 'Theater venue restoration detail'),
('Cleveland', 'Touring City', 0, 'The Rock and Roll Hall of Fame''s pyramid structure was designed by world-renowned architect I.M. Pei', 'interesting_fact', 'fact', 'Landmark architectural credit'),
('Cleveland', 'Touring City', 0, 'The Terminal Tower includes an observation deck at 42 stories up', 'interesting_fact', 'fact', 'Landmark feature detail'),
('Cleveland', 'Touring City', 0, 'Playhouse Square was nearly demolished in the 1970s but was restored through community preservation efforts', 'interesting_fact', 'fact', 'Theater district preservation history'),

-- ============================================================
-- DETROIT
-- ============================================================
('Detroit', 'Touring City', 1, 'Known as the Motor City, this city was the birthplace of the American automobile industry', 'culture', 'very_broad', 'Could apply broadly to automotive history'),
('Detroit', 'Touring City', 1, 'The Fisher Theatre is a major Broadway touring venue in this Michigan city', 'venue', 'very_broad', 'Venue reference without city name'),
('Detroit', 'Touring City', 1, 'Motown Records, the legendary music label, was founded and based in this city', 'culture', 'very_broad', 'Record label reference without city name'),
('Detroit', 'Touring City', 1, 'This city sits on the Detroit River, which separates the United States from Canada', 'geography', 'very_broad', 'Water border reference without city name'),
('Detroit', 'Touring City', 1, 'Broadway in Detroit presents touring productions in this Great Lakes city', 'theater_scene', 'very_broad', 'Touring brand reference without naming'),
('Detroit', 'Touring City', 1, 'The Renaissance Center is a distinctive architectural landmark in downtown this city', 'landmark', 'very_broad', 'Building reference without naming'),
('Detroit', 'Touring City', 2, 'The Fisher Theatre, built in 1928, is a spectacular example of Art Deco architecture with 2,089 seats', 'venue', 'broad', 'Specific opening date, style, and capacity'),
('Detroit', 'Touring City', 2, 'The Fox Theatre is another historic venue hosting Broadway touring productions downtown', 'venue', 'broad', 'Historic theater designation'),
('Detroit', 'Touring City', 2, 'Motown Records recorded legendary artists like Aretha Franklin, The Supremes, and Marvin Gaye', 'culture', 'broad', 'Specific artist recording detail'),
('Detroit', 'Touring City', 2, 'The Motown Museum preserves Hitsville, the original recording studio where Motown records were made', 'landmark', 'broad', 'Historic studio preservation'),
('Detroit', 'Touring City', 2, 'The Henry Ford Museum is one of the largest museums in the United States dedicated to American history', 'landmark', 'broad', 'Museum scale detail'),
('Detroit', 'Touring City', 2, 'This city is home to the Big Three automakers: General Motors, Ford, and Chrysler', 'culture', 'broad', 'Corporate headquarters detail'),
('Detroit', 'Touring City', 3, 'The Fisher Theatre was designed by acclaimed architect Albert Kahn and features an ornate interior', 'venue', 'narrowing', 'Architect attribution and style detail'),
('Detroit', 'Touring City', 3, 'The Fisher Theatre is located on West Grand Boulevard in the cultural center of downtown', 'venue', 'narrowing', 'Specific street location'),
('Detroit', 'Touring City', 3, 'The Fox Theatre, built in 1928, is a companion to the Fisher Theatre in downtown''s entertainment district', 'venue', 'narrowing', 'Historic pairing detail'),
('Detroit', 'Touring City', 3, 'The Motown Museum is located in the original Hitsville studio on West Grand Boulevard', 'landmark', 'narrowing', 'Historic location detail'),
('Detroit', 'Touring City', 3, 'The Henry Ford Museum includes iconic vehicles like Henry Ford''s Model T and historic aircraft', 'landmark', 'narrowing', 'Museum collection highlights'),
('Detroit', 'Touring City', 3, 'This city was a center of labor unionism and the site of historic automobile manufacturing plants', 'history', 'narrowing', 'Labor and manufacturing history'),
('Detroit', 'Touring City', 4, 'The Fisher Theatre''s interior features marble, ornate plasterwork, and a gold-leaf ceiling with murals', 'venue', 'recognition', 'Specific architectural detail'),
('Detroit', 'Touring City', 4, 'The Fisher Theatre has a 2,089-seat capacity and is one of the finest theaters in the United States', 'venue', 'recognition', 'Specific capacity and quality claim'),
('Detroit', 'Touring City', 4, 'The Motown Museum preserves Hitsville, the studio where over 110 hit records were recorded', 'landmark', 'recognition', 'Historic recording achievement'),
('Detroit', 'Touring City', 4, 'This city was the fourth-largest city in the United States by population during the mid-20th century', 'geography', 'recognition', 'Historical population claim'),
('Detroit', 'Touring City', 4, 'The Renaissance Center is a 73-story group of towers at the riverfront and is a distinctive downtown landmark', 'landmark', 'recognition', 'Specific architectural detail'),
('Detroit', 'Touring City', 4, 'The Henry Ford Museum includes over 28 million artifacts spanning American history and innovation', 'landmark', 'recognition', 'Museum collection size'),
('Detroit', 'Touring City', 5, 'The Fisher Theatre is a major Broadway touring venue in this Motor City', 'venue', 'giveaway', 'Specific venue-to-city identification'),
('Detroit', 'Touring City', 5, 'This city is famous for the automobile industry, Motown Records, and the Fisher Theatre', 'culture', 'giveaway', 'Multiple cultural identifiers'),
('Detroit', 'Touring City', 5, 'The Fisher Theatre and Fox Theatre host Broadway tours in this Great Lakes city', 'venue', 'giveaway', 'Multiple theater identification'),
('Detroit', 'Touring City', 5, 'Motown Records was founded and based in this Motor City, recording legendary artists', 'culture', 'giveaway', 'Record label city identification'),
('Detroit', 'Touring City', 0, 'The Fisher Theatre''s interior features imported Italian marble, ornate plasterwork', 'interesting_fact', 'fact', 'Theater venue artistic detail'),
('Detroit', 'Touring City', 0, 'The Fisher Theatre was designed by Albert Kahn, who also designed the Ford Motor Company facilities', 'interesting_fact', 'fact', 'Architect legacy connection'),
('Detroit', 'Touring City', 0, 'The Motown Museum''s Hitsville studio records featured a unique bass-heavy "Motown sound"', 'interesting_fact', 'fact', 'Recording technique detail'),
('Detroit', 'Touring City', 0, 'The Henry Ford Museum''s Village of American Craftsmanship recreates historic American buildings and crafts', 'interesting_fact', 'fact', 'Museum historical recreation'),
('Detroit', 'Touring City', 0, 'The Renaissance Center on the Detroit River is connected to the city below by a system of underground tunnels', 'interesting_fact', 'fact', 'Infrastructure feature detail'),

-- ============================================================
-- MIAMI
-- ============================================================
('Miami', 'Touring City', 1, 'This city is famous for its Art Deco architecture, beaches, and warm tropical climate', 'culture', 'very_broad', 'Could apply to other Florida cities'),
('Miami', 'Touring City', 1, 'The Adrienne Arsht Center for the Performing Arts hosts Broadway touring productions', 'venue', 'very_broad', 'Venue reference without city name'),
('Miami', 'Touring City', 1, 'This city is a major cruise ship port with colorful Caribbean culture and cuisine', 'culture', 'very_broad', 'Could describe other Caribbean gateway cities'),
('Miami', 'Touring City', 1, 'South Beach is a famous neighborhood known for nightlife, restaurants, and sandy beaches', 'culture', 'very_broad', 'Neighborhood reference without city name'),
('Miami', 'Touring City', 1, 'Broadway in Miami presents touring shows in this tropical city', 'theater_scene', 'very_broad', 'Touring brand reference without naming'),
('Miami', 'Touring City', 1, 'This city has a large Cuban and Latin American population, creating a vibrant multicultural community', 'culture', 'very_broad', 'Cultural diversity reference without naming'),
('Miami', 'Touring City', 2, 'The Adrienne Arsht Center for the Performing Arts opened in 2006 and features the Ziff Ballet Opera House', 'venue', 'broad', 'Specific opening date and theater name'),
('Miami', 'Touring City', 2, 'The Ziff Ballet Opera House seats 2,400 patrons and hosts Broadway touring productions and ballet', 'venue', 'broad', 'Specific capacity and programming'),
('Miami', 'Touring City', 2, 'The Art Deco Historic District preserves over 800 buildings from the 1923-1943 period', 'landmark', 'broad', 'Historic district size detail'),
('Miami', 'Touring City', 2, 'Vizcaya Museum and Gardens is a historic Italian Renaissance-style mansion overlooking Biscayne Bay', 'landmark', 'broad', 'Historic property detail'),
('Miami', 'Touring City', 2, 'This city is a gateway to the Caribbean and Central America, with major cruise ship ports', 'geography', 'broad', 'Geographic hub detail'),
('Miami', 'Touring City', 2, 'Little Havana is a historic neighborhood in this city with Cuban culture, restaurants, and shops', 'landmark', 'broad', 'Neighborhood cultural detail'),
('Miami', 'Touring City', 3, 'The Adrienne Arsht Center is located in downtown and is one of the largest performing arts centers', 'venue', 'narrowing', 'Location and regional significance'),
('Miami', 'Touring City', 3, 'The Ziff Ballet Opera House features 2,400 seats and state-of-the-art theatrical technology', 'venue', 'narrowing', 'Specific capacity and technical features'),
('Miami', 'Touring City', 3, 'The Art Deco Historic District extends from 5th to 23rd Streets along the oceanfront', 'landmark', 'narrowing', 'Specific geographic boundary'),
('Miami', 'Touring City', 3, 'Biscayne Bay separates this city from the barrier islands that include Miami Beach and South Beach', 'geography', 'narrowing', 'Water geography detail'),
('Miami', 'Touring City', 3, 'The Everglades, a vast wetland ecosystem, is located just west of this city', 'geography', 'narrowing', 'Geographic proximity detail'),
('Miami', 'Touring City', 3, 'This city experiences a tropical climate with warm temperatures year-round and a hurricane season from June', 'geography', 'narrowing', 'Climate characteristic detail'),
('Miami', 'Touring City', 4, 'The Adrienne Arsht Center''s main theater features cutting-edge stage technology and a 2,400-seat capacity', 'venue', 'recognition', 'Specific technical capability detail'),
('Miami', 'Touring City', 4, 'The Art Deco Historic District is the largest collection of Art Deco architecture in the United States', 'landmark', 'recognition', 'Distinctive architectural claim'),
('Miami', 'Touring City', 4, 'Vizcaya Museum and Gardens, built in 1916, is a 66-room Italian Renaissance-style mansion', 'landmark', 'recognition', 'Specific construction date and room count'),
('Miami', 'Touring City', 4, 'This city is the major hub for cruise ships traveling to the Caribbean', 'geography', 'recognition', 'Port activity detail'),
('Miami', 'Touring City', 4, 'The Wynwood Walls are a famous street art district with murals and graffiti from international artists', 'landmark', 'recognition', 'Contemporary art district detail'),
('Miami', 'Touring City', 4, 'This city hosted the Art Basel Miami Beach art fair, one of the most prestigious art fairs in the world', 'culture', 'recognition', 'Major art event detail'),
('Miami', 'Touring City', 5, 'The Adrienne Arsht Center with the Ziff Ballet Opera House hosts Broadway tours in this tropical city', 'venue', 'giveaway', 'Specific venue identification'),
('Miami', 'Touring City', 5, 'This city is famous for Art Deco architecture, South Beach, and a large Cuban population', 'culture', 'giveaway', 'Multiple cultural identifiers'),
('Miami', 'Touring City', 5, 'The Art Deco Historic District and Adrienne Arsht Center make this city a major cultural destination', 'landmark', 'giveaway', 'Multiple iconic features'),
('Miami', 'Touring City', 5, 'This city on Biscayne Bay is a cruise ship hub and the gateway to the Caribbean', 'geography', 'giveaway', 'Geographic gateway identification'),
('Miami', 'Touring City', 0, 'The Adrienne Arsht Center''s Ziff Ballet Opera House features 2', 'interesting_fact', 'fact', 'Theater venue technical feature'),
('Miami', 'Touring City', 0, 'The Adrienne Arsht Center includes a black box theater and multiple smaller performance spaces alongside', 'interesting_fact', 'fact', 'Theater complex composition detail'),
('Miami', 'Touring City', 0, 'The Art Deco Historic District''s buildings feature distinctive pastel colors, geometric patterns', 'interesting_fact', 'fact', 'Architectural style detail'),
('Miami', 'Touring City', 0, 'Vizcaya Museum''s original construction used architectural elements imported from Europe and famous', 'interesting_fact', 'fact', 'Historic mansion construction detail'),
('Miami', 'Touring City', 0, 'Miami''s tropical location near the equator results in consistent warm temperatures and quick afternoon', 'interesting_fact', 'fact', 'Climate characteristic detail');
