-- SPIKE Clue Bank — Broadway Play
-- 15 subjects x ~33 clues each

INSERT INTO clue_bank (show_name, category, level, clue_text, clue_type, specificity, notes) VALUES

-- ============================================================
-- DEATH OF A SALESMAN
-- ============================================================
('Death of a Salesman', 'Broadway Play', 1, 'A tragic drama about an American working man and his family', 'theme', 'very_broad', 'Could describe many plays; establishes American family drama context'),
('Death of a Salesman', 'Broadway Play', 1, 'Play featuring a middle-aged protagonist struggling with economic pressure', 'theme', 'very_broad', 'Applies to many 20th century plays; very general'),
('Death of a Salesman', 'Broadway Play', 1, 'Drama set in Brooklyn with themes of failed dreams', 'setting', 'very_broad', 'Brooklyn was setting for many dramas; dreams theme is universal'),
('Death of a Salesman', 'Broadway Play', 1, 'Play about a man and his two adult sons', 'character', 'very_broad', 'Father-son relationships appear in many plays'),
('Death of a Salesman', 'Broadway Play', 1, 'American play dealing with home life and work life conflicts', 'theme', 'very_broad', 'Common theme in mid-20th century drama'),
('Death of a Salesman', 'Broadway Play', 1, 'Drama featuring flashbacks and memory sequences', 'structure', 'very_broad', 'Many plays use non-linear storytelling'),
('Death of a Salesman', 'Broadway Play', 2, 'Arthur Miller play from the 1940s about commercial failure', 'playwright', 'broad', 'Miller wrote many plays; 1940s is specific but not identifying'),
('Death of a Salesman', 'Broadway Play', 2, 'Play where the protagonist travels for work and struggles with his career', 'plot', 'broad', 'Work-related struggle is common; traveling salesman adds specificity'),
('Death of a Salesman', 'Broadway Play', 2, 'Winner of the Pulitzer Prize in 1949', 'production', 'broad', 'Multiple plays won Pulitzer; year narrows it down some'),
('Death of a Salesman', 'Broadway Play', 2, 'Directed by Elia Kazan in its original Broadway run', 'production', 'broad', 'Kazan directed several major plays'),
('Death of a Salesman', 'Broadway Play', 2, 'Features an innovative set design with transparent walls by Jo Mielziner', 'production', 'broad', 'Mielziner was renowned for many Broadway designs'),
('Death of a Salesman', 'Broadway Play', 2, 'Play in which two brothers compete for their father''s approval', 'plot', 'broad', 'Family competition theme appears in many dramas'),
('Death of a Salesman', 'Broadway Play', 3, 'The protagonist is named Willy', 'character', 'narrowing', 'Willy is an uncommon first name for a main character; narrows significantly'),
('Death of a Salesman', 'Broadway Play', 3, 'Features the character Biff, Willy''s older son', 'character', 'narrowing', 'Character name is distinctive'),
('Death of a Salesman', 'Broadway Play', 3, 'Linda is the long-suffering wife of the protagonist', 'character', 'narrowing', 'Character name + role narrows it down'),
('Death of a Salesman', 'Broadway Play', 3, 'The play opens with the protagonist returning home from a sales trip', 'plot', 'narrowing', 'Specific plot opening'),
('Death of a Salesman', 'Broadway Play', 3, 'Biff once stole a fountain pen while working for his boss', 'plot', 'narrowing', 'Specific plot detail from early scenes'),
('Death of a Salesman', 'Broadway Play', 3, 'The play ends with a scene at a grave', 'plot', 'narrowing', 'Specific plot ending structure'),
('Death of a Salesman', 'Broadway Play', 4, 'Philip Seymour Hoffman starred in a major 2012 revival on Broadway', 'production', 'recognition', 'Specific actor and year narrows significantly'),
('Death of a Salesman', 'Broadway Play', 4, 'Lee J. Cobb originated the role of the protagonist in 1949', 'production', 'recognition', 'Specific actor in original production'),
('Death of a Salesman', 'Broadway Play', 4, 'The protagonist declares, "I am not a dime a dozen!"', 'quote', 'recognition', 'Famous line from the play'),
('Death of a Salesman', 'Broadway Play', 4, 'The wife''s line "Attention, attention must finally be paid" is a key moment', 'quote', 'recognition', 'Iconic Linda speech about her husband'),
('Death of a Salesman', 'Broadway Play', 4, 'Happy is the name of the younger son', 'character', 'recognition', 'Specific character name'),
('Death of a Salesman', 'Broadway Play', 4, 'The play premiered at the Morosco Theatre in 1949', 'production', 'recognition', 'Specific theatre and date'),
('Death of a Salesman', 'Broadway Play', 5, '"I built my life on the road, and there''s nothing left but waiting for a call."', 'quote', 'giveaway', 'Directly evokes the salesman''s life'),
('Death of a Salesman', 'Broadway Play', 5, 'Willy Loman is driven to suicide at the climax', 'plot', 'giveaway', 'The ending is unmistakable'),
('Death of a Salesman', 'Broadway Play', 5, 'The play is explicitly titled after the main character''s profession', 'iconic_element', 'giveaway', 'Title directly names the answer'),
('Death of a Salesman', 'Broadway Play', 5, 'A woman named Charley and his son Bernard appear as neighbors', 'character', 'giveaway', 'Specific supporting characters'),
('Death of a Salesman', 'Broadway Play', 0, 'The set design featured a house that was partially transparent, allowing audiences to see inside and outside simultaneously—revolutionary for 1949', 'production', 'fact', 'Jo Mielziner''s groundbreaking design; technical innovation'),
('Death of a Salesman', 'Broadway Play', 0, 'Arthur Miller wrote the play partly in response to his own family''s economic struggles during the Great Depression', 'development', 'fact', 'Autobiographical context'),
('Death of a Salesman', 'Broadway Play', 0, 'The play won both the Tony Award and Pulitzer Prize in 1949, making it a landmark American play', 'production', 'fact', 'Major awards validation'),
('Death of a Salesman', 'Broadway Play', 0, 'The original production ran for 742 performances, making it one of the longest-running plays of its era', 'production', 'fact', 'Commercial and critical success; 742 is specific'),
('Death of a Salesman', 'Broadway Play', 0, 'The play explores the concept of the American Dream and its failure—a central theme in post-WWII American drama', 'theme', 'fact', 'Thematic importance'),
('Death of a Salesman', 'Broadway Play', 0, 'Elmer Rice and other notable playwrights praised the play upon its opening, establishing it immediately as a modern classic', 'production', 'fact', 'Critical reception'),
('Death of a Salesman', 'Broadway Play', 0, 'The play was adapted into a film in 1951 and again in 1985, both remaining critically acclaimed', 'development', 'fact', 'Cultural adaptation legacy'),

-- ============================================================
-- A STREETCAR NAMED DESIRE
-- ============================================================
('A Streetcar Named Desire', 'Broadway Play', 1, 'A play about a woman arriving to stay with her sister in the South', 'plot', 'very_broad', 'Southern family reunion stories are common'),
('A Streetcar Named Desire', 'Broadway Play', 1, 'Drama featuring intense marital conflict and masculine aggression', 'theme', 'very_broad', 'Marital drama appears in many plays'),
('A Streetcar Named Desire', 'Broadway Play', 1, 'Play set in a crowded, intimate apartment in a major American city', 'setting', 'very_broad', 'Urban apartment settings are common'),
('A Streetcar Named Desire', 'Broadway Play', 1, 'Drama exploring tension between refinement and raw desire', 'theme', 'very_broad', 'Class and sensuality themes in many works'),
('A Streetcar Named Desire', 'Broadway Play', 1, 'Play featuring a woman struggling with her past and mental health', 'character', 'very_broad', 'Troubled female protagonist in many dramas'),
('A Streetcar Named Desire', 'Broadway Play', 1, 'American play with Southern Gothic elements and dark atmosphere', 'tone', 'very_broad', 'Southern Gothic applies to many plays'),
('A Streetcar Named Desire', 'Broadway Play', 2, 'Tennessee Williams play from the late 1940s', 'playwright', 'broad', 'Williams wrote many plays; 1940s is moderately specific'),
('A Streetcar Named Desire', 'Broadway Play', 2, 'Set in New Orleans during a hot summer', 'setting', 'broad', 'New Orleans setting is distinctive'),
('A Streetcar Named Desire', 'Broadway Play', 2, 'Won the Pulitzer Prize and opened at the Ethel Barrymore Theatre', 'production', 'broad', 'Pulitzer year (1948) and theatre narrow it down'),
('A Streetcar Named Desire', 'Broadway Play', 2, 'Directed by Elia Kazan and featured Marlon Brando in a leading role', 'production', 'broad', 'Kazan and Brando connection is specific'),
('A Streetcar Named Desire', 'Broadway Play', 2, 'The play begins with the arrival of a woman named Blanche', 'plot', 'broad', 'Character arrival plot device is somewhat specific'),
('A Streetcar Named Desire', 'Broadway Play', 2, 'Features a famous scene where the male lead yells a woman''s name repeatedly', 'iconic_element', 'broad', 'The "STELLA!" scene is well-known'),
('A Streetcar Named Desire', 'Broadway Play', 3, 'Blanche DuBois is the protagonist', 'character', 'narrowing', 'Name is distinctive'),
('A Streetcar Named Desire', 'Broadway Play', 3, 'Stanley Kowalski is the aggressive male lead', 'character', 'narrowing', 'Distinctive character name'),
('A Streetcar Named Desire', 'Broadway Play', 3, 'Stella is Stanley''s wife and Blanche''s sister', 'character', 'narrowing', 'Specific character relationship'),
('A Streetcar Named Desire', 'Broadway Play', 3, 'A character named Mitch courts Blanche throughout the play', 'character', 'narrowing', 'Specific character and relationship'),
('A Streetcar Named Desire', 'Broadway Play', 3, 'The play takes place over several days in a cramped New Orleans apartment', 'setting', 'narrowing', 'Specific time period and location'),
('A Streetcar Named Desire', 'Broadway Play', 3, 'Blanche comes from a plantation called Belle Reve', 'plot', 'narrowing', 'Specific location detail'),
('A Streetcar Named Desire', 'Broadway Play', 4, 'Jessica Tandy originated the role of Blanche in the 1947 Broadway production', 'production', 'recognition', 'Specific actress and date'),
('A Streetcar Named Desire', 'Broadway Play', 4, 'Marlon Brando played Stanley and became a major star partly due to this role', 'production', 'recognition', 'Actor and role fame'),
('A Streetcar Named Desire', 'Broadway Play', 4, 'The famous line "STELLA!" is shouted by Stanley from the street', 'quote', 'recognition', 'Iconic line from the play'),
('A Streetcar Named Desire', 'Broadway Play', 4, 'Blanche says, "I have always depended on the kindness of strangers"', 'quote', 'recognition', 'Famous closing line'),
('A Streetcar Named Desire', 'Broadway Play', 4, 'The play culminates with Blanche being taken away to a mental institution', 'plot', 'recognition', 'Specific ending detail'),
('A Streetcar Named Desire', 'Broadway Play', 4, 'A poker game scene is a pivotal moment in the middle of the play', 'iconic_element', 'recognition', 'Famous scene structure'),
('A Streetcar Named Desire', 'Broadway Play', 5, 'Stanley rapes Blanche in Act III', 'plot', 'giveaway', 'Central turning point unmistakable'),
('A Streetcar Named Desire', 'Broadway Play', 5, 'Blanche''s fantasy boyfriend Shep Huntleigh never appears on stage', 'plot', 'giveaway', 'Reveals delusional state'),
('A Streetcar Named Desire', 'Broadway Play', 5, 'The play ends with the line "Whoever you are, I have always depended on the kindness of strangers"', 'quote', 'giveaway', 'Unmistakable closing'),
('A Streetcar Named Desire', 'Broadway Play', 5, 'The poker scene ends with violence and Stella fleeing with Stanley', 'plot', 'giveaway', 'Key plot progression'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Tennessee Williams wrote the play after visiting New Orleans and staying in a cramped apartment himself', 'development', 'fact', 'Autobiographical inspiration'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The play was adapted into a 1951 film directed by Elia Kazan, with Brando, Tandy, and Vivien Leigh, which became one of cinema''s most acclaimed films', 'development', 'fact', 'Major film adaptation'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The original production featured innovative sound design, including the realistic ambient noise of a New Orleans streetcar', 'production', 'fact', 'Technical sound design element'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The play was one of the first Broadway productions to openly address sexual violence and mental illness as central themes', 'theme', 'fact', 'Cultural significance'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Marlon Brando''s method acting performance set new standards for theatrical intensity and realism in American drama', 'production', 'fact', 'Performance innovation'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'The play remained on the Broadway stage for 855 performances, making it a massive commercial and critical success', 'production', 'fact', 'Specific run length: 855'),
('A Streetcar Named Desire', 'Broadway Play', 0, 'Blanche''s lines often reference her time as a schoolteacher and her romantic past in the small town of Laurel, Mississippi', 'character', 'fact', 'Biographical backstory details'),

-- ============================================================
-- A RAISIN IN THE SUN
-- ============================================================
('A Raisin in the Sun', 'Broadway Play', 1, 'Drama about an African American family living in Chicago', 'setting', 'very_broad', 'Family dramas set in major cities are common'),
('A Raisin in the Sun', 'Broadway Play', 1, 'Play exploring family conflict over money and opportunity', 'theme', 'very_broad', 'Economic family conflict in many dramas'),
('A Raisin in the Sun', 'Broadway Play', 1, 'Drama featuring a mother as a moral center of the family', 'character', 'very_broad', 'Matriarchal family structures in many plays'),
('A Raisin in the Sun', 'Broadway Play', 1, 'Play dealing with housing discrimination and neighborhood integration', 'theme', 'very_broad', 'Civil rights themes in many contemporary plays'),
('A Raisin in the Sun', 'Broadway Play', 1, 'Drama set in a crowded apartment with multiple generations', 'setting', 'very_broad', 'Multi-generational apartment settings are common'),
('A Raisin in the Sun', 'Broadway Play', 1, 'American play about dreams deferred and identity struggles', 'theme', 'very_broad', 'Dream and identity themes universal in drama'),
('A Raisin in the Sun', 'Broadway Play', 2, 'Written by a woman playwright and was a landmark for diversity on Broadway', 'production', 'broad', 'Woman playwright context is notable'),
('A Raisin in the Sun', 'Broadway Play', 2, 'Opened at the Ethel Barrymore Theatre in 1959', 'production', 'broad', 'Theatre and year are specific'),
('A Raisin in the Sun', 'Broadway Play', 2, 'Sidney Poitier played Walter Lee, the frustrated son', 'production', 'broad', 'Poitier connection is well-known'),
('A Raisin in the Sun', 'Broadway Play', 2, 'The title references a line from a Langston Hughes poem', 'development', 'broad', 'Literary connection is identifying'),
('A Raisin in the Sun', 'Broadway Play', 2, 'The Younger family receives an insurance check and must decide how to use it', 'plot', 'broad', 'Inheritance-based conflict is specific'),
('A Raisin in the Sun', 'Broadway Play', 2, 'The play was adapted from a novel by the same name', 'development', 'broad', 'Original play not adapted from novel'),
('A Raisin in the Sun', 'Broadway Play', 3, 'Walter Lee Younger is the dreaming, ambitious son', 'character', 'narrowing', 'Character name is distinctive'),
('A Raisin in the Sun', 'Broadway Play', 3, 'Lena Younger is the matriarch and moral center', 'character', 'narrowing', 'Character name and role'),
('A Raisin in the Sun', 'Broadway Play', 3, 'Beneatha is Walter''s sister who dreams of becoming a doctor', 'character', 'narrowing', 'Character name and aspiration'),
('A Raisin in the Sun', 'Broadway Play', 3, 'Travis is the young son of Walter and Ruth', 'character', 'narrowing', 'Specific character in family tree'),
('A Raisin in the Sun', 'Broadway Play', 3, 'The family plans to move to Clybourne Park, a white neighborhood', 'plot', 'narrowing', 'Specific neighborhood and integration theme'),
('A Raisin in the Sun', 'Broadway Play', 3, 'George Murchison is a wealthy suitor interested in Beneatha', 'character', 'narrowing', 'Specific character relationship'),
('A Raisin in the Sun', 'Broadway Play', 4, 'Lorraine Hansberry wrote the play when she was 29 years old', 'playwright', 'recognition', 'Playwright age is distinctive'),
('A Raisin in the Sun', 'Broadway Play', 4, 'The play was the first Broadway production by a Black woman playwright', 'production', 'recognition', 'Historical landmark detail'),
('A Raisin in the Sun', 'Broadway Play', 4, 'A 2014 revival featured Denzel Washington as Walter Lee and Viola Davis as Ruth', 'production', 'recognition', 'Specific revival cast'),
('A Raisin in the Sun', 'Broadway Play', 4, 'Lena receives a check for $10,000 from her late husband''s life insurance', 'plot', 'recognition', 'Specific dollar amount'),
('A Raisin in the Sun', 'Broadway Play', 4, 'Walter loses the family''s money in a bad investment scheme', 'plot', 'recognition', 'Key plot turning point'),
('A Raisin in the Sun', 'Broadway Play', 4, 'The line "What is it you want to be?" recurs throughout the play', 'quote', 'recognition', 'Thematic line'),
('A Raisin in the Sun', 'Broadway Play', 5, 'Walter attempts suicide after losing the family''s money but is prevented by Travis', 'plot', 'giveaway', 'Crucial redemptive moment'),
('A Raisin in the Sun', 'Broadway Play', 5, 'Walter ultimately turns down a buyout offer from the Clybourne Park neighborhood association', 'plot', 'giveaway', 'Character and thematic resolution'),
('A Raisin in the Sun', 'Broadway Play', 5, 'The family moves into Clybourne Park despite the community''s racism', 'plot', 'giveaway', 'Ending statement about dignity'),
('A Raisin in the Sun', 'Broadway Play', 5, 'Beneatha says she is studying to become a doctor, rejecting traditional gender expectations', 'character', 'giveaway', 'Feminist character note'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The play premiered at the Barrymore Theatre and ran for 530 performances, a remarkable achievement for a play by a Black woman in 1959', 'production', 'fact', 'Specific run length: 530'),
('A Raisin in the Sun', 'Broadway Play', 0, 'Lorraine Hansberry died of cancer in 1965 at age 34, just six years after her Broadway triumph', 'playwright', 'fact', 'Biographical tragedy'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The play won the New York Drama Critics'' Circle Award and brought Hansberry immediate national acclaim', 'production', 'fact', 'Critical recognition'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The title comes from Langston Hughes''s 1951 poem "Harlem," which asks "What happens to a dream deferred?"', 'development', 'fact', 'Literary source detail'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The play addresses redlining, restrictive covenants, and housing discrimination—real policies affecting Black Americans in 1950s Chicago', 'theme', 'fact', 'Historical context and accuracy'),
('A Raisin in the Sun', 'Broadway Play', 0, 'The 1961 film adaptation, also directed by Daniel Petrie and starring Sidney Poitier, was filmed on location in Chicago and expanded the play''s scope', 'development', 'fact', 'Film adaptation context'),

-- ============================================================
-- THE CRUCIBLE
-- ============================================================
('The Crucible', 'Broadway Play', 1, 'Drama set during a historical witch trial', 'setting', 'very_broad', 'Witch trial plays and historical drama exist'),
('The Crucible', 'Broadway Play', 1, 'Play exploring themes of hysteria and false accusations', 'theme', 'very_broad', 'Hysteria and accusation themes in many plays'),
('The Crucible', 'Broadway Play', 1, 'American drama about the consequences of mass panic', 'theme', 'very_broad', 'Mass panic themes in various plays'),
('The Crucible', 'Broadway Play', 1, 'Play where innocent people are condemned despite evidence', 'plot', 'very_broad', 'Injustice plots in many dramas'),
('The Crucible', 'Broadway Play', 1, 'Drama set in a Puritan community in early America', 'setting', 'very_broad', 'Puritan setting in historical plays'),
('The Crucible', 'Broadway Play', 1, 'Play featuring a protagonist who must choose between his name and his life', 'theme', 'very_broad', 'Honor and identity themes universal'),
('The Crucible', 'Broadway Play', 2, 'Arthur Miller play from 1953 about the Salem witch trials', 'playwright', 'broad', 'Miller wrote multiple plays; Salem trials is specific'),
('The Crucible', 'Broadway Play', 2, 'The play was written as an allegory for McCarthyism and Communist hunts', 'development', 'broad', 'Historical context is identifying'),
('The Crucible', 'Broadway Play', 2, 'Opened at the Martin Beck Theatre in January 1953', 'production', 'broad', 'Specific theatre and date'),
('The Crucible', 'Broadway Play', 2, 'Miller wrote the play while being investigated by the House Un-American Activities Committee', 'development', 'broad', 'HUAC context is distinctive'),
('The Crucible', 'Broadway Play', 2, 'John Proctor is the moral center and tragic protagonist', 'character', 'broad', 'Character name and role are specific'),
('The Crucible', 'Broadway Play', 2, 'The play involves accusations of witchcraft made by young women', 'plot', 'broad', 'Young women accusers is specific to Salem narrative'),
('The Crucible', 'Broadway Play', 3, 'John Proctor has an affair with Abigail Williams, one of the accusers', 'plot', 'narrowing', 'Specific relationship and conflict'),
('The Crucible', 'Broadway Play', 3, 'Abigail Williams is a teenage girl who leads the false witch hunt accusations', 'character', 'narrowing', 'Character name and role'),
('The Crucible', 'Broadway Play', 3, 'Tituba is an enslaved woman who confesses to witchcraft', 'character', 'narrowing', 'Character name and role'),
('The Crucible', 'Broadway Play', 3, 'Elizabeth Proctor is John''s wife who becomes accused of witchcraft', 'character', 'narrowing', 'Character name and relationship'),
('The Crucible', 'Broadway Play', 3, 'Rebecca Nurse is an elderly woman executed for witchcraft', 'character', 'narrowing', 'Specific character and fate'),
('The Crucible', 'Broadway Play', 3, 'The Deputy Governor Danforth presides over the trials', 'character', 'narrowing', 'Specific character role'),
('The Crucible', 'Broadway Play', 4, 'John Proctor is forced to sign a confession but tears it up, accepting his death', 'plot', 'recognition', 'Famous climactic moment'),
('The Crucible', 'Broadway Play', 4, 'Proctor''s famous line is "Because it is my name!"', 'quote', 'recognition', 'Iconic final line'),
('The Crucible', 'Broadway Play', 4, 'The play culminates with the execution of John Proctor by hanging', 'plot', 'recognition', 'Tragic ending detail'),
('The Crucible', 'Broadway Play', 4, 'The play takes place over several months in 1692 Salem', 'setting', 'recognition', 'Specific historical date and location'),
('The Crucible', 'Broadway Play', 4, 'Fourteen women and five men are executed for witchcraft during the trials depicted', 'production', 'recognition', 'Specific historical casualty numbers'),
('The Crucible', 'Broadway Play', 4, 'A 1996 film adaptation directed by Nicholas Hytner featured Daniel Day-Lewis as John Proctor', 'production', 'recognition', 'Specific film version'),
('The Crucible', 'Broadway Play', 5, 'Proctor declares "I say—I say God is dead" in a moment of despair', 'quote', 'giveaway', 'Blasphemy line unmistakable'),
('The Crucible', 'Broadway Play', 5, 'Abigail falsely accuses Elizabeth Proctor of witchcraft out of jealousy', 'plot', 'giveaway', 'Motivation and accusation are revealing'),
('The Crucible', 'Broadway Play', 5, 'The play ends with Proctor being led to his execution, defending his integrity', 'plot', 'giveaway', 'Specific ending detail'),
('The Crucible', 'Broadway Play', 5, 'The character Mary Warren testifies against the girls but is turned against during the trial', 'plot', 'giveaway', 'Specific plot reversal'),
('The Crucible', 'Broadway Play', 0, 'Arthur Miller based the play on extensive historical research, including court documents from the actual Salem trials of 1692', 'development', 'fact', 'Research basis'),
('The Crucible', 'Broadway Play', 0, 'The play has been adapted into opera, film (1953, 1996, 2020), and continues to be staged worldwide', 'development', 'fact', 'Multiple adaptation legacy'),
('The Crucible', 'Broadway Play', 0, 'Miller was called before HUAC in 1956, where he refused to name Communist associates—paralleling his protagonist John Proctor''s refusal to confess falsely', 'playwright', 'fact', 'Biographical parallel'),
('The Crucible', 'Broadway Play', 0, 'The original production ran for 150 performances and received mixed reviews, but gained recognition later as a masterpiece', 'production', 'fact', 'Initial reception and later reassessment'),
('The Crucible', 'Broadway Play', 0, 'The play uses the historical witch trials as an allegory for any society that allows fear and accusation to override due process', 'theme', 'fact', 'Thematic universality'),
('The Crucible', 'Broadway Play', 0, 'Modern productions have drawn parallels between the play and contemporary events, including political persecution and social media-driven accusations', 'theme', 'fact', 'Ongoing relevance'),

-- ============================================================
-- THE GLASS MENAGERIE
-- ============================================================
('The Glass Menagerie', 'Broadway Play', 1, 'A memory play about a family struggling to find happiness', 'structure', 'very_broad', 'Memory-based family dramas in many plays'),
('The Glass Menagerie', 'Broadway Play', 1, 'Drama set in a modest apartment with three characters struggling with reality', 'setting', 'very_broad', 'Apartment-based family dramas are common'),
('The Glass Menagerie', 'Broadway Play', 1, 'Play featuring a shy young woman with physical disabilities', 'character', 'very_broad', 'Disabled characters in many dramas'),
('The Glass Menagerie', 'Broadway Play', 1, 'American drama exploring themes of escape and unfulfilled dreams', 'theme', 'very_broad', 'Dream and escape themes universal'),
('The Glass Menagerie', 'Broadway Play', 1, 'Play in which a gentleman caller visits an apartment to meet a young woman', 'plot', 'very_broad', 'Visitor plot device common in plays'),
('The Glass Menagerie', 'Broadway Play', 1, 'Drama narrated by one of the characters reflecting on the past', 'structure', 'very_broad', 'First-person narration in many plays'),
('The Glass Menagerie', 'Broadway Play', 2, 'Tennessee Williams'' first major Broadway success, premiered in 1945', 'playwright', 'broad', 'Williams'' early work; 1945 is specific'),
('The Glass Menagerie', 'Broadway Play', 2, 'Set in St. Louis during the Great Depression era', 'setting', 'broad', 'St. Louis setting is distinctive'),
('The Glass Menagerie', 'Broadway Play', 2, 'The play features four main characters and is semi-autobiographical', 'development', 'broad', 'Semi-autobiographical context identifying'),
('The Glass Menagerie', 'Broadway Play', 2, 'Tom serves as both a character and the narrator throughout the play', 'structure', 'broad', 'Narrator-character duality is distinctive'),
('The Glass Menagerie', 'Broadway Play', 2, 'The play features glass figurines as a central symbolic element', 'iconic_element', 'broad', 'Glass objects are thematically important'),
('The Glass Menagerie', 'Broadway Play', 2, 'A collection of small glass sculptures represents fragility and beauty', 'theme', 'broad', 'Symbolism of glass collection'),
('The Glass Menagerie', 'Broadway Play', 3, 'Tom Wingfield is the son who works at a shoe warehouse', 'character', 'narrowing', 'Character name and occupation'),
('The Glass Menagerie', 'Broadway Play', 3, 'Amanda Wingfield is the faded Southern belle mother', 'character', 'narrowing', 'Character name and description'),
('The Glass Menagerie', 'Broadway Play', 3, 'Laura is Tom''s shy sister with a physical disability', 'character', 'narrowing', 'Character name and role'),
('The Glass Menagerie', 'Broadway Play', 3, 'Laura''s favorite glass figurine is a unicorn', 'iconic_element', 'narrowing', 'Specific object detail'),
('The Glass Menagerie', 'Broadway Play', 3, 'Jim O''Connor is the gentleman caller from Tom''s office', 'character', 'narrowing', 'Character name and relationship'),
('The Glass Menagerie', 'Broadway Play', 3, 'Amanda constantly reminisces about her gentlemen callers from her youth', 'character', 'narrowing', 'Specific character behavior'),
('The Glass Menagerie', 'Broadway Play', 4, 'Tom works at the Continental Shoemakers factory', 'plot', 'recognition', 'Specific workplace detail'),
('The Glass Menagerie', 'Broadway Play', 4, 'Laura was unable to attend business college due to her extreme shyness', 'plot', 'recognition', 'Backstory detail'),
('The Glass Menagerie', 'Broadway Play', 4, 'The play is set in 1937, during a particularly difficult time for the family', 'setting', 'recognition', 'Specific year detail'),
('The Glass Menagerie', 'Broadway Play', 4, 'Tom tells the audience he is leaving the city to join the merchant marine', 'plot', 'recognition', 'Character outcome detail'),
('The Glass Menagerie', 'Broadway Play', 4, 'Amanda''s husband abandoned the family years before the play begins', 'character', 'recognition', 'Backstory about absent father'),
('The Glass Menagerie', 'Broadway Play', 4, 'The play features the song "Street Car Named Desire" playing in the background', 'production', 'recognition', 'Music detail'),
('The Glass Menagerie', 'Broadway Play', 5, 'The glass unicorn breaks when Jim dances with Laura, symbolizing the fragility of her world', 'iconic_element', 'giveaway', 'Unmistakable symbolic moment'),
('The Glass Menagerie', 'Broadway Play', 5, 'Jim reveals he is engaged to be married, devastating both Laura and Amanda', 'plot', 'giveaway', 'Crucial revelation and disappointment'),
('The Glass Menagerie', 'Broadway Play', 5, 'Tom abandons his family at the end, fulfilling his desire to escape', 'plot', 'giveaway', 'Character resolution'),
('The Glass Menagerie', 'Broadway Play', 5, 'Laura remains alone in the apartment with her glass menagerie after everyone leaves', 'plot', 'giveaway', 'Bleak ending detail'),
('The Glass Menagerie', 'Broadway Play', 0, 'Tennessee Williams wrote the play in 1943 while working as a bellhop in a St. Louis hotel, drawing directly from his own family experiences', 'development', 'fact', 'Autobiographical source'),
('The Glass Menagerie', 'Broadway Play', 0, 'The original Broadway production in 1945 at the Playhouse Theatre ran for 561 performances, launching Williams to stardom', 'production', 'fact', 'Specific run length: 561'),
('The Glass Menagerie', 'Broadway Play', 0, 'The play was adapted into a 1950 film directed by Irving Rapper, starring Kirk Douglas as Tom and Jane Wyman as Laura', 'development', 'fact', 'Film adaptation details'),
('The Glass Menagerie', 'Broadway Play', 0, 'The set design features unconventional lighting and projection effects that were innovative for 1945, creating a dreamlike atmosphere', 'production', 'fact', 'Technical design innovation'),
('The Glass Menagerie', 'Broadway Play', 0, 'Williams''s sister Rose suffered from severe mental illness and was institutionalized, which inspired the character of Laura', 'playwright', 'fact', 'Personal tragedy influence'),
('The Glass Menagerie', 'Broadway Play', 0, 'The play has been revived numerous times on Broadway, with notable productions in 1983, 2005, and 2013, each bringing new interpretations', 'production', 'fact', 'Revival history'),

-- ============================================================
-- LONG DAY'S JOURNEY INTO NIGHT
-- ============================================================
('Long Day''s Journey Into Night', 'Broadway Play', 1, 'A tragic family drama set over the course of one day', 'structure', 'very_broad', 'Single-day family dramas exist in many plays'),
('Long Day''s Journey Into Night', 'Broadway Play', 1, 'Play exploring family members'' addiction and personal failures', 'theme', 'very_broad', 'Addiction and failure themes in many dramas'),
('Long Day''s Journey Into Night', 'Broadway Play', 1, 'Drama set in a summer cottage by the sea', 'setting', 'very_broad', 'Seaside settings in many plays'),
('Long Day''s Journey Into Night', 'Broadway Play', 1, 'Play featuring four family members confined together in a house', 'plot', 'very_broad', 'Confined family settings in many dramas'),
('Long Day''s Journey Into Night', 'Broadway Play', 1, 'American drama exploring generational trauma and family secrets', 'theme', 'very_broad', 'Family trauma themes universal'),
('Long Day''s Journey Into Night', 'Broadway Play', 1, 'Play in which the past continuously intrudes on the present', 'structure', 'very_broad', 'Past haunting present in many plays'),
('Long Day''s Journey Into Night', 'Broadway Play', 2, 'Eugene O''Neill play published posthumously in 1956', 'playwright', 'broad', 'O''Neill wrote multiple works; posthumous publication is identifying'),
('Long Day''s Journey Into Night', 'Broadway Play', 2, 'Set in Connecticut in August 1912', 'setting', 'broad', 'Specific year and location'),
('Long Day''s Journey Into Night', 'Broadway Play', 2, 'O''Neill''s most autobiographical and intimate work', 'development', 'broad', 'Autobiographical context is identifying'),
('Long Day''s Journey Into Night', 'Broadway Play', 2, 'The play takes place from early morning until late night', 'structure', 'broad', 'All-day time structure is specific'),
('Long Day''s Journey Into Night', 'Broadway Play', 2, 'Features the Tyrone family—parents and two adult sons', 'character', 'broad', 'Family structure is somewhat specific'),
('Long Day''s Journey Into Night', 'Broadway Play', 2, 'Won the Pulitzer Prize posthumously in 1957', 'production', 'broad', 'Pulitzer win is identifying'),
('Long Day''s Journey Into Night', 'Broadway Play', 3, 'James Tyrone is the aging father, a former actor turned theater owner', 'character', 'narrowing', 'Character name and profession'),
('Long Day''s Journey Into Night', 'Broadway Play', 3, 'Mary Cavan Tyrone is the mother struggling with morphine addiction', 'character', 'narrowing', 'Character name and addiction'),
('Long Day''s Journey Into Night', 'Broadway Play', 3, 'Jamie is the elder son, a traveling salesman and failed actor', 'character', 'narrowing', 'Character name and roles'),
('Long Day''s Journey Into Night', 'Broadway Play', 3, 'Edmund is the younger son who discovers he has tuberculosis', 'character', 'narrowing', 'Character name and illness'),
('Long Day''s Journey Into Night', 'Broadway Play', 3, 'The setting is the Tyrone summer house on the Connecticut coast', 'setting', 'narrowing', 'Specific location detail'),
('Long Day''s Journey Into Night', 'Broadway Play', 3, 'The action takes place over one August day in 1912', 'setting', 'narrowing', 'Specific date detail'),
('Long Day''s Journey Into Night', 'Broadway Play', 4, 'Jason Robards Jr. played Edmund in the original Broadway production in 1956', 'production', 'recognition', 'Specific actor and date'),
('Long Day''s Journey Into Night', 'Broadway Play', 4, 'The play was directed by José Quintero, whose production became legendary', 'production', 'recognition', 'Specific director'),
('Long Day''s Journey Into Night', 'Broadway Play', 4, 'Mary''s addiction to morphine is traced back to after Edmund''s birth', 'plot', 'recognition', 'Character backstory detail'),
('Long Day''s Journey Into Night', 'Broadway Play', 4, 'Edmund has contracted tuberculosis, a major source of family anxiety', 'plot', 'recognition', 'Central plot point'),
('Long Day''s Journey Into Night', 'Broadway Play', 4, 'James Tyrone refuses to spend money on a good sanatorium for Edmund''s treatment', 'plot', 'recognition', 'Character conflict detail'),
('Long Day''s Journey Into Night', 'Broadway Play', 4, 'Jamie reveals his resentment toward Edmund for replacing an earlier child who died', 'plot', 'recognition', 'Family trauma revelation'),
('Long Day''s Journey Into Night', 'Broadway Play', 5, 'The play ends with Mary, heavily medicated on morphine, lost in a memory of herself as a young girl', 'plot', 'giveaway', 'Tragic conclusion detail'),
('Long Day''s Journey Into Night', 'Broadway Play', 5, 'James reveals he bought cheap land and made poor financial decisions out of greed', 'plot', 'giveaway', 'Character confession'),
('Long Day''s Journey Into Night', 'Broadway Play', 5, 'Jamie confesses his jealousy and resentment toward Edmund''s talent and promise', 'plot', 'giveaway', 'Emotional confrontation'),
('Long Day''s Journey Into Night', 'Broadway Play', 5, 'Mary''s descent into drugged delirium is the final image of the play', 'plot', 'giveaway', 'Unmistakable ending'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'Eugene O''Neill wrote the play between 1941 and 1942 but stipulated it could not be published or produced for 25 years after his death—it was first performed in 1956', 'development', 'fact', 'Publication restriction history'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The Tyrone family is based directly on O''Neill''s own family: his father, mother, and two brothers', 'development', 'fact', 'Autobiographical family basis'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'O''Neill''s father was a famous Shakespearean actor, his mother was an opioid addict, and his brother was an alcoholic—all reflected in the play', 'playwright', 'fact', 'Family tragedy context'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The original Broadway production ran for 565 performances and won acclaim for its emotional and psychological depth', 'production', 'fact', 'Specific run length: 565'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The play has been adapted into a 1962 film directed by Sidney Lumet, starring Ralph Richardson and Katharine Hepburn, which preserved the stage production''s intensity', 'development', 'fact', 'Notable film adaptation'),
('Long Day''s Journey Into Night', 'Broadway Play', 0, 'The play is considered one of the greatest American dramas ever written, often taught alongside Death of a Salesman as a cornerstone of American theater', 'theme', 'fact', 'Critical legacy'),

-- ============================================================
-- WHO'S AFRAID OF VIRGINIA WOOLF?
-- ============================================================
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 1, 'A play about marital conflict and intellectual combat between two couples', 'theme', 'very_broad', 'Marital conflict dramas common'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 1, 'Drama set in an academic environment with heavy drinking', 'setting', 'very_broad', 'Academic settings in many plays'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 1, 'Play featuring intense verbal sparring and wit', 'tone', 'very_broad', 'Witty intellectual dramas exist'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 1, 'American drama exploring themes of illusion and reality', 'theme', 'very_broad', 'Illusion vs. reality theme universal'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 1, 'Play in which a younger couple visits an older couple''s home for the evening', 'plot', 'very_broad', 'Visit plot device common'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 1, 'Drama featuring an all-night drinking and argument session', 'structure', 'very_broad', 'Extended social gathering plays exist'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 2, 'Edward Albee play from 1962', 'playwright', 'broad', 'Albee wrote multiple plays; 1962 is moderately specific'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 2, 'Premiered at the Billy Rose Theatre on Broadway', 'production', 'broad', 'Specific theatre and Broadway context'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 2, 'Won the Tony Award for Best Play', 'production', 'broad', 'Tony win is identifying'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 2, 'Features two couples: an older married couple and younger married couple', 'character', 'broad', 'Dual couple structure is somewhat specific'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 2, 'The setting is a college professor''s home', 'setting', 'broad', 'Academic home setting is identifying'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 2, 'The action takes place over a single night of drinking and arguing', 'structure', 'broad', 'Single-night drinking structure is distinctive'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 3, 'George is a college professor and Martha''s husband', 'character', 'narrowing', 'Character name and relationship'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 3, 'Martha is George''s acerbic, alcoholic wife', 'character', 'narrowing', 'Character name and description'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 3, 'Nick and Honey are a younger couple visiting for the evening', 'character', 'narrowing', 'Character names and relationship'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 3, 'George and Martha have an imaginary son who exists only in their minds', 'plot', 'narrowing', 'Specific plot element'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 3, 'The younger man Nick is a biology professor', 'character', 'narrowing', 'Character profession detail'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 3, 'Honey is described as mousy and becomes increasingly drunk', 'character', 'narrowing', 'Character description and arc'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 4, 'Elizabeth Taylor and Richard Burton starred in the 1966 film adaptation', 'production', 'recognition', 'Famous film casting'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 4, 'The opening line is "I''m afraid we are not going to be very comfortable here"', 'quote', 'recognition', 'Famous opening line'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 4, 'Martha sings a rendition of "Who''s Afraid of the Big Bad Wolf?"', 'iconic_element', 'recognition', 'Famous performance moment'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 4, 'George announces the imaginary son has died in a car accident', 'plot', 'recognition', 'Central plot revelation'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 4, 'The play includes explicit language and sexual references unusual for 1962 Broadway', 'production', 'recognition', 'Boundary-pushing content'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 4, 'Albee based the title on the famous phrase "Who''s Afraid of the Big Bad Wolf?"', 'development', 'recognition', 'Title origin explanation'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 5, 'George reveals the imaginary son never existed and was purely a construction of George and Martha''s marriage', 'plot', 'giveaway', 'Crucial revelation'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 5, 'The play ends with Martha and George in a moment of vulnerability and tenderness after all-night combat', 'plot', 'giveaway', 'Bittersweet ending detail'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 5, 'The title is a play on Snow White and the Seven Dwarfs''s famous tune', 'iconic_element', 'giveaway', 'Title origin unmistakable'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 5, 'Nick and Honey leave the house as George and Martha sit together in silence', 'plot', 'giveaway', 'Specific ending image'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Edward Albee wrote the play in 1962 when he was 34 years old and at the height of his creative powers', 'playwright', 'fact', 'Playwright age and context'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The original Broadway production ran for 664 performances, making it one of the longest-running plays of the 1960s', 'production', 'fact', 'Specific run length: 664'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The 1966 film adaptation directed by Mike Nichols won four Academy Awards and became one of the most acclaimed adaptations of a play', 'development', 'fact', 'Film adaptation success'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The play was one of the first major Broadway plays to use profanity and explicit sexual references, shocking audiences of 1962', 'production', 'fact', 'Boundary-pushing language'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'Albee had no formal training as a playwright but studied under William Flanagan and absorbed influence from European absurdist theater', 'playwright', 'fact', 'Background and influence'),
('Who''s Afraid of Virginia Woolf?', 'Broadway Play', 0, 'The play has been revived several times on Broadway, including a 2018 production starring Rupert Everett, demonstrating its enduring power', 'production', 'fact', 'Contemporary revivals'),

-- ============================================================
-- ANGELS IN AMERICA
-- ============================================================
('Angels in America', 'Broadway Play', 1, 'An epic two-part play about America in the 1980s', 'structure', 'very_broad', 'Epic multi-part plays exist'),
('Angels in America', 'Broadway Play', 1, 'Drama exploring themes of illness and mortality', 'theme', 'very_broad', 'Illness themes in many plays'),
('Angels in America', 'Broadway Play', 1, 'American play dealing with political upheaval and social change', 'theme', 'very_broad', 'Political themes in many dramas'),
('Angels in America', 'Broadway Play', 1, 'Play featuring LGBTQ+ characters and relationships', 'character', 'very_broad', 'LGBTQ+ characters in contemporary plays'),
('Angels in America', 'Broadway Play', 1, 'Drama set in New York City with urban setting', 'setting', 'very_broad', 'NYC settings in many plays'),
('Angels in America', 'Broadway Play', 1, 'Play incorporating spiritual and religious themes', 'theme', 'very_broad', 'Religious themes in many dramas'),
('Angels in America', 'Broadway Play', 2, 'Tony Kushner play in two parts: Millennium Approaches and Perestroika', 'playwright', 'broad', 'Kushner connection and two-part structure identify'),
('Angels in America', 'Broadway Play', 2, 'Written during the AIDS crisis in the 1980s and early 1990s', 'development', 'broad', 'AIDS crisis context is identifying'),
('Angels in America', 'Broadway Play', 2, 'Premiered at the National Theater in London before coming to Broadway', 'production', 'broad', 'London premiere is specific'),
('Angels in America', 'Broadway Play', 2, 'Won both the Tony Award and Pulitzer Prize', 'production', 'broad', 'Double award win is identifying'),
('Angels in America', 'Broadway Play', 2, 'Total runtime is over seven hours across both parts', 'structure', 'broad', 'Specific length is distinctive'),
('Angels in America', 'Broadway Play', 2, 'Features a connection between a historical lawyer and a contemporary gay man', 'plot', 'broad', 'Historical-contemporary parallel is identifying'),
('Angels in America', 'Broadway Play', 3, 'Roy Cohn, the real-life lawyer and political figure, is a central character', 'character', 'narrowing', 'Character name is distinctive'),
('Angels in America', 'Broadway Play', 3, 'Prior Walter is a young man with AIDS dealing with his diagnosis and relationships', 'character', 'narrowing', 'Character name and situation'),
('Angels in America', 'Broadway Play', 3, 'Louis Ironson is Prior''s boyfriend who abandons him after his AIDS diagnosis', 'character', 'narrowing', 'Character name and relationship'),
('Angels in America', 'Broadway Play', 3, 'Joe Pitt is a closeted Mormon lawyer having an affair with Louis', 'character', 'narrowing', 'Character name and identity'),
('Angels in America', 'Broadway Play', 3, 'An angel visits Prior in a series of hallucinations', 'plot', 'narrowing', 'Angel visitation is specific plot element'),
('Angels in America', 'Broadway Play', 3, 'The second part, Perestroika, is set in 1992 and deals with recovery and rebuilding', 'structure', 'narrowing', 'Specific year and thematic content'),
('Angels in America', 'Broadway Play', 4, 'Andrew Garfield played Prior Walter in the acclaimed 2018 Broadway revival', 'production', 'recognition', 'Specific actor and recent revival'),
('Angels in America', 'Broadway Play', 4, 'The character Harper Pitt is Joe''s wife, a woman dealing with her own crises', 'character', 'recognition', 'Character name and relationship'),
('Angels in America', 'Broadway Play', 4, 'Roy Cohn is portrayed as an unrepentant, ruthless power broker who denies his homosexuality', 'character', 'recognition', 'Character portrayal detail'),
('Angels in America', 'Broadway Play', 4, 'The play features scenes set in hospital rooms, apartments, and even a bookstore', 'setting', 'recognition', 'Multiple setting variety'),
('Angels in America', 'Broadway Play', 4, 'Belize is a character who serves as a nurse, friend, and moral voice', 'character', 'recognition', 'Character name and role'),
('Angels in America', 'Broadway Play', 4, 'The play addresses Ronald Reagan''s presidency and Cold War politics', 'theme', 'recognition', 'Political context detail'),
('Angels in America', 'Broadway Play', 5, 'The angel tells Prior he is chosen to be a prophet for a new age', 'plot', 'giveaway', 'Central supernatural element'),
('Angels in America', 'Broadway Play', 5, 'Roy Cohn dies of AIDS complications, marking a turning point in the play', 'plot', 'giveaway', 'Key character death'),
('Angels in America', 'Broadway Play', 5, 'The play ends with Prior alive, looking toward a hopeful future, despite his illness', 'plot', 'giveaway', 'Bittersweet redemptive ending'),
('Angels in America', 'Broadway Play', 5, 'Joe eventually comes out as gay and leaves his wife Harper', 'plot', 'giveaway', 'Character transformation'),
('Angels in America', 'Broadway Play', 0, 'Tony Kushner spent five years researching and writing the two-part play, incorporating real historical figures and events', 'development', 'fact', 'Extensive research and development'),
('Angels in America', 'Broadway Play', 0, 'The play was initially controversial for its political content and frank depictions of homosexuality, but became widely celebrated as a landmark work', 'production', 'fact', 'Initial controversy and critical reassessment'),
('Angels in America', 'Broadway Play', 0, 'Millennium Approaches premiered in 1993, followed by Perestroika in 1994; both eventually reached Broadway in 1994-1996', 'production', 'fact', 'Release dates and Broadway arrival'),
('Angels in America', 'Broadway Play', 0, 'The play was adapted into an HBO miniseries directed by Mike Nichols in 2003, starring Al Pacino, Meryl Streep, and others', 'development', 'fact', 'Major television adaptation'),
('Angels in America', 'Broadway Play', 0, 'The character of Roy Cohn was based on the real lawyer who worked on the Rosenberg case and influenced McCarthy-era politics', 'development', 'fact', 'Historical figure basis'),
('Angels in America', 'Broadway Play', 0, 'The play has been translated into multiple languages and performed worldwide, becoming one of the most successful American plays of the late 20th century', 'production', 'fact', 'International reach and legacy'),

-- ============================================================
-- AUGUST: OSAGE COUNTY
-- ============================================================
('August: Osage County', 'Broadway Play', 1, 'Family drama set in rural Oklahoma', 'setting', 'very_broad', 'Rural family dramas common'),
('August: Osage County', 'Broadway Play', 1, 'Play dealing with family secrets and dysfunction', 'theme', 'very_broad', 'Family dysfunction theme universal'),
('August: Osage County', 'Broadway Play', 1, 'Drama featuring multiple generations gathering at a family home', 'plot', 'very_broad', 'Multi-generational family gatherings in many plays'),
('August: Osage County', 'Broadway Play', 1, 'Play exploring alcoholism and its impact on families', 'theme', 'very_broad', 'Alcoholism theme in many dramas'),
('August: Osage County', 'Broadway Play', 1, 'American drama set in the contemporary Midwest', 'setting', 'very_broad', 'Midwest settings in various plays'),
('August: Osage County', 'Broadway Play', 1, 'Play featuring powerful female characters and performances', 'character', 'very_broad', 'Strong female roles in many contemporary plays'),
('August: Osage County', 'Broadway Play', 2, 'Tracy Letts play from 2007 that won major awards', 'playwright', 'broad', 'Letts connection and year are identifying'),
('August: Osage County', 'Broadway Play', 2, 'Set in Pawhuska, Oklahoma during a family reunion in August', 'setting', 'broad', 'Oklahoma town and August detail'),
('August: Osage County', 'Broadway Play', 2, 'The play originated at the Steppenwolf Theatre in Chicago', 'production', 'broad', 'Steppenwolf origin is identifying'),
('August: Osage County', 'Broadway Play', 2, 'Opened at the Imperial Theatre on Broadway in 2007', 'production', 'broad', 'Specific theatre and date'),
('August: Osage County', 'Broadway Play', 2, 'Won the Pulitzer Prize for Drama in 2008', 'production', 'broad', 'Pulitzer win and year are identifying'),
('August: Osage County', 'Broadway Play', 2, 'Features a 13-member ensemble cast', 'production', 'broad', 'Specific cast size is distinctive'),
('August: Osage County', 'Broadway Play', 3, 'Violet Weston is the matriarch of the family with a pill addiction', 'character', 'narrowing', 'Character name and condition'),
('August: Osage County', 'Broadway Play', 3, 'Beverly Weston is Violet''s husband, a retired professor', 'character', 'narrowing', 'Character name and profession'),
('August: Osage County', 'Broadway Play', 3, 'The Weston family home is a three-story house in Oklahoma', 'setting', 'narrowing', 'Specific architectural detail'),
('August: Osage County', 'Broadway Play', 3, 'Barb is the eldest daughter and her family come to visit', 'character', 'narrowing', 'Character name and relationship'),
('August: Osage County', 'Broadway Play', 3, 'The play runs approximately three and a half hours', 'structure', 'narrowing', 'Specific length detail'),
('August: Osage County', 'Broadway Play', 3, 'Multiple family conflicts revolve around money, inheritance, and resentment', 'plot', 'narrowing', 'Financial conflict themes'),
('August: Osage County', 'Broadway Play', 4, 'Meryl Streep played Violet Weston in the 2013 film adaptation', 'production', 'recognition', 'Famous actress casting'),
('August: Osage County', 'Broadway Play', 4, 'The original Broadway production featured Deanna Dunagan as Violet', 'production', 'recognition', 'Original actor detail'),
('August: Osage County', 'Broadway Play', 4, 'Barbara has a confrontation with her mother Violet about years of dysfunction', 'plot', 'recognition', 'Key family conflict'),
('August: Osage County', 'Broadway Play', 4, 'Beverly disappears early in the play, setting the action in motion', 'plot', 'recognition', 'Plot catalyst detail'),
('August: Osage County', 'Broadway Play', 4, 'The play includes a shocking dinner scene in which family tensions explode', 'iconic_element', 'recognition', 'Famous scene moment'),
('August: Osage County', 'Broadway Play', 4, 'Karen Weston is the middle daughter who takes her family''s side', 'character', 'recognition', 'Character name and role'),
('August: Osage County', 'Broadway Play', 5, 'Violet reveals deeply hurtful truths about her children and their failures', 'plot', 'giveaway', 'Maternal cruelty revelation'),
('August: Osage County', 'Broadway Play', 5, 'Beverly''s death is revealed to be a suicide, not an accident', 'plot', 'giveaway', 'Central plot twist'),
('August: Osage County', 'Broadway Play', 5, 'The family is left fractured and angry, with no resolution or reconciliation', 'plot', 'giveaway', 'Bleak family outcome'),
('August: Osage County', 'Broadway Play', 5, 'Jean Fordham, the youngest character, has family drama of her own', 'character', 'giveaway', 'Specific character involvement'),
('August: Osage County', 'Broadway Play', 0, 'Tracy Letts originally wrote the play as a screenplay before adapting it for the stage', 'development', 'fact', 'Original format was screenplay'),
('August: Osage County', 'Broadway Play', 0, 'The 2013 film adaptation directed by John Wells featured an ensemble cast including Tom Welling, Julia Roberts, and Chris Pine', 'development', 'fact', 'Film adaptation cast details'),
('August: Osage County', 'Broadway Play', 0, 'The original Broadway production ran for 718 performances before closing, one of the longest-running plays of its decade', 'production', 'fact', 'Specific run length: 718'),
('August: Osage County', 'Broadway Play', 0, 'Deanna Dunagan won a Tony Award for her performance as Violet, while the play itself won multiple Tonys including Best Play', 'production', 'fact', 'Tony Awards success'),
('August: Osage County', 'Broadway Play', 0, 'Letts drew inspiration from his own family experiences in Oklahoma and Midwest family dynamics', 'development', 'fact', 'Autobiographical elements'),
('August: Osage County', 'Broadway Play', 0, 'The play tackles contemporary American themes including the recession, family fragmentation, and the decline of institutional life in rural America', 'theme', 'fact', 'Cultural and economic themes'),

-- ============================================================
-- FENCES
-- ============================================================
('Fences', 'Broadway Play', 1, 'A play about an African American family dealing with broken dreams', 'theme', 'very_broad', 'Broken dreams theme in many plays'),
('Fences', 'Broadway Play', 1, 'Drama set in a working-class neighborhood', 'setting', 'very_broad', 'Working-class settings in many plays'),
('Fences', 'Broadway Play', 1, 'Play exploring father-son relationships and legacy', 'theme', 'very_broad', 'Father-son themes universal in drama'),
('Fences', 'Broadway Play', 1, 'American drama dealing with racism and inequality', 'theme', 'very_broad', 'Racism themes in many contemporary plays'),
('Fences', 'Broadway Play', 1, 'Play featuring a protagonist who built something physical and tangible', 'plot', 'very_broad', 'Concrete accomplishments in many plays'),
('Fences', 'Broadway Play', 1, 'Drama exploring marriage and infidelity', 'theme', 'very_broad', 'Infidelity theme common in dramas'),
('Fences', 'Broadway Play', 2, 'August Wilson play from 1987', 'playwright', 'broad', 'Wilson connection and year moderately specific'),
('Fences', 'Broadway Play', 2, 'Set in Pittsburgh in the 1950s', 'setting', 'broad', 'Pittsburgh and 1950s setting distinctive'),
('Fences', 'Broadway Play', 2, 'Opened at the 46th Street Theatre on Broadway', 'production', 'broad', 'Specific theatre and Broadway'),
('Fences', 'Broadway Play', 2, 'Part of August Wilson''s larger Pittsburgh Cycle of ten plays', 'development', 'broad', 'Cycle context identifying'),
('Fences', 'Broadway Play', 2, 'Won the Pulitzer Prize for Drama in 1987', 'production', 'broad', 'Pulitzer win year identifying'),
('Fences', 'Broadway Play', 2, 'Features a baseball metaphor throughout the play', 'theme', 'broad', 'Baseball metaphor is distinctive'),
('Fences', 'Broadway Play', 3, 'Troy Maxson is the protagonist, a middle-aged garbage collector', 'character', 'narrowing', 'Character name and occupation'),
('Fences', 'Broadway Play', 3, 'Rose Maxson is Troy''s wife of eighteen years', 'character', 'narrowing', 'Character name and marriage detail'),
('Fences', 'Broadway Play', 3, 'Cory is Troy and Rose''s son with aspirations to play professional football', 'character', 'narrowing', 'Character name and ambition'),
('Fences', 'Broadway Play', 3, 'Lyons is Troy''s eldest son from a previous relationship', 'character', 'narrowing', 'Character name and family structure'),
('Fences', 'Broadway Play', 3, 'Troy is building a fence around his house', 'plot', 'narrowing', 'Specific construction project'),
('Fences', 'Broadway Play', 3, 'Troy was once a talented baseball player in the Negro Leagues', 'character', 'narrowing', 'Character sports history'),
('Fences', 'Broadway Play', 4, 'James Earl Jones originated the role of Troy Maxson', 'production', 'recognition', 'Specific actor'),
('Fences', 'Broadway Play', 4, 'Denzel Washington starred as Troy Maxson in a 2010 Broadway revival', 'production', 'recognition', 'Recent star and revival'),
('Fences', 'Broadway Play', 4, 'Viola Davis has played Rose in Broadway productions and the 2016 film', 'production', 'recognition', 'Actress and adaptation'),
('Fences', 'Broadway Play', 4, 'Troy is angry about being passed over because of his race when younger', 'character', 'recognition', 'Character motivation detail'),
('Fences', 'Broadway Play', 4, 'Cory wants to pursue a football scholarship, but Troy opposes it', 'plot', 'recognition', 'Central conflict detail'),
('Fences', 'Broadway Play', 4, 'The play takes place over several years, with scenes at different times', 'structure', 'recognition', 'Non-linear structure'),
('Fences', 'Broadway Play', 5, 'Troy reveals he fathered a child outside his marriage', 'plot', 'giveaway', 'Central betrayal revelation'),
('Fences', 'Broadway Play', 5, 'Rose withdraws her affection and presence from Troy after his infidelity', 'plot', 'giveaway', 'Relationship consequence'),
('Fences', 'Broadway Play', 5, 'Cory confronts Troy and the fence becomes a symbol of the barriers between them', 'plot', 'giveaway', 'Final symbolic moment'),
('Fences', 'Broadway Play', 5, 'Troy dies and the final scene shows the family gathering after his death', 'plot', 'giveaway', 'Ending detail'),
('Fences', 'Broadway Play', 0, 'August Wilson was an African American playwright who created a ten-play cycle examining Black life in Pittsburgh across the 20th century', 'playwright', 'fact', 'Playwright legacy and project'),
('Fences', 'Broadway Play', 0, 'The 2016 film adaptation directed by Denzel Washington and starring Washington and Viola Davis won numerous award nominations', 'development', 'fact', 'Film adaptation success'),
('Fences', 'Broadway Play', 0, 'The original Broadway production ran for 526 performances and became one of the most frequently staged plays in American theater', 'production', 'fact', 'Specific run length: 526'),
('Fences', 'Broadway Play', 0, 'Wilson based Troy Maxson on his own stepfather and drew from observations of working-class Black life in 1950s Pittsburgh', 'development', 'fact', 'Autobiographical inspiration'),
('Fences', 'Broadway Play', 0, 'The play uses the fence as a central symbol representing barriers, protection, confinement, and the boundaries between people', 'theme', 'fact', 'Symbolic meaning'),
('Fences', 'Broadway Play', 0, 'August Wilson won two Pulitzer Prizes and was one of the most celebrated American playwrights before his death in 2005', 'playwright', 'fact', 'Major career achievement'),

-- ============================================================
-- THE CURIOUS INCIDENT OF THE DOG IN THE NIGHT-TIME
-- ============================================================
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 1, 'A play about a young person who is intellectually gifted but socially isolated', 'character', 'very_broad', 'Gifted but isolated characters in many plays'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 1, 'Drama told from an unconventional perspective', 'structure', 'very_broad', 'Unusual narrative structures in various plays'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 1, 'Play featuring a dog as a central plot element', 'plot', 'very_broad', 'Animal-centered plots in some dramas'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 1, 'American play adapted from a popular novel', 'development', 'very_broad', 'Novel-to-stage adaptations common'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 1, 'Drama exploring mathematical and logical thinking patterns', 'theme', 'very_broad', 'Intellectual themes in some plays'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 1, 'Play with innovative staging that includes projection and visual effects', 'production', 'very_broad', 'Technical theatrical innovations in contemporary plays'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 2, 'Based on Mark Haddon''s novel of the same name', 'development', 'broad', 'Mark Haddon source identifying'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 2, 'Adapted by Simon Stephens for the stage', 'playwright', 'broad', 'Simon Stephens playwright credit'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 2, 'Originated at the National Theatre in London in 2012', 'production', 'broad', 'London origin identifying'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 2, 'Arrived on Broadway in 2014 and won multiple Tony Awards', 'production', 'broad', 'Broadway arrival date and Tonys'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 2, 'Won five Tony Awards in 2015, including Best Play', 'production', 'broad', 'Specific award count and year'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 2, 'Features an LED grid floor that serves as a central design element', 'production', 'broad', 'Technical staging innovation'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 3, 'Christopher Boone is a 15-year-old protagonist with autism', 'character', 'narrowing', 'Character name and age'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 3, 'The play is narrated by Christopher in first person', 'structure', 'narrowing', 'First-person narration style'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 3, 'A dog named Wellington has been killed with a garden fork', 'plot', 'narrowing', 'Specific crime and victim'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 3, 'Christopher decides to find out who killed Wellington', 'plot', 'narrowing', 'Investigation motivation'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 3, 'Christopher has an extraordinary ability with mathematics and patterns', 'character', 'narrowing', 'Character intellectual ability'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 3, 'Christopher''s father is revealed to have been lying about his mother', 'plot', 'narrowing', 'Family secret plot element'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 4, 'The stage contains a grid of LED lights that form patterns and represent Christopher''s mind', 'production', 'recognition', 'Technical design detail'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 4, 'Christopher cannot tolerate physical touch and becomes distressed by sudden movements', 'character', 'recognition', 'Sensory sensitivity detail'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 4, 'Christopher thinks in prime numbers and mathematical patterns', 'character', 'recognition', 'Specific thinking pattern'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 4, 'The play involves a journey from England to London', 'plot', 'recognition', 'Geographic journey detail'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 4, 'Christopher is taught by a schoolmaster named Siobhan', 'character', 'recognition', 'Character name and relationship'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 4, 'The novel includes mathematical diagrams and prime number chapter numbers', 'development', 'recognition', 'Structural element from source'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 5, 'Christopher''s mother faked her death but is actually alive', 'plot', 'giveaway', 'Major character revelation'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 5, 'Christopher''s father killed Wellington in a rage', 'plot', 'giveaway', 'Crime perpetrator revelation'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 5, 'Christopher leaves home to find his mother, traveling alone by bus and train', 'plot', 'giveaway', 'Character journey detail'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 5, 'The play ends with Christopher finding strength and independence', 'plot', 'giveaway', 'Character growth conclusion'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Mark Haddon wrote the novel while working as a tutor for a child with autism, informing the character''s perspective', 'development', 'fact', 'Inspirational source'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The stage design received international acclaim, with touring productions using variations of the LED floor concept', 'production', 'fact', 'Design innovation impact'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The play has been performed in over 30 countries and has become one of the most successful contemporary stage adaptations of a novel', 'production', 'fact', 'International success'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The Broadway production ran for 722 performances at the Ethel Barrymore Theatre, continuing for several years', 'production', 'fact', 'Specific run length: 722'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'Simon Stephens'' adaptation maintains Christopher''s perspective while translating the novel''s mathematical structure into theatrical language and staging', 'playwright', 'fact', 'Adaptation technique'),
('The Curious Incident of the Dog in the Night-Time', 'Broadway Play', 0, 'The original National Theatre production helped establish autism representation in contemporary theater', 'production', 'fact', 'Cultural significance'),

-- ============================================================
-- DOUBT
-- ============================================================
('Doubt', 'Broadway Play', 1, 'A play set in a Catholic school with institutional authority at stake', 'setting', 'very_broad', 'School settings in various plays'),
('Doubt', 'Broadway Play', 1, 'Drama exploring themes of suspicion and accusation', 'theme', 'very_broad', 'Suspicion themes in many plays'),
('Doubt', 'Broadway Play', 1, 'American play set in the 1960s with period details', 'setting', 'very_broad', '1960s settings in various plays'),
('Doubt', 'Broadway Play', 1, 'Play featuring a conflict between a nun and a priest', 'character', 'very_broad', 'Religious character conflicts in some plays'),
('Doubt', 'Broadway Play', 1, 'Drama that leaves the truth ambiguous and unresolved', 'structure', 'very_broad', 'Ambiguous endings in some plays'),
('Doubt', 'Broadway Play', 1, 'Play exploring questions of faith and morality', 'theme', 'very_broad', 'Faith and morality themes universal'),
('Doubt', 'Broadway Play', 2, 'John Patrick Shanley play from 2004', 'playwright', 'broad', 'Shanley connection and year identifying'),
('Doubt', 'Broadway Play', 2, 'Set in 1964 at a Catholic school in New York', 'setting', 'broad', 'Specific year and location'),
('Doubt', 'Broadway Play', 2, 'Won the Pulitzer Prize for Drama in 2005', 'production', 'broad', 'Pulitzer Prize year identifying'),
('Doubt', 'Broadway Play', 2, 'Also won the Tony Award for Best Play', 'production', 'broad', 'Tony Award win identifying'),
('Doubt', 'Broadway Play', 2, 'John Patrick Shanley directed the play and later adapted it into a film', 'development', 'broad', 'Shanley as director and filmmaker'),
('Doubt', 'Broadway Play', 2, 'The play is only four scenes long but maintains intense focus', 'structure', 'broad', 'Specific scene count'),
('Doubt', 'Broadway Play', 3, 'Sister Aloysius is the principal nun of the school', 'character', 'narrowing', 'Character name and position'),
('Doubt', 'Broadway Play', 3, 'Father Brendan Flynn is the charismatic priest at the school', 'character', 'narrowing', 'Character name and role'),
('Doubt', 'Broadway Play', 3, 'Sister James is a younger nun who teaches in the school', 'character', 'narrowing', 'Character name and role'),
('Doubt', 'Broadway Play', 3, 'Mrs. Muller is the mother of a student in the school', 'character', 'narrowing', 'Character name and role'),
('Doubt', 'Broadway Play', 3, 'Sister Aloysius suspects Father Flynn of inappropriate behavior with a student', 'plot', 'narrowing', 'Central accusation detail'),
('Doubt', 'Broadway Play', 3, 'The accused student is Donald Muller, a sensitive altar boy', 'character', 'narrowing', 'Character name and relationship'),
('Doubt', 'Broadway Play', 4, 'The play features the famous line, "I have such doubts!"', 'quote', 'recognition', 'Iconic line'),
('Doubt', 'Broadway Play', 4, 'Meryl Streep played Sister Aloysius in the 2008 film adaptation', 'production', 'recognition', 'Film casting detail'),
('Doubt', 'Broadway Play', 4, 'Philip Seymour Hoffman played Father Flynn in the film', 'production', 'recognition', 'Film casting detail'),
('Doubt', 'Broadway Play', 4, 'Sister Aloysius accuses Father Flynn without concrete evidence, only suspicion', 'plot', 'recognition', 'Key accusation detail'),
('Doubt', 'Broadway Play', 4, 'The play never definitively reveals whether Father Flynn is guilty or innocent', 'structure', 'recognition', 'Ambiguous truth structure'),
('Doubt', 'Broadway Play', 4, 'Sister Aloysius forces Father Flynn''s transfer from the school', 'plot', 'recognition', 'Character action outcome'),
('Doubt', 'Broadway Play', 5, 'In the final scene, Sister Aloysius questions her own certainty and admits doubt', 'plot', 'giveaway', 'Final ironic revelation'),
('Doubt', 'Broadway Play', 5, 'Father Flynn denies all accusations but then asks Sister James for advice on leaving', 'plot', 'giveaway', 'Ambiguous guilt implication'),
('Doubt', 'Broadway Play', 5, 'The truth of whether an improper relationship occurred is never confirmed', 'structure', 'giveaway', 'Intentional ambiguity'),
('Doubt', 'Broadway Play', 5, 'Sister Aloysius reveals she used methods of intimidation to obtain the priest''s cooperation', 'plot', 'giveaway', 'Character moral compromise'),
('Doubt', 'Broadway Play', 0, 'John Patrick Shanley was raised Catholic and attended Catholic schools, which directly influenced the play''s authenticity and themes', 'development', 'fact', 'Autobiographical background'),
('Doubt', 'Broadway Play', 0, 'The play was inspired by the growing scandal of sexual abuse in the Catholic Church, though it does not present a definitive case', 'development', 'fact', 'Contemporary context'),
('Doubt', 'Broadway Play', 0, 'The 2008 film adaptation directed by Shanley won multiple Academy Award nominations, bringing the play to a wider audience', 'development', 'fact', 'Film success and recognition'),
('Doubt', 'Broadway Play', 0, 'The play has been frequently performed in schools, churches, and community theaters, making it one of the most widely staged contemporary plays', 'production', 'fact', 'Accessibility and frequency of performance'),
('Doubt', 'Broadway Play', 0, 'The original Broadway production starred Frances Conroy as Sister Aloysius and Brian F. O''Byrne as Father Flynn', 'production', 'fact', 'Original cast members'),
('Doubt', 'Broadway Play', 0, 'The play''s interrogation of certainty and the danger of accusations without proof has become increasingly relevant in discussions of due process and evidence', 'theme', 'fact', 'Continuing social relevance'),

-- ============================================================
-- THE INHERITANCE
-- ============================================================
('The Inheritance', 'Broadway Play', 1, 'An expansive play about gay men living in contemporary New York City', 'character', 'very_broad', 'NYC-set gay drama in contemporary plays'),
('The Inheritance', 'Broadway Play', 1, 'Drama exploring themes of legacy and intergenerational connection', 'theme', 'very_broad', 'Legacy themes in many plays'),
('The Inheritance', 'Broadway Play', 1, 'A two-part play that requires a full day of viewing', 'structure', 'very_broad', 'Epic-length two-part plays exist'),
('The Inheritance', 'Broadway Play', 1, 'Play dealing with history and memory in a contemporary setting', 'theme', 'very_broad', 'Memory themes in contemporary drama'),
('The Inheritance', 'Broadway Play', 1, 'American drama inspired by E.M. Forster''s novel Howards End', 'development', 'very_broad', 'Literary adaptations exist'),
('The Inheritance', 'Broadway Play', 1, 'Play featuring a large ensemble of characters in interconnected relationships', 'character', 'very_broad', 'Large ensemble casts in various plays'),
('The Inheritance', 'Broadway Play', 2, 'Matthew Lopez play that premiered in 2019', 'playwright', 'broad', 'Lopez connection and year identifying'),
('The Inheritance', 'Broadway Play', 2, 'Originated at the Young Vic Theatre in London before Broadway', 'production', 'broad', 'London premiere location'),
('The Inheritance', 'Broadway Play', 2, 'Opened at the Ethel Barrymore Theatre on Broadway', 'production', 'broad', 'Specific theatre'),
('The Inheritance', 'Broadway Play', 2, 'Runs over six hours across two parts', 'structure', 'broad', 'Specific length detail'),
('The Inheritance', 'Broadway Play', 2, 'Won the Tony Award for Best Play in 2020', 'production', 'broad', 'Tony Award year and category'),
('The Inheritance', 'Broadway Play', 2, 'Inspired by E.M. Forster''s novel Howards End but set in contemporary NYC', 'development', 'broad', 'Literary inspiration identifying'),
('The Inheritance', 'Broadway Play', 3, 'Eric is the protagonist, a successful gay lawyer', 'character', 'narrowing', 'Character name and profession'),
('The Inheritance', 'Broadway Play', 3, 'Adam is Eric''s ex-lover from earlier in their relationship', 'character', 'narrowing', 'Character name and relationship'),
('The Inheritance', 'Broadway Play', 3, 'Walter is an older gay man who knew figures from pre-AIDS New York', 'character', 'narrowing', 'Character name and background'),
('The Inheritance', 'Broadway Play', 3, 'The play explores the AIDS crisis and its aftermath', 'theme', 'narrowing', 'Central thematic focus'),
('The Inheritance', 'Broadway Play', 3, 'Henry is another key character in Eric''s life', 'character', 'narrowing', 'Character name and involvement'),
('The Inheritance', 'Broadway Play', 3, 'The play is divided into two parts with distinct focuses', 'structure', 'narrowing', 'Two-part structural organization'),
('The Inheritance', 'Broadway Play', 4, 'Andrew Burnap played Eric in the original Broadway production', 'production', 'recognition', 'Original actor detail'),
('The Inheritance', 'Broadway Play', 4, 'The play features a passing of the torch from older to younger gay men', 'theme', 'recognition', 'Thematic generational element'),
('The Inheritance', 'Broadway Play', 4, 'Part One focuses on Eric''s personal life and early relationship', 'structure', 'recognition', 'Part one thematic focus'),
('The Inheritance', 'Broadway Play', 4, 'Part Two expands into broader historical and cultural perspectives', 'structure', 'recognition', 'Part two thematic focus'),
('The Inheritance', 'Broadway Play', 4, 'The character Walter serves as a link to pre-AIDS gay culture in New York', 'character', 'recognition', 'Character thematic importance'),
('The Inheritance', 'Broadway Play', 4, 'The play ends in a monologue of acceptance and letting go', 'plot', 'recognition', 'Ending structure'),
('The Inheritance', 'Broadway Play', 5, 'Adam dies of AIDS-related complications, marking a turning point', 'plot', 'giveaway', 'Central plot tragedy'),
('The Inheritance', 'Broadway Play', 5, 'Walter reveals his own complicated history with AIDS and loss', 'plot', 'giveaway', 'Character revelation'),
('The Inheritance', 'Broadway Play', 5, 'Eric must confront his own role in the perpetuation of pain and memory', 'plot', 'giveaway', 'Character reckoning'),
('The Inheritance', 'Broadway Play', 5, 'The play ends with a sense of spiritual transcendence despite loss', 'plot', 'giveaway', 'Emotional resolution'),
('The Inheritance', 'Broadway Play', 0, 'Matthew Lopez spent three years researching and writing the play, incorporating oral histories from gay men and AIDS survivors', 'development', 'fact', 'Extensive research period'),
('The Inheritance', 'Broadway Play', 0, 'The play was Lopez''s Broadway debut and won the Tony Award for Best Play, making it one of the highest-profile debuts in recent Broadway history', 'production', 'fact', 'Career-launching success'),
('The Inheritance', 'Broadway Play', 0, 'The two-part structure allows the play to explore both intimate personal drama and broad historical perspective', 'structure', 'fact', 'Structural innovation'),
('The Inheritance', 'Broadway Play', 0, 'The Young Vic London production transferred to Broadway, with most of the original cast remaining', 'production', 'fact', 'International co-production'),
('The Inheritance', 'Broadway Play', 0, 'The play has been cited as a significant contemporary work addressing gay history, community resilience, and post-AIDS identity', 'theme', 'fact', 'Cultural significance'),
('The Inheritance', 'Broadway Play', 0, 'Lopez is among the youngest playwrights to achieve major success at this scale, bringing attention to emerging voices in American theater', 'playwright', 'fact', 'Playwright prominence'),

-- ============================================================
-- SLAVE PLAY
-- ============================================================
('Slave Play', 'Broadway Play', 1, 'A provocative play exploring power dynamics and identity', 'theme', 'very_broad', 'Power and identity themes in many plays'),
('Slave Play', 'Broadway Play', 1, 'American drama set in contemporary times with historical references', 'setting', 'very_broad', 'Contemporary plays with historical elements common'),
('Slave Play', 'Broadway Play', 1, 'Play dealing with race and sexuality in complex ways', 'theme', 'very_broad', 'Race and sexuality themes in some plays'),
('Slave Play', 'Broadway Play', 1, 'Drama featuring multiple characters and relationship dynamics', 'character', 'very_broad', 'Multi-character relationship dramas common'),
('Slave Play', 'Broadway Play', 1, 'Play that generated significant controversy and debate', 'production', 'very_broad', 'Controversial plays exist in contemporary theater'),
('Slave Play', 'Broadway Play', 1, 'American play set in a therapeutic or counseling context', 'setting', 'very_broad', 'Therapy-setting plays in contemporary drama'),
('Slave Play', 'Broadway Play', 2, 'Jeremy O. Harris play that premiered in 2018', 'playwright', 'broad', 'Harris connection and year identifying'),
('Slave Play', 'Broadway Play', 2, 'Opened at the John Golden Theatre on Broadway', 'production', 'broad', 'Specific theatre'),
('Slave Play', 'Broadway Play', 2, 'Received 12 Tony Award nominations in 2019, the most ever for a play', 'production', 'broad', 'Record-breaking nomination count'),
('Slave Play', 'Broadway Play', 2, 'Generated significant controversy for its subject matter and explicit content', 'production', 'broad', 'Controversial reception note'),
('Slave Play', 'Broadway Play', 2, 'Jeremy O. Harris was one of the youngest playwrights to achieve Broadway prominence', 'playwright', 'broad', 'Playwright age and context'),
('Slave Play', 'Broadway Play', 2, 'The title refers to a therapy technique for addressing racial trauma', 'development', 'broad', 'Therapeutic context understanding'),
('Slave Play', 'Broadway Play', 3, 'The play involves couples engaging in role-play scenarios', 'plot', 'narrowing', 'Specific plot mechanism'),
('Slave Play', 'Broadway Play', 3, 'The therapy sessions are facilitated by a Black female therapist', 'character', 'narrowing', 'Character profession and identity'),
('Slave Play', 'Broadway Play', 3, 'The couples are interracial, exploring power and desire through historical trauma', 'character', 'narrowing', 'Character demographic and dynamic'),
('Slave Play', 'Broadway Play', 3, 'The play''s full title includes the phrase "Antebellum Sexual Performance Therapy"', 'iconic_element', 'narrowing', 'Specific extended title'),
('Slave Play', 'Broadway Play', 3, 'The play is divided into different scenes exploring different couples and scenarios', 'structure', 'narrowing', 'Multi-scenario structure'),
('Slave Play', 'Broadway Play', 3, 'The play ends with an unexpected rupture and confrontation', 'plot', 'narrowing', 'Specific ending structure'),
('Slave Play', 'Broadway Play', 4, 'The play uses explicit racial language and imagery as part of its exploration', 'production', 'recognition', 'Content warning detail'),
('Slave Play', 'Broadway Play', 4, 'Harris wrote the play while studying at Yale School of Drama', 'playwright', 'recognition', 'Educational background'),
('Slave Play', 'Broadway Play', 4, 'The play won zero Tony Awards despite the 12 nominations, which was notable', 'production', 'recognition', 'Award voting disconnect'),
('Slave Play', 'Broadway Play', 4, 'The play explores the intersection of anti-Black racism and homophobia', 'theme', 'recognition', 'Thematic focus detail'),
('Slave Play', 'Broadway Play', 4, 'The therapist character serves as a provocative voice challenging the narrative', 'character', 'recognition', 'Character function'),
('Slave Play', 'Broadway Play', 4, 'The play includes a final monologue that destabilizes the audience''s understanding', 'structure', 'recognition', 'Ending technique'),
('Slave Play', 'Broadway Play', 5, 'A character breaks character to challenge the audience''s complicity', 'plot', 'giveaway', 'Fourth-wall breaking moment'),
('Slave Play', 'Broadway Play', 5, 'The therapist delivers a devastating critique of the couples'' choices', 'plot', 'giveaway', 'Central confrontation'),
('Slave Play', 'Broadway Play', 5, 'The play ends with ambiguity about whether healing or harm has occurred', 'plot', 'giveaway', 'Unresolved ending'),
('Slave Play', 'Broadway Play', 5, 'The play questions whether therapy or performance can address systemic racism', 'theme', 'giveaway', 'Central philosophical question'),
('Slave Play', 'Broadway Play', 0, 'Jeremy O. Harris wrote the play as part of his Yale thesis, which became a full production', 'development', 'fact', 'Development from academic work'),
('Slave Play', 'Broadway Play', 0, 'The play generated petitions both for and against its Broadway run, becoming a flashpoint in cultural debates about art and representation', 'production', 'fact', 'Cultural controversy'),
('Slave Play', 'Broadway Play', 0, 'The play''s 12 Tony nominations made it a historic moment, though its zero wins also raised questions about the play''s reception', 'production', 'fact', 'Tony history context'),
('Slave Play', 'Broadway Play', 0, 'Critics praised the play''s boldness and intellectual provocation, while others criticized it for exploitation and lack of clarity', 'production', 'fact', 'Divided critical reception'),
('Slave Play', 'Broadway Play', 0, 'Harris has stated the play is intentionally difficult and meant to challenge audiences, not provide easy answers', 'playwright', 'fact', 'Playwright intent'),
('Slave Play', 'Broadway Play', 0, 'The play marked a moment of increased visibility for young Black playwrights in mainstream American theater', 'production', 'fact', 'Cultural significance'),

-- ============================================================
-- TO KILL A MOCKINGBIRD
-- ============================================================
('To Kill a Mockingbird', 'Broadway Play', 1, 'A play about racial injustice set in the American South', 'theme', 'very_broad', 'Racial injustice themes in many plays'),
('To Kill a Mockingbird', 'Broadway Play', 1, 'Drama featuring a lawyer defending an innocent client', 'plot', 'very_broad', 'Defense and justice plots in various plays'),
('To Kill a Mockingbird', 'Broadway Play', 1, 'American play told from the perspective of a young person', 'structure', 'very_broad', 'Child perspective narratives in some plays'),
('To Kill a Mockingbird', 'Broadway Play', 1, 'Play set in a small town in the American South during economic hardship', 'setting', 'very_broad', 'Southern small-town settings common'),
('To Kill a Mockingbird', 'Broadway Play', 1, 'Drama exploring themes of morality and social conscience', 'theme', 'very_broad', 'Moral themes universal in drama'),
('To Kill a Mockingbird', 'Broadway Play', 1, 'Play featuring multiple generations of a family', 'character', 'very_broad', 'Multi-generational families in many plays'),
('To Kill a Mockingbird', 'Broadway Play', 2, 'Aaron Sorkin adaptation of Harper Lee''s novel', 'playwright', 'broad', 'Sorkin connection and literary source identifying'),
('To Kill a Mockingbird', 'Broadway Play', 2, 'Premiered on Broadway in 2018 at the Shubert Theatre', 'production', 'broad', 'Specific theatre and year'),
('To Kill a Mockingbird', 'Broadway Play', 2, 'Set in the fictional town of Maycomb, Alabama in the 1930s', 'setting', 'broad', 'Specific setting and time period'),
('To Kill a Mockingbird', 'Broadway Play', 2, 'Jeff Daniels played Atticus Finch in the original Broadway production', 'production', 'broad', 'Specific actor casting'),
('To Kill a Mockingbird', 'Broadway Play', 2, 'Won the Tony Award for Best Play in 2019', 'production', 'broad', 'Tony Award year'),
('To Kill a Mockingbird', 'Broadway Play', 2, 'The play broke box office records during its Broadway run', 'production', 'broad', 'Commercial success detail'),
('To Kill a Mockingbird', 'Broadway Play', 3, 'Scout Finch is the young protagonist who narrates and experiences the story', 'character', 'narrowing', 'Character name and role'),
('To Kill a Mockingbird', 'Broadway Play', 3, 'Atticus Finch is a lawyer defending Tom Robinson, a Black man falsely accused', 'character', 'narrowing', 'Character name and profession'),
('To Kill a Mockingbird', 'Broadway Play', 3, 'Jem is Scout''s older brother who also learns lessons of morality', 'character', 'narrowing', 'Character name and relationship'),
('To Kill a Mockingbird', 'Broadway Play', 3, 'Tom Robinson is falsely accused of assaulting Mayella Ewell', 'character', 'narrowing', 'Character name and situation'),
('To Kill a Mockingbird', 'Broadway Play', 3, 'Boo Radley is a reclusive neighbor who helps Scout and Jem', 'character', 'narrowing', 'Character name and role'),
('To Kill a Mockingbird', 'Broadway Play', 3, 'The trial is the central dramatic event of the play', 'plot', 'narrowing', 'Central plot structure'),
('To Kill a Mockingbird', 'Broadway Play', 4, 'Harper Lee''s novel was published in 1960 and won the Pulitzer Prize', 'development', 'recognition', 'Literary source details'),
('To Kill a Mockingbird', 'Broadway Play', 4, 'The 1962 film starred Gregory Peck as Atticus Finch and won multiple Academy Awards', 'development', 'recognition', 'Film adaptation success'),
('To Kill a Mockingbird', 'Broadway Play', 4, 'Sorkin restructured the narrative for the stage, creating a more theatrical version', 'development', 'recognition', 'Adaptation technique'),
('To Kill a Mockingbird', 'Broadway Play', 4, 'The trial scene shows Tom Robinson''s testimony and the false accuser Mayella Ewell', 'plot', 'recognition', 'Central trial detail'),
('To Kill a Mockingbird', 'Broadway Play', 4, 'Atticus delivers his summation to the jury defending Tom''s innocence', 'plot', 'recognition', 'Famous courtroom speech moment'),
('To Kill a Mockingbird', 'Broadway Play', 4, 'Scout learns about prejudice and empathy through her father''s actions and Boo Radley''s secret kindness', 'theme', 'recognition', 'Thematic moral lesson'),
('To Kill a Mockingbird', 'Broadway Play', 5, 'Tom Robinson is found guilty despite clear evidence of his innocence', 'plot', 'giveaway', 'Tragic trial outcome'),
('To Kill a Mockingbird', 'Broadway Play', 5, 'Tom is killed while allegedly escaping prison, a further injustice', 'plot', 'giveaway', 'Character tragic fate'),
('To Kill a Mockingbird', 'Broadway Play', 5, 'Boo Radley saves Scout and Jem from a violent attack', 'plot', 'giveaway', 'Climactic rescue moment'),
('To Kill a Mockingbird', 'Broadway Play', 5, 'Atticus tells Scout that real courage is "when you know you''re licked but you begin anyway"', 'quote', 'giveaway', 'Famous moral line'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Harper Lee wrote the novel based partly on her own observations of a trial in her hometown and her father''s legal practice', 'development', 'fact', 'Autobiographical inspiration'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'Aaron Sorkin is known for his fast-paced, witty dialogue style; his adaptation reflects his theatrical voice while honoring the source material', 'playwright', 'fact', 'Sorkin''s adaptation approach'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The play was one of the most commercially successful Broadway plays of its era, running for over 1,000 performances', 'production', 'fact', 'Commercial success and run length'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The play uses the title from the novel''s central metaphor about protecting innocence and avoiding harm', 'theme', 'fact', 'Title and symbolic meaning'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The play has been widely taught in schools and universities as a cornerstone of American literature and social justice education', 'theme', 'fact', 'Educational impact and legacy'),
('To Kill a Mockingbird', 'Broadway Play', 0, 'The 2019 Sorkin adaptation arrived on Broadway during renewed conversations about racism, representation, and the relevance of this historical narrative', 'production', 'fact', 'Contemporary cultural context');
